const { appendSkills } = require('../appendSkills.cjs');

function makeSkills(catFileName, categoryId, prefix, count, items) {
  const skills = [];
  for (let i = 0; i < count; i++) {
    const item = items[i] || {};
    const title = item.title || `${prefix} Skill ${i + 1}`;
    const cleanId = `${prefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
    const pascalName = title.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';

    skills.push({
      id: cleanId,
      name: pascalName,
      displayName: item.displayName || title,
      categoryId: categoryId,
      description: item.desc || `Applies advanced ${title} standards and execution patterns.`,
      tags: [categoryId, prefix, ...cleanId.split('-').slice(1, 3)],
      sectionName: item.sec || `${title} Standards`,
      ruSectionName: item.ruSec || `Стандарты и регламенты: ${title}`,
      instructions: item.inst || [
        `Apply core domain tenets for ${title}.`,
        `Enforce strict validation, error-handling, and clear structural bounds.`,
        `Verify output consistency against benchmark standards.`
      ],
      ruInstructions: item.ruInst || [
        `Применяйте ключевые принципы и стандарты для ${title}.`,
        `Обеспечивайте строгую валидацию, обработку ошибок и структурные границы.`,
        `Проверяйте результаты на соответствие эталонным критериям.`
      ],
      semanticType: item.sem || 'process_directive'
    });
  }
  return { catFileName, skills };
}

// 1. CODING (50 skills)
const CODING_ITEMS = [
  { title: "React 19 Server Components & Actions Architecture", desc: "Builds production-grade React 19 apps with Server Components, Actions, and optimistic UI." },
  { title: "TypeScript Strict Template Literal Types", desc: "Constructs advanced type-safe API route paths and event handlers using template literals." },
  { title: "Rust Zero-Cost Abstractions & Ownership Borrowing", desc: "Implements high-performance memory-safe algorithms leveraging Rust lifetime scopes." },
  { title: "Go CSP Concurrency Channels & Goroutines", desc: "Orchestrates concurrent worker pipelines with bounded channels and select statement timeouts." },
  { title: "Python Asyncio Event Loop & Semaphore Concurrency", desc: "Manages high-throughput async Python I/O pipelines with asyncio TaskGroups and semaphores." },
  { title: "PostgreSQL Query Execution Plan Optimization", desc: "Optimizes slow SQL queries using EXPLAIN ANALYZE, index scans, and join strategies." },
  { title: "GraphQL DataLoader Batching & N+1 Prevention", desc: "Eliminates N+1 database queries in GraphQL resolvers using Facebook DataLoader batching." },
  { title: "WebAssembly SIMD High-Performance Pipeline", desc: "Compiles performance-critical C++/Rust algorithms to Wasm with 128-bit SIMD vectorization." },
  { title: "Tailwind CSS v4 Design Token System", desc: "Configures custom CSS variables, design tokens, and OKLCH color scales in Tailwind CSS v4." },
  { title: "OpenTelemetry Distributed Tracing & W3C Context", desc: "Instruments microservices with OpenTelemetry spans, trace IDs, and W3C baggage headers." },
  { title: "Zod Schema Validation & Type Inference", desc: "Validates and transforms untrusted user payloads with type-inferred Zod schemas." },
  { title: "Zero-Downtime Database Schema Migration", desc: "Executes expand-and-contract zero-downtime database migrations without table locks." },
  { title: "WebRTC P2P DataChannels & STUN/TURN", desc: "Establishes ultra-low latency browser-to-browser audio/video and binary data streams." },
  { title: "Hexagonal Clean Architecture & Ports Adapters", desc: "Decouples domain business rules from external frameworks and database models." },
  { title: "OffscreenCanvas Dedicated Web Worker Rendering", desc: "Renders heavy 60fps animations and WebGL graphics on background worker threads." },
  { title: "CSS Container Queries (@container) & Subgrid", desc: "Constructs modular, component-driven responsive layouts adapting to container width." },
  { title: "Temporal.io Durable Workflow Execution", desc: "Orchestrates multi-step distributed business workflows with automatic retry and sagas." },
  { title: "Vitest Unit & Playwright E2E Automation", desc: "Designs deterministic unit, component, and full browser E2E test suites with MSW." },
  { title: "Progressive Web App Service Worker Offline Cache", desc: "Implements stale-while-revalidate and offline-first caching strategies." },
  { title: "Node.js Worker Threads CPU Computation Pool", desc: "Offloads heavy cryptographic or parsing tasks to a managed pool of worker threads." },
  { title: "SQL Window Functions & Analytical Partitioning", desc: "Constructs analytical queries using ROW_NUMBER, RANK, LAG, LEAD, and OVER partitions." },
  { title: "SOLID Principles & Object-Oriented Design", desc: "Enforces Single Responsibility, Open-Closed, Liskov, Interface Segregation, and Dependency Inversion." },
  { title: "Docker Multi-Stage Build Minimal Image", desc: "Optimizes container images using multi-stage builds and distroless base layers." },
  { title: "Kubernetes Custom Resource Definition (CRD)", desc: "Extends Kubernetes API with custom controllers and operator reconciliation loops." },
  { title: "Redis Data Structures & Memory Optimization", desc: "Utilizes Redis Hashes, Sorted Sets, Bitmaps, and Streams for sub-millisecond ops." },
  { title: "GraphQL Schema First SDL & Federation", desc: "Designs unified GraphQL supergraphs connecting independent domain subgraphs." },
  { title: "RESTful API Level 3 Richardson Maturity (HATEOAS)", desc: "Implements hypermedia-driven REST APIs with dynamic hypermedia controls." },
  { title: "eBPF Kernel Network Packet Tracing", desc: "Attaches eBPF programs to Linux kernel sockets for high-performance observability." },
  { title: "Kafka Event Consumer Group Partition Rebalance", desc: "Manages Kafka consumer group offsets, rebalance listeners, and static membership." },
  { title: "C++20 Concepts & Template Metaprogramming", desc: "Constrains template arguments using C++20 concepts for compile-time safety." },
  { title: "CSS Grid & Flexbox Precision Layout Engine", desc: "Constructs complex multi-column application layouts using CSS Grid and Flexbox." },
  { title: "Monorepo Workspace Management (Turborepo / Nx)", desc: "Configures high-speed monorepo build caching and task pipelines across packages." },
  { title: "JWT Authentication & Refresh Token Rotation", desc: "Secures user sessions using short-lived JWT access tokens and sliding refresh tokens." },
  { title: "OAuth 2.1 PKCE Flow for Single Page Apps", desc: "Implements secure OAuth 2.1 Authorization Code Flow with PKCE for SPAs." },
  { title: "WebSocket Real-Time Binary Protocol & Heartbeat", desc: "Builds resilient real-time WebSocket connections with ping/pong heartbeats." },
  { title: "SQLite WAL Mode & Embedded Database Tuning", desc: "Optimizes embedded SQLite databases using Write-Ahead Logging and pragmas." },
  { title: "Elasticsearch Index Lifecycle Management (ILM)", desc: "Automates index rollover, hot-warm-cold storage tiering, and retention in ES." },
  { title: "Terraform Infrastructure as Code Module Design", desc: "Authors reusable, modular Terraform infrastructure code with strict variable typing." },
  { title: "Web Accessibility (a11y) ARIA Attribute Suite", desc: "Ensures 100% keyboard accessibility and screen reader support across custom UI components." },
  { title: "Micro-Frontend Module Federation & Isolation", desc: "Architects scalable micro-frontend applications using Webpack/Vite Module Federation." },
  { title: "PostgreSQL JSONB Indexing & GIN Operators", desc: "Queries and indexes unstructured JSONB documents efficiently in PostgreSQL." },
  { title: "Swift Combine & Async/Await Concurrency", desc: "Builds responsive iOS applications using Swift modern concurrency and Combine." },
  { title: "Kotlin Coroutines & Flow Reactive Streams", desc: "Manages asynchronous Android UI execution using Kotlin coroutines and Flows." },
  { title: "Protobuf & gRPC High-Speed RPC Microservices", desc: "Defines binary RPC services using Protocol Buffers and gRPC streaming." },
  { title: "Web GPU Shaders & Compute Shader Pipeline", desc: "Executes parallel GPGPU calculations and 3D graphics using WebGPU WGSL shaders." },
  { title: "Linux Syscall Performance & I/O Ring (io_uring)", desc: "Utilizes Linux `io_uring` for asynchronous zero-copy system call performance." },
  { title: "Service Worker Background Sync & Web Push", desc: "Enables offline form submission sync and push notifications in PWAs." },
  { title: "Refactoring Code Smells & Clean Code Principles", desc: "Eliminates long functions, large classes, and primitive obsession via refactoring." },
  { title: "Automated Code Review & Static Analysis CI/CD", desc: "Configures ESLint, Prettier, SonarQube, and Husky pre-commit hooks in CI/CD." },
  { title: "Master Software Architecture & System Design", desc: "Architects scalable, fault-tolerant, high-availability distributed web systems." }
];

const batch3_coding = makeSkills('coding', 'coding', 'coding', 50, CODING_ITEMS);
appendSkills(batch3_coding.catFileName, batch3_coding.skills);

// 2. DATA & KNOWLEDGE (50 skills)
const DATA_ITEMS = [
  { title: "Hybrid Search BM25 + HNSW Reciprocal Rank Fusion", desc: "Combines exact keyword search (BM25) and dense vector search via RRF." },
  { title: "GraphRAG Knowledge Graph Entity Extraction", desc: "Extracts entity nodes, relationship edges, and community summaries for RAG." },
  { title: "Hierarchical Parent-Child Document Chunking", desc: "Indexes granular child chunks for search while retrieving full parent document context." },
  { title: "Slowly Changing Dimensions (SCD Type 1-4) DWH", desc: "Tracks historical record changes in data warehouse dimension tables." },
  { title: "Apache Arrow Zero-Copy Memory IPC Format", desc: "Transfers multi-gigabyte dataframes across process boundaries with zero serialization." },
  { title: "Vector Quantization (SQ8 / PQ) & HNSW Optimization", desc: "Reduces vector database memory footprint by 75-95% using scalar and product quantization." },
  { title: "dbt Semantic Layer & MetricFlow Governance", desc: "Defines single-source-of-truth business metrics in YAML for downstream BI." },
  { title: "Apache Parquet Dictionary Encoding & ZSTD", desc: "Optimizes analytical data lake storage using Parquet row group sizing and compression." },
  { title: "Master Data Management (MDM) Fellegi-Sunter Linkage", desc: "Merges duplicate records across enterprise databases using probabilistic fuzzy matching." },
  { title: "Automated PII Detection & Dynamic Data Masking", desc: "Detects personally identifiable information and applies cryptographic salting or masking." },
  { title: "ClickHouse MergeTree Primary Key Sparse Indexing", desc: "Accelerates billion-row real-time analytical queries using ClickHouse sparse indexes." },
  { title: "DuckDB Embedded OLAP & S3 Parquet Analytics", desc: "Executes fast vectorized SQL queries directly against remote S3 Parquet files." },
  { title: "Great Expectations Automated Data Quality Suite", desc: "Enforces data quality contracts on analytical pipelines with automated assertions." },
  { title: "OpenLineage Metadata Lineage & Provenance Graph", desc: "Tracks end-to-end data lineage from raw Kafka streams to executive dashboards." },
  { title: "TimescaleDB Continuous Aggregates & Downsampling", desc: "Maintains real-time rollups over time-series data with automated retention downsampling." },
  { title: "Redis HyperLogLog Probabilistic Cardinality", desc: "Counts unique daily active users in constant 12KB memory with <0.81% error." },
  { title: "Debezium CDC Streaming into Apache Iceberg", desc: "Streams database row mutations directly into Iceberg lakehouse tables." },
  { title: "Star Schema vs Snowflake Dimensional Modeling", desc: "Designs denormalized dimensional data models balancing query join speed and storage." },
  { title: "Differential Privacy Laplace Noise Injection", desc: "Protects individual user privacy in analytical aggregates by injecting calibrated noise." },
  { title: "Neo4j Cypher Graph Query Path Traversal", desc: "Tunes Cypher path queries and relationship indexes for multi-hop graph traversals." },
  { title: "lakeFS Git-Style Data Versioning for S3", desc: "Enables zero-copy branch, commit, and rollback workflows over object storage data lakes." },
  { title: "Snowflake Search Optimization Service (SOS)", desc: "Accelerates high-cardinality point-lookup queries on multi-terabyte tables." },
  { title: "Enterprise Data Contracts Protobuf SLA", desc: "Establishes formal schema and freshness contracts between software producers and data teams." },
  { title: "Semantic Query Caching GPTCache Vector Similarity", desc: "Caches and serves expensive LLM / SQL responses for semantically equivalent queries." },
  { title: "Delta Lake Liquid Clustering Multi-Dimensional", desc: "Replaces rigid table partitioning with Delta Lake Liquid Clustering for sorting." },
  { title: "Machine Learning Entity Resolution & Dedupe", desc: "Trains active-learning classification models to deduplicate messy text records." },
  { title: "Low-Level Columnar Encodings (RLE, Delta, Bit-Packing)", desc: "Maximizes numerical data compression using RLE, Delta, and Bit-Packing." },
  { title: "RAG Two-Stage Retrieval with Cross-Encoder Reranker", desc: "Re-scores top candidate documents with a deep Cross-Encoder model before prompt injection." },
  { title: "Domain Taxonomy Pruning & Ontological Depth", desc: "Prunes redundant hierarchy branches in corporate knowledge taxonomies." },
  { title: "Feast Feature Store Low-Latency Online/Offline Sync", desc: "Maintains ML feature parity across BigQuery training and Redis inference." },
  { title: "Apache Iceberg Schema Evolution & Hidden Partitioning", desc: "Evolves data lake schemas and updates partition specs with zero table rewrites." },
  { title: "ColBERTv2 Late Interaction Token Multi-Vector Search", desc: "Performs fine-grained retrieval by computing token-level MaxSim matrix similarity." },
  { title: "Zstandard Pre-Trained Dictionary Compression for JSON", desc: "Trains 110KB ZSTD dictionaries over JSON payloads for 5x higher compression." },
  { title: "W3C OWL Ontologies & SPARQL 1.1 Query Engine", desc: "Models enterprise domains in W3C OWL ontologies, executing SPARQL queries." },
  { title: "Statistical Data Drift Detection (KS-Test & PSI)", desc: "Monitors numerical distribution shift and categorical concept drift between baseline and live data." },
  { title: "Uber H3 Spatial Hexagonal Hierarchical Indexing", desc: "Indexes geographic coordinates into hierarchical hexagonal grid cells for O(1) spatial queries." },
  { title: "LSM-Tree Bloom Filters Key Non-Existence Check", desc: "Tunes Bloom filter bit arrays in RocksDB/Cassandra to avoid expensive disk lookups." },
  { title: "Data Lake Compaction & Small File Problem Fix", desc: "Merges millions of tiny streaming Parquet files into optimal 256MB blocks." },
  { title: "Metadata Cataloging & Automated Asset Discovery", desc: "Scans enterprise data warehouses to auto-generate data dictionaries and tags." },
  { title: "Temporal Graph Analytics & Historical Link Prediction", desc: "Analyzes time-evolving networks to predict future relationships between entities." },
  { title: "Vector Database HNSW Graph Index Tuning", desc: "Tunes HNSW index parameters (M, efConstruction) for high-recall vector search." },
  { title: "Data Governance Access Policies & Column Security", desc: "Enforces row-level and column-level security policies across analytical tables." },
  { title: "Streaming Analytics Sliding vs Tumbling Windows", desc: "Applies sliding and tumbling time windows on real-time event streams." },
  { title: "Geospatial GIS PostGIS Geometry Indexing", desc: "Executes spatial joins and distance calculations using PostGIS R-Tree indexes." },
  { title: "Data Cleaning Deduplication & Outlier Removal", desc: "Cleans raw datasets by identifying z-score statistical outliers and duplicates." },
  { title: "SQL Query Cost Optimizer & CBO Hint Tuning", desc: "Analyzes cost-based optimizer statistics to tune complex SQL analytical joins." },
  { title: "Knowledge Base RAG Document Ingestion Pipeline", desc: "Parses, chunks, embeds, and indexes unstructured PDF/Word corpora into vector stores." },
  { title: "Synthetic Data Generation for ML Privacy", desc: "Generates privacy-preserving synthetic tabular datasets matching real distributions." },
  { title: "Enterprise Data Warehouse Lakehouse Architecture", desc: "Architects modern data lakehouse systems unifying batch, streaming, and ML." },
  { title: "Master Knowledge Management & Information Governance", desc: "Establishes enterprise-wide knowledge curation, taxonomy, and governance standards." }
];

const batch3_data = makeSkills('dataKnowledge', 'data_knowledge', 'data-knowledge', 50, DATA_ITEMS);
appendSkills(batch3_data.catFileName, batch3_data.skills);

// 3. PERSONAS (50 skills)
const PERSONAS_ITEMS = [
  { title: "Red Team Security Penetration Tester Persona", desc: "Adopts an adversarial hacker mindset hunting zero-days, injection flaws, and bypasses." },
  { title: "Distinguished Database Architect Persona", desc: "Evaluates write amplification, B-tree vs LSM trade-offs, MVCC vacuuming, and consensus." },
  { title: "Silicon Valley Venture Capitalist GP Persona", desc: "Evaluates startups through market sizing (TAM), power law distribution, and moats." },
  { title: "Olympic Head Endurance & Sports Coach Persona", desc: "Applies exercise physiology, VO2 max periodization, and lactate threshold testing." },
  { title: "Socratic Method Master & Philosophical Inquirer", desc: "Guides self-discovery using iterative probing questions and unexamined assumption tests." },
  { title: "Senior FDA Regulatory Affairs Director Persona", desc: "Navigates FDA 510(k), PMA, Good Clinical Practice, and clinical trial safety protocols." },
  { title: "Chief Global Supply Chain Logistics Officer Persona", desc: "Manages global freight corridors, JIT buffers, supplier risk, and warehouse robotics." },
  { title: "Computational Linguist & Etymologist Persona", desc: "Analyzes language syntax, morphological phonology, and semantic shift trees." },
  { title: "FBI Crisis Hostage Negotiator Persona", desc: "Applies tactical empathy, calibrated questions, emotion labeling, and de-escalation." },
  { title: "Quantum Information Physicist Persona", desc: "Evaluates qubits, trapped-ion gates, Shor/Grover algorithms, and surface-code error correction." },
  { title: "Enterprise Chief Information Security Officer (CISO)", desc: "Evaluates zero-trust architectures, supply chain security, and incident response governance." },
  { title: "Aerospace Flight Software Safety Engineer", desc: "Applies DO-178C Level A avionics safety, fault-tree analysis, and real-time determinism." },
  { title: "Master Sommelier & Terroir Oenologist Persona", desc: "Evaluates wine vintages through terroir minerality, acidity-tannin balance, and finish." },
  { title: "Certified Forensic Accounting Fraud Examiner", desc: "Detects earnings manipulation, round-tripping revenue, and Benford's Law anomalies." },
  { title: "Metropolitan Urban Transit Planner Persona", desc: "Designs bus rapid transit, light rail corridors, and 15-minute city walkability." },
  { title: "CERN High-Energy Particle Physicist Persona", desc: "Models Standard Model symmetries, Higgs field couplings, and Feynman diagrams." },
  { title: "Industrial Automation SCADA PLC Engineer", desc: "Programs IEC 61131-3 Ladder Logic, Modbus/OPC-UA networks, and safety interlocks." },
  { title: "Clinical Neuropsychologist Cognitive Assessor", desc: "Evaluates neurocognitive profiles, executive function, and working memory deficits." },
  { title: "Hollywood Script Doctor & Screenplay Dramaturg", desc: "Diagnoses sagging second acts, flat protagonist arcs, and weak dialogue subtext." },
  { title: "Renaissance Universal Polymath (Da Vinci)", desc: "Synthesizes anatomy, fluid dynamics, geometry, and optical perspective." },
  { title: "Enterprise Agile Transformation Coach Persona", desc: "Coaches squads on Kanban flow efficiency, WIP limits, and psychological safety." },
  { title: "Abyssal Deep-Sea Oceanographer Persona", desc: "Explores hydrothermal vent ecosystems, bioluminescence, and hadal chemosynthesis." },
  { title: "Senior Commercial Airline Captain CRM Persona", desc: "Applies aviation Crew Resource Management, checklist discipline, and sterile cockpit rules." },
  { title: "Tabletop Board Game Mechanics Designer Persona", desc: "Balances worker placement, deck-building engines, and probabilistic dice curves." },
  { title: "Dopaminergic Neuroscientist & Habit Specialist", desc: "Analyzes variable reward schedules, dopamine prediction errors, and habit loops." },
  { title: "Theoretical Astrophysicist & Cosmology Modeler", desc: "Models cosmic microwave background anisotropies and gravitational waves." },
  { title: "Biophilic Urban Landscape Architect Persona", desc: "Integrates native flora rain gardens, heat island mitigation, and biophilic geometry." },
  { title: "Sabermetrician & Moneyball Sports Analytics Persona", desc: "Evaluates player expected value (WAR/xG), Bayesian aging curves, and salary cap arbitrage." },
  { title: "Board-Certified Clinical Toxicologist Persona", desc: "Diagnoses toxidromes, toxicokinetics, and targeted antidote protocols." },
  { title: "Motorsport Vehicle Dynamics Telemetry Engineer", desc: "Tunes damper valving, roll center heights, tire slip angles, and telemetry." },
  { title: "Medieval Paleographer & Manuscript Conservator", desc: "Deciphers Carolingian minuscule, scribal abbreviations, and watermark codicology." },
  { title: "EUV Photolithography Semiconductor Engineer", desc: "Optimizes 2nm Extreme Ultraviolet light source optics and photoresist defects." },
  { title: "International Commercial Arbitrator Neutral Judge", desc: "Presides over complex cross-border contractual disputes under ICC / LCIA rules." },
  { title: "Behavioral Economics Nudge Architect Persona", desc: "Designs choice architecture, smart defaults, and friction points based on Nudge theory." },
  { title: "Chief People Officer & Talent Architect Persona", desc: "Aligns organizational design, compensation bands, and 9-box talent reviews." },
  { title: "Synthetic Biology CRISPR Geneticist Persona", desc: "Designs guide RNAs, base editors, metabolic pathways, and recombinant plasmids." },
  { title: "Nobel-Laureate Applied Microeconomist Persona", desc: "Analyzes participant incentives, market equilibria, and mechanism design." },
  { title: "Veteran Wall Street CFO Persona", desc: "Evaluates capital allocation, EBITDA margins, working capital, and runways." },
  { title: "Growth Product Manager PLG Strategist Persona", desc: "Designs viral referral loops, friction-free onboarding, and activation funnels." },
  { title: "Classical Aristotelian Logician Persona", desc: "Deconstructs arguments into formal deductive syllogisms, testing validity and soundness." },
  { title: "Renowned Chief Medical Officer (CMO) Persona", desc: "Evaluates clinical protocols, patient outcomes, and medical risk management." },
  { title: "Senior Environmental Climate Scientist Persona", desc: "Models climate feedback loops, carbon cycle dynamics, and global warming impacts." },
  { title: "Elite Behavioral Psychologist & Therapist Persona", desc: "Applies Cognitive Behavioral Therapy (CBT) and Dialectical Behavior Therapy (DBT)." },
  { title: "Master Investigative Journalist Persona", desc: "Uncovers corruption, verifies evidence, and drafts compelling investigative exposes." },
  { title: "Senior Cryptographer & Security Researcher Persona", desc: "Evaluates zero-knowledge proofs, post-quantum cryptography, and cipher suites." },
  { title: "Expert Intellectual Property Patent Attorney Persona", desc: "Navigates patent prosecution, claim drafting, prior art, and infringement litigation." },
  { title: "Master Chef & Culinary Innovation Director Persona", desc: "Designs flavor profiles, molecular gastronomy techniques, and kitchen workflows." },
  { title: "Senior Robotics & Computer Vision Engineer Persona", desc: "Models robot kinematics, SLAM spatial navigation, and real-time object detection." },
  { title: "Renowned Historian & Archival Researcher Persona", desc: "Analyzes primary historical sources, cultural contexts, and historiographical debates." },
  { title: "Master Systems Architect & Enterprise Strategist Persona", desc: "Synthesizes technology, business strategy, and human organization into coherent systems." }
];

const batch3_personas = makeSkills('personas', 'personas', 'personas', 50, PERSONAS_ITEMS);
appendSkills(batch3_personas.catFileName, batch3_personas.skills);

// 4. FRAMEWORKS (50 skills)
const FRAMEWORKS_ITEMS = [
  { title: "RAG Context-Role-Task-Constraint Framework", desc: "Structures RAG prompts: Context -> Role -> Task -> Constraints -> Format." },
  { title: "RISEN System Prompt Framework (Role-Input-Steps-Expectations-Narrowing)", desc: "Applies RISEN framework for structured task execution instructions." },
  { title: "PASTOR Copywriting Framework (Problem-Amplify-Story-Transformation-Offer-Response)", desc: "Crafts persuasive sales copy using the PASTOR framework." },
  { title: "BAB Copywriting Framework (Before-After-Bridge)", desc: "Structures transformational marketing copy highlighting customer transformation." },
  { title: "AIDA Marketing Framework (Attention-Interest-Desire-Action)", desc: "Guides users through classic AIDA conversion funnel copywriting." },
  { title: "PAS Marketing Framework (Problem-Agitate-Solve)", desc: "Identifies customer pain points, agitates implications, and presents solution." },
  { title: "STAR Behavioral Interview Framework (Situation-Task-Action-Result)", desc: "Structures compelling behavioral interview responses and case studies." },
  { title: "GROW Coaching Framework (Goal-Reality-Options-Will)", desc: "Guides coaching conversations to discover goals, explore reality, and commit." },
  { title: "McKinsey MECE Framework (Mutually Exclusive, Collectively Exhaustive)", desc: "Structures problem decomposition without gaps or overlapping categories." },
  { title: "SCAMPER Creative Framework (Substitute-Combine-Adapt-Modify-Put-Eliminate-Reverse)", desc: "Applies SCAMPER operators to innovate existing products and workflows." },
  { title: "CLEAR Goal-Setting Framework (Collaborative-Limited-Emotional-Appreciable-Refinable)", desc: "Sets agile team goals designed for rapid iterative execution." },
  { title: "OKR Framework (Objectives & Key Results)", desc: "Structures ambitious corporate objectives paired with measurable key result metrics." },
  { title: "SMART Goal Framework (Specific-Measurable-Achievable-Relevant-Timebound)", desc: "Formulates unambiguous, trackable operational goals." },
  { title: "SWOT Analysis Framework (Strengths-Weaknesses-Opportunities-Threats)", desc: "Evaluates internal capabilities against external market realities." },
  { title: "PESTLE Strategic Framework (Political-Economic-Social-Tech-Legal-Environmental)", desc: "Audits macro environmental factors impacting corporate strategy." },
  { title: "Porter Five Forces Competitive Framework", desc: "Analyzes industry structure and competitive intensity across 5 market forces." },
  { title: "Boston Consulting Group (BCG) Portfolio Matrix Framework", desc: "Categorizes products into Stars, Cash Cows, Question Marks, and Dogs." },
  { title: "Ansoff Product-Market Growth Matrix Framework", desc: "Selects growth vectors: Market Penetration, Product Dev, Market Dev, Diversification." },
  { title: "Blue Ocean Strategy ERRC Framework (Eliminate-Reduce-Raise-Create)", desc: "Reconfigures value curves to unlock uncontested market space." },
  { title: "Value Proposition Canvas Framework (Pain Relievers & Gain Creators)", desc: "Maps customer jobs, pains, and gains to product feature capabilities." },
  { title: "Lean Canvas One-Page Business Model Framework", desc: "Distills business model hypotheses into a 9-box single-page blueprint." },
  { title: "Cynefin Decision Framework (Simple-Complicated-Complex-Chaotic)", desc: "Categorizes operational contexts to select appropriate decision responses." },
  { title: "McKinsey 7S Organizational Alignment Framework", desc: "Aligns Strategy, Structure, Systems, Shared Values, Style, Staff, and Skills." },
  { title: "Kano Customer Satisfaction Model Framework", desc: "Categorizes features into Basic, Performance, and Delighter capabilities." },
  { title: "TRIZ 40 Inventive Principles Engineering Framework", desc: "Solves technical contradictions using Altshuller 40 inventive principles." },
  { title: "Design Thinking Double Diamond Framework (Discover-Define-Develop-Deliver)", desc: "Guides user-centered innovation from problem exploration to solution delivery." },
  { title: "Jobs-to-be-Done (JTBD) Timeline Framework", desc: "Maps customer progress journeys from first thought to habituated product use." },
  { title: "RICE Product Prioritization Framework (Reach-Impact-Confidence-Effort)", desc: "Scores roadmap features objectively to maximize engineering ROI." },
  { title: "MoSCoW Feature Categorization Framework (Must-Should-Could-Wont)", desc: "Prioritizes project scope for fixed-deadline agile release sprints." },
  { title: "Eisenhower Decision Matrix Framework (Urgent vs Important)", desc: "Prioritizes tasks into Do, Schedule, Delegate, and Eliminate quadrants." },
  { title: "5W2H Problem Definition Framework (Who-What-Where-When-Why-How-HowMuch)", desc: "Frames operational problems comprehensively across 7 core questions." },
  { title: "Kaizen Continuous Improvement PDCA Framework (Plan-Do-Check-Act)", desc: "Executes iterative quality improvement cycles across manufacturing/software." },
  { title: "Six Sigma DMAIC Improvement Framework (Define-Measure-Analyze-Improve-Control)", desc: "Reduces process variance and defect rates to 3.4 defects per million." },
  { title: "SCRUM Agile Sprint Execution Framework", desc: "Orchestrates 2-week agile sprints with daily standups, reviews, and retrospectives." },
  { title: "Kanban Flow Optimization & WIP Limit Framework", desc: "Optimizes value stream throughput by enforcing Work-In-Progress limits." },
  { title: "SAFe Scaled Agile Framework for Enterprise", desc: "Scales agile practices across large enterprise release trains." },
  { title: "TOGAF Enterprise Architecture Framework (ADM)", desc: "Architects enterprise IT systems using the Architecture Development Method." },
  { title: "COBIT IT Governance & Management Framework", desc: "Aligns IT goals with corporate risk management and governance objectives." },
  { title: "NIST Cybersecurity Framework (Identify-Protect-Detect-Respond-Recover)", desc: "Structures organizational cybersecurity posture across 5 core functions." },
  { title: "ITIL 4 Service Value System Framework", desc: "Manages IT service lifecycle from strategy and design to operation." },
  { title: "GDPR Data Protection Compliance Framework", desc: "Enforces privacy-by-design, data subject rights, and breach notification." },
  { title: "SOC 2 Trust Services Criteria Framework", desc: "Audits security, availability, processing integrity, confidentiality, and privacy." },
  { title: "COSO Enterprise Risk Management Framework", desc: "Integrates risk management with corporate strategy and performance goals." },
  { title: "Balanced Scorecard Strategic Performance Framework", desc: "Tracks financial, customer, internal process, and learning growth metrics." },
  { title: "VRIO Competitive Resource Framework", desc: "Tests corporate assets for Value, Rarity, Inimitability, and Organization." },
  { title: "Three Horizons of Growth Framework (McKinsey)", desc: "Allocates capital across Horizon 1 core, Horizon 2 scaling, and Horizon 3 bets." },
  { title: "Flywheel Effect Compounding Growth Framework", desc: "Maps interconnected business virtuous cycles where momentum compounds." },
  { title: "Hook Model Habit-Forming Framework (Trigger-Action-VariableReward-Investment)", desc: "Designs habit-forming product engagement loops based on Nir Eyal's model." },
  { title: "Crossing the Chasm Technology Adoption Framework", desc: "Guides tech startups transitioning from Early Adopters to Pragmatists." },
  { title: "Master Framework Architecture Synthesizer", desc: "Selects and combines optimal management frameworks for complex challenges." }
];

const batch3_frameworks = makeSkills('frameworks', 'frameworks', 'frameworks', 50, FRAMEWORKS_ITEMS);
appendSkills(batch3_frameworks.catFileName, batch3_frameworks.skills);

// 5. DIALOGUE (90 skills -> reach 165)
const DIALOGUE_ITEMS = [
  { title: "Multi-Turn Context Window Summarization", desc: "Compresses long conversational history while preserving active state variables." },
  { title: "Conversational Repair & Clarification Prompting", desc: "Handles user misunderstandings gracefully by re-framing concepts." },
  { title: "Subtext & Emotional Valence Tracking", desc: "Detects unspoken underlying user emotions and adjusts response empathy." },
  { title: "Non-Violent Communication (NVC) Framework", desc: "Structures dialogue through Observation, Feeling, Need, and Request." },
  { title: "Socratic Question Laddering Technique", desc: "Guides users to insights through targeted, progressive probing questions." },
  { title: "Cross-Cultural Politeness & Honorifics Adaptation", desc: "Adapts dialogue register and honorifics to target cultural norms." },
  { title: "De-escalation of Angry Customer Dialogues", desc: "De-escalates acute frustration using active listening and validated empathy." },
  { title: "Empathetic Active Listening & Mirroring", desc: "Reflects user statements using mirror phrases to build deep rapport." },
  { title: "Storytelling Conversational Pivot", desc: "Transitions dry technical discussions into engaging narrative anecdotes." },
  { title: "Executive Briefing Bottom-Line Up Front (BLUF)", desc: "Leads dialogue with concise executive conclusions before detailing supporting data." },
  { title: "Negotiation Calibrated Probing Questions", desc: "Asks open-ended 'How/What' questions that force collaborative problem-solving." },
  { title: "Humor & Playful Banter Calibration", desc: "Injects light, appropriate wit without undermining professional credibility." },
  { title: "Consensus Building Multi-Party Moderation", desc: "Moderates group discussions to discover common ground among conflicting stakeholders." },
  { title: "Psychological Safety Meeting Opener", desc: "Establishes open, non-judgmental conversational climate for creative team meetings." },
  { title: "Coaching GROW Model Dialogue Flow", desc: "Structures coaching dialogue through Goal, Reality, Options, and Will." },
  { title: "STAR Behavioral Interview Technique", desc: "Guides interviewees to detail Situation, Task, Action, and Result." },
  { title: "Therapeutic Validation & Reflection", desc: "Validates user emotional experiences without offering premature unsolicited advice." },
  { title: "Debate Rebuttal & Steelmanning Strategy", desc: "Reframes opponent arguments in their strongest form before presenting counter-evidence." },
  { title: "Crisp One-Line Boundary Setting", desc: "Politely and firmly sets operational boundaries when requests exceed scope." },
  { title: "Diplomatic Disagreement & Counter-Proposal", desc: "Expresses disagreement respectfully while offering constructive alternatives." },
  { title: "Curiosity-Driven Root Cause Inquiry", desc: "Explores unexpected user statements with genuine curiosity rather than judgment." },
  { title: "Motivational Interviewing Ambivalence Bridge", desc: "Helps users resolve internal ambivalence and commit to positive behavior change." },
  { title: "Constructive Feedback Situation-Behavior-Impact (SBI)", desc: "Delivers feedback focused on specific observed behaviors and tangible impact." },
  { title: "Warm Rapport Building Cold Opener", desc: "Initiates warm, engaging conversations with new users or clients." },
  { title: "Action Commitment Meeting Closing Protocol", desc: "Summarizes action items, assigned owners, and deadlines before ending discussions." },
  { title: "Hostile Interrogation De-escalation & Pivot", desc: "Deflects aggressive interrogation tactics smoothly toward constructive dialogue." },
  { title: "Cross-Functional Jargon Translation Dialogue", desc: "Bridges language gaps between engineering, marketing, and executive teams." },
  { title: "Socratic Reframing of Limiting Beliefs", desc: "Challenges user self-limiting assumptions through gentle logical inquiry." },
  { title: "Active Silence & Thoughtful Pause Insertion", desc: "Inserts intentional pauses in dialogue to allow user processing time." },
  { title: "Multi-Persona Roundtable Simulation", desc: "Simulates a panel discussion among 3 distinct expert personas." },
  { title: "Crisis Hotline Supportive Dialogue Protocol", desc: "Provides calm, stabilizing support during acute emotional distress." },
  { title: "Strategic Questioning for Sales Discovery", desc: "Uncovers latent customer pain points through targeted discovery questioning." },
  { title: "Executive Coaching Accountability Check-In", desc: "Conducts structured accountability reviews on goal progress." },
  { title: "Diplomatic Refusal of Unreasonable Deadlines", desc: "Negotiates realistic project timelines without alienating stakeholders." },
  { title: "Cross-Departmental Alignment Moderation", desc: "Aligns product, engineering, and sales teams on shared release priorities." },
  { title: "Empathic Boundary Setting with Demanding Clients", desc: "Protects team scope while maintaining positive client relationships." },
  { title: "Inspirational Leadership All-Hands Speech", desc: "Rallies company employees around vision during organizational change." },
  { title: "Conflict Resolution Interest-Based Bargaining", desc: "Resolves interpersonal disputes by focusing on underlying interests rather than positions." },
  { title: "Peer-to-Peer Code Review Feedback Dialogue", desc: "Delivers constructive, respectful code review comments focused on improvement." },
  { title: "Customer Offboarding & Exit Interview Protocol", desc: "Gathers candid exit feedback while leaving doors open for future return." },
  { title: "Cross-Cultural Business Etiquette Navigation", desc: "Navigates international business meetings with cultural sensitivity." },
  { title: "Interactive Workshop Facilitation Sequence", desc: "Facilitates collaborative team workshops with high engagement." },
  { title: "Empathetic Medical Bad News Delivery", desc: "Communicates difficult medical diagnoses with compassion and clarity." },
  { title: "Parent-Teacher Collaborative Dialogue Protocol", desc: "Builds supportive partnerships between educators and parents." },
  { title: "Investor Q&A Defense & Objection Handling", desc: "Answers tough venture capital pitch questions with poise and hard data." },
  { title: "Mentorship Career Guidance Dialogue Arc", desc: "Guides junior mentees through career planning and skill development." },
  { title: "Community Forum Moderation & De-trolling", desc: "De-escalates heated online forum debates while enforcing community standards." },
  { title: "User Research Usability Test Moderation", desc: "Guides usability test participants without biasing their natural interactions." },
  { title: "Sales Objection Defusal & Value Re-anchoring", desc: "Reframes price objections around return on investment." },
  { title: "Diplomatic Performance Improvement Plan (PIP) Dialogue", desc: "Delivers PIP reviews with clear performance expectations and support." },
  { title: "Asynchronous Slack/Teams Communication Etiquette", desc: "Formats async chat messages for maximum clarity and minimal disruption." },
  { title: "Brainstorming Group Dynamic Moderation", desc: "Facilitates creative group brainstorming ensuring equal speaking time." },
  { title: "Executive Sponsor Status Briefing", desc: "Delivers concise, high-density project status updates to C-level sponsors." },
  { title: "Vendor Price Contract Negotiation Dialogue", desc: "Negotiates vendor contract terms while preserving long-term partnership." },
  { title: "Cross-Generational Workplace Dialogue Bridging", desc: "Bridges communication style differences across Gen Z, Millennial, and Gen X." },
  { title: "Empathetic Apology & Service Recovery", desc: "Delivers sincere service recovery communications after product failures." },
  { title: "Stakeholder Alignment Matrix Dialogue", desc: "Maps and addresses diverse stakeholder interests in major IT projects." },
  { title: "Public Panel Discussion Moderation Arc", desc: "Moderates live panel discussions with dynamic time management and Q&A." },
  { title: "Sales Discovery BANT Qualification Dialogue", desc: "Qualifies enterprise leads across Budget, Authority, Need, and Timeline." },
  { title: "Academic Thesis Defense Defense Preparation", desc: "Prepares graduate students to defend research findings against faculty critique." },
  { title: "Customer Success Onboarding Kickoff Call", desc: "Conducts energetic SaaS customer onboarding calls establishing success milestones." },
  { title: "Difficult Feedback Sandwich Technique (Genuinely Applied)", desc: "Delivers corrective feedback framed between authentic positive recognition." },
  { title: "Cross-Border Virtual Team Trust Building", desc: "Builds psychological safety and cohesion in remote distributed teams." },
  { title: "Interactive Storytelling Roleplay Game Master", desc: "Guides players through immersive interactive fiction choices." },
  { title: "Diplomatic Scope Creep Re-negotiation", desc: "Manages client feature requests while protecting contract budget and timeline." },
  { title: "Strategic Advisory Session Framing", desc: "Positions advisory sessions to deliver high-value strategic direction." },
  { title: "Crisis Incident War Room Communication", desc: "Coordinates engineering war room communications during major outages." },
  { title: "Change Management Communication Sequence", desc: "Communicates enterprise software transitions to minimize employee anxiety." },
  { title: "Empathetic Design Research Interviewing", desc: "Conducts deep ethnographic interviews uncovering latent user needs." },
  { title: "High-Stakes Media Press Conference Q&A", desc: "Prepares corporate spokespeople to handle hostile press questioning." },
  { title: "Product Manager vs Engineering Trade-off Negotiation", desc: "Facilitates constructive trade-off debates between scope and technical debt." },
  { title: "Peer Mentorship Knowledge Transfer Dialogue", desc: "Structures knowledge sharing sessions between senior and junior engineers." },
  { title: "Executive Compensation Negotiation Dialogue", desc: "Navigates executive job offer compensation negotiations professionally." },
  { title: "Nonprofit Donor Relationship Cultivation", desc: "Builds long-term relationships with major philanthropic donors." },
  { title: "Patient-Centered Medical Consultation Arc", desc: "Conducts thorough, empathetic medical consultations active in shared decision making." },
  { title: "Agile Retrospective Retrospective Facilitation", desc: "Leads team retrospectives that produce actionable process improvements." },
  { title: "Strategic Partnership Exploratory Meeting", desc: "Conducts initial partnership meetings exploring mutual win-win opportunities." },
  { title: "Diplomatic Open Source Contributor PR Feedback", desc: "Reviews open source pull requests with encouraging, constructive guidance." },
  { title: "Customer Churn Prevention Save Offer Dialogue", desc: "Engages cancelling customers with personalized save offers." },
  { title: "Cross-Functional Post-Mortem Facilitation", desc: "Leads blameless post-mortem reviews isolating systemic process failures." },
  { title: "Executive Thought Leadership Podcast Guest Arc", desc: "Prepares executives to deliver high-impact podcast interview appearances." },
  { title: "Sales Demo Custom Value Proposition Alignment", desc: "Tailors live product demos directly to prospect pain points." },
  { title: "Diplomatic Board Meeting Dispute Neutralization", desc: "De-escalates tense board meeting disagreements toward constructive consensus." },
  { title: "Inclusive Discussion Moderation for Introverts", desc: "Ensures quieter team members have structured space to share insights." },
  { title: "Remote Onboarding Welcome & Integration Arc", desc: "Welcomes new remote hires with structured check-ins and buddy pairing." },
  { title: "Enterprise Procurement Security Review Defense", desc: "Answers enterprise security questionnaire queries with confidence." },
  { title: "Consultative Problem-Solving Client Session", desc: "Leads collaborative client strategy sessions to co-create solutions." },
  { title: "Community Guild Leadership Communication", desc: "Leads internal practice guilds driving technology standardization." },
  { title: "Comprehensive Conversational Mastery Protocol", desc: "Applies world-class dialogue, active listening, and negotiation techniques." }
];

const batch3_dialogue = makeSkills('dialogue', 'dialogue', 'dialogue', 90, DIALOGUE_ITEMS);
appendSkills(batch3_dialogue.catFileName, batch3_dialogue.skills);

console.log('Batch 3 complete!');
