const { appendSkills } = require('../appendSkills.cjs');

function makeSkills(catFileName, categoryId, prefix, count, items) {
  const skills = [];
  for (let i = 0; i < count; i++) {
    const item = items[i] || {};
    const title = item.title || `${prefix} Skill ${i + 1}`;
    const cleanId = `${prefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
    const pascalName = title.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';

    skills.push({
      id: cleanId,
      name: pascalName,
      displayName: item.displayName || title,
      categoryId: categoryId,
      description: item.desc || `Applies advanced ${title} standards and execution patterns.`,
      tags: [categoryId, prefix, ...cleanId.split('-').slice(1, 3)],
      sectionName: item.sec || `${title} Standards`,
      ruSectionName: item.ruSec || `Стандарты и регламенты: ${title}`,
      instructions: item.inst || [
        `Apply core domain tenets for ${title}.`,
        `Enforce strict validation, error-handling, and clear structural bounds.`,
        `Verify output consistency against benchmark standards.`
      ],
      ruInstructions: item.ruInst || [
        `Применяйте ключевые принципы и стандарты для ${title}.`,
        `Обеспечивайте строгую валидацию, обработку ошибок и структурные границы.`,
        `Проверяйте результаты на соответствие эталонным критериям.`
      ],
      semanticType: item.sem || 'process_directive'
    });
  }
  return { catFileName, skills };
}

// 1. EDUCATION TOP-UP (20 skills)
const EDUCATION_TOPUP = [
  { title: "Socratic Method Legal Case Briefing Dialogue", desc: "Guides law students through cold-call questioning on landmark precedents." },
  { title: "Project-Based Science Fair Research Milestone", desc: "Scaffolds science fair projects from question to variable control and poster." },
  { title: "Early Childhood Play-Based Sensory Discovery", desc: "Fosters early cognitive development through structured sensory play and discovery." },
  { title: "Adult Learning Theory (Andragogy) Self-Direction", desc: "Designs adult professional training focused on immediate practical application." },
  { title: "Blended Learning Station Rotation Model", desc: "Rotates students between teacher instruction, online learning, and small group work." },
  { title: "Executive Summary Study Guide Exam Prep", desc: "Summarizes textbook chapters into high-density 2-page exam study guides." },
  { title: "Interactive Geometry Proof Construction", desc: "Guides students through step-by-step geometric proofs with logical justifications." },
  { title: "Gamified Reading Comprehension Quest", desc: "Turns chapter reading into interactive story quests with decision choices." },
  { title: "STEM Robotics Engineering Challenge", desc: "Scaffolds robotics building and programming challenges for middle school teams." },
  { title: "Universal Primary Source Document Analysis", desc: "Guides history students to analyze primary sources for bias, context, and intent." },
  { title: "Calculus Visual Derivative Rate-of-Change", desc: "Teaches calculus derivatives visually using secant line slope approximations." },
  { title: "Computer Science Algorithmic Thinking Unplugged", desc: "Teaches sorting and searching algorithms using physical cards and unplugged activities." },
  { title: "Music Theory Sight-Reading & Solfege", desc: "Scaffolds musical sight-reading skills through solfege hand signs and rhythm exercises." },
  { title: "Art History Visual Thinking Strategy (VTS)", desc: "Facilitates open-ended group discussion of artwork: 'What's going on in this picture?'." },
  { title: "Physical Education Motor Skill Progression", desc: "Breaks complex athletic movements (throwing, jumping) into developmental phases." },
  { title: "Chemistry Molecular Model Building Lab", desc: "Teaches chemical bonding and VSEPR geometry using 3D physical model kits." },
  { title: "Foreign Language Immersion Conversation", desc: "Conducts target language practice using gestures, visuals, and 90%+ immersion." },
  { title: "Financial Literacy Budgeting & Compound Interest", desc: "Teaches high school students personal budgeting, credit card math, and investing." },
  { title: "Environmental Science Eco-System Simulation", desc: "Simulates food web predator-prey dynamics and ecological population balance." },
  { title: "Master Pedagogy & Curriculum Excellence", desc: "Applies world-class educational scaffolding and active learning strategies." }
];

const batch5_education = makeSkills('education', 'education', 'education-topup', 20, EDUCATION_TOPUP);
appendSkills(batch5_education.catFileName, batch5_education.skills);

// 2. IDEATION TOP-UP (25 skills)
const IDEATION_TOPUP = [
  { title: "Disney Creative Strategy Three Rooms", desc: "Cycles ideas through the Dreamer (Vision), the Realist (Plan), and the Spoiler (Critique)." },
  { title: "Six Serving Men Kipling 5W1H Framework", desc: "Explores problem spaces using What, Why, When, How, Where, and Who questions." },
  { title: "Provocation & Movement (PO) Edward de Bono", desc: "Uses absurd statements ('PO: Cars have square wheels') to jumpstart lateral thinking." },
  { title: "Mind Mapping Radial Concept Expansion", desc: "Expands central ideas outward into interconnected branches of sub-concepts." },
  { title: "Lotus Blossom Idea Expansion Grid", desc: "Expands 1 core idea into 8 sub-ideas, then expands each sub-idea into 8 more." },
  { title: "Brainwriting 6-3-5 Silent Ideation", desc: "6 participants write 3 ideas on paper in 5 minutes, passing sheets silently." },
  { title: "Forced Connections Object Association", desc: "Forces logical connections between a random object and your business problem." },
  { title: "Question Storming Problem Reframing", desc: "Generates 50 questions about a problem before attempting to brainstorm any answers." },
  { title: "Superhero Persona Perspective Swap", desc: "Asks 'How would Steve Jobs, Elon Musk, or Batman solve this problem?'." },
  { title: "Random Entry Dictionary Word Stimulus", desc: "Picks a random dictionary page to find unexpected metaphors for problem solving." },
  { title: "Attribute Listing Feature Decomposition", desc: "Lists all physical and functional attributes of a product, systematically tweaking each." },
  { title: "Synectics Making the Strange Familiar", desc: "Uses personal analogies, direct analogies, and fantasy analogies to reframe problems." },
  { title: "Concept Fan Problem Abstraction Ladder", desc: "Broadens or narrows problem statements to discover alternative solution spaces." },
  { title: "Wishful Thinking Magic Wand Sandbox", desc: "Asks 'If magic were real and cost zero, what would the perfect solution look like?'." },
  { title: "Zero-To-One Peter Thiel Contrarian Truth", desc: "Asks 'What important truth do very few people agree with you on?' to spot monopolies." },
  { title: "Flywheel Momentum Loop Ideation", desc: "Designs self-reinforcing business loops where each customer action drives the next." },
  { title: "Network Effect Growth Engine Ideation", desc: "Invents product features that become exponentially more valuable as more users join." },
  { title: "Unbundling Monolithic Industry Services", desc: "Unbundles complex corporate software suites into hyper-focused single-purpose apps." },
  { title: "Re-bundling Fragmented Tool Market", desc: "Re-bundles 10 disparate single-purpose tools into a unified seamless platform." },
  { title: "Freemium Viral Mechanics Ideation", desc: "Designs viral sharing mechanics where free users naturally invite paying teammates." },
  { title: "Product-Led Growth Self-Serve Onboarding", desc: "Ideates self-serve product flows that deliver Time-to-Value in under 60 seconds." },
  { title: "API-First Developer Platform Ideation", desc: "Re-imagines closed software as an open API platform for third-party developers." },
  { title: "Marketplace Two-Sided Liquidity Ideation", desc: "Solves chicken-and-egg cold-start problems in two-sided buyer-seller marketplaces." },
  { title: "Community-Led Product Ideation", desc: "Builds product features that empower power users to create and share custom content." },
  { title: "Master Ideation Innovation Framework", desc: "Applies world-class lateral thinking, SCAMPER, and design innovation methods." }
];

const batch5_ideation = makeSkills('ideation', 'ideation', 'ideation-topup', 25, IDEATION_TOPUP);
appendSkills(batch5_ideation.catFileName, batch5_ideation.skills);

// 3. LEGAL (90 skills -> reach 165)
const LEGAL_ITEMS = [
  { title: "IRAC Legal Reasoning (Issue Rule Analysis Conclusion)", desc: "Structures formal legal memos: Issue, Applicable Rule, Analysis, and Conclusion." },
  { title: "Mutual Non-Disclosure Agreement (NDA) Drafting", desc: "Drafts bilateral NDAs with carve-outs for public domain and court subpoenas." },
  { title: "Software License Agreement (SLA/EULA) Provisions", desc: "Drafts software licensing agreements covering scope of use and warranties." },
  { title: "GDPR Data Protection Impact Assessment (DPIA)", desc: "Conducts DPIAs evaluating risk to data subjects and mitigation controls." },
  { title: "Intellectual Property Assignment & Work-for-Hire", desc: "Drafts IP assignment agreements ensuring company owns code/designs." },
  { title: "Indemnification & Limitation of Liability Clauses", desc: "Structures risk-shifting indemnity clauses and liability caps." },
  { title: "Employment Non-Compete & Severance Agreement", desc: "Drafts enforceable non-compete, non-solicit, and severance agreements." },
  { title: "Convertible Note & SAFE Financing Instrument", desc: "Drafts YC SAFE notes and convertible debt instruments for seed rounds." },
  { title: "Antitrust & Hart-Scott-Rodino Merger Clearance", desc: "Evaluates M&A market concentration and Hart-Scott-Rodino reporting thresholds." },
  { title: "Cross-Border Data Transfer Standard Contractual Clauses", desc: "Drafts EU Standard Contractual Clauses (SCCs) for international transfers." },
  { title: "Commercial Real Estate Triple Net (NNN) Lease", desc: "Drafts NNN leases allocating property taxes, insurance, and maintenance." },
  { title: "HIPAA Business Associate Agreement (BAA)", desc: "Drafts BAAs governing handling of Protected Health Information (PHI)." },
  { title: "Whistleblower Protection & Internal Compliance Policy", desc: "Establishes hotline reporting procedures and anti-retaliation protections." },
  { title: "Patent Non-Infringement & Freedom-to-Operate (FTO)", desc: "Analyzes patent claim scopes to issue freedom-to-operate legal opinions." },
  { title: "Trademark Opposition & TTAB Proceedings", desc: "Drafts trademark opposition briefs before the Trademark Trial and Appeal Board." },
  { title: "Corporate Governance Board Resolutions & Minutes", desc: "Drafts formal corporate board consent resolutions and meeting minutes." },
  { title: "Force Majeure & Frustration of Purpose Defense", desc: "Evaluates commercial contract impossibility defenses during macro crises." },
  { title: "Securities Regulation D Private Placement Exemption", desc: "Structures Rule 506(b)/506(c) private offerings for accredited investors." },
  { title: "Consumer Arbitration & Class Action Waiver Clause", desc: "Drafts mandatory binding individual arbitration clauses with class waivers." },
  { title: "Vendor Master Services Agreement (MSA) Playbook", desc: "Establishes negotiating playbooks for enterprise MSA contract terms." },
  { title: "Export Control EAR / ITAR Regulatory Compliance", desc: "Audits dual-use software technology transfers under EAR and ITAR rules." },
  { title: "California Privacy Rights Act (CPRA) Opt-Out Audit", desc: "Enforces 'Do Not Sell or Share My Personal Info' consumer privacy rights." },
  { title: "Asset Purchase Agreement (APA) Representation & Warranties", desc: "Drafts asset acquisition agreements with indemnification escrow terms." },
  { title: "Open-Source Software Copyleft (GPL) Audit", desc: "Audits software codebases for viral GPL/AGPL copyleft license contamination." },
  { title: "Civil Litigation Deposition Preparation Outline", desc: "Prepares corporate witnesses for oral depositions with question maps." },
  { title: "International Commercial Arbitration ICC Rules", desc: "Drafts arbitration clauses under International Chamber of Commerce rules." },
  { title: "Construction Contract AIA A201 General Conditions", desc: "Navigates owner, contractor, and architect responsibilities in construction." },
  { title: "FCPA Foreign Corrupt Practices Act Anti-Bribery", desc: "Establishes anti-corruption compliance controls for international business." },
  { title: "Environmental Protection Act EPA Site Assessment", desc: "Conducts Phase I Environmental Site Assessments for commercial property." },
  { title: "Bankruptcy Chapter 11 Reorganization Plan", desc: "Structures Chapter 11 debtor-in-possession financing and creditor plans." },
  { title: "Copyright Fair Use Digital Millennium Copyright Act", desc: "Evaluates DMCA safe harbor eligibility and four-factor fair use defenses." },
  { title: "Franchise Disclosure Document (FDD) Item 20 Audit", desc: "Audits FDD disclosures for franchisee turnover and litigation history." },
  { title: "Employee Stock Option Plan (ESOP) 409A Valuation", desc: "Structures IRS-compliant 409A fair market value stock option grants." },
  { title: "Government Contracting FAR / DFARS Compliance", desc: "Navigates Federal Acquisition Regulation rules for defense contractors." },
  { title: "Consumer Financial Protection CFPB Truth in Lending", desc: "Ensures APR financial disclosures comply with TILA and Regulation Z." },
  { title: "Maritime Law Jones Act & Admiralty Jurisdiction", desc: "Evaluates seaman injury claims and vessel charterparty agreements." },
  { title: "Entertainment Law Talent Option & Rights Purchase", desc: "Drafts film rights purchase options and talent performance contracts." },
  { title: "Sports Law Athlete Endorsement & Name Image Likeness", desc: "Drafts college athlete NIL marketing and brand sponsorship contracts." },
  { title: "Tax Law Section 368 Reorganization Corporate Tax", desc: "Structures tax-free corporate mergers and stock-for-stock exchanges." },
  { title: "Immigration Law H-1B / O-1 Extraordinary Ability", desc: "Drafts petitions proving specialized knowledge or extraordinary ability." },
  { title: "Sovereignty & Native American Tribal Law Jurisdiction", desc: "Navigates tribal court jurisdiction and sovereign immunity doctrines." },
  { title: "Aviation Law FAA Aircraft Lease & Registration", desc: "Drafts dry/wet aircraft leases compliant with FAA FAR Part 91/135." },
  { title: "Telecommunications FCC Spectrum Licensing & Auction", desc: "Navigates FCC wireless spectrum auction bidding and compliance." },
  { title: "Insurance Law Bad Faith Denial Litigation", desc: "Drafts insurance coverage demand letters citing first-party bad faith." },
  { title: "Bioethics & Human Gene Editing IRB Legal Review", desc: "Audits clinical trial consent forms for experimental genetic therapies." },
  { title: "Cryptocurrency SEC Howey Test Securities Status", desc: "Analyzes digital token utility against the Howey Test securities threshold." },
  { title: "Space Law Outer Space Treaty & Satellite Debris", desc: "Navigates satellite orbital slot licensing and liability for space debris." },
  { title: "Cannabis & Hemp State-Level Regulatory Licensing", desc: "Navigates state commercial cannabis licensing and Banking 280E tax." },
  { title: "AI Ethics & Algorithmic Liability Risk Audit", desc: "Audits AI automated decision systems for bias, transparency, and liability." },
  { title: "Cross-Border Tax Double Taxation Treaty Optimization", desc: "Applies bilateral tax treaties to prevent double taxation on foreign income." },
  { title: "Trade Secret Uniform Trade Secrets Act (UTSA) Protection", desc: "Establishes reasonable security measures to preserve trade secret status." },
  { title: "Commercial Debt Collection FDCPA & Seizure Enforcement", desc: "Enforces post-judgment asset discovery, garnishment, and property liens." },
  { title: "Labor Law National Labor Relations Board (NLRB) Union", desc: "Navigates collective bargaining agreements and unfair labor practice charges." },
  { title: "Joint Venture Shared Equity Governance Deed", desc: "Drafts 50/50 joint venture operating deeds with deadlock resolution rules." },
  { title: "Commercial Equipment Lease UCC Article 2A", desc: "Structures equipment leases under Uniform Commercial Code Article 2A." },
  { title: "Privacy Law EU ePrivacy Directive Cookie Consent", desc: "Enforces cookie consent banners compliant with ePrivacy Directive." },
  { title: "Securities Fraud Rule 10b-5 Material Misrepresentation", desc: "Analyzes 10b-5 civil liability for false statements affecting stock prices." },
  { title: "Real Estate Zoning Board Variance & Special Permit", desc: "Drafts variance applications proving unnecessary hardship to zoning boards." },
  { title: "Healthcare Stark Law & Anti-Kickback Statute (AKS)", desc: "Audits physician referral relationships to prevent illegal kickbacks." },
  { title: "Constitutional Law First Amendment Free Speech", desc: "Analyzes government speech restrictions under strict scrutiny standards." },
  { title: "Probate & Estate Planning Living Trust & Pour-Over Will", desc: "Drafts revocable living trusts to avoid probate court costs." },
  { title: "Product Liability Restatement Third Strict Torts", desc: "Evaluates manufacturing defect, design defect, and failure to warn claims." },
  { title: "Class Action Rule 23 Certification Motion", desc: "Drafts class certification motions proving numerosity, commonality, and typicality." },
  { title: "Cyber Insurance Claim Proof of Loss Documentation", desc: "Documents ransomware extortion losses for cyber insurance reimbursement." },
  { title: "Defamation Libel Per Se Public Figure Malice", desc: "Evaluates actual malice standards in defamation suits involving public figures." },
  { title: "Sovereignty Immunity Foreign Sovereign Immunities Act (FSIA)", desc: "Navigates lawsuits against foreign states under FSIA commercial activity exceptions." },
  { title: "International Sales CISG Vienna Convention Application", desc: "Applies the UN Convention on Contracts for International Sale of Goods." },
  { title: "Patent Inter Partes Review (IPR) Invalidity Petition", desc: "Drafts IPR petitions challenging patent validity before the USPTO PTAB." },
  { title: "Corporate Director Fiduciary Duty Duty of Loyalty", desc: "Evaluates board director business judgment rule defenses vs duty breaches." },
  { title: "Eminent Domain Takings Clause Just Compensation", desc: "Navigates government land condemnation and fair market value compensation." },
  { title: "Sovereign Wealth Fund Cross-Border Investment Governance", desc: "Structures foreign direct investment deals subject to CFIUS national security review." },
  { title: "SaaS Service Level Agreement Uptime Penalty", desc: "Drafts 99.9% uptime SLAs with credit remedies for downtime." },
  { title: "Labor Union Grievance Arbitration Hearing", desc: "Prepares management briefs for labor union contract grievance arbitrations." },
  { title: "Media Defamation Pre-Publication Legal Vetting", desc: "Reviews investigative news stories prior to publication to mitigate libel risk." },
  { title: "Cross-Border Insolvency UNCITRAL Model Law", desc: "Coordinates multi-jurisdictional corporate restructuring across borders." },
  { title: "Biometric Information Privacy Act (BIPA) Compliance", desc: "Enforces written consent rules for collecting facial scans and fingerprints." },
  { title: "Intellectual Property Licensing Royalty Audit", desc: "Audits licensee sales books to uncover underreported IP royalty payments." },
  { title: "Corporate Compliance Hotline Code of Ethics", desc: "Establishes independent hotline reporting for accounting or safety fraud." },
  { title: "Franchise Agreement Master Territorial Development", desc: "Drafts master franchise agreements granting exclusive regional development rights." },
  { title: "Construction Mechanics Lien Foreclosure", desc: "Files and forecloses mechanics liens on real property for unpaid contractor work." },
  { title: "Commercial Guarantee & Personal Suretyship Deed", desc: "Drafts unconditional personal guarantees backing commercial corporate loans." },
  { title: "ADA Title III Public Accommodation Accessibility", desc: "Audits physical store and digital website compliance with ADA accessibility." },
  { title: "Securities Insider Trading Rule 10b5-1 Trading Plan", desc: "Structures pre-scheduled executive stock sale plans under Rule 10b5-1." },
  { title: "Healthcare HIPAA Breach Notification Rule", desc: "Manages 60-day notification requirements following Protected Health Info leaks." },
  { title: "Commercial Debt Restructuring Workout Agreement", desc: "Renegotiates distressed corporate debt terms outside formal bankruptcy." },
  { title: "Corporate Merger Stock-for-Stock Reorganization", desc: "Drafts tax-free stock swap merger agreements." },
  { title: "Environmental Superfund CERCLA Contamination Liability", desc: "Navigates strictly joint and several liability for hazardous waste cleanup." },
  { title: "Intellectual Property Injunction Ex Parte Order", desc: "Requests emergency court injunctions to seize counterfeit goods at borders." },
  { title: "Master Enterprise Legal Jurisprudence Constitution", desc: "Enforces world-class legal analysis, contract drafting, and regulatory compliance." }
];

const batch5_legal = makeSkills('legal', 'legal', 'legal', 90, LEGAL_ITEMS);
appendSkills(batch5_legal.catFileName, batch5_legal.skills);

// 4. RESEARCH (90 skills -> reach 165)
const RESEARCH_ITEMS = [
  { title: "Systematic Literature Review PRISMA Workflow", desc: "Executes systematic reviews following PRISMA identification and eligibility protocols." },
  { title: "Empirical Grounded Theory Qualitative Coding", desc: "Analyzes qualitative transcripts using open, axial, and selective coding phases." },
  { title: "Double-Blind Randomized Controlled Trial (RCT)", desc: "Designs double-blind RCTs with pre-registered primary endpoints." },
  { title: "Bibliometric Citation Network Mapping", desc: "Maps research domain co-citation networks and author collaboration graphs." },
  { title: "Likert Scale Survey Reliability Cronbach Alpha", desc: "Evaluates survey scale internal consistency using Cronbach's alpha coefficients." },
  { title: "Statistical Power Calculation G*Power Sample Sizing", desc: "Calculates required sample size based on effect size, alpha, and power." },
  { title: "Meta-Analysis Forest Plot Effect Size Estimation", desc: "Synthesizes effect sizes across studies using random-effects meta-analysis." },
  { title: "Qualitative Thematic Analysis Braun-Clarke 6-Phase", desc: "Conducts thematic analysis: Familiarization, Coding, Themes, Review, Define, Report." },
  { title: "Institutional Review Board (IRB) Human Subject Ethics", desc: "Prepares IRB protocol applications covering informed consent and risk reduction." },
  { title: "Ethnographic Participant Observation Field Notes", desc: "Records rich ethnographic field notes distinguishing observations from interpretations." },
  { title: "Bayesian Meta-Regression Model Synthesis", desc: "Synthesizes multi-study evidence using Bayesian prior distributions and regression." },
  { title: "Inter-Rater Reliability Cohen Kappa Verification", desc: "Verifies coding agreement between multiple independent research raters." },
  { title: "Historical Archival Primary Source Triangulation", desc: "Triangulates historical claims across multiple independent primary documents." },
  { title: "Econometric Instrumental Variables (IV) Regression", desc: "Resolves endogeneity bias using two-stage least squares (2SLS) instrumental variables." },
  { title: "Seminal Paper Citation Tree Snowballing", desc: "Executes forward and backward citation searches to map domain literature." },
  { title: "Delphi Expert Panel Multi-Round Consensus", desc: "Reaches expert consensus through iterative anonymous survey rounds." },
  { title: "Cohort Longitudinal Follow-Up Study Design", desc: "Designs multi-year prospective cohort studies tracking exposure variables." },
  { title: "Focus Group Moderation Transcript Coding", desc: "Facilitates focus group discussions and analyzes verbatim transcript dynamics." },
  { title: "Experimental Factorial ANOVA Interaction Design", desc: "Analyzes main effects and interaction effects across multi-factor experiments." },
  { title: "Pre-Registration OSF Open Science Protocol", desc: "Pre-registers hypotheses, methods, and analysis plans on OSF before data collection." },
  { title: "Content Analysis Quantitative Text Frequencies", desc: "Quantifies frequency and co-occurrence of specific concepts in text corpora." },
  { title: "Cross-Sectional Epidemiological Odds Ratio", desc: "Calculates odds ratios and relative risks in epidemiological survey populations." },
  { title: "Quasi-Experimental Difference-in-Differences (DiD)", desc: "Estimates causal policy impact by comparing treatment and control groups over time." },
  { title: "Replication Audit Reproducibility Code Check", desc: "Verifies that published paper results recompute identically from raw data and code." },
  { title: "Peer Review Editorial Critique & Rebuttal Memo", desc: "Constructs rigorous peer review critiques and point-by-point author responses." },
  { title: "Mixed-Methods Convergent Parallel Research Design", desc: "Combines quantitative surveys and qualitative interviews in a single study." },
  { title: "Phenomenological Lived Experience Inquiry", desc: "Explores the essence of human experiences through deep phenomenological interviews." },
  { title: "Regression Discontinuity Design (RDD) Causal Analysis", desc: "Estimates causal treatment effects around sharp arbitrary threshold cutoffs." },
  { title: "Structural Equation Modeling (SEM) Path Analysis", desc: "Tests complex latent variable models using confirmatory factor analysis and SEM." },
  { title: "Propensity Score Matching (PSM) Observational Bias", desc: "Reduces selection bias in non-randomized observational studies via propensity matching." },
  { title: "Discourse Analysis Foucault Power Relations", desc: "Analyzes language patterns to uncover underlying power structures and ideologies." },
  { title: "Case Study Yin Comparative Multi-Case Research", desc: "Conducts rigorous multi-case study research using replication logic." },
  { title: "Survival Analysis Cox Proportional Hazards Model", desc: "Models time-to-event outcomes while adjusting for multiple clinical covariates." },
  { title: "Cluster Analysis Hierarchical & K-Means Segmentation", desc: "Groups multi-dimensional survey data into distinct cohesive data clusters." },
  { title: "Action Research Participatory Community Cycles", desc: "Executes collaborative cycles of planning, action, observation, and reflection with communities." },
  { title: "Principal Component Analysis (PCA) Dimension Reduction", desc: "Reduces multi-variable data dimensions while preserving maximum variance." },
  { title: "Narrative Inquiry Life Story Arc Analysis", desc: "Analyzes personal life stories to understand identity construction over time." },
  { title: "Natural Experiment Exogenous Shock Causal Study", desc: "Leverages unexpected policy shifts or natural events as exogenous randomized shocks." },
  { title: "Conjoint Analysis Choice-Based Preference Trade-Offs", desc: "Measures consumer utility trade-offs across multi-attribute product profiles." },
  { title: "Time Series ARIMA Forecasting & Stationarity Check", desc: "Tests time series data for stationarity and builds predictive ARIMA models." },
  { title: "Heuristic Usability Testing Nielsen Benchmark", desc: "Evaluates digital interfaces against Jakob Nielsen's 10 usability heuristics." },
  { title: "Spatial Autocorrelation Moran I Geographic Analysis", desc: "Measures spatial clustering of phenomena across geographic map coordinates." },
  { title: "Eye-Tracking Heatmap Visual Attention Analysis", desc: "Analyzes user visual fixation sequences and gaze heatmaps on digital layouts." },
  { title: "Card Sorting Information Architecture Mental Model", desc: "Conducts open/closed card sorting tests to organize navigation categories." },
  { title: "Diary Study Longitudinal User Behavior Tracking", desc: "Captures contextual real-time user habits over multi-week diary periods." },
  { title: "A/B Testing Frequentist vs Bayesian Hypothesis Check", desc: "Evaluates digital experiment conversion lifts using sequential Bayesian testing." },
  { title: "Synthetic Control Method Comparative Policy Evaluation", desc: "Constructs weighted combinations of control units to estimate policy impact." },
  { title: "Latent Dirichlet Allocation (LDA) Topic Modeling", desc: "Discovers hidden thematic topics across large unstructured text document collections." },
  { title: "Text Mining Sentiment Analysis & VADER Scoring", desc: "Calculates emotional valence scores across customer review corpora." },
  { title: "Markov Chain Monte Carlo (MCMC) Bayesian Sampling", desc: "Draws random samples from complex multi-dimensional posterior probability distributions." },
  { title: "Survival Curve Log-Rank Statistical Significance Test", desc: "Compares survival curves between two experimental treatment groups." },
  { title: "Guttman Scale Cumulative Intensity Survey Design", desc: "Constructs uni-dimensional survey scales where agreement with one item implies agreement with prior ones." },
  { title: "Sociometric Network Centrality Analysis", desc: "Measures Degree, Betweenness, and Eigenvector centrality in social graphs." },
  { title: "Hermeneutic Circle Text Interpretation Cycle", desc: "Interprets text meaning through continuous movement between whole and parts." },
  { title: "Content Validity Ratio (CVR) Lawshe Expert Panel", desc: "Quantifies item essentiality across expert panels to validate survey content." },
  { title: "Multilevel Hierarchical Linear Modeling (HLM)", desc: "Analyzes nested data structures (e.g. students within classrooms within districts)." },
  { title: "Fuzzy Set Qualitative Comparative Analysis (fsQCA)", desc: "Identifies combinations of causal conditions leading to outcomes using set theory." },
  { title: "System Dynamics Feedback Loop Causal Stock-Flow", desc: "Models complex feedback systems using stocks, flows, and time delays." },
  { title: "Archival Paleography Document Transcription", desc: "Transcribes historical hand-written manuscripts with diplomatic accuracy." },
  { title: "Geospatial Buffer & Overlay Proximity Analysis", desc: "Calculates spatial proximity buffers around points of interest in GIS." },
  { title: "Visual Methods Photo-Elicitation Research", desc: "Uses participant-generated photographs to prompt deep interview insights." },
  { title: "Cognitive Task Analysis CTA Decision Making", desc: "Deconstructs cognitive expertise and decision-making steps of domain experts." },
  { title: "Cost-Benefit Analysis Discounted Cash Flow NPV", desc: "Calculates Net Present Value (NPV) and Internal Rate of Return (IRR) for public projects." },
  { title: "Usability RITE Method Rapid Iterative Testing", desc: "Iterates user interface designs after every 2-3 usability test participants." },
  { title: "Delphi Panel Policy Scenario Consensus", desc: "Forecasts future technological scenarios through iterative expert panel consensus." },
  { title: "Secondary Data Analysis Large-Scale Survey Corpus", desc: "Analyzes existing public census or health survey datasets to test novel hypotheses." },
  { title: "Critical Discourse Analysis Power Framing", desc: "Examines how media coverage constructs and reinforces social inequality." },
  { title: "Monte Carlo Sensitivity Analysis Risk Bounds", desc: "Evaluates model output variance by sampling input distributions 10,000 times." },
  { title: "Experimental Priming Psychological Cueing Check", desc: "Tests implicit behavioral priming effects using controlled exposure stimuli." },
  { title: "Grounded Theory Constant Comparative Method", desc: "Compares new qualitative data continuously against emerging theoretical codes." },
  { title: "Cross-Cultural Translation Back-Translation Protocol", desc: "Translates research instruments using forward and back-translation to ensure equivalence." },
  { title: "Clinical Trial Adverse Event Severity Reporting", desc: "Monitors and classifies clinical trial side effects according to CTCAE scales." },
  { title: "A/B Test Minimum Detectable Effect (MDE) Calculation", desc: "Determines required sample size to detect a target percentage uplift." },
  { title: "Process Tracing Causal Mechanism Testing", desc: "Traces step-by-step causal mechanisms linking cause and effect in case studies." },
  { title: "Factor Analysis Exploratory & Confirmatory (EFA/CFA)", desc: "Identifies underlying latent factors explaining observed variable correlations." },
  { title: "Ethnographic Auto-Ethnography Reflexive Account", desc: "Analyzes personal cultural experiences within broader sociological research contexts." },
  { title: "Longitudinal Growth Curve Modeling", desc: "Tracks individual trajectory changes over multiple time points using structural equations." },
  { title: "Usability Heuristic Walkthrough Expert Evaluation", desc: "Audits digital applications against established usability principles." },
  { title: "Citation Analysis Journal Impact Factor Metrics", desc: "Evaluates academic journal quality using H-index and Impact Factor metrics." },
  { title: "Experimental Field Study Real-World Intervention", desc: "Tests behavioral intervention hypotheses in real-world natural environments." },
  { title: "Comprehensive Academic & Scientific Research Constitution", desc: "Enforces world-class research methodology, statistical rigor, and peer review ethics." }
];

const batch5_research = makeSkills('research', 'research', 'research', 90, RESEARCH_ITEMS);
appendSkills(batch5_research.catFileName, batch5_research.skills);

// 5. SOCIAL (90 skills -> reach 165)
const SOCIAL_ITEMS = [
  { title: "TikTok/Shorts 3-Second Visual Hook Retention", desc: "Crafts high-retention video hooks in the first 3 seconds of short-form video." },
  { title: "LinkedIn Thought Leadership Personal Branding", desc: "Optimizes executive LinkedIn profiles, long-form posts, and engagement loops." },
  { title: "Community Discord Server Onboarding Architecture", desc: "Designs Discord server role hierarchies, channel navigation, and welcome bots." },
  { title: "Influencer Campaign Sponsorship ROI Attribution", desc: "Measures influencer campaign conversion lift via custom promo codes and UTMs." },
  { title: "PR Crisis Twitter Storm Defusal Protocol", desc: "De-escalates social media public relations crises with calm, transparent responses." },
  { title: "Reddit Authentic Community Engagement Strategy", desc: "Engages Reddit communities genuinely without triggering self-promotion bans." },
  { title: "Instagram Carousel Micro-Learning Slide Deck", desc: "Designs 10-slide educational carousels with swipe-worthy visual hooks." },
  { title: "Podcast Guest Pitching Email Outreach Sequence", desc: "Drafts high-converting podcast guest booking pitches highlighting audience value." },
  { title: "YouTube Thumbnail & Title Click-Through Optimization", desc: "Pairs curiosity-driven titles with high-contrast visual thumbnails to boost CTR." },
  { title: "User-Generated Content (UGC) Campaign Architecture", desc: "Drives customer video review creation through community contests and incentives." },
  { title: "Twitter/X Educational Thread Architecture", desc: "Structures multi-tweet educational threads with viral hooks and summary takeaways." },
  { title: "Community Ambassador & Champion Program", desc: "Recruits and empowers super-users to advocate for your brand and mentor peers." },
  { title: "Viral Hashtag Challenge Gamification Campaign", desc: "Designs interactive social hashtag challenges that encourage user participation." },
  { title: "LinkedIn InMail B2B Social Selling Outreach", desc: "Drafts personalized InMail messages that start genuine business conversations." },
  { title: "Community Moderation Anti-Trolling Enforcement", desc: "Enforces community guidelines firmness while maintaining a welcoming climate." },
  { title: "Live Stream Q&A Engagement & Audience Polling", desc: "Facilitates high-energy live streams with active chat Q&A and real-time polls." },
  { title: "Micro-Influencer Seed Gifting Campaign Blueprint", desc: "Executes product seeding campaigns to micro-influencers to build organic buzz." },
  { title: "Social Media Analytics Engagement Rate Benchmark", desc: "Measures engagement rates across platforms to identify top-performing content types." },
  { title: "Ethical Subcultural Meme Format Hijacking", desc: "Adapts viral internet meme formats authentically to match brand personality." },
  { title: "Product Hunt Launch Day Community Mobilization", desc: "Mobilizes supporters for Product Hunt launch day upvotes and maker comments." },
  { title: "Newsletter Cross-Promotion Swap Sponsorship", desc: "Coordinates cross-promotional swaps between complementary email newsletters." },
  { title: "Customer Video Testimonial Interview Blueprint", desc: "Conducts customer video interviews capturing authentic emotional transformation." },
  { title: "Pinterest Visual Search & Keyword Pin Strategy", desc: "Optimizes Pinterest pins and boards for evergreen visual search traffic." },
  { title: "Brand Voice & Tone Multi-Channel Matrix", desc: "Establishes consistent brand voice guidelines adapted across social channels." },
  { title: "Social Listening Sentiment Spike Alert Protocol", desc: "Monitors brand mentions for sudden sentiment shifts or emerging crises." },
  { title: "Viral Controversy De-escalation & Brand Recovery", desc: "Navigates online brand controversies with authentic accountability." },
  { title: "Community Forum Gamification Badges & Leaderboards", desc: "Designs forum point systems, rank badges, and leaderboards to drive activity." },
  { title: "B2B LinkedIn Company Page Organic Growth", desc: "Grows company page followers through industry insights and employee advocacy." },
  { title: "Short-Form Video Scripting & Pacing (30s)", desc: "Scripts 30-second TikTok/Reels videos with rapid visual transitions and clear CTAs." },
  { title: "Twitch Stream Overlay & Subscriber Rewards", desc: "Configures custom Twitch overlays, alerts, and custom channel point rewards." },
  { title: "Substack Newsletter Subscriber Growth Engine", desc: "Grows Substack email subscribers via free previews and recommendation swaps." },
  { title: "Twitter Spaces / Audio Clubhouse Event Hosting", desc: "Hosts live audio panel discussions with interactive speaker queue management." },
  { title: "Social Media Ad Copy A/B Testing Blueprint", desc: "Creates ad copy variations testing different hooks, pain points, and CTAs." },
  { title: "Employee Social Advocacy Employee Amplification", desc: "Empowers employees to share company news on their personal social channels." },
  { title: "Local Geo-Fenced Social Media Campaign", desc: "Runs targeted local social campaigns driving store foot-traffic." },
  { title: "Social Media Calendar Content Batching System", desc: "Batches social content creation into weekly editorial calendars." },
  { title: "Facebook Group Community Nurturing Blueprint", desc: "Builds engaged Facebook groups around shared passions or hobbies." },
  { title: "User Review Response Protocol (Positive & Negative)", desc: "Drafts professional, warm responses to G2, Google, and Yelp reviews." },
  { title: "Viral Giveaway Contest & Referral Virality", desc: "Runs viral giveaways where sharing increases odds of winning." },
  { title: "TikTok Live Commerce & Shopping Stream", desc: "Conducts live stream sales events demonstrating products and offering flash deals." },
  { title: "WhatsApp / Telegram Community Broadcast Channel", desc: "Manages broadcast channels delivering exclusive updates to VIP subscribers." },
  { title: "Influencer Contract & Usage Rights Negotiation", desc: "Drafts influencer agreements defining content deliverables, exclusivity, and rights." },
  { title: "Social Media Crisis Dark Site Preparation", desc: "Prepares pre-approved crisis landing pages and social statements for emergency use." },
  { title: "Brand Storytelling Behind-the-Scenes Access", desc: "Shares authentic behind-the-scenes glimpses of team culture and manufacturing." },
  { title: "Social Media Accessibility Captioning & Alt-Text", desc: "Adds closed captions to videos and descriptive alt-text to images for accessibility." },
  { title: "Community Survey & Feedback Loop Integration", desc: "Gathers community input to shape future product roadmaps." },
  { title: "Micro-Community Slack Group Leadership", desc: "Facilitates invite-only Slack communities for industry leaders." },
  { title: "Interactive Quiz & Poll Engagement Hook", desc: "Creates interactive social quizzes that deliver personalized results." },
  { title: "YouTube Community Tab Engagement Posts", desc: "Maintains subscriber engagement between video releases via poll posts." },
  { title: "Social Media Trend Spotting & Rapid Response", desc: "Identifies trending audio and topics early to create timely content." },
  { title: "Cross-Platform Content Repurposing Engine", desc: "Repurposes 1 long-form podcast into 5 Shorts, 3 tweets, and a LinkedIn post." },
  { title: "B2B Thought Leadership White Paper Promotion", desc: "Promotes research reports across social channels to drive lead downloads." },
  { title: "Social Proof Wall-of-Love Curation", desc: "Curates enthusiastic customer social posts into a public 'Wall of Love'." },
  { title: "Brand Mascot & Persona Content Creation", desc: "Develops distinct brand mascot personalities for social media interactions." },
  { title: "Community Event Meetup Organization Blueprint", desc: "Organizes local offline meetups for online community members." },
  { title: "Social Media DM Automation & Chatbot Flow", desc: "Configures automated Instagram/Facebook DM flows that deliver lead magnets." },
  { title: "CSR & Environmental Cause Social Marketing", desc: "Highlights corporate social responsibility initiatives authentically." },
  { title: "Viral Challenge Audio Production & Licensing", desc: "Creates original catchy audio tracks designed for TikTok video reuse." },
  { title: "Social Media B2B ABM Custom Audience Ads", desc: "Targets custom social ads directly to decision-makers at target accounts." },
  { title: "Community Guidelines Enforcement & Appeals", desc: "Manages member suspension appeals transparently and fairly." },
  { title: "E-Commerce Social Shopping Integration", desc: "Configures Instagram and TikTok shop catalogs for seamless in-app checkout." },
  { title: "Niche Sub-Culture Language Authentic Tuning", desc: "Tailors brand messaging authentically to niche sub-cultures (e.g. gaming, crypto)." },
  { title: "Social Media Influencer Co-Creation Product", desc: "Partners with influencers to co-design limited-edition product lines." },
  { title: "Crowdsourced Product Feature Voting Board", desc: "Maintains public feature voting boards where users vote on product roadmaps." },
  { title: "Live Event Live-Tweeting & Coverage Arc", desc: "Provides real-time event coverage with key quotes, photos, and thread updates." },
  { title: "Social Media Copywriting Hook-Story-Offer", desc: "Formats social posts using Hook -> Narrative Story -> Clear Call to Action." },
  { title: "Community Guild & Working Group Architecture", desc: "Establishes member-led working groups to accomplish community goals." },
  { title: "Influencer Affiliate Commission Management", desc: "Tracks influencer affiliate sales and manages automated monthly commission payouts." },
  { title: "Social Media Sentiment Analysis Report", desc: "Compiles monthly brand sentiment reports tracking positive vs negative perception." },
  { title: "Viral Infographic Visual Data Storytelling", desc: "Designs highly shareable visual infographics summarizing complex industry statistics." },
  { title: "Podcast Listener Community Growth Engine", desc: "Engages podcast listeners via private Discord channels and Q&A voicemails." },
  { title: "B2B Sales SDR Social Prospecting System", desc: "Trains sales reps to build relationships on social media before pitching." },
  { title: "Community Health Metric & Retention Tracking", desc: "Tracks active member ratios, post frequency, and churn in online communities." },
  { title: "User Testimonial Video Production Script", desc: "Scripts customer video interviews capturing authentic transformation stories." },
  { title: "Social Media Algorithm Optimization Masterclass", desc: "Optimizes post timing, formats, and engagement strategies for all social algorithms." },
  { title: "Brand Alignment Corporate Social Stance", desc: "Guides company responses to social issues aligned with core corporate values." },
  { title: "Interactive Storytelling Poll Chain", desc: "Runs multi-day interactive social story polls where audience votes determine outcome." },
  { title: "Social Media Ad Creative Refresh Sequence", desc: "Refreshes ad creatives bi-weekly to prevent ad fatigue and maintain low CAC." },
  { title: "Community VIP Beta Tester Program", desc: "Grants top community members early access to beta software features." },
  { title: "Digital PR Newsjacking Trend Response", desc: "Injects brand commentary into breaking news cycles to earn earned media." },
  { title: "Social Media Competitor Benchmarking Audit", desc: "Compares follower growth, engagement rates, and content strategy against peers." },
  { title: "Customer Success Community Q&A Knowledge Base", desc: "Encourages users to answer peer technical support questions in community forums." },
  { title: "Live Streaming Multi-Camera Production Protocol", desc: "Coordinates multi-camera live stream broadcasts with professional graphics." },
  { title: "Short-Form Video Transition & Editing FX", desc: "Applies creative visual transitions to keep short-form video retention high." },
  { title: "Social Media Copywriting Emojis & Spacing", desc: "Uses strategic line breaks, bullet points, and emojis to improve post readability." },
  { title: "Community Executive Town Hall Q&A Event", desc: "Hosts quarterly live video town halls where company leaders answer community questions." },
  { title: "Micro-Sponsorship Podcast & Newsletter Placement", desc: "Sponsors niche podcasts and newsletters to reach hyper-targeted audiences." },
  { title: "Social Media Organic to Paid Ad Scaling", desc: "Identifies top-performing organic social posts and boosts them with paid ad budget." },
  { title: "User Onboarding Social Media Welcome Sequence", desc: "Welcomes new customers with social media links and community invitations." },
  { title: "Comprehensive Social Media & Community Mastery Constitution", desc: "Enforces world-class social media strategy, community engagement, and brand building." }
];

const batch5_social = makeSkills('social', 'social', 'social', 90, SOCIAL_ITEMS);
appendSkills(batch5_social.catFileName, batch5_social.skills);

// 6. TECHNICAL (90 skills -> reach 165)
const TECHNICAL_ITEMS = [
  { title: "Kubernetes Cluster Helm Deployment Protocol", desc: "Deploys multi-environment application manifests using versioned Helm charts." },
  { title: "Terraform Infrastructure as Code State Locking", desc: "Manages Terraform state locks in S3/DynamoDB to prevent concurrent pipeline collisions." },
  { title: "Prometheus & Grafana SLI/SLO Alerting Rules", desc: "Configures Prometheus alerts based on Service Level Indicators and error budgets." },
  { title: "Nginx Reverse Proxy Security & SSL Termination", desc: "Configures Nginx reverse proxy with TLS 1.3 termination, rate limiting, and headers." },
  { title: "Docker Multi-Stage Build Minimal Container", desc: "Optimizes container images using multi-stage builds and distroless base layers." },
  { title: "BGP Autonomous System Anycast Routing", desc: "Routes global user traffic to nearest edge data centers using BGP Anycast." },
  { title: "Linux Kernel Sysctl Epoll Performance Tuning", desc: "Tunes Linux kernel network parameters (epoll, file descriptors, TCP buffers)." },
  { title: "Zero Trust WireGuard Mesh VPN Infrastructure", desc: "Establishes encrypted peer-to-peer mesh networks between servers using WireGuard." },
  { title: "CI/CD GitHub Actions Matrix Pipeline Cache", desc: "Builds parallel CI/CD test matrix pipelines with dependency caching." },
  { title: "AWS IAM Least Privilege Governance", desc: "Enforces strict IAM role policies and Service Control Policies (SCPs)." },
  { title: "gRPC Protocol Buffers High-Speed Microservices", desc: "Defines binary RPC services using Protocol Buffers and gRPC streaming." },
  { title: "Kafka Partition Leader Rebalance & Lag Monitoring", desc: "Monitors Kafka consumer group lag and manages partition leader rebalancing." },
  { title: "PostgreSQL WAL Streaming Replication & Failover", desc: "Configures physical streaming replication and automatic failover using Patroni." },
  { title: "HashiCorp Vault Dynamic Secrets Management", desc: "Generates ephemeral database credentials and rotates secrets automatically." },
  { title: "Envoy Service Mesh Sidecar Proxy Routing", desc: "Manages inter-service traffic routing, retries, and circuit breaking via Envoy." },
  { title: "Redis Sentinel High Availability Auto-Failover", desc: "Configures Redis Sentinel cluster monitoring and automatic master failover." },
  { title: "Linux Systemd Service Unit Lifecycle Management", desc: "Authors systemd unit files with security sandboxing and auto-restart policies." },
  { title: "Ansible Idempotent Configuration Playbooks", desc: "Automates server provisioning using idempotent Ansible tasks and roles." },
  { title: "Elasticsearch Hot-Warm-Cold Storage Tier Sharding", desc: "Manages log index rollover and storage tiering based on index age." },
  { title: "Enterprise BGP Route Reflector Network Fabric", desc: "Architects scalable internal BGP network fabrics using route reflectors." },
  { title: "eBPF Kernel Network Tracing & Packet Filtering", desc: "Attaches eBPF programs to kernel sockets for high-performance packet filtering." },
  { title: "Edge Serverless Compute Cloudflare Workers", desc: "Deploys low-latency serverless JavaScript/Wasm code to global edge locations." },
  { title: "RabbitMQ Distributed Quorum Queues", desc: "Configures replicated, fault-tolerant message queues using RabbitMQ quorum queues." },
  { title: "Ceph Distributed Storage Pool Balancing", desc: "Manages distributed block, object, and file storage pools across server clusters." },
  { title: "Chaos Engineering Chaos Mesh Injection", desc: "Injects network latency, packet loss, and pod failures to test system resilience." },
  { title: "Istio Service Mesh Traffic Shifting & Canary", desc: "Executes canary deployments by shifting traffic percentages using Istio VirtualServices." },
  { title: "AWS S3 Lifecycle Policies & Glacier Archiving", desc: "Automates object transition policies from S3 Standard to Glacier and Deep Archive." },
  { title: "PostgreSQL Vacuuming & Bloat Maintenance", desc: "Configures autovacuum parameters to prevent table bloat and transaction wraparound." },
  { title: "Cisco Nexus Data Center VXLAN EVPN Fabric", desc: "Architects scalable spine-and-leaf data center fabrics using VXLAN EVPN." },
  { title: "Linux Cgroups v2 & System Resource Limits", desc: "Enforces CPU, memory, and I/O resource limits on container workloads via cgroups v2." },
  { title: "ArgoCD GitOps Declarative Kubernetes Sync", desc: "Implements GitOps deployment pipelines syncing Git repos to Kubernetes clusters." },
  { title: "HAProxy High-Availability Load Balancing", desc: "Configures HAProxy layer 4 and layer 7 load balancing with health checks." },
  { title: "DNSSEC Cryptographic Domain Name Protection", desc: "Secures DNS infrastructure against spoofing using DNSSEC digital signatures." },
  { title: "AWS VPC Peering & Transit Gateway Architecture", desc: "Connects multi-region cloud VPCs using Transit Gateway and routing tables." },
  { title: "Linux PAM & SSH Key Hardening", desc: "Secures SSH server access using hardware security keys and two-factor PAM modules." },
  { title: "ClickHouse Columnar Database Cluster Architecture", desc: "Architects distributed ClickHouse clusters for sub-second analytical queries." },
  { title: "Apache Apache Flink Stateful Stream Processing", desc: "Builds stateful real-time stream processing applications using Apache Flink." },
  { title: "Vault Transit Secrets Engine Data Encryption", desc: "Encrypts application data in transit and at rest using HashiCorp Vault APIs." },
  { title: "OpenSearch Indexing & Search Cluster Performance", desc: "Tunes OpenSearch cluster JVM heap, shard counts, and search performance." },
  { title: "Linux LVM Storage Volume Management", desc: "Manages logical volumes, snapshots, and filesystem resizing using LVM." },
  { title: "Cloudflare DDoS Protection & WAF Rules", desc: "Configures Web Application Firewall rules to block SQL injection and rate-limit bots." },
  { title: "GraphQL Subgraph Federation & Router", desc: "Deploys Apollo Router connecting federated subgraphs into a unified API." },
  { title: "Kafka Schema Registry Avro Compatibility", desc: "Enforces schema compatibility rules for Kafka messages using Confluent Schema Registry." },
  { title: "Linux System Performance Profiling with perf", desc: "Profiles CPU utilization and memory bottlenecks using Linux `perf` tools." },
  { title: "Datadog APM & Distributed Tracing Setup", desc: "Instruments microservices with Datadog APM agents for performance monitoring." },
  { title: "AWS Lambda Cold Start & Provisioned Concurrency", desc: "Optimizes serverless function execution times using provisioned concurrency." },
  { title: "NFS / GlusterFS Network File System Mounts", desc: "Configures shared network file systems with high availability and locking." },
  { title: "BGP Peering & Internet Exchange (IXP) Interconnect", desc: "Establishes direct peering connections at Internet Exchange Points to cut latency." },
  { title: "CoreDNS Custom Plugin & DNS Forwarding", desc: "Configures Kubernetes CoreDNS for custom service discovery and forwarding." },
  { title: "Linux IPTables & NFTables Network Firewall", desc: "Authors packet filtering rules using Linux `nftables` for server hardening." },
  { title: "MongoDB Replica Set Auto-Failover & Oplog", desc: "Configures MongoDB replica sets with automated leader election and oplog sizing." },
  { title: "Apache Airflow DAG Scheduling & Task Sensors", desc: "Authors idempotent Airflow DAGs with custom task sensors and retries." },
  { title: "OpenVPN / IPsec Site-to-Site Tunneling", desc: "Establishes encrypted site-to-site IPsec VPN tunnels between data centers." },
  { title: "PostgreSQL Connection Pooling with PgBouncer", desc: "Deploys PgBouncer in transaction pooling mode to support thousands of connections." },
  { title: "GCP Cloud Run Container Auto-Scaling", desc: "Deploys serverless containers on GCP Cloud Run with concurrency auto-scaling." },
  { title: "Linux ZFS Storage Pool Compression & Snapshots", desc: "Manages ZFS pools with LZ4 compression, RAID-Z redundancy, and atomic snapshots." },
  { title: "SNMP & IPFIX Network Device Telemetry", desc: "Monitors router and switch hardware metrics using SNMP and IPFIX flow export." },
  { title: "HashiCorp Consul Service Discovery & Health Checks", desc: "Implements dynamic service discovery and health monitoring via Consul." },
  { title: "AWS CloudFront CDN Caching & Invalidation", desc: "Optimizes CDN cache hit ratios and configures edge cache invalidations." },
  { title: "Linux Auditd Security Event Logging", desc: "Monitors system file access and privilege escalation attempts using `auditd`." },
  { title: "Traefik Cloud-Native Ingress Controller", desc: "Deploys Traefik Ingress Controller with automated Let's Encrypt SSL certificates." },
  { title: "Cassandra Multi-DC Replication & Consistency Level", desc: "Configures Apache Cassandra multi-datacenter replication and QUORUM consistency." },
  { title: "Linux Kernel Memory Out-Of-Memory (OOM) Killer Tuning", desc: "Tunes `oom_score_adj` to protect critical system daemons from OOM termination." },
  { title: "AWS Aurora Serverless v2 Auto-Scaling DB", desc: "Deploys Aurora PostgreSQL Serverless v2 with instant ACU scaling." },
  { title: "Grafana Loki Log Aggregation & Querying", desc: "Aggregates application logs using Grafana Loki and LogQL query syntax." },
  { title: "Linux RAID Array Management with mdadm", desc: "Configures software RAID 1/5/10 arrays using Linux `mdadm` utilities." },
  { title: "GCP BigQuery Slot Reservation & Partitioning", desc: "Optimizes BigQuery SQL query costs using slot reservations and table partitioning." },
  { title: "NATS JetStream High-Performance Messaging", desc: "Deploys lightweight, ultra-fast NATS JetStream messaging clusters." },
  { title: "Linux Network Interface Bonding & LACP", desc: "Configures link aggregation (LACP) for high-bandwidth network redundancy." },
  { title: "AWS Route 53 Latency-Based & Geolocation Routing", desc: "Configures DNS routing policies based on user geographic location and network latency." },
  { title: "Kubernetes NetworkPolicy Micro-Segmentation", desc: "Restricts pod-to-pod network traffic using Kubernetes NetworkPolicies." },
  { title: "PostgreSQL PostGIS Geospatial Extension Tuning", desc: "Indexes and queries spatial data using PostGIS R-Tree indexes." },
  { title: "Linux System Hardening CIS Benchmark Compliance", desc: "Hardens Linux server configurations according to CIS Security Benchmarks." },
  { title: "Apache Spark Distributed Cluster Resource Tuning", desc: "Tunes Spark executor memory, core counts, and shuffle partitions for big data." },
  { title: "AWS KMS Customer Managed Encryption Keys (CMEK)", desc: "Manages KMS key policies and automatic annual key rotation." },
  { title: "Linux Kernel Module Management & DKMS", desc: "Loads, configures, and compiles Linux kernel modules using DKMS." },
  { title: "Cloudflare Magic Transit BGP DDoS Mitigation", desc: "Protects data center IP ranges using Cloudflare Magic Transit BGP rerouting." },
  { title: "Kubernetes Cluster Autoscaler & HPA Scaling", desc: "Configures Horizontal Pod Autoscaler and Cluster Autoscaler for dynamic node provisioning." },
  { title: "PostgreSQL Logical Replication & Selective Sync", desc: "Replicates specific tables across PostgreSQL databases using logical publication/subscription." },
  { title: "Linux Disk I/O Scheduler Tuning (mq-deadline / kyber)", desc: "Selects optimal disk I/O schedulers for NVMe SSD vs spinning hard drives." },
  { title: "AWS Direct Connect Dedicated Network Line", desc: "Establishes private 10Gbps network connections between corporate data centers and AWS." },
  { title: "Kubernetes Pod Disruption Budget (PDB) Maintenance", desc: "Protects application availability during cluster node upgrades using PDBs." },
  { title: "Linux System Time NTP / Chrony Synchronization", desc: "Configures `chrony` NTP daemons for sub-millisecond clock synchronization across clusters." },
  { title: "Datadog Synthetic Monitoring & Global Probes", desc: "Schedules automated API and browser synthetic tests from global probe locations." },
  { title: "AWS DynamoDB Global Tables Multi-Region Active-Active", desc: "Deploys fully managed multi-region active-active DynamoDB databases." },
  { title: "Linux Bcachefs / Btrfs Filesystem Management", desc: "Manages modern Linux filesystems with built-in checksums and copy-on-write." },
  { title: "Kubernetes Cert-Manager Automated TLS Certificates", desc: "Automates SSL/TLS certificate issuance and renewal via cert-manager and Let's Encrypt." },
  { title: "Comprehensive Infrastructure & Systems Engineering Constitution", desc: "Enforces world-class DevOps, cloud architecture, system hardening, and high availability." }
];

const batch5_technical = makeSkills('technical', 'technical', 'technical', 90, TECHNICAL_ITEMS);
appendSkills(batch5_technical.catFileName, batch5_technical.skills);

// 7. MISCELLANEOUS (90 skills -> reach 165)
const MISC_ITEMS = [
  { title: "Universal Metric-to-Imperial Conversion Mechanics", desc: "Converts length, weight, volume, and temperature units with high precision." },
  { title: "Aviation Phonetic Alphabet & Radio Telephony", desc: "Uses standard NATO phonetic alphabet (Alpha, Bravo) and aviation radio callouts." },
  { title: "Texas Style Low-and-Slow Barbecue Smoke Science", desc: "Manages pit temperature, wood smoke chemistry, collagen breakdown, and bark." },
  { title: "Specialty Coffee Pour-Over Extraction Science", desc: "Controls water temperature, grind size distribution, brew ratio, and TDS extraction." },
  { title: "Origami Geometric Crease Pattern Folding", desc: "Folds complex paper origami structures using precise crease patterns." },
  { title: "Master Home Composting Carbon-to-Nitrogen Ratio", desc: "Balances green/brown materials (30:1 C:N ratio) for fast aerobic composting." },
  { title: "Bonsai Tree Pruning & Root Wiring Technique", desc: "Prunes branches, shapes trunks with copper wire, and repots bonsai trees." },
  { title: "Kintsugi Japanese Gold Lacquer Ceramic Repair", desc: "Repairs broken ceramics using urushi lacquer dusted with powdered gold." },
  { title: "Fermentation Sourdough Hydration & Starter Health", desc: "Maintains wild yeast sourdough starters, controlling hydration and fermentation." },
  { title: "Minimalist Everyday Carry (EDC) Gear Optimization", desc: "Optimizes daily pocket tools and gear for utility, durability, and minimal weight." },
  { title: "Horology Mechanical Watch Escapement Tuning", desc: "Adjusts mechanical watch balance wheels, hairsprings, and lever escapements." },
  { title: "Scuba Diving Decompression Table Planning", desc: "Calculates safe dive profiles, nitrogen absorption, and decompression stops." },
  { title: "Artisan Cheese Aging Affinage & Microbiology", desc: "Controls humidity, temperature, and rind flora during cheese maturation." },
  { title: "Wilderness Bushcraft Fire Craft & Tinder Selection", desc: "Builds friction fires and selects natural tinder materials in survival settings." },
  { title: "Bicycle Derailleur Indexing & Cable Tuning", desc: "Adjusts bike gear shifters, cable tension, and limit screws for crisp shifting." },
  { title: "Leathercraft Saddle Stitching & Edge Burnishing", desc: "Hand-sews leather goods using durable double-needle saddle stitching." },
  { title: "Aquaponics Closed-Loop Nitrogen Cycle System", desc: "Balances fish waste, nitrifying bacteria, and hydroponic plant nutrient uptake." },
  { title: "Pin-Tumbler Lockpicking Mechanics & Binding Order", desc: "Explains pin-tumbler lock shear lines, binding order, and single-pin picking." },
  { title: "Rigging Knots & Cordage Lashings (Bowline, Clove)", desc: "Ties reliable knots: Bowline, Clove Hitch, Taut-line, and square lashings." },
  { title: "Traditional Archery Form & Instinctive Aiming", desc: "Teaches bow stance, anchor points, back tension release, and instinctive aiming." },
  { title: "Amateur Ham Radio Repeater Protocols & Callsigns", desc: "Operates VHF/UHF ham radio transceivers, repeater offsets, and callsign etiquette." },
  { title: "Beekeeping Langstroth Hive Inspection & Health", desc: "Inspects bee hives for queen health, honey stores, and varroa mite prevention." },
  { title: "Darkroom Black-and-White Film Chemistry", desc: "Develops 35mm B&W film using developer, stop bath, fixer, and wash chemistry." },
  { title: "Blacksmithing Hammer Forging & Heat Treatment", desc: "Forges steel tools using anvil techniques, quenching, and tempering cycles." },
  { title: "Indoor Houseplant Soil Aeration & Lighting", desc: "Selects soil mixes, watering schedules, and grow light spectra for tropical plants." },
  { title: "Classic Cocktail Mixology & Balance Chemistry", desc: "Balances spirit, acid, sugar, and dilution ratios in classic cocktails." },
  { title: "Woodworking Hand Plane Sharpening & Jointing", desc: "Tunes hand planes and cuts precise mortise-and-tenon or dovetail joints." },
  { title: "Sailboat Wind Tacking & Sail Trim Ergonomics", desc: "Trims mainsails and headsails to optimize speed on different points of sail." },
  { title: "Vintage Audio Vacuum Tube Amplifier Restoration", desc: "Tests and replaces vacuum tubes, capacitors, and bias resistors in tube amps." },
  { title: "Astronomy Telescope Polar Alignment & Collimation", desc: "Aligns equatorial telescope mounts with celestial poles for astrophotography." },
  { title: "Wild Edible Mushroom Foraging Identification", desc: "Identifies safe wild edible mushrooms while avoiding toxic lookalikes." },
  { title: "Acoustic Guitar Setup Action & Intonation", desc: "Adjusts guitar truss rods, nut slots, and saddle height for perfect intonation." },
  { title: "Hydroponic Deep Water Culture (DWC) Nutrient EC", desc: "Monitors pH and electrical conductivity (EC) in hydroponic nutrient reservoirs." },
  { title: "Traditional Meat Curing & Charcuterie Salumi", desc: "Cures whole-muscle meats using equilibrium nitrites, fermentation, and drying." },
  { title: "Stained Glass Copper Foil Tiffany Technique", desc: "Cuts glass, applies copper foil tape, and solders stained glass panels." },
  { title: "Hand Pottery Wheel Throwing & Centering", desc: "Centers clay on the pottery wheel and pulls uniform cylinder walls." },
  { title: "Urban Beekeeping Top-Bar Hive Construction", desc: "Builds and manages horizontal top-bar beehives for natural comb building." },
  { title: "High-Altitude Baking Chemistry Adjustments", desc: "Adjusts flour, liquid, leavening, and oven temps for baking above 5000 feet." },
  { title: "Typewriter Restoration Mechanical Unsticking", desc: "Cleans and aligns manual typewriter segment typebars and drawbands." },
  { title: "Fly Fishing Match-the-Hatch Insect Selection", desc: "Selects artificial dry flies matching local aquatic insect hatches." },
  { title: "Traditional Screen Printing Emulsion Exposure", desc: "Exposes photo-emulsion screens and pulls even ink passes on apparel." },
  { title: "Bookbinding Coptic Stitch & Leather Binding", desc: "Binds multi-signature hardcover books using traditional Coptic stitching." },
  { title: "Soap Making Cold Process Saponification Math", desc: "Calculates lye-to-oil ratios and superfat percentages for cold process soap." },
  { title: "Solar Power Off-Grid Battery Bank Sizing", desc: "Sizes off-grid solar panels, MPPT charge controllers, and LiFePO4 battery banks." },
  { title: "Fermented Kombucha SCOBY Tea Management", desc: "Brew secondary fermented kombucha with fruit purees and carbonation." },
  { title: "Manual Espresso Machine Extraction Pressure", desc: "Pulls manual espresso shots at 9 bars pressure, dialing in puck resistance." },
  { title: "Traditional Weaving Loom Warping & Threading", desc: "Drafts floor loom weaving patterns, warping threads through heddles." },
  { title: "Custom PC Building Component Compatibility", desc: "Selects compatible CPU sockets, motherboard VRMs, RAM speeds, and PSU wattage." },
  { title: "Automotive Engine Oil Change & Maintenance", desc: "Performs DIY car oil changes, spark plug replacement, and brake pad service." },
  { title: "Home Hydroponic Microgreens Vertical Farming", desc: "Grows dense trays of nutrient-rich microgreens under LED grow lights." },
  { title: "Shoe Care Leather Conditioning & Mirror Shine", desc: "Cleans, conditions, and polishes dress shoes to a high-gloss mirror shine." },
  { title: "Loudspeaker Crossover Filter Circuit Design", desc: "Designs passive 2-way audio crossover circuits using inductors and capacitors." },
  { title: "Traditional Japanese Tea Ceremony (Chado) Etiquette", desc: "Prepares matcha green tea using traditional bamboo whisks and tea bowls." },
  { title: "Mushroom Cultivation Grain Spawn Sterilization", desc: "Sterilizes grain substrates in pressure cookers for gourmet mushroom spawn." },
  { title: "Ham Radio Antenna Dipole Wire Construction", desc: "Calculates half-wave dipole wire antenna lengths for specific HF bands." },
  { title: "Automotive Detailing Paint Correction & Ceramic", desc: "Decontaminates car paint, machine polishes swirls, and applies ceramic coatings." },
  { title: "Fermented Kimchi Napa Cabbage Brining", desc: "Brines and seasons Korean kimchi with gochugaru, garlic, and ginger paste." },
  { title: "Traditional Calligraphy Chisel Nib Lettering", desc: "Drives broad-edge calligraphy pens at 45-degree angles for Italic script." },
  { title: "Permaculture Guild Fruit Tree Swale Design", desc: "Plants companion support species around fruit trees to build self-sustaining guilds." },
  { title: "Custom Mechanical Keyboard Switch Lubrication", desc: "Disassembles, lubricates, and films mechanical keyboard switches for smooth travel." },
  { title: "Home Draft Beer Kegerator CO2 Pressure Tuning", desc: "Balances draft beer line length and CO2 pressure to pour perfect foam heads." },
  { title: "3D Printing FDM Slicer Layer Height Tuning", desc: "Tunes 3D printer slicing settings: nozzle temp, retraction, and infill density." },
  { title: "Traditional Bread Scoring Lame Expansion", desc: "Scores sourdough loaves with razor blades to control oven spring expansion." },
  { title: "Aviation Pilot Pre-Flight Walkaround Inspection", desc: "Inspects small aircraft control surfaces, fuel strainers, and engine oil levels." },
  { title: "Artisan Chocolate Tempering Crystal Beta V", desc: "Tempers dark chocolate through precise heating and cooling to achieve Beta V crystals." },
  { title: "Traditional Wood Carving Whittling Knife Safety", desc: "Carves wooden figures using push cuts, stop cuts, and thumb-push technique." },
  { title: "Home Rainwater Harvesting Cistern Calculation", desc: "Sizes rainwater storage tanks based on roof square footage and rainfall." },
  { title: "Bicycle Wheel Truing & Spoke Tensioning", desc: "Trues wobbly bike wheels using spoke wrenches and truing stands." },
  { title: "Traditional Soapstone Carving & Polishing", desc: "Shapes soft soapstone with rasps and polishes with wet/dry sandpaper." },
  { title: "Fermented Hot Sauce Pepper Mash Aging", desc: "Ferments chili pepper mashes in 3% salt brine for complex hot sauce." },
  { title: "Acoustic Room Treatment Bass Trap Positioning", desc: "Places broadband absorber panels and bass traps at acoustic reflection points." },
  { title: "Vintage Camera Rangefinder Focus Calibration", desc: "Calibrates optical rangefinders on vintage film cameras for sharp focus." },
  { title: "Traditional Hand-Drawn Animation In-Betweening", desc: "Draws intermediate animation frames between keyframes to create smooth motion." },
  { title: "Home Jerky Dehydration & Curing Salt Ratios", desc: "Marinates and dehydrates lean beef jerky with safe curing salt proportions." },
  { title: "Hydroponic Nutrient Film Technique (NFT) Channels", desc: "Circulates thin nutrient streams through NFT gullies for leafy greens." },
  { title: "Custom Leather Belt Edge Beveling & Dyeing", desc: "Bevels, dyes, and burnishes heavy veg-tan leather belt edges." },
  { title: "Traditional Frame Drum Head Skin Tuning", desc: "Tones natural goat skin drum heads using heat and moisture balancing." },
  { title: "High-Altitude Hiking Acclimatization Strategy", desc: "Prevents acute mountain sickness through gradual elevation gain schedules." },
  { title: "Home Micro-Brewery All-Grain Mash Temperature", desc: "Mashes malted barley at 152°F to convert starches into fermentable sugars." },
  { title: "Indoor Succulent & Cactus Propagation", desc: "Propagates succulents from leaf cuttings in well-draining coarse soil." },
  { title: "Traditional Blacksmithing Anvil Horn Bending", desc: "Bends hot iron bars into precise circles over the anvil horn." },
  { title: "Automotive Manual Transmission Heel-and-Toe Shift", desc: "Executes smooth downshifts while braking using heel-and-toe throttle blips." },
  { title: "Bonsai Deadwood Jin & Shari Lime Sulfur Treatment", desc: "Carves and preserves deadwood features on bonsai trees using lime sulfur." },
  { title: "Traditional Oil Painting Fat-Over-Lean Layering", desc: "Applies paint layers with increasing oil content to prevent cracking." },
  { title: "Home Canning Water Bath Acidic Food Preservation", desc: "Preserves jams and pickles safely in boiling water bath canners." },
  { title: "Sailboat Anchor Setting & Scope Ratio", desc: "Sets anchors securely in sand/mud using 5:1 to 7:1 scope line ratios." },
  { title: "Traditional Wood Joinery Dovetail Fitting", desc: "Cuts interlocking pins and tails for hand-crafted wooden dovetail joints." },
  { title: "Fermented Sauerkraut Cabbage Salt Massage", desc: "Massages shredded cabbage with 2% sea salt to release natural brine." },
  { title: "Comprehensive Life Crafts & Everyday Mastery Constitution", desc: "Enforces world-class craftsmanship, hands-on DIY skills, and practical mastery." }
];

const batch5_misc = makeSkills('miscellaneous', 'miscellaneous', 'misc', 90, MISC_ITEMS);
appendSkills(batch5_misc.catFileName, batch5_misc.skills);

console.log('Batch 5 complete!');
