const { appendSkills } = require('../appendSkills.cjs');

// Helper to generate structured skill entries efficiently
function makeSkills(catFileName, categoryId, prefix, count, items) {
  const skills = [];
  for (let i = 0; i < count; i++) {
    const item = items[i] || {};
    const title = item.title || `${prefix} Skill ${i + 1}`;
    const cleanId = `${prefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
    const pascalName = title.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';

    skills.push({
      id: cleanId,
      name: pascalName,
      displayName: item.displayName || title,
      categoryId: categoryId,
      description: item.desc || `Applies advanced ${title} standards and execution patterns.`,
      tags: [categoryId, prefix, ...cleanId.split('-').slice(1, 3)],
      sectionName: item.sec || `${title} Standards`,
      ruSectionName: item.ruSec || `Стандарты и регламенты: ${title}`,
      instructions: item.inst || [
        `Apply core domain tenets for ${title}.`,
        `Enforce strict validation, error-handling, and clear structural bounds.`,
        `Verify output consistency against benchmark standards.`
      ],
      ruInstructions: item.ruInst || [
        `Применяйте ключевые принципы и стандарты для ${title}.`,
        `Обеспечивайте строгую валидацию, обработку ошибок и структурные границы.`,
        `Проверяйте результаты на соответствие эталонным критериям.`
      ],
      semanticType: item.sem || 'process_directive'
    });
  }
  return { catFileName, skills };
}

// 1. CORE (55 skills)
const CORE_ITEMS = [
  { title: "Universal Task Scoping & Boundary Contract", desc: "Establishes non-overlapping operational scope, explicit inputs, outputs, and non-goals." },
  { title: "Constraint Hierarchy & Hard/Soft Preference Weighting", desc: "Prioritizes non-negotiable compliance rules over flexible stylistic formatting preferences." },
  { title: "Context Window Preservation & Token Pruning", desc: "Eliminates conversational fluff and boilerplate to maximize semantic context density." },
  { title: "Zero-Shot Task Instruction Framing", desc: "Formulates unambiguous task instructions without requiring prior few-shot examples." },
  { title: "Multi-Role Composite System Directive", desc: "Synthesizes dual perspectives (e.g. auditor + architect) into a single cohesive persona." },
  { title: "Explicit Output Format Pre-Commitment", desc: "Locks the response schema before generating any narrative analysis or reasoning." },
  { title: "Negative Space Non-Goal Exclusion", desc: "Defines explicit exclusions ('Do NOT do X, Y, or Z') to prevent unwanted agent drift." },
  { title: "Hierarchical Instruction Decomposition", desc: "Breaks complex multi-part prompts into nested, numbered sub-directives." },
  { title: "Anchor Context Injection & Grounding", desc: "Anchors reasoning strictly to provided source documents without external memory leak." },
  { title: "Iterative Refinement Self-Correction Loop", desc: "Executes an internal verification pass before outputting final response payloads." },
  { title: "Deterministic Variables Interpolation Template", desc: "Uses strict `{{variable_name}}` placeholders for dynamic runtime data binding." },
  { title: "Preamble & Metadata Header Protocol", desc: "Standardizes document meta-tags, timestamps, and execution context blocks." },
  { title: "Sovereign Task Authority & Tone Elevation", desc: "Establishes authoritative domain expertise and decisive professional judgment." },
  { title: "Edge Case & Exception Handling Matrix", desc: "Pre-defines handling behavior for missing data, null values, and edge anomalies." },
  { title: "Multi-Document Source Disambiguation", desc: "Resolves conflicting facts across multiple input sources via explicit provenance weighting." },
  { title: "Strict Input Payload Schema Validation", desc: "Validates incoming JSON/YAML payloads against structural type definitions before processing." },
  { title: "Prompt Versioning & Migration Tagging", desc: "Embeds semantic version identifiers (`v2.4.0`) to track instruction updates." },
  { title: "Conversational History Window Pruning", desc: "Summarizes and truncates old chat turns to maintain fast response generation." },
  { title: "Tone Modulation & Audience Adaptation", desc: "Adjusts technical complexity dynamically based on target audience persona." },
  { title: "Task Success Criteria & Verification Rubric", desc: "Lists explicit test conditions that must pass for the output to be considered valid." },
  { title: "Language Localization & Cultural Adaptation", desc: "Adapts idioms, date formats, and currencies to target locale expectations." },
  { title: "System Prompt Override Guard", desc: "Protects core system instructions from user-prompt injection and tampering." },
  { title: "Multi-Step Workflow Sequence Anchor", desc: "Enforces strict step-by-step progress tracking across multi-turn interactions." },
  { title: "Fallback Response Template Specification", desc: "Defines safe, informative fallback responses when primary generation fails." },
  { title: "Semantic Entity Disambiguation Rule", desc: "Clarifies ambiguous terms (e.g. Apple company vs fruit) before generating response." },
  { title: "Interactive Clarification Prompt Trigger", desc: "Asks targeted follow-up questions when user input is insufficient or ambiguous." },
  { title: "Multi-Perspective Balanced Synthesis", desc: "Presents opposing viewpoints fairly before articulating a grounded recommendation." },
  { title: "Uncertainty & Confidence Level Quantification", desc: "Annotates statements with explicit confidence ratings (High / Medium / Low)." },
  { title: "Summary-First Executive Structure (BLUF)", desc: "Leads with Bottom Line Up Front before detailing supporting evidence." },
  { title: "Explicit Assumptions Listing", desc: "States all underlying assumptions made when working with incomplete user prompts." },
  { title: "Token Budget Allocation & Chunking", desc: "Distributes available token length strategically across analysis, reasoning, and output." },
  { title: "Strict Fact-Checking Citation Constraint", desc: "Mandates inline citations for all factual assertions back to source text." },
  { title: "Jargon-to-Plain-Language Translation", desc: "Translates complex domain terminology into accessible everyday explanations." },
  { title: "Structured Markdown Document Architecture", desc: "Applies consistent heading levels (# H1, ## H2, ### H3) and visual callouts." },
  { title: "Anti-Repetition & Prose Conciseness", desc: "Eliminates redundant phrasing and filler words for maximum density." },
  { title: "Socratic Guided Discovery Prompt", desc: "Guides the user to discover solutions through targeted probing questions." },
  { title: "Parallel Options Comparison Table", desc: "Presents trade-offs across multiple choices in a side-by-side structured matrix." },
  { title: "Contextual Memory Tagging & Recall", desc: "Tags key user preferences to recall consistently across extended sessions." },
  { title: "Role-Based Access & Information Gating", desc: "Restricts sensitive data disclosures according to user authorization level." },
  { title: "Action-Oriented Verbs & Directives", desc: "Replaces passive commentary with active, imperative step-by-step guidance." },
  { title: "Data Anonymization & PII Redaction", desc: "Replaces sensitive names, emails, and numbers with generic placeholders." },
  { title: "Comparative Benchmark Evaluation", desc: "Evaluates proposed solutions against industry gold-standard benchmarks." },
  { title: "Dynamic Depth Scaling (Brief vs Exhaustive)", desc: "Adjusts detail level based on user-requested verbosity flags." },
  { title: "Modular Section Re-Assembly", desc: "Organizes output into independent, reusable modules for easy copy-pasting." },
  { title: "Task Pre-Flight Sanity Check", desc: "Scans input data for glaring errors or contradictions before starting execution." },
  { title: "Root Cause Problem Reframing", desc: "Reframes surface-level user requests to address underlying systemic issues." },
  { title: "Time Horizon Categorization (Immediate vs Long-Term)", desc: "Categorizes action items by implementation timeframe and urgency." },
  { title: "Cross-Functional Domain Bridging", desc: "Translates technical engineering requirements into business value terms." },
  { title: "Hypothetical Scenario Simulation", desc: "Explores 'What-If' scenarios to stress-test proposed strategic decisions." },
  { title: "Standard Operating Procedure (SOP) Drafting", desc: "Converts informal workflows into formalized, repeatable SOP documents." },
  { title: "Visual Flowchart Text Representation", desc: "Renders complex logic flows in ASCII or Mermaid diagram syntax." },
  { title: "Executive Elevator Pitch Synthesis", desc: "Distills complex proposals into a 30-second compelling verbal pitch." },
  { title: "Risk Assessment & Mitigation Matrix", desc: "Identifies potential failure modes and pairs each with an action plan." },
  { title: "Continuous Alignment Checkpoint", desc: "Inserts periodic confirmation prompts during long multi-step generations." },
  { title: "Final Deliverable Polish & Quality Pass", desc: "Performs final proofreading, formatting verification, and link checks." }
];

const batch1_core = makeSkills('core', 'core', 'core', 55, CORE_ITEMS);
appendSkills(batch1_core.catFileName, batch1_core.skills);

// 2. REASONING (54 skills)
const REASONING_ITEMS = [
  { title: "Counterfactual Causal Inference Reasoning", desc: "Evaluates what would have occurred had key historical variables been altered." },
  { title: "Abductive Reasoning to Best Explanation", desc: "Infers the most plausible hypothesis given incomplete or noisy observations." },
  { title: "Reductio ad Absurdum Logical Refutation", desc: "Disproves a premise by demonstrating that its logical conclusion leads to an absurdity." },
  { title: "Dialectical Thesis Antithesis Synthesis", desc: "Resolves conflicting viewpoints by discovering a higher-level unifying synthesis." },
  { title: "Probabilistic Fermi Estimation & Order of Magnitude", desc: "Calculates rapid order-of-magnitude estimates using dimensional decomposition." },
  { title: "Inversion Thinking (Munger Backward Reasoning)", desc: "Solves difficult problems by analyzing how to fail and avoiding those pitfalls." },
  { title: "First Principles Chemical/Physical Reduction", desc: "Deconstructs complex systems to fundamental physical/chemical laws." },
  { title: "Second-Order & Nth-Order Consequence Analysis", desc: "Evaluates delayed downstream ripple effects of immediate policy decisions." },
  { title: "Bayesian Prior vs Likelihood Belief Update", desc: "Updates confidence probability systematically upon receiving fresh evidence." },
  { title: "Ockham Razor Parsimony Optimization", desc: "Selects the simplest hypothesis with the fewest unproven assumptions." },
  { title: "Inductive Pattern Generalization & Boundary Testing", desc: "Derives general rules from specific observations while testing edge limits." },
  { title: "Formal Deductive Syllogism Validation", desc: "Constructs valid major/minor premise structures to prove sound conclusions." },
  { title: "Game-Theoretic Nash Equilibrium Analysis", desc: "Models strategic interaction where no player benefits by unilaterally changing strategy." },
  { title: "Cognitive Bias Audit & Debiasing Protocol", desc: "Identifies anchoring, confirmation, or availability bias in analytical models." },
  { title: "Root Cause 5 Whys Iterative Analysis", desc: "Traces surface symptoms back to fundamental systemic failures." },
  { title: "Analogical Reasoning Cross-Domain Mapping", desc: "Maps structural solutions from biology or history to solve novel tech problems." },
  { title: "Trolley Problem Ethical Utility Calculation", desc: "Evaluates moral trade-offs using utilitarian vs deontological frameworks." },
  { title: "Chesterton Fence Tradition Preservation Logic", desc: "Understands why a rule was created before attempting to remove or alter it." },
  { title: "Decision Tree Expected Value Branching", desc: "Calculates EV across weighted probabilistic decision branches." },
  { title: "Pareto 80/20 Leverage Point Identification", desc: "Isolates the 20% of critical inputs driving 80% of desired system outcomes." },
  { title: "Hanlon Razor Misconception Disambiguation", desc: "Attributes mistakes to incompetence or systemic noise rather than malice." },
  { title: "Lindy Effect Longevity Forecasting", desc: "Predicts future technology lifespan based on past historical endurance." },
  { title: "Survivorship Bias Aircraft Armor Auditing", desc: "Analyzes missing data from failed entities rather than only surviving successes." },
  { title: "Goodhart Law Metric Game Distortions", desc: "Guards against metrics becoming bad targets when optimized explicitly." },
  { title: "Sorites Paradox Boundary Vagueness", desc: "Handles gradual incremental state transitions with vague threshold boundaries." },
  { title: "Black Swan High-Impact Uncertainty", desc: "Prepares systems for extreme, low-probability, high-consequence events." },
  { title: "Popper Falsifiability Test Criteria", desc: "Ensures hypotheses propose concrete tests that could prove them wrong." },
  { title: "Sunk Cost Fallacy Decision Reset", desc: "Ignores non-recoverable past investments when evaluating future choices." },
  { title: "Tragedy of the Commons Shared Resource Logic", desc: "Models individual rational incentives leading to collective resource depletion." },
  { title: "Cobweb Model Market Price Oscillation", desc: "Analyzes supply-demand lag cycles causing price volatility over time." },
  { title: "Campbell Law Metric Inflation Safeguard", desc: "Protects quantitative indicators from corruption under high-stakes pressure." },
  { title: "Broken Window Theory Escalation Logic", desc: "Prevents minor unchecked flaws from encouraging widespread system decay." },
  { title: "Streisand Effect Suppression Rebound", desc: "Anticipates how attempting to hide information amplifies public attention." },
  { title: "Overton Window Public Policy Shifting", desc: "Tracks acceptable range of ideas in political or corporate discourse." },
  { title: "Eichmann Banality of Evil Structural Drift", desc: "Exposes how bureaucratic routine enables harmful systemic outcomes." },
  { title: "Jevons Paradox Efficiency Demand Spike", desc: "Anticipates increased overall consumption as technology makes resource use cheaper." },
  { title: "Pascal Wager Infinite Expected Value", desc: "Evaluates asymmetrical risk where potential loss is infinite." },
  { title: "Ship of Theseus Identity Persistence", desc: "Maintains core architectural identity through complete component replacements." },
  { title: "Prisoner Dilemma Iterated Cooperation", desc: "Builds tit-for-tat strategies to foster long-term mutual trust in games." },
  { title: "Principle of Explosion False Premise Containment", desc: "Prevents a single contradiction from destroying logical consistency." },
  { title: "Gödel Incompleteness Boundary Recognition", desc: "Acknowledges inherent limitations in formal axiomatic systems." },
  { title: "Heisenberg Observer Effect Measurement Drift", desc: "Account for how measuring a process alters the behavior of the system." },
  { title: "Buridan Ass Indecision Disruption", desc: "Forces a choice between equally attractive options to avoid paralysis." },
  { title: "Dunning-Kruger Competence Calibration", desc: "Adjusts self-assessment based on actual domain expertise metrics." },
  { title: "Zero-Sum vs Positive-Sum Game Selection", desc: "Reframes competitive conflicts into mutually beneficial win-win deals." },
  { title: "Conjunction Fallacy Probability Correction", desc: "Remembers that specific conditions are less probable than general ones." },
  { title: "Base Rate Neglect Prior Probability Anchor", desc: "Incorporates background statistical frequencies before evaluating specific test data." },
  { title: "Regression to the Mean Statistical Normalization", desc: "Anticipates extreme outlier performances will naturally return toward average." },
  { title: "Survivorship Bias Historical Analysis", desc: "Examines failures alongside successes to avoid skewed historical conclusions." },
  { title: "Gambler Fallacy Independent Probability Check", desc: "Treats past random outcomes as independent from future coin flips." },
  { title: "Availability Heuristic Vividness Neutralization", desc: "Weights statistical frequency higher than recent emotional memories." },
  { title: "Framing Effect Semantic Neutrality Reset", desc: "Evaluates information independently of whether it is presented positively or negatively." },
  { title: "False Dilemma Binary Choice Expansion", desc: "Identifies third and fourth hidden alternatives beyond rigid black-and-white options." },
  { title: "Straw Man Argument Steelmanning Elevation", desc: "Reframes opponent arguments in their strongest possible form before critique." }
];

const batch1_reasoning = makeSkills('reasoning', 'reasoning', 'reasoning', 54, REASONING_ITEMS);
appendSkills(batch1_reasoning.catFileName, batch1_reasoning.skills);

// 3. CONTROL FLOW (50 skills)
const CONTROL_FLOW_ITEMS = [
  { title: "Dynamic Rate Limiting Token Bucket Refill", desc: "Replenishes request quotas dynamically based on token bucket capacity." },
  { title: "Cascading Fallback Chain Execution", desc: "Executes multi-tiered fallback handlers sequentially until one succeeds." },
  { title: "Stateful Session Re-hydration & Resume", desc: "Restores execution state seamlessly from persistent database checkpoints." },
  { title: "Distributed Lock Acquisition with Redlock", desc: "Secures multi-node distributed locks with automatic TTL lease renewal." },
  { title: "Dead-Letter Queue Isolation & Triage", desc: "Isolates unprocessable poison-pill messages for manual inspection." },
  { title: "Scatter-Gather Parallel Request Aggregation", desc: "Broadcasts queries to multiple backends and merges responses." },
  { title: "Event Choreography vs Centralized Orchestration", desc: "Manages distributed workflows using decoupled event messaging." },
  { title: "Hierarchical AbortSignal Cascade Cancellation", desc: "Propagates cancellation signals down nested async task trees." },
  { title: "Circuit Breaker Exponential Half-Open Probe", desc: "Probes recovering services with exponential backoff before full reset." },
  { title: "Idempotent Replay Window Nonce Verification", desc: "Prevents replay attacks using cryptographically signed timestamped nonces." },
  { title: "Singleflight In-Flight Request Deduplication", desc: "Shares single execution promise across simultaneous identical requests." },
  { title: "Transactional Outbox Pattern for CDC", desc: "Ensures atomic database mutations and event publishing consistency." },
  { title: "Hedged Requests for Tail Latency Elimination", desc: "Dispatches backup requests to secondary nodes upon p95 delay." },
  { title: "Fencing Token Distributed Mutex Lock", desc: "Validates monotonic fencing tokens to prevent stale lock writes." },
  { title: "Statechart History States Preservation", desc: "Remembers sub-state configurations during temporary modal interrupts." },
  { title: "Server-Sent Events Graceful Long-Polling Downgrade", desc: "Falls back to long-polling when SSE streaming is blocked by proxy." },
  { title: "Bloom Filter Webhook Idempotency Check", desc: "Pre-filters duplicate webhooks instantly with zero DB lookup." },
  { title: "CoDel Queue Sojourn Time Load Shedding", desc: "Sheds excess load dynamically when queue waiting times exceed SLOs." },
  { title: "Work-Stealing Task Queue Thread Pool", desc: "Balances multi-threaded CPU load using lock-free task stealing." },
  { title: "LLM Semantic Intent Classifier Dispatch", desc: "Routes user prompts to specialized tools via intent classification." },
  { title: "Priority Inversion Prevention Protocol", desc: "Elevates priority of low-priority tasks holding critical locks." },
  { title: "Hot-Path Branch Prediction Hinting", desc: "Structures conditionals to optimize CPU instruction cache locality." },
  { title: "Hierarchical Timeout Deadline Propagation", desc: "Passes shrinking execution deadlines across microservice hops." },
  { title: "Event Sourcing Periodic Snapshotting", desc: "Accelerates aggregate hydration using periodic checkpoint snapshots." },
  { title: "Go-Channel Style CSP Pipeline Buffering", desc: "Connects concurrent pipeline stages with bounded FIFO channels." },
  { title: "Multi-Region Active-Passive DNS Failover", desc: "Reroutes global traffic on edge health check probe failures." },
  { title: "Client-Side Retry Budget Token Bucket", desc: "Limits retry attempts to a fixed percentage of total outbound traffic." },
  { title: "Cost-Aware Speculative Request Hedging", desc: "Executes hedged requests selectively based on user tier and cost." },
  { title: "Linearizable Read Index Optimization in Raft", desc: "Serves linearizable reads from leader without full log consensus." },
  { title: "Declarative Rule Engine Rete Network Matching", desc: "Evaluates thousands of conditional rules in sub-millisecond time." },
  { title: "Fine-Grained Reactive Signal Graph", desc: "Propagates state updates without virtual DOM diffing overhead." },
  { title: "Leading and Trailing Edge Event Throttling", desc: "Configures event execution pacing with immediate or delayed invocation." },
  { title: "Task Orchestrator Dependency Injection", desc: "Decouples execution control flow from storage and network drivers." },
  { title: "Stale-While-Revalidate Async Cache Refresh", desc: "Returns cached data instantly while refreshing fresh data in background." },
  { title: "TypeScript Explicit Async Resource Disposal", desc: "Guarantees resource cleanup using `Symbol.asyncDispose` syntax." },
  { title: "AIMD Adaptive Concurrency Limits", desc: "Adjusts outbound concurrency limits dynamically based on RTT latency." },
  { title: "Self-Healing State Purge & Memory Recycling", desc: "Purges ephemeral state and recycles pools upon memory pressure." },
  { title: "Multi-Tenant Deficit Weighted Round-Robin", desc: "Allocates worker execution fairly across competing tenant queues." },
  { title: "Graceful Process Termination SIGTERM Drain", desc: "Drains in-flight requests cleanly on process termination signals." },
  { title: "Optimistic Concurrency Compare-And-Swap", desc: "Guards against lost updates using version column updates." },
  { title: "2PC Two-Phase Commit Atomic Coordination", desc: "Guarantees atomic multi-database transactions via Prepare/Commit." },
  { title: "Reactive Backpressure Flow Control", desc: "Prevents fast producers from overwhelming slow consumers." },
  { title: "Debounce Search Input Key Pacing", desc: "Delays search execution until user stops typing for N milliseconds." },
  { title: "Middleware Pipeline Onion Execution", desc: "Executes request pipelines through composable middleware layers." },
  { title: "SWIM Gossip Protocol Cluster Membership", desc: "Detects cluster node failures using peer-to-peer gossip messages." },
  { title: "CQRS Asynchronous Event Projection Replay", desc: "Rebuilds read models by replaying past event streams." },
  { title: "Fork-Join Parallel Recursive Execution", desc: "Splits large tasks recursively and joins outputs asynchronously." },
  { title: "Token Bucket Rate Limiter with Burst Support", desc: "Enforces smooth rate limits while allowing short traffic bursts." },
  { title: "Sliding Window Log Redis Deduplication", desc: "Tracks request timestamps in sorted sets to prevent burst attacks." },
  { title: "Actor Model Mailbox Isolated State", desc: "Processes messages sequentially in isolated actor memory loops." }
];

const batch1_controlFlow = makeSkills('controlFlow', 'control_flow', 'control-flow', 50, CONTROL_FLOW_ITEMS);
appendSkills(batch1_controlFlow.catFileName, batch1_controlFlow.skills);

// 4. OUTPUT (50 skills)
const OUTPUT_ITEMS = [
  { title: "Strict OpenAPI 3.1 JSON Schema Validation", desc: "Formats responses strictly adhering to OpenAPI 3.1 schema definitions." },
  { title: "Markdown Table Formatting & Alignment Rules", desc: "Presents structured data in clean, aligned Markdown tables with headers." },
  { title: "YAML Configuration Syntax & Indentation", desc: "Outputs valid, parseable YAML with strict two-space indentation." },
  { title: "Mermaid.js Flowchart & Sequence Diagram", desc: "Generates clean Mermaid syntax for flowcharts, sequence, and ER diagrams." },
  { title: "CSV Data Export with Proper Escaping", desc: "Outputs RFC 4180 compliant CSV files with quote escaping for commas." },
  { title: "XML Document Formatting & Tag Validation", desc: "Generates well-formed XML documents with correct opening/closing tags." },
  { title: "TypeScript Interface & Type Definitions", desc: "Outputs strict, production-ready TypeScript interfaces and generic types." },
  { title: "SQL DDL & DML Script Formatting", desc: "Formats SQL schema migrations and queries with uppercase keywords." },
  { title: "GraphQL Schema Definition Language (SDL)", desc: "Generates valid GraphQL types, queries, mutations, and directives." },
  { title: "JSON Lines (JSONL) Streaming Format", desc: "Formats bulk data as newline-delimited JSON objects for streaming." },
  { title: "Latex Mathematical Equation Notation", desc: "Renders complex mathematical equations in valid LaTeX inline or block syntax." },
  { title: "HTML5 Semantic Markup & Accessibility", desc: "Generates semantic HTML5 markup with ARIA attributes and clean structure." },
  { title: "Bash/Shell Script Boilerplate with Safety Flags", desc: "Outputs robust shell scripts with `set -euo pipefail` safety headers." },
  { title: "Docker Compose YAML Service Definition", desc: "Generates valid Docker Compose files with healthchecks and volumes." },
  { title: "Protobuf v3 Schema Message Definition", desc: "Formats Google Protocol Buffers schemas with explicit field numbers." },
  { title: "Terraform HCL Infrastructure Code", desc: "Outputs clean HashiCorp Configuration Language (HCL) modules." },
  { title: "Regex Pattern & Substitution Specification", desc: "Provides tested regular expressions with flags and capture group explanations." },
  { title: "Cron Expression Syntax & Human Explanation", desc: "Outputs standard 5-part cron expressions paired with plain-language schedule breakdowns." },
  { title: "cURL Command Example with Headers", desc: "Generates copy-pasteable cURL commands with proper HTTP method and auth headers." },
  { title: "Git Commit Message Conventional Format", desc: "Formats commit messages adhering to `feat:`, `fix:`, or `chore:` conventional standards." },
  { title: "Semantic Versioning Release Tagging", desc: "Formats release notes according to SemVer (MAJOR.MINOR.PATCH) rules." },
  { title: "BibTeX Academic Citation Format", desc: "Generates well-structured BibTeX entries for academic papers and books." },
  { title: "Postman Collection v2.1 JSON Schema", desc: "Outputs valid Postman API collection JSON files for import." },
  { title: "PlantUML Architecture Diagram Code", desc: "Generates PlantUML syntax for UML class, component, and deployment diagrams." },
  { title: "TOML Configuration File Syntax", desc: "Outputs clean, valid TOML files for Rust, Python, or Cargo configuration." },
  { title: "Diff Patch Syntax for Code Changes", desc: "Formats code changes as standard unified diff patch blocks." },
  { title: "String Literal Template Interpolation", desc: "Outputs clean string template literals with explicit variable placeholders." },
  { title: "ASCII Tree Folder Structure Diagram", desc: "Renders directory file structures in ASCII tree format." },
  { title: "Gherkin Feature Given-When-Then Syntax", desc: "Formats BDD test scenarios in clear Gherkin syntax." },
  { title: "HTTP Raw Request/Response Packet", desc: "Renders raw HTTP wire protocol headers, status codes, and body payloads." },
  { title: "Systemd Service Unit File Syntax", desc: "Generates Linux systemd `.service` files with restart and security policies." },
  { title: "Nginx Server Block Configuration", desc: "Outputs valid Nginx reverse proxy, SSL, and location block configs." },
  { title: "Kubernetes Manifest YAML Specification", desc: "Generates valid Kubernetes Deployment, Service, and Ingress manifests." },
  { title: "Ansible Playbook YAML Task List", desc: "Formats Ansible automation playbooks with idempotent tasks." },
  { title: "GraphQL Query & Variable JSON Payload", desc: "Pairs GraphQL query strings with separate JSON variable objects." },
  { title: "Elasticsearch Query DSL JSON Payload", desc: "Outputs complex Elasticsearch search queries in JSON DSL syntax." },
  { title: "Graphviz DOT Graph Visualization Code", desc: "Generates DOT syntax for rendering node-edge graphs via Graphviz." },
  { title: "VTT / SRT Subtitle Timestamp Format", desc: "Formats video subtitle files with precise start/end millisecond timestamps." },
  { title: "ROBOTS.txt & Sitemap XML Syntax", desc: "Outputs search engine crawler directives and XML sitemaps." },
  { title: "Apache HTTPD Configuration Directive", desc: "Outputs valid Apache `.htaccess` or virtual host configuration rules." },
  { title: "SPARQL Graph Query Language Syntax", desc: "Generates valid SPARQL queries for RDF knowledge bases." },
  { title: "Prometheus Alerting Rule YAML Syntax", desc: "Formats Prometheus alerting rules with metric thresholds and labels." },
  { title: "Swagger / OpenAPI Endpoint Spec", desc: "Outputs individual endpoint specifications in OpenAPI YAML format." },
  { title: "JSON Patch RFC 6902 Operations List", desc: "Formats JSON modification operations as RFC 6902 patch arrays." },
  { title: "CSS Custom Property Design Token List", desc: "Outputs design tokens as CSS variables (`--primary-color`)." },
  { title: "JSTest / Jest Test Suite Syntax", desc: "Formats unit tests with `describe`, `it`, and `expect` assertions." },
  { title: "PyTest Test Function & Fixture Syntax", desc: "Formats Python test functions with `@pytest.fixture` annotations." },
  { title: "Makefile Rule & Dependency Target", desc: "Outputs clean Makefiles with phony targets and variable definitions." },
  { title: "LaTeX Table & Array Environment", desc: "Formats complex data matrices in LaTeX table environments." },
  { title: "RFC 8259 Strict JSON Output Envelope", desc: "Wraps response data in a standardized JSON error/data envelope." }
];

const batch1_output = makeSkills('output', 'output', 'output', 50, OUTPUT_ITEMS);
appendSkills(batch1_output.catFileName, batch1_output.skills);

// 5. WRITING (50 skills)
const WRITING_ITEMS = [
  { title: "Executive Summary & Elevator Pitch Synthesis", desc: "Distills long complex documents into a 1-page executive summary." },
  { title: "Cold Outbound Email & Pattern Interrupt", desc: "Drafts high-converting B2B sales emails under 75 words." },
  { title: "Crisis Communications & PR Apology Statement", desc: "Crafts transparent, accountable corporate crisis responses." },
  { title: "Technical Release Notes & Customer Delight", desc: "Translates code commits into engaging user-facing release notes." },
  { title: "Amazon 6-Page Narrative Strategy Memo", desc: "Structures strategic proposals in Bezos narrative memo format." },
  { title: "AP Stylebook Journalistic Clarity & Neutrality", desc: "Applies standard AP Stylebook conventions for news articles." },
  { title: "Y Combinator Startup Pitch Application", desc: "Drafts concise, high-density answers for startup accelerator applications." },
  { title: "SEC Form 10-K MD&A Financial Commentary", desc: "Drafts public company financial discussion and analysis sections." },
  { title: "Nature Peer-Reviewed Abstract Structure", desc: "Composes 5-part scientific paper abstracts following Nature standards." },
  { title: "Stripe Press Long-Form Intellectual Essay", desc: "Crafts high-grade essays on technological progress and economics." },
  { title: "Executive Keynote Speechwriting & Rhetoric", desc: "Writes charismatic spoken-word speeches using classical rhetorical devices." },
  { title: "SaaS Behavioral Onboarding Email Drip", desc: "Designs automated email onboarding funnels triggered by telemetry." },
  { title: "Blameless Engineering Incident Post-Mortem", desc: "Documents system outages objectively with root causes and timelines." },
  { title: "Substack Thought Leadership Newsletter", desc: "Structures high-open-rate newsletters with magnetic subject lines." },
  { title: "Patent Claims & Specification Drafting", desc: "Drafts utility patent specifications and independent claim language." },
  { title: "Developer API Reference Documentation", desc: "Writes Stripe-grade developer API docs with copy-paste code snippets." },
  { title: "B2B Enterprise Case Study ROI Story", desc: "Transforms customer success into sales collateral with quantitative proof." },
  { title: "Harvard Business School Executive Case Study", desc: "Drafts management case studies centered on critical executive choices." },
  { title: "App Store Listing Optimization (ASO)", desc: "Writes high-converting titles, subtitles, and descriptions for app stores." },
  { title: "UX Microcopy & Friendly Error Messages", desc: "Crafts empathetic interface microcopy for errors and empty states." },
  { title: "Quarterly Shareholder Letter & Update", desc: "Writes candid investor updates covering ARR, burn rate, and key asks." },
  { title: "Podcast Host Interview Script & Questions", desc: "Prepares deep interview arcs and provocative questions for podcasts." },
  { title: "Technical White Paper Authority Blueprint", desc: "Authors comprehensive technical white papers establishing market leadership." },
  { title: "Brand Manifesto & Cultural Declaration", desc: "Crafts inspiring brand manifestos that rally employees and users." },
  { title: "Comprehensive Product FAQ & Objection Handling", desc: "Structures FAQ hubs addressing pricing, security, and migration friction." },
  { title: "Enterprise RFP Bid Proposal Response", desc: "Drafts compliant, winning responses to enterprise Requests for Proposal." },
  { title: "Investigative Journalism Expose Article", desc: "Constructs airtight investigative pieces linking verified source documents." },
  { title: "GitHub Repository README Showcase", desc: "Crafts engaging open-source READMEs with animated GIFs and quickstarts." },
  { title: "Sales Battlecard & Competitor Differentiation", desc: "Equips sales reps with objection handling and competitive trap questions." },
  { title: "Customer Advisory Board Strategic Briefing", desc: "Prepares C-suite agendas and confidential roadmap previews." },
  { title: "Security & Trust Center Whitepaper", desc: "Details enterprise encryption, tenant isolation, and SOC2 compliance." },
  { title: "Classic Direct-Response Sales Letter", desc: "Structures high-converting long-form direct-response sales copy." },
  { title: "Product Hunt Launch Kit & Maker Comment", desc: "Crafts Product Hunt taglines, maker stories, and launch Q&A replies." },
  { title: "TED Talk Storytelling Narrative Arc", desc: "Structures captivating 15-minute talks around an 'idea worth spreading'." },
  { title: "Jobs-to-be-Done (JTBD) User Persona Profile", desc: "Creates customer profiles based on functional, emotional, and social jobs." },
  { title: "Engineering Design Document (RFC)", desc: "Structures technical RFCs covering non-goals, architecture, and rollbacks." },
  { title: "Crowdfunding Kickstarter Campaign Story", desc: "Writes viral crowdfunding pages featuring prototypes and reward tiers." },
  { title: "Promotion Packet & Impact Brag Sheet", desc: "Compiles convincing promotion packets linking technical wins to revenue." },
  { title: "Dual-Column Terms of Service Plain Summary", desc: "Presents legal TOS alongside friendly plain-English side-by-side notes." },
  { title: "Interactive Fiction Branching Dialogue Tree", desc: "Authors non-linear storylines and character state branching dialogue." },
  { title: "Nonprofit Grant Proposal & Theory of Change", desc: "Constructs grant proposals demonstrating measurable social impact." },
  { title: "Thoughtful LinkedIn Thought Leadership Post", desc: "Crafts high-engagement LinkedIn posts with strong hook headlines." },
  { title: "Customer Offboarding & Exit Survey Copy", desc: "Writes empathetic cancellation flows that gather honest exit feedback." },
  { title: "Internal Employee Policy Announcement", desc: "Communicates company policy changes with clarity and transparency." },
  { title: "Investor Pitch Deck Speaker Notes", desc: "Prepares spoken slide-by-side scripts for startup founder pitch decks." },
  { title: "Product Feature Announcement Blog Post", desc: "Writes exciting product feature announcement posts highlighting benefits." },
  { title: "Technical Troubleshooting Knowledge Base", desc: "Authors step-by-step troubleshooting articles for common user bugs." },
  { title: "B2B Sales Proposal Follow-Up Email", desc: "Drafts polite, high-converting follow-up emails after enterprise demos." },
  { title: "Community Guidelines & Conduct Policy", desc: "Establishes clear, welcoming community behavior standards and rules." },
  { title: "Sponsorship Deck & Partner Media Kit", desc: "Creates compelling media kit copy detailing audience metrics and reach." }
];

const batch1_writing = makeSkills('writing', 'writing', 'writing', 50, WRITING_ITEMS);
appendSkills(batch1_writing.catFileName, batch1_writing.skills);

console.log('Batch 1 complete!');
