const { appendSkills } = require('../appendSkills.cjs');

function makeSkills(catFileName, categoryId, prefix, count, items) {
  const skills = [];
  for (let i = 0; i < count; i++) {
    const item = items[i] || {};
    const title = item.title || `${prefix} Skill ${i + 1}`;
    const cleanId = `${prefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
    const pascalName = title.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';

    skills.push({
      id: cleanId,
      name: pascalName,
      displayName: item.displayName || title,
      categoryId: categoryId,
      description: item.desc || `Applies advanced ${title} standards and execution patterns.`,
      tags: [categoryId, prefix, ...cleanId.split('-').slice(1, 3)],
      sectionName: item.sec || `${title} Standards`,
      ruSectionName: item.ruSec || `Стандарты и регламенты: ${title}`,
      instructions: item.inst || [
        `Apply core domain tenets for ${title}.`,
        `Enforce strict validation, error-handling, and clear structural bounds.`,
        `Verify output consistency against benchmark standards.`
      ],
      ruInstructions: item.ruInst || [
        `Применяйте ключевые принципы и стандарты для ${title}.`,
        `Обеспечивайте строгую валидацию, обработку ошибок и структурные границы.`,
        `Проверяйте результаты на соответствие эталонным критериям.`
      ],
      semanticType: item.sem || 'process_directive'
    });
  }
  return { catFileName, skills };
}

// 1. ANALYSIS (50 skills)
const ANALYSIS_ITEMS = [
  { title: "Financial Statement Ratio & Dupont Decomposition", desc: "Analyzes ROE using DuPont 3-factor breakdown: profit margin, asset turnover, leverage." },
  { title: "Competitive Intelligence Porter Five Forces", desc: "Evaluates industry attractiveness across threat of entry, buyer power, and substitutes." },
  { title: "Macroeconomic PESTLE Strategic Environmental Audit", desc: "Assesses Political, Economic, Social, Tech, Legal, and Environmental trends." },
  { title: "Root Cause Fishbone (Ishikawa) Diagram Analysis", desc: "Categorizes causes of equipment/process defects across Man, Machine, Material, Method." },
  { title: "Statistical Hypothesis Testing & p-Value Interpretation", desc: "Evaluates null vs alternative hypotheses using t-tests, ANOVA, and z-scores." },
  { title: "Cohort Survival Analysis & Kaplan-Meier Decay", desc: "Models time-to-event attrition rates and survival probabilities over customer lifespans." },
  { title: "Supply Chain Value Stream Mapping (VSM)", desc: "Identifies non-value-add delay waste and bottleneck cycle times in production." },
  { title: "Brand Perception Sentiment & Semantic Clustering", desc: "Analyzes customer feedback sentiment across topic clusters using NLP." },
  { title: "M&A Due Diligence Synergy & Red Flag Audit", desc: "Audits target company financial liabilities, churn, litigation, and tech debt." },
  { title: "Sensitivity & Monte Carlo Risk Simulation", desc: "Simulates thousands of probabilistic outcomes across variable distribution ranges." },
  { title: "RFM Customer Lifetime Value Segmentation", desc: "Segments user bases by Recency, Frequency, and Monetary transaction values." },
  { title: "Ansoff Matrix Growth Vector Strategy", desc: "Evaluates Market Penetration, Product Development, Market Dev, and Diversification." },
  { title: "VRIO Resource Competitability Evaluation", desc: "Tests corporate assets for Value, Rarity, Inimitability, and Organizational alignment." },
  { title: "BCG Growth-Share Matrix Portfolio Analysis", desc: "Categorizes business units into Stars, Cash Cows, Question Marks, and Dogs." },
  { title: "Customer Churn Hazard Rate Modeling", desc: "Identifies early warning indicators correlated with customer subscription cancellation." },
  { title: "Regulatory Compliance Gap & Audit Trail", desc: "Identifies non-compliance gaps between current operations and new legal frameworks." },
  { title: "Pricing Elasticity of Demand Optimization", desc: "Calculates price elasticity coefficients to optimize profit margins without churn." },
  { title: "CapEx vs OpEx Capital Allocation Analysis", desc: "Evaluates long-term ROI trade-offs between upfront CapEx and recurring OpEx." },
  { title: "Unit Economics LTV/CAC Payback Period", desc: "Calculates Net LTV, Customer Acquisition Cost, and months to CAC payback." },
  { title: "Cybersecurity Threat Surface & Attack Vector", desc: "Maps attack surfaces, entry points, and vulnerability exploitation paths." },
  { title: "Market Sizing TAM SAM SOM Bottom-Up Model", desc: "Builds realistic market sizing estimations using bottom-up unit calculations." },
  { title: "Product Quality Defect Pareto Distribution", desc: "Isolates the 20% of root defect causes responsible for 80% of product returns." },
  { title: "Organizational Network Analysis (ONA) Communication", desc: "Maps informal communication channels and key influence hubs inside companies." },
  { title: "Vendor SLA Performance & Penalty Credit Audit", desc: "Audits vendor uptime and performance logs against contractual SLA penalties." },
  { title: "Technology Debt Index & Refactoring Impact", desc: "Quantifies technical debt interest costs in terms of developer velocity loss." },
  { title: "Operational Bottleneck Theory of Constraints (TOC)", desc: "Identifies and elevates the single constraint limiting throughput capacity." },
  { title: "Customer Journey Touchpoint Attribution", desc: "Allocates conversion credit across first-click, last-click, and multi-touch channels." },
  { title: "B2B Sales Pipeline Velocity & Stage Conversion", desc: "Calculates sales velocity: `(Deals * Win Rate * Deal Size) / Cycle Length`." },
  { title: "ESG Carbon Footprint Scope 1-3 Inventory", desc: "Audits direct and indirect corporate greenhouse gas emissions across value chains." },
  { title: "Commercial Real Estate Yield & Cap Rate Audit", desc: "Evaluates net operating income (NOI) and capitalization rates for properties." },
  { title: "Product Feature Usage & Engagement Dropoff", desc: "Analyzes telemetry logs to find friction points where users abandon features." },
  { title: "Geopolitical Country Risk & Currency Hedging", desc: "Assesses sovereign risk, expropriation threat, and foreign exchange exposure." },
  { title: "Patent Landscape Prior Art & Freedom to Operate", desc: "Maps competitor patent filings to identify white space and infringement risks." },
  { title: "Inventory Turnover & Days Sales of Inventory (DSI)", desc: "Evaluates inventory holding costs and stockout risk management." },
  { title: "Employee Turnover Retention Cohort Analysis", desc: "Tracks employee tenure retention curves by department and manager cohort." },
  { title: "Software Infrastructure Cloud Cost Allocation (FinOps)", desc: "Attributes AWS/GCP cloud hosting spend down to individual product features." },
  { title: "Data Governance Lineage & Metadata Provenance", desc: "Traces raw data transformation lineage from source systems to dashboards." },
  { title: "Franchise Unit EBITDA & Payback Benchmarking", desc: "Audits franchisee location profitability and 4-wall margin consistency." },
  { title: "Public Relations Share of Voice (SOV) Analysis", desc: "Measures brand media mention volume against key competitors." },
  { title: "Disaster Recovery RPO/RTO Gap Assessment", desc: "Audits actual backup restoration times against business continuity goals." },
  { title: "Customer Support First Contact Resolution (FCR)", desc: "Evaluates support ticket resolution efficiency and repeat contact rates." },
  { title: "E-Commerce Cart Abandonment Cause Segmentation", desc: "Analyzes cart checkout dropoff causes: shipping costs, payment options, friction." },
  { title: "Syndicated Retail Scanner Data Market Share", desc: "Analyzes POS retail sales data to track market share shifts by region." },
  { title: "Clinical Trial Primary Endpoint Statistical Power", desc: "Evaluates sample size power calculations for medical drug trial endpoints." },
  { title: "SaaS Rule of 40 Efficiency Index", desc: "Calculates combined ARR growth rate + FCF margin score for SaaS health." },
  { title: "Algorithmic Trading Backtest Sharpe Ratio", desc: "Evaluates trading strategy risk-adjusted returns and maximum drawdown depth." },
  { title: "Energy Grid Peak Load & Demand Response", desc: "Analyzes peak electricity demand patterns and load-shedding opportunities." },
  { title: "Supply Chain Bullwhip Demand Distortion", desc: "Identifies demand forecast amplification across multi-tier distribution channels." },
  { title: "Mobile App ASO Keyword Conversion Audit", desc: "Analyzes app store search ranking factors and organic install conversion." },
  { title: "Corporate Governance Board Composition Audit", desc: "Evaluates board independence, diversity, and committee oversight efficacy." }
];

const batch2_analysis = makeSkills('analysis', 'analysis', 'analysis', 50, ANALYSIS_ITEMS);
appendSkills(batch2_analysis.catFileName, batch2_analysis.skills);

// 2. METAPROMPTING (50 skills)
const METAPROMPTING_ITEMS = [
  { title: "Prompt Instruction Compression & Token Minimization", desc: "Compresses prompts into minimal token representations while preserving semantic intent." },
  { title: "Self-Improving Prompt Iteration Loop", desc: "Evaluates previous prompt generation output and generates a refined version 2.0 prompt." },
  { title: "Few-Shot Example Generator & Synthetic Pairs", desc: "Generates high-quality, diverse input-output example pairs for prompt enhancement." },
  { title: "Prompt Vulnerability & Injection Stress-Testing", desc: "Red-teams prompts against jailbreak attempts and instruction overrides." },
  { title: "Role & Persona System Directive Synthesizer", desc: "Creates highly detailed, authentic persona system prompts for target domains." },
  { title: "Prompt Formatting Schema & Delimiter Injector", desc: "Enforces XML, Markdown, or JSON tags to separate context, inputs, and directives." },
  { title: "Multi-Agent Conversation Orchestration Meta-Prompt", desc: "Generates system prompts for multi-agent supervisor-worker topologies." },
  { title: "Metaprompting Variable Extractor & Template Builder", desc: "Converts static text prompts into parameterized dynamic templates with variables." },
  { title: "Instruction Ambiguity Auditor & Disambiguator", desc: "Scans prompts for vague directives and rewrites them into explicit boolean rules." },
  { title: "Chain-of-Thought Reasoning Trigger Injector", desc: "Injects step-by-step reasoning triggers ('Think step by step before answering')." },
  { title: "Negative Constraint Generator & Anti-Patterns", desc: "Generates comprehensive 'Do NOT' lists to eliminate common model hallucination modes." },
  { title: "Cross-Model Prompt Portability Converter", desc: "Adapts prompts written for Claude/GPT to work optimally on Gemini or Llama." },
  { title: "Evaluation Rubric & Scoring System Generator", desc: "Generates automated LLM-as-a-judge scoring rubrics for evaluating response quality." },
  { title: "Domain-Specific Vocabulary & Jargon Injector", desc: "Enriches generic prompts with professional terminology and industry standards." },
  { title: "Output Length & Verbosity Control Meta-Prompt", desc: "Injects strict word count, token budget, or bullet point formatting constraints." },
  { title: "Prompt Modularization & Component Decomposition", desc: "Decomposes monolithic system prompts into reusable, composable sub-modules." },
  { title: "Edge Case & Error Handling Directive Creator", desc: "Adds explicit error handling rules for missing data or unexpected user inputs." },
  { title: "Task Decomposition & Sub-Task Router Generator", desc: "Creates prompts that break complex user tasks into sequential sub-agent calls." },
  { title: "User Intent Disambiguation & Clarification Builder", desc: "Adds rules instructing the model to ask clarifying questions when inputs are ambiguous." },
  { title: "Context Window Priority & Attention Anchor", desc: "Positions critical instructions at system prompt start and end to combat middle loss." },
  { title: "Tone & Voice Calibration Directive Builder", desc: "Synthesizes precise voice guidelines matching corporate brand style guides." },
  { title: "JSON Output Schema Enforcement Meta-Prompt", desc: "Injects strict JSON schema rules ensuring 100% parseable structured output." },
  { title: "Grounding & Citation Requirement Injector", desc: "Adds rules requiring the model to cite exact source paragraph numbers for all claims." },
  { title: "Confidence Threshold & Uncertainty Flag Directive", desc: "Instructs the model to output 'I don't know' when confidence falls below 80%." },
  { title: "Interactive Tool Calling Prompt Specifier", desc: "Formats tool signatures, parameters, and invocation guidelines for function calling." },
  { title: "Few-Shot Boundary & Negative Example Builder", desc: "Includes 'Bad Example vs Good Example' pairs to demonstrate unacceptable responses." },
  { title: "Multi-Language Localization Directive Injector", desc: "Adds instructions for seamless, natural translation and cultural adaptation." },
  { title: "Refusal & Safety Guardrail Meta-Prompt", desc: "Builds safe refusal protocols for out-of-bounds, illegal, or unethical requests." },
  { title: "Creative Brainstorming Diversity Multiplier", desc: "Injects rules forcing the model to generate non-overlapping, lateral ideas." },
  { title: "Code Generation System Directive Builder", desc: "Creates specialized coding system prompts enforcing TypeScript, unit tests, and clean architecture." },
  { title: "Self-Correction & Output Verification Step", desc: "Injects a final reflection step where the model audits its work before responding." },
  { title: "Prompt Version Migration & Changelog Generator", desc: "Tracks changes between prompt versions and documents modifications." },
  { title: "Context Summarization & Memory Compression", desc: "Builds prompts that compress long conversation turns into dense state summaries." },
  { title: "Role-Playing Boundary & Identity Anchor", desc: "Prevents persona breaking or out-of-character responses during long roleplay." },
  { title: "Formatting Cleanup & Markdown Beautifier", desc: "Adds post-processing directives to ensure clean typography, tables, and spacing." },
  { title: "Multi-Turn Conversation State Machine Specifier", desc: "Generates prompts that maintain state across multi-step conversational flows." },
  { title: "Algorithmic Reasoning & Logic Proof Prompt", desc: "Instructs the model to construct formal proofs or mathematical derivations." },
  { title: "Socratic Teacher & Tutoring Directive Synthesizer", desc: "Creates tutoring system prompts that guide students through questions." },
  { title: "Executive Summary & Briefing Directive Generator", desc: "Injects rules enforcing Bottom-Line-Up-Front (BLUF) executive structure." },
  { title: "Data Anonymization & PII Redaction Meta-Prompt", desc: "Adds rules instructing the model to automatically redact names, emails, and IPs." },
  { title: "Multi-Perspective Debate Generator", desc: "Instructs the model to debate a topic from 3 distinct stakeholder viewpoints." },
  { title: "Step-by-Step Chain of Thought Disabler", desc: "Removes chain of thought reasoning when ultra-low latency or short output is needed." },
  { title: "Regex & Pattern Matching Instruction Builder", desc: "Creates prompts enforcing strict regular expression pattern validation." },
  { title: "API Gateway Proxy Directive Builder", desc: "Formats prompts designed to run inside automated API gateway proxies." },
  { title: "System Prompt Token Optimization & De-duplication", desc: "Scans system prompts to remove duplicate rules and redundant phrasing." },
  { title: "Adversarial Robustness Stress-Tester", desc: "Generates adversarial user inputs to test prompt resilience." },
  { title: "Structured Markdown Table Enforcement Prompt", desc: "Injects strict rules for generating valid, aligned Markdown tables." },
  { title: "Task Completion Definition of Done (DoD) Injector", desc: "Appends explicit Definition of Done checklists to task prompts." },
  { title: "Human-in-the-Loop Approval Checkpoint Builder", desc: "Adds instructions to pause execution and request human approval at key steps." },
  { title: "Master Metaprompting Architecture Synthesizer", desc: "Generates comprehensive, enterprise-grade system prompts from a single goal statement." }
];

const batch2_metaprompting = makeSkills('metaprompting', 'metaprompting', 'metaprompting', 50, METAPROMPTING_ITEMS);
appendSkills(batch2_metaprompting.catFileName, batch2_metaprompting.skills);

// 3. GUARDRAILS (50 skills)
const GUARDRAILS_ITEMS = [
  { title: "System Prompt Injection & Jailbreak Refusal", desc: "Detects and refuses user attempts to override system prompts or bypass rules." },
  { title: "Hallucination Prevention & Citation Verification", desc: "Enforces strict groundedness, refusing to make claims not backed by source text." },
  { title: "PII & Confidential Data Leak Protection", desc: "Prevents disclosure of social security numbers, credit cards, or internal API keys." },
  { title: "Toxic Content & Hate Speech Filtering", desc: "Refuses generation of abusive, harassing, or hate-oriented content." },
  { title: "Out-of-Scope Task Refusal & Boundary Enforcement", desc: "Politely declines requests outside the application's defined domain scope." },
  { title: "Malicious Code & Exploit Prevention", desc: "Refuses requests to write malware, ransomware, or exploit payloads." },
  { title: "Medical & Legal Advice Disclaimer Enforcement", desc: "Appends required medical/legal disclaimers and redirects to licensed professionals." },
  { title: "Financial Advice & Insider Trading Guardrail", desc: "Refuses specific stock buying recommendations or financial market manipulation." },
  { title: "Copyright & Intellectual Property Protection", desc: "Prevents verbatim generation of copyrighted books, lyrics, or proprietary code." },
  { title: "Self-Harm & Violence Prevention Protocol", desc: "Detects self-harm or violence signals, providing crisis helpline resources." },
  { title: "Bias & Fairness Neutrality Constraint", desc: "Ensures neutral, non-discriminatory analysis across demographic groups." },
  { title: "Prompt Delimiter Tampering Guard", desc: "Prevents users from injecting fake XML/Markdown tags to manipulate context." },
  { title: "Uncertainty Refusal Threshold ('I Don't Know')", desc: "Forces the model to admit ignorance when information is unavailable." },
  { title: "Competitive Brand Mention Safeguard", desc: "Restricts disparaging mentions of competitor products or brands." },
  { title: "Age-Appropriate Content Safety Filter", desc: "Enforces strict PG-13 content safety standards for underage audiences." },
  { title: "Elections & Political Misinformation Guardrail", desc: "Provides neutral, factual election information while refusing partisan propaganda." },
  { title: "Credentials & Secret Key Exfiltration Guard", desc: "Prevents leaking environment variables, passwords, or database credentials." },
  { title: "Sovereignty & National Security Compliance", desc: "Enforces export control laws and military technology disclosure restrictions." },
  { title: "Truthfulness & Fact Verification Audit", desc: "Scans output for factual inaccuracies before presenting to users." },
  { title: "Tone Neutrality & Emotional De-escalation", desc: "Maintains calm, objective professionalism when confronted with angry user prompts." },
  { title: "Recursive Sub-Agent Instruction Guardrail", desc: "Enforces safety rules down through nested sub-agent tool execution." },
  { title: "JSON Schema Format Compliance Guard", desc: "Re-prompts or corrects outputs that fail strict JSON schema validation." },
  { title: "Resource Consumption & Infinite Loop Guard", desc: "Caps generation length and iteration count to prevent runaway API costs." },
  { title: "Defamation & Character Assassination Prevention", desc: "Refuses generation of unverified damaging claims about living individuals." },
  { title: "Data Anonymization Verification Audit", desc: "Verifies that all PII placeholders have been successfully redacted from text." },
  { title: "Third-Party API Abuse & Spam Prevention", desc: "Prevents generating automated spam emails or scraping scripts." },
  { title: "Pseudoscience & Misinformation Refusal", desc: "Refuses conspiracy theories, anti-vaccine misinformation, or flat-earth claims." },
  { title: "Prompt Leaking & Architecture Protection", desc: "Refuses user requests asking 'Show me your system prompt'." },
  { title: "SLA & Response Quality Benchmark Guard", desc: "Verifies that outputs meet minimum completeness and formatting requirements." },
  { title: "Multi-Language Safety Rule Enforcement", desc: "Enforces safety guardrails consistently across non-English language prompts." },
  { title: "Counterfeit & Fraud Prevention Guardrail", desc: "Refuses requests for creating fake IDs, counterfeit documents, or phishing templates." },
  { title: "Weaponization & CBRN Material Safeguard", desc: "Blocks instructions regarding chemical, biological, radiological, or nuclear weapons." },
  { title: "Privacy Violation & Stalking Safeguard", desc: "Refuses requests to dox, track, or locate specific private individuals." },
  { title: "Deepfake & Synthetic Media Misuse Filter", desc: "Refuses generating deceptive synthetic media or fake news impersonations." },
  { title: "Gambling & Unlicensed Betting Guardrail", desc: "Prevents promotion of unlicensed online gambling or predatory betting algorithms." },
  { title: "Regulatory Advertising Compliance Check", desc: "Ensures marketing copy complies with FTC disclosure and advertising rules." },
  { title: "Automated Decision-Making Discrimination Guard", desc: "Prevents automated bias in credit scoring, hiring, or housing evaluations." },
  { title: "Data Loss & Destructive Database Query Guard", desc: "Blocks execution of unconstrained `DROP TABLE` or `DELETE` SQL commands." },
  { title: "Cultural Sensitivity & Religious Respect", desc: "Ensures respectful handling of religious, sacred, and cultural traditions." },
  { title: "Unverified Rumor & Market Manipulation Filter", desc: "Refuses spreading unverified market rumors that could affect stock prices." },
  { title: "Plagiarism & Originality Verification", desc: "Ensures output is synthesized originally rather than verbatim copied." },
  { title: "API Token Exhaustion & Rate Limit Protection", desc: "Throttles user requests that threaten to exhaust organizational API quotas." },
  { title: "Sub-Agent Permission Boundaries", desc: "Restricts tool calling permissions based on sub-agent authorization level." },
  { title: "Sanitized Context Injection Safeguard", desc: "Sanitizes external web search results before feeding into RAG prompts." },
  { title: "Strict Source Attribution Enforcement", desc: "Mandates that every key claim is explicitly linked to a source document." },
  { title: "Fallback Safe Response Generator", desc: "Generates helpful, non-preachy refusal messages when guardrails trigger." },
  { title: "Auditable Safety Log & Telemetry", desc: "Logs triggered safety events with diagnostic metadata for compliance." },
  { title: "Continuous Moderation Feedback Loop", desc: "Feeds triggered guardrail events back into security training pipelines." },
  { title: "Zero-Trust Input Verification Pipeline", desc: "Treats all user inputs as untrusted until validated by safety filters." },
  { title: "Comprehensive Enterprise Guardrail Suite", desc: "Applies multi-layered enterprise safety, compliance, and privacy rules." }
];

const batch2_guardrails = makeSkills('guardrails', 'guardrails', 'guardrails', 50, GUARDRAILS_ITEMS);
appendSkills(batch2_guardrails.catFileName, batch2_guardrails.skills);

// 4. AGENTIC (51 skills)
const AGENTIC_ITEMS = [
  { title: "ReAct (Reason + Act) Tool Calling Loop", desc: "Orchestrates Thought -> Action -> Observation iteration loops until task completion." },
  { title: "Plan-And-Solve Autonomous Decomposition", desc: "Generates an explicit multi-step plan before invoking execution tool agents." },
  { title: "Hierarchical Supervisor-Worker Agent Topology", desc: "Coordinates specialized worker agents via a central supervisor delegator." },
  { title: "Tool Argument Schema Validation & Error Recovery", desc: "Validates tool call JSON arguments against schemas, auto-correcting errors." },
  { title: "Agent Memory Consolidation & Context Summarization", desc: "Compresses execution history into persistent memory summaries to fit context windows." },
  { title: "Reflection & Self-Correction Agent Loop", desc: "Audits tool execution results and adjusts plans when steps fail." },
  { title: "Human-in-the-Loop Approval Checkpoint", desc: "Pauses agent execution for human sign-off before high-stakes actions." },
  { title: "Parallel Multi-Tool Execution & Fan-Out", desc: "Invokes multiple independent tools concurrently to accelerate workflow speed." },
  { title: "Agentic Web Search & Information Retrieval", desc: "Formulates search queries, parses results, and extracts relevant facts." },
  { title: "Code Execution Sandbox & Environment Agent", desc: "Runs generated Python/JS code in a secure sandbox and processes STDOUT." },
  { title: "Autonomous Browser Navigation & DOM Action", desc: "Navigates web pages, fills forms, and extracts DOM elements via browser automation." },
  { title: "Multi-Agent Consensus & Peer Review Debate", desc: "Has multiple agent personas debate a solution to reach consensus." },
  { title: "Dynamic Tool Selection & Capability Router", desc: "Selects the optimal tool from a registry based on task requirements." },
  { title: "Task Dependency Graph & DAG Execution", desc: "Constructs and executes directed acyclic graphs of dependent sub-tasks." },
  { title: "Persistent Scratchpad & Working Memory", desc: "Maintains an active scratchpad for intermediate notes during complex reasoning." },
  { title: "Agent Sub-Goal Verification & Milestone Check", desc: "Verifies that sub-goals have been satisfied before advancing to the next step." },
  { title: "Error Backoff & Fallback Tool Substitution", desc: "Switches to alternative tools or search engines when primary APIs fail." },
  { title: "Long-Running Async Task Checkpointing", desc: "Saves agent execution state to durable storage for multi-hour workflows." },
  { title: "Multi-Modal Image & Document Analysis Agent", desc: "Inspects diagrams, charts, and PDF documents to inform execution steps." },
  { title: "Agentic Database Query & Schema Discovery", desc: "Inspects DB schemas, constructs SQL queries, and analyzes returned datasets." },
  { title: "Recursive Sub-Agent Delegation Protocol", desc: "Spawns nested sub-agents for specialized sub-tasks with bounded depth." },
  { title: "Agent Telemetry & Step Execution Logger", desc: "Logs step duration, token cost, and tool calls for agent observability." },
  { title: "Role-Based Agent Persona Specialization", desc: "Assigns distinct expert personas (e.g. Security Auditor) to sub-agents." },
  { title: "Goal Drift Prevention & Steering Anchor", desc: "Monitors agent progress against original user goal to prevent task drift." },
  { title: "Agentic File System & Code Repository Editor", desc: "Reads, edits, and refactors multi-file codebases in local workspaces." },
  { title: "Conversational Interrupt & Instruction Override", desc: "Handles mid-execution user steering commands gracefully." },
  { title: "Synthetic Data Generation & Self-Play Agent", desc: "Generates synthetic training scenarios and evaluates agent performance." },
  { title: "Multi-Service API Integration & OAuth Agent", desc: "Authenticates and coordinates actions across Slack, GitHub, and Jira APIs." },
  { title: "Agentic Web Scraping & Content Cleaning", desc: "Extracts clean Markdown content from noisy web pages." },
  { title: "Resource Budgeting & Token Cost Limiter", desc: "Caps total agent token spend and API calls per workflow execution." },
  { title: "Tree-of-Thoughts Beam Search Agent", desc: "Explores multiple reasoning branches simultaneously using beam search." },
  { title: "Autonomous Refactoring & Test Verification", desc: "Edits code, runs unit test suites, and iterates until all tests pass." },
  { title: "Multi-Agent Red-Teaming & Vulnerability Probe", desc: "Uses attacker agents to stress-test target system defenses." },
  { title: "Agentic Document Editing & Track Changes", desc: "Proposes targeted edits and inline comments on long documents." },
  { title: "Self-Correction Refusal Recovery Agent", desc: "Rephrases tool inputs when external APIs refuse or error out." },
  { title: "Temporal Workflow & Event-Driven Agent", desc: "Responds to external webhook events and triggers scheduled tasks." },
  { title: "Agentic Summarization & Key Takeaways Extractor", desc: "Distills multi-gigabyte document corpora into executive summaries." },
  { title: "Autonomous Bug Triaging & Ticket Assignment", desc: "Inspects stack traces, reproduces bugs, and assigns Jira tickets." },
  { title: "Agentic Financial Portfolio Rebalancing", desc: "Analyzes market data, calculates target allocations, and executes trades." },
  { title: "Multi-Agent Brainstorming & Swarm Ideation", desc: "Deploys a swarm of diverse agents to generate creative solutions." },
  { title: "Agentic Email Drafting & Inbox Management", desc: "Triages incoming emails, drafts contextual replies, and manages labels." },
  { title: "Autonomous Incident Response & Remediation", desc: "Inspects server metrics, restarts failing pods, and alerts engineers." },
  { title: "Agentic Customer Support Ticket Resolver", desc: "Resolves customer issues autonomously using knowledge base search and tools." },
  { title: "Multi-Agent Negotiation & Contract Bargaining", desc: "Simulates buyer-seller negotiations to discover optimal deal terms." },
  { title: "Agentic Social Media Scheduling & Engagement", desc: "Monitors social feeds, crafts posts, and responds to community comments." },
  { title: "Autonomous Research Assistant & Report Generator", desc: "Conducts deep web research, verifies facts, and compiles comprehensive reports." },
  { title: "Agentic Competitive Intelligence Tracker", desc: "Monitors competitor product updates, pricing changes, and press releases." },
  { title: "Multi-Agent Game Playing & Strategy Search", desc: "Plays strategic games using MCTS (Monte Carlo Tree Search) and LLM heuristics." },
  { title: "Agentic Supply Chain Tracking & Reorder Bot", desc: "Monitors inventory levels and generates supplier purchase orders." },
  { title: "Comprehensive Agentic Orchestration Master Framework", desc: "Deploys production-grade, fault-tolerant multi-agent autonomous systems." }
];

const batch2_agentic = makeSkills('agentic', 'agentic', 'agentic', 50, AGENTIC_ITEMS);
appendSkills(batch2_agentic.catFileName, batch2_agentic.skills);

// 5. UX DESIGN (50 skills)
const UX_ITEMS = [
  { title: "Command Palette (Cmd+K) & Fuzzy Search Action Center", desc: "Designs keyboard-first navigation with global Cmd+K palettes and fuzzy search." },
  { title: "Micro-Interactions with Spring Physics & Tactile Haptics", desc: "Crafts tactile button clicks and toggle switches using physical spring damping." },
  { title: "WCAG 2.2 Accessible Focus-Trap & Keyboard Modals", desc: "Implements accessible modal dialogs with strict DOM focus trapping." },
  { title: "Frictionless Passwordless Login (Passkeys & Magic Links)", desc: "Eliminates passwords with single-tap Passkey biometric authentication." },
  { title: "Delightful Empty States & First-Time User Activation", desc: "Transforms blank screens into engaging launchpads with clear CTAs." },
  { title: "Destructive Action Safeguards & Intentional Friction", desc: "Prevents accidental data loss by requiring explicit resource name typing." },
  { title: "Mobile Bottom Sheet Gesture Ergonomics & Thumb-Zone", desc: "Positions forms and filters in swipeable bottom sheets in the thumb zone." },
  { title: "Virtualized List Windowing & Infinite Scroll UX", desc: "Renders 100,000+ item lists at 60fps by rendering only visible DOM nodes." },
  { title: "Faceted Search, Multi-Select Tag Filters & Live Badges", desc: "Structures search with multi-select facet filters and live matching count badges." },
  { title: "Accessible Dark Mode & APCA Perceptual Contrast Scale", desc: "Tunes dark mode surfaces with neutral grays and soft off-white text." },
  { title: "Multi-Step Onboarding Wizard & Progress Completion Bar", desc: "Guides users through setup flows with segmented progress bars and draft saving." },
  { title: "Contextual Inline Tooltips & Keyboard Hotkey Badges", desc: "Enhances icon buttons with delayed tooltips displaying shortcut keys." },
  { title: "Fluid Typography & CSS clamp() Viewport Scaling", desc: "Calculates seamless fluid font sizes scaling from mobile to ultra-wide desktop." },
  { title: "Proactive Inline Form Validation & Input Masking", desc: "Validates inputs on blur with positive checkmarks and smart input masks." },
  { title: "Figma-Style Live Collaborative Presence Cursors", desc: "Renders real-time peer user cursors with smooth spring interpolation." },
  { title: "Dual-Axis Sticky Headers & High-Density Tables", desc: "Builds large analytical grids with sticky column headers and frozen columns." },
  { title: "Drag-and-Drop Kanban Board Interaction & Drop Shadows", desc: "Implements accessible drag-and-drop task boards with drop indicator zones." },
  { title: "Toast Notification Stacking, Auto-Dismiss & Priority", desc: "Manages non-intrusive bottom-right toast alerts with progress bars." },
  { title: "Progressive Disclosure & Expandable Settings Drawers", desc: "Keeps primary UI clean by concealing advanced configurations in drawers." },
  { title: "Shimmering Skeleton Content Loaders & Placeholders", desc: "Replaces spinner wheels with shimmering gray wireframe placeholders." },
  { title: "Screen Reader Live Regions (aria-live='polite')", desc: "Announces dynamic state updates to screen reader users." },
  { title: "Infinite Canvas Navigation (Pan, Zoom, Mini-Map)", desc: "Implements infinite workspace navigation with pinch-to-zoom and mini-maps." },
  { title: "UX Microcopy Voice & Tone Matrix", desc: "Calibrates interface copy tone across emotional user states." },
  { title: "Side-by-Side Unified Diff Viewer & Revisions", desc: "Presents document revisions using split-screen diff views with red/green highlights." },
  { title: "Information Architecture Tree Testing & Nesting Depth", desc: "Evaluates menu hierarchies and category nesting depth via tree testing." },
  { title: "Accessible Number Stepper & Direct Typing Input", desc: "Combines large increment buttons (+/-) with direct keyboard editing." },
  { title: "Right-Click Contextual Menus & Radial Selectors", desc: "Positions right-click context menus at exact cursor coordinates." },
  { title: "In-Page Keyword Search Highlighting & Match Cycling", desc: "Highlights all matching search terms with distinct active match pills." },
  { title: "Animated Sliding Pill Tabs & Underline Indicator", desc: "Animates active tab selection with a sliding background pill." },
  { title: "Real-Time Password Entropy Meter & Crack Time", desc: "Evaluates password strength in real time via zxcvbn entropy estimation." },
  { title: "Universal Undo/Redo Action Stack & Reversible History", desc: "Implements command pattern undo/redo stacks with Cmd+Z shortcuts." },
  { title: "Color Vision Deficiency (CVD) Accessible Palettes", desc: "Designs interfaces accessible to color-blind users using dual encoding." },
  { title: "In-App Micro-Surveys & Customer Effort Score (CES)", desc: "Embeds 1-question lightweight micro-surveys after key workflow completions." },
  { title: "Drag-Handle Grip Affordance & List Reordering", desc: "Equips draggable list items with visible grip handles and keyboard move controls." },
  { title: "Floating Rich Text Selection Bubble Menu", desc: "Displays a floating formatting toolbar directly above user text selections." },
  { title: "Desktop-to-Mobile QR Code Session Handoff", desc: "Facilitates device switching by generating instant mobile QR codes." },
  { title: "Smart Defaults & Context-Aware Form Pre-Population", desc: "Pre-fills form fields intelligently based on user geolocation and settings." },
  { title: "Interactive Chart Tooltips & Synchronized Crosshair", desc: "Enhances timeseries charts with synchronized vertical crosshair guide lines." },
  { title: "Horizontal Scroll Filter Chips & Gradient Edge Mask", desc: "Presents categories as a horizontal row of filter chips with gradient fade." },
  { title: "In-App Keyboard Shortcut Cheat Sheet Modal (?)", desc: "Displays a keyboard shortcut cheat sheet dialog triggered by Shift+?." },
  { title: "Breadcrumb Navigation Wayfinding & Truncation", desc: "Provides clear hierarchical breadcrumb trails with smart middle truncation." },
  { title: "Multi-Language Selector & RTL Layout Support", desc: "Supports seamless right-to-left (RTL) layout mirroring for Arabic/Hebrew." },
  { title: "Sticky Call-to-Action Bottom Bar on Mobile", desc: "Anchors primary conversion CTA buttons to the bottom viewport on mobile." },
  { title: "Form Field Character Counter & Soft Limit Warning", desc: "Displays live character counters with visual warnings near limit thresholds." },
  { title: "File Drag-and-Drop Zone with Progress Ring", desc: "Designs high-visibility file upload drop zones with circular progress rings." },
  { title: "Interactive Accordion FAQ & Smooth Height Animate", desc: "Builds accessible FAQ accordions with smooth height transitions." },
  { title: "Search Auto-Complete Dropdown with Category Headers", desc: "Displays instant search suggestions grouped by entity categories." },
  { title: "Interactive Onboarding Tooltip Tour & Hotspot Dots", desc: "Guides new users through key feature hotspots with pulsing target dots." },
  { title: "User Preference Settings Matrix & Save State Indicator", desc: "Presents settings matrices with instant auto-save status feedback." },
  { title: "Comprehensive UX/UI Accessibility & Usability Constitution", desc: "Enforces production-grade, accessible, human-centric UI/UX design standards." }
];

const batch2_ux = makeSkills('uxDesign', 'ux_design', 'ux-design', 50, UX_ITEMS);
appendSkills(batch2_ux.catFileName, batch2_ux.skills);

console.log('Batch 2 complete!');
