const { appendSkills } = require('../appendSkills.cjs');

function makeSkills(catFileName, categoryId, prefix, count, items) {
  const skills = [];
  for (let i = 0; i < count; i++) {
    const item = items[i] || {};
    const title = item.title || `${prefix} Skill ${i + 1}`;
    const cleanId = `${prefix}-${title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`;
    const pascalName = title.replace(/[^a-zA-Z0-9]/g, '') + 'Skill';

    skills.push({
      id: cleanId,
      name: pascalName,
      displayName: item.displayName || title,
      categoryId: categoryId,
      description: item.desc || `Applies advanced ${title} standards and execution patterns.`,
      tags: [categoryId, prefix, ...cleanId.split('-').slice(1, 3)],
      sectionName: item.sec || `${title} Standards`,
      ruSectionName: item.ruSec || `Стандарты и регламенты: ${title}`,
      instructions: item.inst || [
        `Apply core domain tenets for ${title}.`,
        `Enforce strict validation, error-handling, and clear structural bounds.`,
        `Verify output consistency against benchmark standards.`
      ],
      ruInstructions: item.ruInst || [
        `Применяйте ключевые принципы и стандарты для ${title}.`,
        `Обеспечивайте строгую валидацию, обработку ошибок и структурные границы.`,
        `Проверяйте результаты на соответствие эталонным критериям.`
      ],
      semanticType: item.sem || 'process_directive'
    });
  }
  return { catFileName, skills };
}

// 1. DIALOGUE TOP-UP (20 skills -> reach 165)
const DIALOGUE_TOPUP = [
  { title: "Dialogue Protocol for Remote Team Retrospectives", desc: "Leads retrospective discussions identifying continuous process improvements." },
  { title: "Strategic Questioning for High-Stakes Negotiations", desc: "Uncovers counterpart priorities through calibrated non-confrontational questions." },
  { title: "Empathetic Patient History Taking Protocol", desc: "Conducts supportive medical intake interviews uncovering hidden symptoms." },
  { title: "Socratic Guided Discovery for Student Mentorship", desc: "Guides learners to solve complex math and coding problems through inquiry." },
  { title: "Diplomatic Executive Alignment Conversation", desc: "Aligns VP-level stakeholders on shared strategic objectives and resource split." },
  { title: "De-escalation Sequence for Hostile Public Feedback", desc: "Responds to angry public comments with calm, accountable, solution-focused messaging." },
  { title: "Cross-Departmental War Room Incident Coordination", desc: "Facilitates rapid incident management dialogue between Ops and Product leads." },
  { title: "Warm Rapport Building for Executive Interviews", desc: "Establishes immediate trust and open dialogue during C-suite candidate interviews." },
  { title: "Interactive Workshop Icebreaker & Warm-Up", desc: "Engages workshop participants with active icebreaker exercises." },
  { title: "Constructive Code Review Feedback Communication", desc: "Delivers actionable, respectful code feedback encouraging engineer growth." },
  { title: "Client Offboarding & Bridge-Building Dialogue", desc: "Concludes client projects professionally while keeping doors open for future work." },
  { title: "Diplomatic Refusal of Scope Creep Requests", desc: "Manages feature requests while protecting team capacity and release dates." },
  { title: "Parent-Teacher Collaborative Growth Meeting", desc: "Builds constructive partnerships between parents and teachers to support students." },
  { title: "Investor Q&A Pitch Defense Strategy", desc: "Answers tough venture capital questions with confidence and verified data." },
  { title: "Cross-Generational Workplace Communication Bridge", desc: "Facilitates productive collaboration between team members of different generations." },
  { title: "Community Forum Anti-Trolling De-escalation", desc: "Moderates heated online discussions maintaining community guidelines." },
  { title: "Sales Objection Reframing & ROI Anchor", desc: "Addresses pricing objections by focusing on measurable business return." },
  { title: "Asynchronous Slack Team Communication Etiquette", desc: "Structures async team messages for clarity, brevity, and minimal disruption." },
  { title: "Executive Sponsor Project Briefing Protocol", desc: "Delivers concise, high-density project status updates to executive sponsors." },
  { title: "Master Dialogue & Communication Excellence", desc: "Applies world-class active listening, empathy, and negotiation skills." }
];

const batch4_dialogue = makeSkills('dialogue', 'dialogue', 'dialogue-topup', 20, DIALOGUE_TOPUP);
appendSkills(batch4_dialogue.catFileName, batch4_dialogue.skills);

// 2. CREATIVE (90 skills -> reach 165)
const CREATIVE_ITEMS = [
  { title: "Hard Magic System Sanderson Three Laws", desc: "Designs consistent fantasy magic systems governed by Sanderson's laws." },
  { title: "Pixar 22 Rules of Emotional Storytelling", desc: "Applies Pixar narrative principles: admire character effort, embrace vulnerability." },
  { title: "Poetic Synesthesia & Multi-Sensory Imagery", desc: "Constructs evocative figurative language blending cross-modal sensory perceptions." },
  { title: "Hardboiled Noir Detective Cynical Subtext", desc: "Emulates classic Raymond Chandler / Dashiell Hammett noir atmosphere and similes." },
  { title: "Cyberpunk Dystopian High-Tech Low-Life", desc: "Constructs dense cyberpunk settings: megacorps, neural wetware, street culture." },
  { title: "Surrealist Dream Logic & Automatic Writing", desc: "Explores subconscious associations, non-Euclidean spaces, and poetic juxtapositions." },
  { title: "Classical Japanese Haiku Kigo & Kireji", desc: "Composes 5-7-5 syllable haiku rooted in seasonal kigo references and kireji cutting words." },
  { title: "Homeric Epic Poetry Dactylic Hexameter", desc: "Crafts epic heroic poetry featuring Muse invocations, epithets, and extended similes." },
  { title: "Gabriel Garcia Marquez Magical Realism", desc: "Blends fantastical occurrences with calm, journalistic realism in Latin American style." },
  { title: "Steampunk Victorian Clockwork Worldbuilding", desc: "Designs alternative 19th-century worlds powered by brass gears, steam, and airships." },
  { title: "Lovecraftian Cosmic Horror & Dread", desc: "Evokes atmospheric dread through ancient non-Euclidean architectures and cosmic entities." },
  { title: "Commercial Lyric Songwriting & Prosody", desc: "Structures radio-ready song lyrics: storytelling verses, explosive choruses, bridges." },
  { title: "Epic Space Opera Intergalactic Geopolitics", desc: "Builds massive sci-fi sagas: dynastic royal houses, FTL trade, planet-spanning cultures." },
  { title: "Children Picture Book Rhythm & Rhyme", desc: "Crafts playful, read-aloud early childhood picture books featuring refrains." },
  { title: "Flash Fiction Under 500 Words Twist", desc: "Distills powerful short narratives under 500 words with punchline twists." },
  { title: "Gothic Romance Haunted Manor Atmosphere", desc: "Constructs atmospheric Victorian gothic fiction: windswept moors, ancestral curses." },
  { title: "Satirical News Parody The Onion Style", desc: "Writes razor-sharp journalistic satire using deadpan headlines and absurd premises." },
  { title: "Solarpunk Optimistic Eco-Utopian World", desc: "Builds hopeful, high-tech sustainable futures: solar glass, permaculture, co-ops." },
  { title: "Stand-Up Comedy Setup Punchline Callback", desc: "Structures stand-up comedy sets: relatable premises, misdirection, tags, callbacks." },
  { title: "Agatha Christie Murder Mystery Clue Matrix", desc: "Designs fair-play whodunits: locked-room scenes, suspect alibis, red herrings." },
  { title: "Vladimir Propp Folk Tale 31 Morphology", desc: "Structures authentic folktales using Propp's 31 narrative functions." },
  { title: "Stream of Consciousness Joyce Woolf Prose", desc: "Captures unedited sensory flow, internal monologues, and involuntary memory." },
  { title: "Cyber-Noir Augmented Reality Investigation", desc: "Merges rain-drenched hardboiled detective tropes with ocular HUD overlays." },
  { title: "Mythological Cosmogony Pantheon Creation", desc: "Generates coherent polytheistic pantheons: creation cosmogonies and divine domains." },
  { title: "Fantasy Conlang Phonotactics & Naming", desc: "Develops fictional languages with strict phonetic inventories and naming rules." },
  { title: "Blake Snyder Save the Cat 15-Beat Sheet", desc: "Structures cinematic screenplays according to the proven 15-beat timeline." },
  { title: "High Fantasy Worldbuilding Cultural Map", desc: "Architects high fantasy worlds: geography, trade routes, magic, and heraldry." },
  { title: "Post-Apocalyptic Survival Scarcity Fiction", desc: "Writes gritty post-apocalyptic fiction focused on resource scarcity and moral choices." },
  { title: "Historical Fiction Period Authenticity Arc", desc: "Crafts historical fiction with authentic dialogue, material culture, and social norms." },
  { title: "Psychological Thriller unreliable Narrator", desc: "Designs psychological thrillers featuring gaslighting and unreliable narrators." },
  { title: "Cozy Mystery Small-Town Amateur Sleuth", desc: "Writes charming cozy mysteries featuring amateur sleuths and small-town eccentricities." },
  { title: "Space Horror Alien Containment Isolation", desc: "Evokes claustrophobic horror aboard isolated space stations hunted by alien life." },
  { title: "Urban Fantasy Hidden Magic Underbelly", desc: "Designs urban fantasy settings where secret magical societies coexist with modern cities." },
  { title: "Time Travel Multiverse Causality Paradox", desc: "Structures complex time travel narratives managing grandfather paradoxes and timelines." },
  { title: "Sonnet Shakespearean iambic pentameter", desc: "Composes 14-line Shakespearean sonnets in iambic pentameter with ABAB CDCD EFEF GG rhyme." },
  { title: "Hero Journey Campbell Mythic Blueprint", desc: "Guides narrative arcs through Joseph Campbell's 12-stage monomyth journey." },
  { title: "Noir Femme Fatale & Moral Ambiguity", desc: "Crafts compelling femme fatale characters and noir moral compromises." },
  { title: "Biopunk Genetic Engineering Dystopia", desc: "Explores biopunk themes: DNA splicing, bio-hacking, and organic technology." },
  { title: "Epistolary Novel Letter & Journal Format", desc: "Tells stories through fictional letters, diary entries, emails, and police transcripts." },
  { title: "Slipstream Weird Fiction Reality Bending", desc: "Blends literary fiction, sci-fi, and surrealism into slipstream 'weird' stories." },
  { title: "Grimdark Dark Fantasy Moral Decay", desc: "Writes gritty, cynical grimdark fantasy with antiheroes and moral compromise." },
  { title: "Wuxia Martial Arts Xianxia Cultivation", desc: "Crafts Chinese wuxia/xianxia martial arts fantasy with qi cultivation and honor." },
  { title: "Regency Romance Austen Manner Social Comedy", desc: "Writes witty Regency romance focusing on ballroom etiquette and social satire." },
  { title: "Space Colonization Terraforming Hard Sci-Fi", desc: "Explores hard sci-fi terraforming mechanics and Martian colony survival." },
  { title: "Dieselpunk Interwar Retro-Futurism", desc: "Designs 1920s-1940s dieselpunk aesthetics: art deco, giant war machines, and aviation." },
  { title: "Weird West Supernatural Frontier Western", desc: "Blends 19th-century American western frontier themes with occult magic and monsters." },
  { title: "LitRPG Video Game Mechanics Narrative", desc: "Writes LitRPG fiction featuring stat screens, leveling up, loot drops, and quest lines." },
  { title: "Micro-Poetry Couplet & Epigram Precision", desc: "Crafts 2-line micro-poems and sharp epigrams delivering profound philosophical punch." },
  { title: "Interactive Narrative Choose-Your-Own-Path", desc: "Structures branching choose-your-own-adventure storylines with multiple endings." },
  { title: "Eldritch Cosmic Horror Artifact Inspection", desc: "Describes cursed artifacts whose inspection drives scholars to madness." },
  { title: "Solarpunk Community Garden City Architecture", desc: "Envisions sustainable urban architecture integrating vertical farming and solar." },
  { title: "Dark Academia Ancient Library Mystery", desc: "Writes dark academia fiction set in gothic universities centered on secret societies." },
  { title: "Hopepunk Compassionate Resistance Narrative", desc: "Crafts hopepunk fiction emphasizing radical kindness, community, and standing up to tyranny." },
  { title: "Cybernetic Cyberpunk Body Augmentation", desc: "Explores human identity trade-offs as characters replace organs with cyberware." },
  { title: "Mythic Retelling Classic Tale Feminist Lens", desc: "Retells ancient Greek or Norse myths from the perspective of sidelined female figures." },
  { title: "Hard Sci-Fi Orbital Mechanics Space Navigation", desc: "Calculates realistic delta-v burns, Hohmann transfer orbits, and artificial gravity." },
  { title: "Spaghetti Western Silent Gunslinger Standoff", desc: "Writes tense western showdowns featuring Sergio Leone cinematic pacing and silence." },
  { title: "Gaslamp Fantasy Victorian Faerie Courts", desc: "Blends Victorian London gaslight aesthetics with secret faerie realm politics." },
  { title: "Prose Poetry Paragraph Lyricism & Cadence", desc: "Writes dense, poetic prose paragraphs prioritizing rhythm and sensory resonance." },
  { title: "Kaiju Giant Monster City Destruction Arc", desc: "Drafts epic titan monster narratives featuring urban destruction and military response." },
  { title: "Time Loop Groundhog Day Narrative Arc", desc: "Structures time loop stories where protagonists relive the same day to learn lessons." },
  { title: "Cyber-Espionage Hacktivist Thriller Arc", desc: "Writes high-stakes cyber-espionage thrillers featuring encryption and whistleblowers." },
  { title: "Mythic Beast Beastiary Lore Directory", desc: "Creates detailed bestiary entries for mythical creatures: habits, weaknesses, lore." },
  { title: "Absurdist Theater Ionesco Existential Comedy", desc: "Writes absurdist theatrical dialogue exploring the breakdown of human communication." },
  { title: "High-Seas Pirate Swashbuckler Adventure", desc: "Drafts high-seas nautical adventures: naval broadsides, treasure maps, and mutinies." },
  { title: "Afrofuturism African Mythology Tech Utopia", desc: "Combines African cultural traditions, mythology, and futuristic technology." },
  { title: "Metaphorical Fabulism Animal Allegory", desc: "Writes modern Aesop-style fables using animal characters to critique human society." },
  { title: "Gothic Horror Haunted Asylum Medical Lore", desc: "Explores 19th-century abandoned asylum medical horrors and psychological dread." },
  { title: "Parallel Dimension Portal Fantasy Worlding", desc: "Designs portal fantasy transitions between mundane real-world locations and magical realms." },
  { title: "Retro 80s Synthwave Neon Nostalgia Narrative", desc: "Evokes 1980s VHS nostalgia: arcade games, synthwave music, and summer adventures." },
  { title: "Steampunk Airship Naval Battle Tactics", desc: "Describes sky battles between armored steam-powered dirigibles and gunships." },
  { title: "Interactive RPG Quest Dialogue Tree Design", desc: "Drafts branching NPC quest dialogue trees with reputation checks." },
  { title: "Cozy Fantasy Teahouse Community Craft", desc: "Writes low-stakes, warm cozy fantasy stories centered on running teahouses or bakeries." },
  { title: "Hardboiled Detective Crime Scene Forensics", desc: "Describes 1940s noir crime scenes with gritty forensic observation." },
  { title: "Surrealist Object Transformation Poem", desc: "Writes poetry where everyday household objects mutate into natural landscapes." },
  { title: "Cyberpunk Netrunning Cyberspace Visuals", desc: "Visualizes virtual reality cyberspace matrix hacks as geometric glowing architectures." },
  { title: "Epic Battle Tactical Army Formation Arc", desc: "Describes medieval military battles featuring shield walls, cavalry flanks, and archery." },
  { title: "Philosophical Dialogue Mind-Body Dualism", desc: "Writes engaging philosophical dialogues exploring consciousness and AI identity." },
  { title: "Mythological Underworld Descent Orpheus Arc", desc: "Structures heroic descent narratives into the realm of the dead to retrieve loved ones." },
  { title: "Solarpunk Permaculture Community Building", desc: "Describes cooperative eco-villages building zero-waste closed-loop systems." },
  { title: "Dark Fantasy Necromancy Magic Mechanics", desc: "Designs dark magic systems based on soul manipulation and undead animation." },
  { title: "Space Western Frontier Colony Saloon", desc: "Blends space opera and western themes on lawless outer-rim desert mining planets." },
  { title: "Cyberpunk Street Slang Lexicon & Idioms", desc: "Develops rich futuristic street slang and corporate jargon for sci-fi dialogue." },
  { title: "Gothic Romance Secret Passage Discovery", desc: "Describes dramatic discoveries of hidden chambers and diary secrets in ancient manors." },
  { title: "Time Travel Causality Repair Agency Arc", desc: "Follows time cops repairing historical anomalies caused by rogue time travelers." },
  { title: "Noir Voiceover Monologue Cynical Reflection", desc: "Writes iconic rain-slicked noir detective opening voiceover monologues." },
  { title: "High Fantasy Sacred Sword Legend Prophecy", desc: "Drafts ancient prophecies and legendary weapon forging mythologies." },
  { title: "Micro-Fiction 6-Word Story Emotional Punch", desc: "Drafts ultra-compressed 6-word micro-stories that deliver instant emotional resonance." },
  { title: "Interactive Fiction Game Master DM Guide", desc: "Provides game masters with evocative room descriptions and improvisational prompts." },
  { title: "Comprehensive Creative Writing Master Constitution", desc: "Enforces world-class creative writing, narrative architecture, and prose craft." }
];

const batch4_creative = makeSkills('creative', 'creative', 'creative', 90, CREATIVE_ITEMS);
appendSkills(batch4_creative.catFileName, batch4_creative.skills);

// 3. IDEATION (90 skills -> reach 165)
const IDEATION_ITEMS = [
  { title: "SCAMPER Creative Transformation Operator", desc: "Applies Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, Reverse." },
  { title: "Lateral Thinking Random Stimulus Association", desc: "Forces unexpected creative connections between random dictionary words and problems." },
  { title: "Crazy Eights Rapid Solution Sketching", desc: "Generates 8 distinct, rapid solution ideas in 8 minutes for rapid design exploration." },
  { title: "Six Thinking Hats Multi-Perspective Rotation", desc: "Rotates team thinking across White (Data), Red (Emotion), Black (Risk), Yellow (Optimism), Green (Creative), Blue (Process)." },
  { title: "Worst Possible Idea Reverse Brainstorming", desc: "Generates terrible ideas first to unlock hidden insights and remove performance anxiety." },
  { title: "Biomimicry Nature-Inspired Product Innovation", desc: "Adapts biological mechanisms (burrs, shark skin, bird beaks) to solve engineering problems." },
  { title: "Morphological Analysis Attribute Matrix", desc: "Deconstructs products into parameters and generates novel combinations in a grid." },
  { title: "First Principles Deconstructive Synthesis", desc: "Breaks problems down to basic physical truths and rebuilds innovative solutions." },
  { title: "Analogical Transfer Cross-Domain Synthesis", desc: "Imports proven business models from one industry into completely unrelated sectors." },
  { title: "Future Backcasting Long-Term Trajectory", desc: "Envisions a desirable 10-year future state and works backward to define present steps." },
  { title: "10x Moonshot Thinking & Extreme Scale", desc: "Forces 10x radical improvements rather than 10% incremental optimizations." },
  { title: "Value Proposition Canvas Pain-Reliever Grid", desc: "Maps customer jobs, pains, and gains to innovative product feature ideas." },
  { title: "TRIZ 40 Inventive Principles Contradiction Matrix", desc: "Resolves technical contradictions using Genrich Altshuller's 40 inventive principles." },
  { title: "Disruptive Opportunity Matrix Exploration", desc: "Identifies underserved low-end market segments ripe for simple, low-cost disruption." },
  { title: "Crazy Mashup Unrelated Domain Collision", desc: "Combines two radically different industries (e.g. Uber + Laundromat) to invent new concepts." },
  { title: "Opposable Mind Integrative Thinking Synthesis", desc: "Holds two opposing ideas in tension to create a superior third solution." },
  { title: "Customer Journey Bottleneck Inversion", desc: "Identifies the single worst moment in a customer journey and turns it into a key delight." },
  { title: "Constraint-Induced Radical Creativity", desc: "Imposes extreme artificial constraints (e.g. zero budget, 1-hour delivery) to spark breakthroughs." },
  { title: "Assumption Smashing Orthodox Challenge", desc: "Lists all industry 'unspoken rules' and systematically breaks each one." },
  { title: "Trend Collision Exponential Synthesis", desc: "Combines two emerging megatrends (e.g. AI + Synthetic Biology) to forecast new markets." },
  { title: "Science Fiction Prototyping Worldbuilding", desc: "Writes fictional future scenarios to stress-test emerging product concepts." },
  { title: "Anti-Problem Solving Dark Mode Brainstorm", desc: "Brainstorms how an enemy could destroy your business to identify defensive innovations." },
  { title: "Design Thinking Empathize-Define Innovation Loop", desc: "Generates user-centered concepts based on deep ethnographic empathy observations." },
  { title: "Blue Sky Unbounded Scenario Sandbox", desc: "Removes all technical, financial, and legal constraints for pure blue-sky ideation." },
  { title: "Rapid Paper Prototyping Concept Mock", desc: "Creates quick low-fidelity paper concept sketches to test ideas with users in 1 hour." },
  { title: "Disney Creative Strategy Three Rooms", desc: "Cycles ideas through the Dreamer (Vision), the Realist (Plan), and the Spoiler (Critique)." },
  { title: "Six Serving Men Kipling 5W1H Framework", desc: "Explores problem spaces using What, Why, When, How, Where, and Who questions." },
  { title: "Provocation & Movement (PO) Edward de Bono", desc: "Uses absurd statements ('PO: Cars have square wheels') to jumpstart lateral thinking." },
  { title: "Mind Mapping Radial Concept Expansion", desc: "Expands central ideas outward into interconnected branches of sub-concepts." },
  { title: "Lotus Blossom Idea Expansion Grid", desc: "Expands 1 core idea into 8 sub-ideas, then expands each sub-idea into 8 more." },
  { title: "SCAMPER Substitute Component Exploration", desc: "Explores substituting materials, processes, or audiences in an existing product." },
  { title: "SCAMPER Combine Feature Integration", desc: "Combines two separate products or services into a unified multi-tool." },
  { title: "SCAMPER Adapt Cross-Industry Feature", desc: "Adapts a feature from video games, aviation, or sports into corporate software." },
  { title: "SCAMPER Modify Magnify/Minify Scale", desc: "Magnifies or minifies size, speed, price, or frequency to invent new tiers." },
  { title: "SCAMPER Put to Other Uses Repurposing", desc: "Repurposes waste products or dormant assets for completely new markets." },
  { title: "SCAMPER Eliminate Feature Reduction", desc: "Eliminates core features to create ultra-simple, low-cost product variants." },
  { title: "SCAMPER Reverse Inverted Workflow", desc: "Reverses the order of operations or flips buyer-seller roles in a transaction." },
  { title: "Brainwriting 6-3-5 Silent Ideation", desc: "6 participants write 3 ideas on paper in 5 minutes, passing sheets to build on ideas silently." },
  { title: "Forced Connections Object Association", desc: "Forces logical connections between a toaster, a tree, or a shoe and your business problem." },
  { title: "Question Storming Problem Reframing", desc: "Generates 50 questions about a problem before attempting to brainstorm any answers." },
  { title: "Superhero Persona Perspective Swap", desc: "Asks 'How would Steve Jobs, Elon Musk, or Batman solve this problem?'." },
  { title: "Random Entry Dictionary Word Stimulus", desc: "Picks a random dictionary page to find unexpected metaphors for problem solving." },
  { title: "Attribute Listing Feature Decomposition", desc: "Lists all physical and functional attributes of a product, systematically tweaking each." },
  { title: "Synectics Making the Strange Familiar", desc: "Uses personal analogies, direct analogies, and fantasy analogies to reframe problems." },
  { title: "Concept Fan Problem Abstraction Ladder", desc: "Broadens or narrows problem statements to discover alternative solution spaces." },
  { title: "Wishful Thinking Magic Wand Sandbox", desc: "Asks 'If magic were real and cost zero, what would the perfect solution look like?'." },
  { title: "Zero-To-One Peter Thiel Contrarian Truth", desc: "Asks 'What important truth do very few people agree with you on?' to spot monopolies." },
  { title: "Flywheel Momentum Loop Ideation", desc: "Designs self-reinforcing business loops where each customer action drives the next." },
  { title: "Network Effect Growth Engine Ideation", desc: "Invents product features that become exponentially more valuable as more users join." },
  { title: "Unbundling Monolithic Industry Services", desc: "Unbundles complex corporate software suites into hyper-focused single-purpose apps." },
  { title: "Re-bundling Fragmented Tool Market", desc: "Re-bundles 10 disparate single-purpose tools into a unified seamless platform." },
  { title: "Freemium Viral Mechanics Ideation", desc: "Designs viral sharing mechanics where free users naturally invite paying teammates." },
  { title: "Product-Led Growth Self-Serve Onboarding", desc: "Ideates self-serve product flows that deliver Time-to-Value in under 60 seconds." },
  { title: "API-First Developer Platform Ideation", desc: "Re-imagines closed software as an open API platform for third-party developers." },
  { title: "Marketplace Two-Sided Liquidity Ideation", desc: "Solves chicken-and-egg cold-start problems in two-sided buyer-seller marketplaces." },
  { title: "Community-Led Product Ideation", desc: "Builds product features that empower power users to create and share custom content." },
  { title: "Gamification Behavior Modification Ideation", desc: "Applies streaks, XP points, leaderboards, and badges to make boring tasks engaging." },
  { title: "Micro-SaaS Niche Market Opportunity Spotting", desc: "Identifies hyper-focused software niches serving specific professional sub-cultures." },
  { title: "Subscription Recurring Revenue Model Ideation", desc: "Converts traditional one-time purchases into recurring value-add subscriptions." },
  { title: "Usage-Based Dynamic Pricing Ideation", desc: "Aligns pricing directly with customer success metrics (API calls, storage, revenue)." },
  { title: "AI-Native Workflow Re-imagination", desc: "Re-imagines classic software workflows with generative AI at the core." },
  { title: "Zero-UI Voice & Ambient Interface Ideation", desc: "Designs invisible ambient interfaces that operate via sensors and voice." },
  { title: "No-Code Visual Builder Ideation", desc: "Transforms complex code tasks into intuitive drag-and-drop visual canvas builders." },
  { title: "Sustainable Circular Economy Product Ideation", desc: "Designs products for zero-waste repair, disassembly, and infinite material recycling." },
  { title: "Hyper-Personalization Data Loop Ideation", desc: "Builds recommendation engines that customize UI and content for each individual." },
  { title: "Edge Computing Zero-Latency Ideation", desc: "Invents local-first software features that run entirely on user devices offline." },
  { title: "Augmented Reality Spatial Computing Ideation", desc: "Designs spatial 3D interfaces overlaid onto physical environments via AR glasses." },
  { title: "Biometric Continuous Authentication Ideation", desc: "Replaces login forms with passive biometric security signals." },
  { title: "Decentralized Peer-to-Peer Protocol Ideation", desc: "Architects serverless peer-to-peer applications without central company control." },
  { title: "Autonomous Agent Execution Ideation", desc: "Designs software that operates autonomously as background AI workers." },
  { title: "SaaS Vertical Integration Expansion", desc: "Expands horizontal software into vertically integrated end-to-end industry suites." },
  { title: "Crowdsourced Intelligence Engine Ideation", desc: "Harnesses collective human intelligence to solve complex data labeling tasks." },
  { title: "Embedded Financial Services Integration", desc: "Embeds banking, insurance, and lending features directly inside non-financial SaaS." },
  { title: "Dark Horse Unconventional Strategy Ideation", desc: "Explores radical, counter-intuitive business moves that competitors would never expect." },
  { title: "Silent Brainstorming Digital Card Sorting", desc: "Conducts async digital card sorting to group and prioritize product concepts." },
  { title: "User Persona Friction Point Inversion", desc: "Turns the top 3 complaints of target user personas into headline marketing features." },
  { title: "Rapid Prototyping Smoke Test Landing Page", desc: "Tests product demand by launching 1-page landing pages with email waitlists." },
  { title: "A/B Test Hypothesis Matrix Ideation", desc: "Generates high-velocity growth experiment hypotheses for conversion optimization." },
  { title: "Cross-Pollination Ecosystem Partnership", desc: "Creates strategic co-marketing partnerships with complementary non-competing brands." },
  { title: "Product Disassembly & Tear-down Analysis", desc: "Tears down competitor products step-by-step to identify hidden engineering innovations." },
  { title: "Strategic Pre-Mortem Failure Prevention", desc: "Assumes a project failed 1 year in the future and identifies all causes today." },
  { title: "Value Chain Disintermediation Ideation", desc: "Cuts out middleman distributors to connect producers directly with end consumers." },
  { title: "Hyper-Local Community Marketplace Ideation", desc: "Designs geo-fenced services that connect neighbors for local resource sharing." },
  { title: "Ethical Nudge Choice Architecture Ideation", desc: "Designs subtle interface nudges that guide users toward healthy financial/health choices." },
  { title: "Accessibility-First Innovation Universal Design", desc: "Innovates for disabled users first, creating superior features for all users." },
  { title: "Open Source Commercialization Model Ideation", desc: "Designs sustainable open-source business models around enterprise hosting/support." },
  { title: "Continuous Product Discovery Customer Cadence", desc: "Establishes weekly customer interview habits to fuel continuous feature ideation." },
  { title: "Iterative Hackathon Rapid MVP Prototyping", desc: "Runs 24-hour hackathons to build working proof-of-concept software MVPs." },
  { title: "Comprehensive Ideation & Creative Innovation Framework", desc: "Applies world-class lateral thinking, SCAMPER, and design innovation methods." }
];

const batch4_ideation = makeSkills('ideation', 'ideation', 'ideation', 90, IDEATION_ITEMS);
appendSkills(batch4_ideation.catFileName, batch4_ideation.skills);

// 4. BUSINESS (90 skills -> reach 165)
const BUSINESS_ITEMS = [
  { title: "B2B SaaS Magic Number & Sales Efficiency", desc: "Calculates SaaS Magic Number, CAC Payback, and Rule of 40." },
  { title: "Blue Ocean Strategy Canvas & ERRC Grid", desc: "Identifies uncontested market space using Eliminate-Reduce-Raise-Create grid." },
  { title: "Jim Collins Compounding Flywheel Architecture", desc: "Maps interconnected business virtuous cycles where momentum compounds." },
  { title: "Cohort Retention Heatmap & Decay Curves", desc: "Analyzes monthly customer cohort retention decay curves and asymptotic flattening." },
  { title: "McKinsey Three Horizons Portfolio Framework", desc: "Allocates capital across Horizon 1 core, Horizon 2 scaling, and Horizon 3 bets." },
  { title: "Land and Expand Enterprise Sales Framework", desc: "Enters accounts with departmental beachheads and expands to site licenses." },
  { title: "Zero-Based Budgeting (ZBB) Cost Optimization", desc: "Rebuilds department budgets from zero requiring explicit operational justification." },
  { title: "Van Westendorp Price Sensitivity Meter (PSM)", desc: "Determines acceptable price ranges using the 4-question PSM survey methodology." },
  { title: "Clayton Christensen Low-End Disruption", desc: "Analyzes how simpler, cheaper solutions enter underserved market bottoms." },
  { title: "David Sacks Burn Multiple & Capital Efficiency", desc: "Evaluates startup capital efficiency: Net Burn / Net New ARR." },
  { title: "BCG Growth-Share Portfolio Matrix Strategy", desc: "Categorizes business units into Stars, Cash Cows, Question Marks, and Dogs." },
  { title: "Product-Led Growth (PLG) Self-Serve Funnel", desc: "Drives software distribution through self-serve product experience." },
  { title: "Gross Margin Profile & COGS Structuring", desc: "Structures COGS to target healthy 75%+ software gross margins." },
  { title: "Geoffrey Moore Crossing the Chasm Framework", desc: "Guides tech startups transitioning from Early Adopters to Pragmatists." },
  { title: "Dunbar Number Organizational Scaling Points", desc: "Restructures management hierarchy at team thresholds: 15, 50, 150, 500." },
  { title: "Dynamic Pricing & Perishable Yield Management", desc: "Maximizes revenue for time-sensitive capacity via elasticity models." },
  { title: "B2B Procurement & Vendor Risk Assessment", desc: "Evaluates vendor financial solvency, SLA penalties, and business continuity." },
  { title: "Freemium Conversion & Paywall Placement", desc: "Structures feature gating, reverse trials, and contextual upgrade triggers." },
  { title: "Closed-Loop NPS Operational System", desc: "Segments feedback into Promoters, Passives, and Detractors with SLA follow-ups." },
  { title: "Franchise Model & Unit Economics Replication", desc: "Standardizes 4-wall EBITDA, royalty fees, and SOPs for franchising." },
  { title: "Post-Merger Integration (PMI) 100-Day Plan", desc: "Executes post-acquisition integration covering IT, culture, and cost synergies." },
  { title: "Channel Partner & VAR Reseller Program", desc: "Designs multi-tier reseller programs, deal registration, and co-op funds." },
  { title: "Corporate ESG & CSRD Sustainability Reporting", desc: "Measures Scope 1-3 carbon emissions and supply chain labor ethics." },
  { title: "Voice of the Customer (VoC) Listening Engine", desc: "Synthesizes customer call recordings, tickets, and reviews into feature backlogs." },
  { title: "Working Capital Cash Conversion Cycle (CCC)", desc: "Compresses DSO + DSI - DPO to liberate operating cash." },
  { title: "Key Account Management (KAM) Joint Plans", desc: "Aligns executive sponsorship and 12-month joint business plans." },
  { title: "SaaS Net Revenue Retention (NRR) Expansion", desc: "Drives account expansion through seat additions, upsells, and usage tiers." },
  { title: "B2B Sales Pipeline Stage Conversion Rate", desc: "Analyzes pipeline bottlenecks across MQL, SQL, Opportunity, and Closed-Won." },
  { title: "Unit Economics CAC Payback Period Calculation", desc: "Calculates fully-burdened CAC and payback period in months." },
  { title: "Enterprise SLA Uptime Guarantee Penalty", desc: "Structures 99.9% uptime SLAs with tier-based financial penalty credits." },
  { title: "B2B Pricing Tier Packaging & Feature Matrix", desc: "Packages features into Good-Better-Best tier plans targeting buyer personas." },
  { title: "Customer Success Health Score Early Warning", desc: "Combines telemetry, support tickets, and NPS into composite health scores." },
  { title: "Strategic Supplier Single-Source Diversification", desc: "Mitigates supply chain risk by qualifying secondary backup suppliers." },
  { title: "Corporate Divestiture & Carve-Out Strategy", desc: "Executes non-core business unit spin-offs and carve-out asset sales." },
  { title: "Subscription Churn Voluntary vs Involuntary", desc: "Reduces involuntary churn via automated dunning credit card retry logic." },
  { title: "B2B Sales Territory Realignment & Quota", desc: "Allocates enterprise sales territories and sets achievable account quotas." },
  { title: "Corporate Treasury Liquidity Runway Management", desc: "Manages cash reserves, short-term yields, and 24-month runway projections." },
  { title: "Strategic Intellectual Property Portfolio Licensing", desc: "Monetizes patent portfolios through out-licensing and cross-licensing." },
  { title: "E-Commerce Average Order Value (AOV) Boost", desc: "Increases order values via bundle discounts, cross-sells, and threshold free shipping." },
  { title: "B2B Enterprise Discount Governance Matrix", desc: "Restricts AE sales discount authority with approval workflows." },
  { title: "Joint Venture & Strategic Alliance Structure", desc: "Negotiates equity joint ventures and shared governance agreements." },
  { title: "Executive Compensation & Stock Option Pool", desc: "Designs 4-year vesting stock option pools with 1-year cliff terms." },
  { title: "Customer Acquisition Channel ROI Attribution", desc: "Attributes customer acquisition spend across Google, LinkedIn, and Organic." },
  { title: "B2B Contract Renewal Auto-Escalation Clause", desc: "Includes annual 5% price increase auto-escalation clauses in enterprise SLAs." },
  { title: "Corporate Credit Rating & Debt Covenant", desc: "Monitors leverage ratios (Net Debt / EBITDA) to comply with debt covenants." },
  { title: "Retail Store Foot-Traffic Conversion Audit", desc: "Analyzes store visitor foot-traffic conversion rates and basket sizes." },
  { title: "B2B Sales Engineering Demo Conversion", desc: "Pairs AEs with sales engineers to conduct high-converting technical proof-of-concepts." },
  { title: "Corporate Board Governance & Audit Committee", desc: "Establishes independent board audit committees and risk oversight." },
  { title: "SaaS Usage-Based Pricing Consumption Metering", desc: "Implements metered billing based on active storage, compute, or API tokens." },
  { title: "Product Sunset & Legacy EOL Migration Plan", desc: "Deprecates legacy software products with structured migration paths for users." },
  { title: "Strategic Advisory Board Incentive Equity", desc: "Recruits industry luminary advisors using 0.25%-0.5% 2-year vesting equity." },
  { title: "B2B Cold Calling Script & Objection Defusal", desc: "Arms sales SDRs with pattern-interrupt cold call scripts and objection handling." },
  { title: "Corporate Debt Refinancing & Term Loan B", desc: "Structures corporate debt refinancing to lower interest expense and extend maturities." },
  { title: "Customer Trial-to-Paid Conversion Optimization", desc: "Optimizes 14-day free trial conversion through in-app guided onboarding." },
  { title: "B2B Sales Commission Plan Incentive Structure", desc: "Designs quota-based commission tiers with accelerators for over-performance." },
  { title: "Global Transfer Pricing Tax Compliance", desc: "Sets arm's length intercompany transfer prices compliant with OECD standards." },
  { title: "Commercial Real Estate Lease Subleasing Strategy", desc: "Subleases excess corporate office footprint to reduce operating overhead." },
  { title: "B2B Enterprise Security Questionnaire Defense", desc: "Accelerates enterprise procurement deals by streamlining SOC2/ISO answers." },
  { title: "Product Category Creation & Market Education", desc: "Establishes new software product categories through thought leadership." },
  { title: "Corporate Philanthropy & Foundation Matching", desc: "Establishes corporate 1% pledge programs matching employee charitable donations." },
  { title: "B2B Content Marketing Lead Generation Funnel", desc: "Generates MQLs through gated white papers, webinars, and ROI calculators." },
  { title: "Supply Chain Vendor Quality Defect Penalties", desc: "Enforces factory defect SLA penalties on manufacturing suppliers." },
  { title: "SaaS Gross Margin Cloud Cost Optimization", desc: "Reduces AWS/GCP hosting costs to increase software gross margins toward 80%." },
  { title: "Corporate Restructuring & Severance Plan", desc: "Executes organizational rightsizing with transparent severance and job placement." },
  { title: "B2B Account-Based Marketing (ABM) Campaign", desc: "Coordinates personalized multi-channel marketing campaigns targeting top 100 enterprise accounts." },
  { title: "Franchisee Royalty Collection & Field Audit", desc: "Audits franchisee POS sales records to ensure accurate royalty collection." },
  { title: "Retail Inventory Markdown & Clearance Strategy", desc: "Executes seasonal inventory markdowns to clear slow-moving SKUs." },
  { title: "B2B Executive Sponsor Relationship Mapping", desc: "Pairs internal VP executives with C-suite stakeholders at top clients." },
  { title: "Corporate Crisis Financial Solvency Plan", desc: "Draws down credit lines and freezes non-essential CapEx during macro downturns." },
  { title: "SaaS Customer Churn Save Desk & Win-Back", desc: "Deploys specialized save desk reps to offer customized retention plans." },
  { title: "B2B Sales Partner Portal & Co-Op Funds", desc: "Provides resellers with co-branded marketing materials and MDF funds." },
  { title: "Corporate Shared Services Efficiency Hub", desc: "Consolidates back-office HR, Finance, and IT functions into shared service hubs." },
  { title: "E-Commerce Return Rate Reduction Strategy", desc: "Reduces apparel return rates via accurate sizing charts and 3D product previews." },
  { title: "B2B Enterprise Pilot-to-Contract Conversion", desc: "Converts paid proof-of-concept pilots into multi-year site licenses." },
  { title: "Corporate Insurance Liability & D&O Coverage", desc: "Secures Directors & Officers (D&O), cyber liability, and general liability policies." },
  { title: "SaaS Multi-Year Contract Upfront Payment Discount", desc: "Offers 15% discounts for multi-year upfront contract cash payments." },
  { title: "B2B SDR Lead Qualification BANT Standard", desc: "Qualifies inbound sales leads across Budget, Authority, Need, and Timeline." },
  { title: "Corporate Employee Referral Bonus Program", desc: "Drives high-quality engineering hires through cash employee referral bonuses." },
  { title: "Supply Chain Just-in-Time (JIT) Buffer Safety", desc: "Balances JIT lean inventory with strategic safety stock buffers." },
  { title: "B2B Customer Advocacy & Reference Program", desc: "Nurtures customer advocates to participate in prospect reference calls." },
  { title: "Corporate Pension & 401(k) Matching Governance", desc: "Manages employee retirement benefits and fiduciary committee oversight." },
  { title: "SaaS Benchmark Valuation Multiple Analysis", desc: "Evaluates company valuation multiples (EV/ARR) based on growth and NRR." },
  { title: "B2B Field Marketing Regional Event Strategy", desc: "Hosts intimate C-suite dinners and regional roundtables to accelerate enterprise deals." },
  { title: "Corporate Foreign Exchange Risk Hedging", desc: "Mitigates currency fluctuations using forward contracts and currency options." },
  { title: "E-Commerce Loyalty Program Point Redemption", desc: "Designs gamified customer loyalty programs driving repeat purchase frequency." },
  { title: "B2B Sales Demo Script & Value Narrative", desc: "Structures 30-minute sales demo scripts focused on prospect pain points." },
  { title: "Corporate Offshoring & Global Capability Center", desc: "Establishes global capability centers (GCC) in India or Poland for engineering." },
  { title: "SaaS Product Expansion Seat Add-On Engine", desc: "Drives organic seat expansion as client departments adopt software." },
  { title: "Comprehensive Business Strategy & Execution Constitution", desc: "Enforces world-class corporate strategy, unit economics, and operational rigor." }
];

const batch4_business = makeSkills('business', 'business', 'business', 90, BUSINESS_ITEMS);
appendSkills(batch4_business.catFileName, batch4_business.skills);

// 5. EDUCATION (90 skills -> reach 165)
const EDUCATION_ITEMS = [
  { title: "Bloom Taxonomy Cognitive Scaffolding", desc: "Scaffolds learning from Remember -> Understand -> Apply -> Analyze -> Evaluate -> Create." },
  { title: "Feynman Radical Concept Simplification", desc: "Simplifies complex scientific topics so a 12-year-old can understand without jargon." },
  { title: "Spaced Repetition & Leitner Box Schedule", desc: "Schedules review intervals based on memory decay curves to maximize retention." },
  { title: "Cognitive Load Working Memory Limits", desc: "Manages intrinsic, extraneous, and germane cognitive load in instructional design." },
  { title: "Inquiry-Based Learning Scientific Discovery", desc: "Guides students through hypothesis formation, experimentation, and data analysis." },
  { title: "Gamified Formative Quiz & Feedback", desc: "Designs low-stakes interactive quizzes providing instant corrective feedback." },
  { title: "Universal Design for Learning (UDL)", desc: "Provides multiple means of Engagement, Representation, and Action/Expression." },
  { title: "Socratic Seminar Critical Inquiry Circles", desc: "Facilitates student-led discussion circles analyzing foundational primary texts." },
  { title: "Problem-Based Case Challenge Learning", desc: "Presents messy real-world scenarios for small team collaborative problem-solving." },
  { title: "Scaffolded Worked Examples Step-by-Step", desc: "Provides fully solved examples transitioning gradually to independent practice." },
  { title: "Metacognitive Self-Reflection Prompting", desc: "Prompts students to reflect on their own thinking, strategies, and learning gaps." },
  { title: "Flipped Classroom Interactive Exploration", desc: "Moves lectures to home viewing, freeing class time for active problem-solving." },
  { title: "Differentiated Tiered Instruction", desc: "Adapts lesson complexity and support levels for diverse learner readiness tiers." },
  { title: "Peer Instruction & Mazur Concept Tests", desc: "Uses short conceptual clicker questions followed by peer discussion to fix misconceptions." },
  { title: "Direct Instruction Mastery Learning", desc: "Requires 90% mastery on foundational modules before advancing to next topics." },
  { title: "Experiential Learning Kolb Cycle", desc: "Cycles through Concrete Experience -> Reflection -> Abstract Concepts -> Active Testing." },
  { title: "Story-Driven Mnemonic Memory Palaces", desc: "Associates abstract information with vivid spatial locations in memory palaces." },
  { title: "Zone of Proximal Development (ZPD) Calibrator", desc: "Keeps task difficulty in the sweet spot between boring ease and overwhelming anxiety." },
  { title: "Formative Rubric Scoring & Feedback", desc: "Evaluates student work using clear analytic rubrics paired with actionable next steps." },
  { title: "Interleaved Practice Problem Sets", desc: "Mixes different problem types within practice sets to build flexible problem selection." },
  { title: "Project-Based Learning Showcase Milestones", desc: "Guides semester-long student projects culminating in public community showcases." },
  { title: "Dual Coding Theory Visual-Verbal Harmony", desc: "Pairs concise verbal explanations with complementary visual diagrams." },
  { title: "Concept Mapping Hierarchical Schemas", desc: "Guides students to construct visual maps connecting core concepts and relationships." },
  { title: "Growth Mindset Productive Struggle Cues", desc: "Praises effort, strategy, and perseverance rather than innate intelligence." },
  { title: "Real-World Scenario Roleplay Simulation", desc: "Immerses students in simulated professional roles to apply theoretical knowledge." },
  { title: "Retrieval Practice Active Flashcard Recall", desc: "Uses active recall quizzes rather than passive re-reading to solidify memory." },
  { title: "Adaptive Learning Individualized Pace", desc: "Dynamically adjusts curriculum difficulty based on real-time student performance." },
  { title: "Elaborative Interrogation 'Why' Questions", desc: "Prompts learners to explain why facts are true to deepen conceptual encoding." },
  { title: "Explicit Schema Activation Warm-Up", desc: "Activates prior knowledge before introducing new complex academic concepts." },
  { title: "Anchor Based Instruction Video Context", desc: "Anchors math and science learning in engaging video-based adventure contexts." },
  { title: "Peer Tutoring Cross-Age Buddy System", desc: "Pairs older students with younger peers to reinforce mastery through teaching." },
  { title: "Micro-Learning Bitesized Video Modules", desc: "Breaks complex courses into 3-5 minute self-contained video learning modules." },
  { title: "Rubric Co-Creation Student Ownership", desc: "Involves students in co-creating grading rubrics to build ownership of quality." },
  { title: "Self-Regulated Learning Goal Tracking", desc: "Guides students to set weekly learning goals, monitor time, and evaluate progress." },
  { title: "Analogical Mapping Conceptual Bridges", desc: "Uses familiar everyday analogies to introduce unintuitive scientific concepts." },
  { title: "Culturally Responsive Teaching Pedagogy", desc: "Connects curriculum content to diverse student cultural backgrounds and experiences." },
  { title: "Interactive Science Lab Virtual Simulator", desc: "Guides virtual physics and chemistry experiments with parameter controls." },
  { title: "Authentic Assessment Real-World Portfolio", desc: "Evaluates student competence through curated portfolios of authentic work." },
  { title: "Socio-Emotional Learning (SEL) Self-Awareness", desc: "Integrates emotional regulation, empathy, and relationship building into daily routines." },
  { title: "Jigsaw Cooperative Expert Group Learning", desc: "Divides topics among student 'experts' who teach their section to group members." },
  { title: "Think-Pair-Share Collaborative Pacing", desc: "Allows individual thinking time, peer discussion, and whole-class sharing." },
  { title: "Guided Note-Taking Graphic Organizers", desc: "Provides structured fill-in-the-blank outline notes to support lecture listening." },
  { title: "Math Concrete-Representational-Abstract (CRA)", desc: "Transitions math instruction from physical blocks to visual drawings to abstract symbols." },
  { title: "Phonics Explicit Decodable Reading", desc: "Teaches early reading through systematic phonics rules and decodable text practice." },
  { title: "Vocabulary Frayer Model Definition Grid", desc: "Explores new terms via Definition, Characteristics, Examples, and Non-Examples." },
  { title: "Constructivist Knowledge Co-Construction", desc: "Facilitates student discovery where learners actively construct their own understanding." },
  { title: "Scaffolded Writing CER (Claim-Evidence-Reasoning)", desc: "Structures persuasive academic essays: Claim -> Supporting Evidence -> Reasoning." },
  { title: "Gamified Digital Leaderboard & Badge Systems", desc: "Motivates student assignment completion through badges, levels, and achievements." },
  { title: "Special Education Individualized Education Program (IEP)", desc: "Adapts curriculum accommodations and goals for neurodiverse special needs learners." },
  { title: "English Language Learner (ELL) Sheltered Instruction", desc: "Supports non-native speakers with visual aids, sentence frames, and simplified syntax." },
  { title: "Mastery-Based Standards Grading Scale", desc: "Grades student work against standards mastery rather than points-based homework completion." },
  { title: "Flipped Classroom Pre-Class Video Quiz", desc: "Checks pre-class video comprehension with 3 quick check-in questions before class." },
  { title: "Case-Based Clinical Medical Education", desc: "Guides medical students through patient diagnostic case studies and differential reasoning." },
  { title: "Executive Function Time Management Coaching", desc: "Teaches students how to break large term papers into manageable daily tasks." },
  { title: "Design Thinking K-12 Innovation Challenge", desc: "Guides middle school students through design thinking projects to solve community problems." },
  { title: "Interactive Coding Playground Auto-Grader", desc: "Provides instant feedback on coding exercises with automated test suite checks." },
  { title: "Peer-to-Peer Essay Review Protocol", desc: "Structures constructive peer writing reviews using rubric checklists." },
  { title: "Socratic Method Legal Case Dialogue", desc: "Guides law students through cold-call questioning on landmark legal precedents." },
  { title: "Project-Based Science Fair Research Milestone", desc: "Scaffolds science fair projects from question to variable control and poster presentation." },
  { title: "Early Childhood Play-Based Learning Exploration", desc: "Fosters early cognitive development through structured sensory play and discovery." },
  { title: "Adult Learning Theory (Andragogy) Self-Direction", desc: "Designs adult professional training focused on immediate practical application." },
  { title: "Blended Learning Station Rotation Model", desc: "Rotates students between teacher instruction, online learning, and small group work." },
  { title: "Executive Summary Study Guide Synthesis", desc: "Summarizes textbook chapters into high-density 2-page exam study guides." },
  { title: "Interactive Geometry Proof Construction", desc: "Guides students through step-by-step geometric proofs with logical justifications." },
  { title: "Gamified Reading Comprehension Quest", desc: "Turns chapter reading into interactive story quests with decision choices." },
  { title: "STEM Robotics Engineering Challenge", desc: "Scaffolds robotics building and programming challenges for middle school teams." },
  { title: "Universal Primary Source Document Analysis", desc: "Guides history students to analyze primary sources for bias, context, and intent." },
  { title: "Calculus Visual Derivative Rate-of-Change", desc: "Teaches calculus derivatives visually using secant line slope approximations." },
  { title: "Computer Science Algorithmic Thinking unplugged", desc: "Teaches sorting and searching algorithms using physical cards and unplugged activities." },
  { title: "Music Theory Sight-Reading & Solfege", desc: "Scaffolds musical sight-reading skills through solfege hand signs and rhythm exercises." },
  { title: "Art History Visual Thinking Strategy (VTS)", desc: "Facilitates open-ended group discussion of artwork: 'What's going on in this picture?'." },
  { title: "Physical Education Motor Skill Progression", desc: "Breaks complex athletic movements (throwing, jumping) into developmental phases." },
  { title: "Chemistry Molecular Model Building Lab", desc: "Teaches chemical bonding and VSEPR geometry using 3D physical model kits." },
  { title: "Foreign Language Immersion Conversation", desc: "Conducts target language practice using gestures, visuals, and 90%+ immersion." },
  { title: "Financial Literacy Budgeting & Compound Interest", desc: "Teaches high school students personal budgeting, credit card math, and investing." },
  { title: "Environmental Science Eco-System Simulation", desc: "Simulates food web predator-prey dynamics and ecological population balance." },
  { title: "Geography Spatial Map Layering Skills", desc: "Teaches GIS map reading, topographic elevation lines, and spatial analysis." },
  { title: "Psychology Behavioral Conditioning Lab", desc: "Demonstrates classical and operant conditioning principles through interactive examples." },
  { title: "Debate Club Argumentation & Refutation", desc: "Trains high school debate teams in constructing arguments, evidence, and cross-examination." },
  { title: "Creative Writing Story Arc Workshop", desc: "Guides young writers to develop character motivations, inciting incidents, and climaxes." },
  { title: "Philosophy Ethics Thought Experiment Circle", desc: "Facilitates student discussions of ethical dilemmas (Trolley Problem, Experience Machine)." },
  { title: "Microbiology Bacterial Culture & Staining Lab", desc: "Teaches sterile lab techniques, Gram staining, and microscope identification." },
  { title: "Physics Kinematics Motion Graphing", desc: "Connects physical toy car motion to position-time and velocity-time graphs." },
  { title: "Civics & Government Mock Trial Simulation", desc: "Immerses students in court trial roles: attorneys, witnesses, and jury members." },
  { title: "Data Literacy Chart Reading & Misleading Graphs", desc: "Teaches students how to spot manipulated Y-axes and misleading data visualizations." },
  { title: "Mindfulness & Brain Break Stress Reduction", desc: "Leads short 2-minute breathing exercises before high-stakes exams to reduce anxiety." },
  { title: "Peer Study Group Facilitation Guide", desc: "Provides student study groups with structured agendas and practice question sets." },
  { title: "Holistic Teacher Professional Development Workshop", desc: "Trains educators on innovative classroom management and instructional tech." },
  { title: "Comprehensive Pedagogy & Instructional Excellence Constitution", desc: "Enforces world-class educational scaffolding, Bloom taxonomy, and active learning." }
];

const batch4_education = makeSkills('education', 'education', 'education', 90, EDUCATION_ITEMS);
appendSkills(batch4_education.catFileName, batch4_education.skills);

// 6. MEDICAL (90 skills -> reach 165)
const MEDICAL_ITEMS = [
  { title: "SOAP Note Clinical Documentation Standard", desc: "Structures medical encounters: Subjective, Objective, Assessment, and Plan." },
  { title: "GRADE Evidence-Based Quality Assessment", desc: "Scores clinical research evidence quality from High to Very Low." },
  { title: "Clinical Pharmacokinetics Dosing Calculation", desc: "Calculates drug clearance, volume of distribution, and peak/trough levels." },
  { title: "qSOFA & Sepsis Early Warning Screening", desc: "Screens patients for sepsis using altered mental status, respiratory rate, and blood pressure." },
  { title: "12-Lead Electrocardiogram (ECG) Interpretation", desc: "Systematically reads ECGs: rate, rhythm, axis, intervals, ST elevation, ischemia." },
  { title: "Palliative Care Serious Illness Conversation", desc: "Navigates end-of-life goals of care discussions with patients and families." },
  { title: "Antibiotic Stewardship Antibiogram Guidance", desc: "Selects empirical antibiotics based on local hospital resistance patterns." },
  { title: "TNM Cancer Staging & Multidisciplinary Tumor Board", desc: "Stages solid tumors by Tumor size, Nodal spread, and Metastasis." },
  { title: "Pediatric Resuscitation Broselow Tape Dosing", desc: "Calculates emergency pediatric drug doses and equipment sizes by length." },
  { title: "ATLS Trauma Primary & Secondary Survey", desc: "Executes Advanced Trauma Life Support survey: Airway, Breathing, Circulation, Disability." },
  { title: "ACC/AHA Hypertension Treatment Algorithm", desc: "Manages blood pressure using stepwise lifestyle, ACEi/ARB, CCB, and thiazides." },
  { title: "ADA Type 2 Diabetes Glycemic Management", desc: "Manages HbA1c targets using metformin, SGLT2i, GLP-1 RA, and insulin." },
  { title: "DSM-5 Diagnostic Criteria Mental Health Workup", desc: "Evaluates psychiatric symptoms against DSM-5 criteria for Major Depression, Bipolar, Anxiety." },
  { title: "Chest X-Ray ABCDE Systematic Interpretation", desc: "Reads CXRs systematically: Airway, Breathing, Cardiac, Diaphragm, Everything else." },
  { title: "Revised Cardiac Risk Index (RCRI) Preop Assessment", desc: "Evaluates perioperative cardiac risk before major non-cardiac surgery." },
  { title: "NIHSS Rapid Stroke Assessment & tPA Eligibility", desc: "Evaluates acute ischemic stroke severity and contraindications for thrombolytics." },
  { title: "Obstetric Postpartum Hemorrhage Emergency Protocol", desc: "Manages 4 Ts of PPH (Tone, Trauma, Tissue, Thrombin) with uterotonics." },
  { title: "Hospital Infection Control & PPE Biohazard Isolation", desc: "Enforces Contact, Droplet, and Airborne isolation precautions." },
  { title: "KDIGO Chronic Kidney Disease Staging", desc: "Stages CKD by GFR and albuminuria categories, managing renoprotection." },
  { title: "GINA Asthma Stepwise Escalation Management", desc: "Adjusts inhaler therapy based on symptom control and exacerbation history." },
  { title: "Rapid Sequence Induction (RSI) Emergency Airway", desc: "Executes emergency endotracheal intubation with induction agents and paralytics." },
  { title: "Dermatology ABCDE Melanoma Lesion Screening", desc: "Evaluates skin lesions for Asymmetry, Border, Color, Diameter, and Evolving." },
  { title: "Surgical Site Infection (SSI) Prevention Surveillance", desc: "Implements pre-op chlorhexidine, prophylactic antibiotics, and sterile technique." },
  { title: "ACLS Cardiac Arrest Megacode Algorithm", desc: "Directs CPR, defibrillation for VF/pVT, epinephrine, and amiodarone." },
  { title: "Medical Ethics Four Principles Framework", desc: "Balances Autonomy, Beneficence, Non-Maleficence, and Justice in clinical cases." },
  { title: "SBAR Clinical Handoff Communication Standard", desc: "Communicates patient handoffs: Situation, Background, Assessment, Recommendation." },
  { title: "Differential Diagnosis Bayesian Probability Synthesis", desc: "Refines pre-test to post-test disease probabilities using likelihood ratios." },
  { title: "Opioid Risk Tool & Safe Chronic Pain Management", desc: "Screens patients for addiction risk and monitors multimodal non-opioid pain plans." },
  { title: "Anaphylaxis Emergency Treatment & Epinephrine Dosing", desc: "Identifies systemic allergic reactions and administers immediate IM epinephrine." },
  { title: "DKA / HHS Diabetic Emergency Fluid & Insulin Protocol", desc: "Manages diabetic ketoacidosis with aggressive fluids, IV insulin, and potassium monitoring." },
  { title: "Heart Failure HFrEF Quadruple Therapy Escalation", desc: "Optimizes ARNI/ACEi, beta-blockers, MRA, and SGLT2i for reduced ejection fraction." },
  { title: "Venous Thromboembolism (VTE) Prophylaxis Risk Score", desc: "Evaluates Padua/Caprini scores to prescribe chemical/mechanical DVT prevention." },
  { title: "Acute Coronary Syndrome (ACS) Initial Management", desc: "Administers MONA (Morphine, Oxygen, Nitrates, Aspirin) and heparin for chest pain." },
  { title: "Inpatient Delirium CAM Screening & Prevention", desc: "Screens for acute confusion using Confusion Assessment Method and avoids sedatives." },
  { title: "Polytrauma Massive Transfusion Protocol (MTP)", desc: "Transfuses 1:1:1 ratios of packed RBCs, FFP, and platelets in hemorrhagic shock." },
  { title: "Pediatric Dehydration Oral vs IV Rehydration", desc: "Calculates fluid deficit and maintenance requirements in pediatric gastroenteritis." },
  { title: "Thyroid Storm Emergency Resuscitation Protocol", desc: "Manages hyperthyroid crisis with propylthiouracil, iodine, beta-blockers, and steroids." },
  { title: "Spinal Cord Injury Immobilization & Neuro Check", desc: "Maintains C-spine stabilization and conducts ASIA neurological impairment scoring." },
  { title: "Hepatic Encephalopathy Lactulose & Rifaximin Therapy", desc: "Treats liver cirrhosis confusion with lactulose bowel cleanses and targeted antibiotics." },
  { title: "COPD Acute Exacerbation Oxygen & Steroid Protocol", desc: "Manages COPD flares with controlled O2 targets (88-92%), bronchodilators, and steroids." },
  { title: "Acute Pancreatitis Ranson Criteria & Fluid Resuscitation", desc: "Predicts pancreatitis severity and administers targeted crystalloid fluids." },
  { title: "Hypertensive Emergency Target Organ Damage Escalation", desc: "Reduces blood pressure by max 25% in hour 1 using IV nicardipine or labetalol." },
  { title: "Pediatric Febrile Seizure Parental Reassurance", desc: "Evaluates simple vs complex febrile seizures and counsels anxious parents." },
  { title: "Neutropenic Fever Empiric Antibiotic Escalation", desc: "Initiates immediate antipseudomonal beta-lactam monotherapy for oncology fevers." },
  { title: "Psychiatric Suicide Risk Assessment (SAFE-T Protocol)", desc: "Evaluates ideation, intent, plan, and protective factors to determine level of care." },
  { title: "Geriatric Polypharmacy & Beers Criteria Medication Audit", desc: "Identifies potentially inappropriate medications in elderly patients to prevent falls." },
  { title: "Burn Resuscitation Parkland Formula Fluid Calculation", desc: "Calculates 24-hour Lactated Ringer's fluid requirements based on % Total Body Surface Area." },
  { title: "Acute Glaucoma Intraocular Pressure Reduction Protocol", desc: "Administers topical beta-blockers, alpha-agonists, and IV acetazolamide for eye pain." },
  { title: "Rheumatoid Arthritis Disease-Modifying Anti-Rheumatic Therapy", desc: "Escalates methotrexate and biologic DMARDs to achieve clinical remission." },
  { title: "Inflammatory Bowel Disease Crohn's vs Ulcerative Colitis", desc: "Differentiates skip lesions vs continuous mucosal inflammation on colonoscopy." },
  { title: "Gout Acute Exacerbation Colchicine & NSAID Therapy", desc: "Treats acute uric acid crystal arthritis with colchicine and avoids starting allopurinol mid-flare." },
  { title: "Hyperkalemia Emergency Cardiac Membrane Stabilization", desc: "Administers IV calcium gluconate for ECG changes, followed by insulin/glucose." },
  { title: "Hyponatremia Corrected Sodium & Osmotic Demyelination", desc: "Limits sodium correction to max 8 mEq/L in 24 hours to prevent central pontine myelinolysis." },
  { title: "Alcohol Withdrawal CIWA Protocol & Benzodiazepines", desc: "Monitors CIWA-Ar scores and administers symptom-triggered lorazepam." },
  { title: "Lyme Disease Erythema Migrans & Doxycycline Protocol", desc: "Diagnoses bullseye rash and prescribes 10-14 days of oral doxycycline." },
  { title: "Community-Acquired Pneumonia CURB-65 Outpatient vs Inpatient", desc: "Scores Confusion, Urea, Respiratory rate, Blood pressure, Age 65 to decide admission." },
  { title: "Osteomyelitis MRI Diagnosis & Long-Term Antibiotics", desc: "Confirms bone infection on MRI and manages 6-week targeted IV antibiotic courses." },
  { title: "Deep Vein Thrombosis (DVT) Wells Score & DOAC Therapy", desc: "Evaluates pre-test probability, orders D-dimer/ultrasound, and initiates apixaban." },
  { title: "Pulmonary Embolism PERC Rule & CT Pulmonary Angiogram", desc: "Rules out PE with PERC criteria or confirms with CTPA in high-risk patients." },
  { title: "Cervical Spine Clearance Nexus Criteria & Canadian Rule", desc: "Clears C-spine clinically without X-rays in low-risk trauma patients." },
  { title: "Pericarditis Friction Rub & Colchicine Anti-Inflammatory", desc: "Identifies PR depression / diffuse ST elevation on ECG and prescribes colchicine." },
  { title: "Infective Endocarditis Duke Criteria & Blood Cultures", desc: "Diagnoses heart valve infections using major bacteremia and echo criteria." },
  { title: "Multiple Sclerosis McDonald Diagnostic Criteria & MRI", desc: "Confirms demyelinating lesions separated in time and space on brain MRI." },
  { title: "Parkinson's Disease Cardinal Symptoms & Levodopa Therapy", desc: "Identifies Bradykinesia, Resting Tremor, and Rigidity, titrating carbidopa-levodopa." },
  { title: "Myasthenia Gravis Pyridostigmine & Crisis Surveillance", desc: "Treats neuromuscular weakness with acetylcholinesterase inhibitors." },
  { title: "Aortic Dissection Stanford Type A vs B Emergency", desc: "Identifies tearing chest/back pain, managing Type A with immediate surgery." },
  { title: "Abdominal Aortic Aneurysm (AAA) Screening & Repair Threshold", desc: "Monitors AAA diameter with ultrasound, referring for repair at >= 5.5 cm." },
  { title: "Peripheral Artery Disease Ankle-Brachial Index (ABI)", desc: "Diagnoses leg claudication with ABI < 0.9 and prescribes cilostazol." },
  { title: "Idiopathic Pulmonary Fibrosis High-Resolution CT", desc: "Identifies usual interstitial pneumonia (UIP) honeycombing on chest CT." },
  { title: "Obstructive Sleep Apnea Stop-Bang Screening & CPAP", desc: "Screens snoring and daytime somnolence, prescribing continuous positive airway pressure." },
  { title: "Gastroesophageal Reflux Disease (GERD) PPI Escalation", desc: "Manages heartburn with 8-week proton pump inhibitor trials and lifestyle changes." },
  { title: "Peptic Ulcer Disease H. pylori Eradication Quadruple Therapy", desc: "Treats stomach ulcers with bismuth, metronidazole, tetracycline, and PPI." },
  { title: "C. difficile Colitis Vancomycin Oral Regimen", desc: "Treats severe watery diarrhea after antibiotic exposure with oral vancomycin." },
  { title: "Nonalcoholic Fatty Liver Disease (NAFLD) FIB-4 Score", desc: "Calculates non-invasive liver fibrosis risk scores to guide lifestyle interventions." },
  { title: "Polycystic Ovary Syndrome (PCOS) Rotterdam Criteria", desc: "Diagnoses PCOS based on oligo-ovulation, hyperandrogenism, and polycystic ovaries." },
  { title: "Endometriosis Dysmenorrhea & Hormonal Suppression", desc: "Manages pelvic pain with NSAIDs, oral contraceptives, and GnRH agonists." },
  { title: "Benign Prostatic Hyperplasia (BPH) AUA Symptom Score", desc: "Treats urinary hesitancy with tamsulosin (alpha-blocker) and finasteride." },
  { title: "Nephrolithiasis Kidney Stone CT & Alpha-Blocker Pass", desc: "Evaluates stone size on non-contrast CT, prescribing tamsulosin for stones < 10mm." },
  { title: "Urinary Tract Infection Uncomplicated Cystitis Nitrofurantoin", desc: "Treats female dysuria with 5 days of oral nitrofurantoin or single-dose fosfomycin." },
  { title: "Osteoporosis DEXA Scan T-Score & Bisphosphonate", desc: "Diagnoses osteoporosis at T-score <= -2.5, prescribing oral alendronate." },
  { title: "Fibromyalgia Widespread Pain Index & SNRI Therapy", desc: "Manages chronic musculoskeletal pain with duloxetine, pregabalin, and exercise." },
  { title: "Major Depressive Disorder PHQ-9 & SSRI Selection", desc: "Monitors depression severity with PHQ-9, selecting sertraline or escitalopram." },
  { title: "Generalized Anxiety Disorder GAD-7 & CBT Therapy", desc: "Treats persistent worry with cognitive behavioral therapy and SSRIs." },
  { title: "Schizophrenia Positive vs Negative Symptoms & Antipsychotics", desc: "Manages hallucinations with second-generation antipsychotics like risperidone." },
  { title: "Bipolar I Disorder Acute Mania Lithium & Valproate", desc: "Stabilizes mood swings with lithium or divalproex, monitoring serum blood levels." },
  { title: "Attention Deficit Hyperactivity Disorder (ADHD) Stimulant Titration", desc: "Treats inattention in children and adults with methylphenidate or amphetamines." },
  { title: "Post-Traumatic Stress Disorder (PTSD) PCL-5 & Prolonged Exposure", desc: "Treats trauma flashbacks with trauma-focused CBT and prazosin for nightmares." },
  { title: "Anorexia Nervosa Refeeding Syndrome Prevention", desc: "Monitors electrolyte drops (phosphate, potassium) during nutritional re-feeding." },
  { title: "Obesity Bariatric Surgery Qualification Criteria", desc: "Refers patients with BMI >= 40 or BMI >= 35 with comorbidities for bariatric evaluation." },
  { title: "Comprehensive Clinical Medicine & Evidence-Based Constitution", desc: "Enforces world-class medical evidence scoring, SOAP documentation, and patient safety." }
];

const batch4_medical = makeSkills('medical', 'medical', 'medical', 90, MEDICAL_ITEMS);
appendSkills(batch4_medical.catFileName, batch4_medical.skills);

console.log('Batch 4 complete!');
