const { appendSkillsToCategory } = require('./appendSkills.cjs');

// 37 skills for analysis (current 33 -> 70)
const analysisSkills = [
  {
    id: 'fmea-rpn-severity-occurrence-detection',
    name: 'FmeaRpnSeverityOccurrenceDetectionSkill',
    displayName: 'Failure Mode and Effects Analysis (FMEA & RPN Scoring)',
    categoryId: 'analysis',
    description: 'Calculates Risk Priority Numbers (RPN = Severity x Occurrence x Detection) to objectively rank system vulnerabilities.',
    tags: ['analysis', 'fmea', 'rpn', 'risk-assessment', 'reliability'],
    semanticType: 'process_directive',
    sectionName: 'FMEA Failure Mode & RPN Scoring Protocol',
    ruSectionName: 'Анализ видов и последствий отказов (FMEA / RPN)',
    instructionsEn: [
      'Catalog all discrete failure modes and score each on a 1-10 scale across three factors: Severity (S), Occurrence frequency (O), and Detectability (D).',
      'Compute the Risk Priority Number: RPN = S x O x D (range 1-1,000).',
      'Establish a hard remediation threshold: mandate corrective engineering actions for any failure mode with RPN > 100 or Severity ≥ 9.',
      'Document post-mitigation RPN target scores verifying residual risk reduction.',
    ],
    instructionsRu: [
      'Составьте перечень сценариев отказов и оцените каждый по шкале 1–10: Тяжесть (S), Частота возникновения (O), Обнаруживаемость (D).',
      'Рассчитайте индекс приоритета риска: RPN = S x O x D (диапазон от 1 до 1000).',
      'Внедрите жесткий порог: обязательное инженерное устранение любого риска с RPN > 100 или тяжестью S ≥ 9.',
      'Зафиксируйте целевые остаточные баллы RPN после внедрения защитных мер.',
    ],
  },
  {
    id: 'static-program-slicing-defect-isolation',
    name: 'StaticProgramSlicingDefectIsolationSkill',
    displayName: 'Static Program Slicing & Defect Isolation',
    categoryId: 'analysis',
    description: 'Isolates the minimal subset of source code instructions that directly or indirectly influence a failing variable or assertion.',
    tags: ['analysis', 'program-slicing', 'debugging', 'data-flow', 'code-analysis'],
    semanticType: 'process_directive',
    sectionName: 'Static Backward/Forward Program Slicing Protocol',
    ruSectionName: 'Статический слайсинг программ для локализации дефектов',
    instructionsEn: [
      'Define the slicing criterion: a tuple of (instruction_line, variable_name) corresponding to the observed defect.',
      'Execute backward static slicing: trace control-flow and data-dependence graphs to extract all statements that affect that criterion.',
      'Prune all orthogonal, non-interfering code paths to create a minimal, standalone reproduction slice.',
      'Analyze the slice for null-pointer dereferences, uninitialized state, and variable shadowing.',
    ],
    instructionsRu: [
      'Задайте критерий среза: пару (номер_строки, имя_переменной) в точке проявления ошибки.',
      'Выполните обратный статический слайсинг: проследите граф зависимостей по данным и управлению для выделения влияющих инструкций.',
      'Отсеките независимые участки кода, сформировав минимальный изолированный срез для локализации бага.',
      'Проверьте срез на разыменование null, неинициализированные переменные и конфликты областей видимости.',
    ],
  },
  {
    id: 'dynamic-taint-source-to-sink-tracking',
    name: 'DynamicTaintSourceToSinkTrackingSkill',
    displayName: 'Dynamic Taint Analysis & Source-to-Sink Tracking',
    categoryId: 'analysis',
    description: 'Tracks untrusted external inputs from ingestion sources across transformations to sensitive execution sinks.',
    tags: ['analysis', 'taint-analysis', 'security', 'data-flow', 'vulnerabilities'],
    semanticType: 'process_directive',
    sectionName: 'Source-to-Sink Dynamic Taint Tracking',
    ruSectionName: 'Анализ распространения заражения (Taint Analysis: Source-to-Sink)',
    instructionsEn: [
      'Tag all untrusted external input boundaries as Taint Sources (HTTP headers, query params, webhook payloads, file uploads).',
      'Trace taint propagation through internal variables, object mutations, string concatenations, and intermediate buffers.',
      'Identify critical Taint Sinks: SQL execution engines, OS shell commands, DOM innerHTML sinks, and eval primitives.',
      'Verify that a validated, cryptographically sound Sanitizer or Escaping primitive intervenes between source and sink.',
    ],
    instructionsRu: [
      'Пометьте все внешние точки ввода как источники заражения (HTTP-заголовки, параметры URL, вебхуки, загружаемые файлы).',
      'Отслеживайте путь распространения данных через трансформации, конкатенации строк и буферы памяти.',
      'Выделите критические точки назначения (Sinks): SQL-движки, вызовы shell-команд, вставки в DOM, парсеры.',
      'Убедитесь, что между источником и приемником обязательно стоит проверенная функция валидации и санитизации.',
    ],
  },
  {
    id: 'littles-law-queueing-bottleneck-audit',
    name: 'LittlesLawQueueingBottleneckAuditSkill',
    displayName: 'Little\'s Law Queueing & Capacity Saturation Audit',
    categoryId: 'analysis',
    description: 'Applies Little\'s Law (L = lambda x W) to diagnose concurrency bottlenecks, queue buildup, and thread pool starvation.',
    tags: ['analysis', 'littles-law', 'queueing-theory', 'capacity-planning', 'performance'],
    semanticType: 'process_directive',
    sectionName: 'Little\'s Law Queueing & Concurrency Audit',
    ruSectionName: 'Закон Литтла и аудит насыщения очередей (L = lambda * W)',
    instructionsEn: [
      'Apply Little\'s Law: Average concurrent requests in system (L) equals Arrival rate (lambda) multiplied by Average response time (W).',
      'Calculate theoretical queue buildup when arrival rate exceeds processing service rate (rho = lambda / mu >= 1.0).',
      'Audit thread pool and connection pool dimensions to prevent cascading saturation deadlocks.',
      'Determine optimal concurrency limits that prevent tail latency degradation under burst traffic.',
    ],
    instructionsRu: [
      'Применяйте закон Литтла: число одновременных запросов в системе (L) = скорость поступления (lambda) * время обработки (W).',
      'Рассчитывайте лавинообразный рост очереди при приближении коэффициента загрузки к единице (rho >= 1.0).',
      'Аудируйте размеры пулов потоков и коннектов к БД, предотвращая каскадные блокировки.',
      'Определяйте оптимальные лимиты конкурентности (concurrency limits) для удержания хвостовой задержки p99.',
    ],
  },
  {
    id: 'differential-flamegraph-profiling',
    name: 'DifferentialFlamegraphProfilingSkill',
    displayName: 'Differential Flamegraph CPU/Memory Profiling',
    categoryId: 'analysis',
    description: 'Compares baseline vs regressed production profiles using differential flamegraphs (red for regression, blue for improvement).',
    tags: ['analysis', 'flamegraph', 'profiling', 'performance', 'regression-testing'],
    semanticType: 'process_directive',
    sectionName: 'Differential Flamegraph Profiling Architecture',
    ruSectionName: 'Дифференциальное профилирование флеймграфов (CPU / Memory)',
    instructionsEn: [
      'Capture stack traces across identical traffic conditions for both baseline version and candidate release.',
      'Generate differential flamegraphs highlighting regressed frames in red and optimized frames in blue.',
      'Isolate specific callstack frames exhibiting disproportionate self-time or memory allocation expansions.',
      'Correlate regressions directly with recent git commit diffs to pinpoint problematic algorithmic changes.',
    ],
    instructionsRu: [
      'Соберите профили стеков вызовов под одинаковой нагрузкой для базовой версии и кандидатного релиза.',
      'Постройте дифференциальный флеймграф с подсветкой регрессий красным цветом, а оптимизаций — синим.',
      'Локализуйте конкретные функции в стеке вызовов с максимальным ростом собственного времени выполнения (self-time).',
      'Сопоставьте найденные горячие точки с недавними коммитами для точечного рефакторинга.',
    ],
  },
  {
    id: 'sobol-sensitivity-variance-decomposition',
    name: 'SobolSensitivityVarianceDecompositionSkill',
    displayName: 'Sobol Sensitivity & Variance Decomposition',
    categoryId: 'analysis',
    description: 'Decomposes total system variance into main effects and higher-order interaction effects using variance-based Sobol indices.',
    tags: ['analysis', 'sobol-indices', 'sensitivity-analysis', 'variance', 'modeling'],
    semanticType: 'process_directive',
    sectionName: 'Sobol Global Sensitivity Analysis Protocol',
    ruSectionName: 'Глобальный анализ чувствительности Соболя (декомпозиция дисперсии)',
    instructionsEn: [
      'Decompose the variance of the model outcome into contributions from individual input parameters and parameter interactions.',
      'Compute first-order Sobol indices (S_i) measuring main effect of each parameter alone.',
      'Compute total-order Sobol indices (S_Ti) measuring main effect plus all higher-order cross-parameter interactions.',
      'Rank input parameters to identify which variables dictate 90%+ of outcome volatility.',
    ],
    instructionsRu: [
      'Разложите общую дисперсию исхода модели на доли, приходящиеся на отдельные входные параметры и их взаимодействия.',
      'Рассчитайте индексы Соболя первого порядка (S_i) для оценки изолированного влияния каждого фактора.',
      'Рассчитайте полные индексы Соболя (S_Ti), учитывающие кросс-факторные нелинейные связки.',
      'Ранжируйте переменные, выделив критические факторы, определяющие свыше 90% волатильности системы.',
    ],
  },
  {
    id: 'boundary-value-equivalence-partitioning',
    name: 'BoundaryValueEquivalencePartitioningSkill',
    displayName: 'Boundary Value & Equivalence Class Partitioning',
    categoryId: 'analysis',
    description: 'Partitions input domains into valid/invalid equivalence classes and tests exact mathematical boundary edges (min-1, min, max, max+1).',
    tags: ['analysis', 'boundary-value', 'qa', 'testing', 'equivalence-partitioning'],
    semanticType: 'process_directive',
    sectionName: 'Boundary Value & Equivalence Partitioning Protocol',
    ruSectionName: 'Граничные значения и классы эквивалентности (Boundary Value Analysis)',
    instructionsEn: [
      'Divide the input domain into distinct equivalence classes where the system should behave identically.',
      'Test exact boundary edges: Minimum - 1, Minimum, Nominal value, Maximum, Maximum + 1.',
      'Test data type boundaries: 0, -1, 1, INT_MAX, INT_MIN, empty string, single-char, max-length string, and null/undefined.',
      'Verify that invalid classes trigger clean, structured error responses without unhandled 500 exceptions.',
    ],
    instructionsRu: [
      'Разбейте область входных данных на классы эквивалентности, в рамках которых система ведет себя одинаково.',
      'Протестируйте точные границы диапазонов: Мин - 1, Мин, Номинал, Макс, Макс + 1.',
      'Проверьте экстремумы типов данных: 0, -1, INT_MAX, пустая строка, спецсимволы, максимальная длина, null/undefined.',
      'Убедитесь, что недопустимые классы вызывают контролируемые ошибки 4xx без падений сервера с кодом 500.',
    ],
  },
  {
    id: 'code-churn-vs-defect-density-correlation',
    name: 'CodeChurnVsDefectDensityCorrelationSkill',
    displayName: 'Code Churn vs Defect Density Correlation Audit',
    categoryId: 'analysis',
    description: 'Correlates git commit churn (lines added/modified/deleted) with bug incident clusters to pinpoint fragile code modules.',
    tags: ['analysis', 'code-churn', 'defect-density', 'git-metrics', 'technical-debt'],
    semanticType: 'process_directive',
    sectionName: 'Code Churn & Hotspot Defect Correlation Protocol',
    ruSectionName: 'Корреляция частоты изменений кода (Churn) и плотности дефектов',
    instructionsEn: [
      'Extract git history metrics: calculate churn rate (lines modified per week) and revision count per file.',
      'Overlay historical defect tickets and bug regressions onto the file topology.',
      'Isolate high-churn, high-defect "hotspots" exhibiting fragile technical debt and lack of test coverage.',
      'Prioritize these fragile hotspot files for targeted refactoring and automated contract testing.',
    ],
    instructionsRu: [
      'Соберите метрики git-репозитория: частота правок строк в неделю и число ревизий по каждому файлу.',
      'Наложите историю инцидентов и баг-репортов на топологию исходного кода проекта.',
      'Выделите горячие точки (hotspots) с высокой частотой правок и высокой концентрацией ошибок.',
      'Назначьте эти нестабильные модули первоочередными кандидатами на декомпозицию и покрытие тестами.',
    ],
  },
  {
    id: 'telemetry-cardinality-explosion-audit',
    name: 'TelemetryCardinalityExplosionAuditSkill',
    displayName: 'Metrics High-Cardinality Explosion Audit',
    categoryId: 'analysis',
    description: 'Audits Prometheus/OpenTelemetry metric labels to prevent cardinality explosions and memory exhaustion in TSDBs.',
    tags: ['analysis', 'cardinality', 'telemetry', 'prometheus', 'observability'],
    semanticType: 'constraints',
    sectionName: 'Telemetry High-Cardinality Prevention Protocol',
    ruSectionName: 'Аудит взрыва кардинальности метрик (Prometheus / TSDB)',
    instructionsEn: [
      'Audit all metric label keys: strictly forbid unbounded dynamic identifiers (UUIDs, user IDs, raw timestamps, full URLs with query params).',
      'Calculate theoretical label permutation count: multiply unique values across all label keys per metric.',
      'Enforce label whitelists: restrict labels to low-cardinality enumerations (status_code, method, region, service_name).',
      'Transition high-cardinality debugging attributes into OpenTelemetry trace spans or structured logs rather than metric dimensions.',
    ],
    instructionsRu: [
      'Проверьте ключи меток метрик: запретите использование UUID, ID пользователей, полных URL и таймстемпов в лейблах.',
      'Рассчитайте число перестановок: произведение уникальных значений всех лейблов не должно превышать допустимый лимит TSDB.',
      'Ограничивайте метки перечислимыми константами: код ответа (200, 500), HTTP-метод, регион, имя микросервиса.',
      'Переносите высококардинальные атрибуты в распределенные спаны трейсинга или логи, разгружая базу метрик.',
    ],
  },
  {
    id: 'heap-dump-memory-leak-retainer-tree',
    name: 'HeapDumpMemoryLeakRetainerTreeSkill',
    displayName: 'Heap Dump Memory Leak & Retainer Tree Analysis',
    categoryId: 'analysis',
    description: 'Analyzes V8/JVM heap dumps, identifies shallow vs retained heap size anomalies, and traces dominator trees to roots.',
    tags: ['analysis', 'memory-leak', 'heap-dump', 'profiling', 'garbage-collection'],
    semanticType: 'process_directive',
    sectionName: 'Heap Dump Retainer Tree Analysis Architecture',
    ruSectionName: 'Анализ утечек памяти и дерева удержания объектов (Heap Dump)',
    instructionsEn: [
      'Differentiate Shallow Size (memory allocated to object itself) from Retained Size (memory freed if object were garbage collected).',
      'Trace Dominator Tree upwards to identify which GC Root (closure, global event listener, uncleaned cache) retains the leaking instances.',
      'Detect common leak patterns: forgotten RxJS/EventEmitter subscriptions, detached DOM nodes, and unbounded Map caches.',
      'Recommend precise teardown lifecycle hooks (`dispose()`, `unsubscribe()`, WeakMap references) to resolve retention.',
    ],
    instructionsRu: [
      'Различайте собственный размер объекта (Shallow Size) и удерживаемый объем памяти (Retained Size).',
      'Проследите дерево доминаторов вверх до корня сборщика мусора (GC Root), удерживающего неиспользуемые объекты.',
      'Выявляйте типичные утечки: забытые подписки на события, отсоединенные узлы DOM, неочищаемые глобальные Map.',
      'Предлагайте точные хуки очистки жизненного цикла (`onDestroy`, `unsubscribe`, использование WeakMap/WeakRef).',
    ],
  },
  {
    id: 'sql-execution-plan-cost-buffer-audit',
    name: 'SqlExecutionPlanCostBufferAuditSkill',
    displayName: 'SQL Execution Plan & Buffer Cache Hit Ratio Audit',
    categoryId: 'analysis',
    description: 'Deeply analyzes `EXPLAIN (ANALYZE, BUFFERS)` plans: sequential scans, nested loop spills, and buffer cache misses.',
    tags: ['analysis', 'sql', 'explain-analyze', 'database', 'query-optimization'],
    semanticType: 'process_directive',
    sectionName: 'SQL EXPLAIN ANALYZE Buffer Audit Architecture',
    ruSectionName: 'Аудит планов выполнения SQL (EXPLAIN ANALYZE BUFFERS)',
    instructionsEn: [
      'Examine execution plans for catastrophic Sequential Scans on tables exceeding 10,000 rows.',
      'Compare Estimated Rows vs Actual Rows: discrepancy >10x indicates stale table statistics requiring `ANALYZE`.',
      'Analyze Shared Hit vs Read buffers: identify queries performing excessive disk reads instead of in-memory buffer hits.',
      'Diagnose suboptimal joins: suggest covering indexes (INCLUDE clause) to convert Seq Scans into Index Only Scans.',
    ],
    instructionsRu: [
      'Ищите последовательные сканирования (Seq Scan) на таблицах размером более 10 000 строк.',
      'Сравнивайте расчетное и реальное число строк (Estimated vs Actual): расхождение >10 раз говорит об устаревшей статистике таблицы.',
      'Анализируйте буферы (Shared Hit vs Read): выявляйте запросы, считывающие данные с диска вместо буферного кэша RAM.',
      'Оптимизируйте соединения: проектируйте покрывающие индексы (INCLUDE) для перехода к Index Only Scan.',
    ],
  },
  {
    id: 'distributed-deadlock-wait-for-graph',
    name: 'DistributedDeadlockWaitForGraphSkill',
    displayName: 'Distributed Deadlock & Wait-For Graph Cycle Detection',
    categoryId: 'analysis',
    description: 'Models lock contention across distributed services as a directed Wait-For Graph (WFG) and detects cyclic deadlock dependencies.',
    tags: ['analysis', 'deadlock', 'concurrency', 'distributed-systems', 'locks'],
    semanticType: 'process_directive',
    sectionName: 'Wait-For Graph Deadlock Detection Protocol',
    ruSectionName: 'Обнаружение распределенных взаимных блокировок (Wait-For Graph)',
    instructionsEn: [
      'Construct a directed Wait-For Graph (WFG) where nodes represent active transactions/threads and directed edges represent lock requests.',
      'Execute Tarjan\'s or Johnson\'s cycle detection algorithm to identify circular lock dependencies: T1 -> T2 -> ... -> T1.',
      'Enforce global resource ordering conventions: mandate acquiring distributed locks in strictly deterministic alphanumeric order.',
      'Implement lock lease timeouts and abort-and-retry policies for the transaction contributing the least work.',
    ],
    instructionsRu: [
      'Постройте граф ожидания (WFG): узлы — активные транзакции/потоки, ребра — ожидаемые блокировки ресурсов.',
      'Примените алгоритм поиска циклов для обнаружения кольцевых блокировок (T1 ждет T2, T2 ждет T1).',
      'Внедрите строгое глобальное упорядочивание захвата блокировок в алфавитном порядке их ключей.',
      'Настройте тайм-ауты удержания блокировок и алгоритм прерывания транзакции с наименьшим выполненным объемом работ.',
    ],
  },
  {
    id: 'tcp-network-mtu-window-loss-audit',
    name: 'TcpNetworkMtuWindowLossAuditSkill',
    displayName: 'TCP Window, MTU & Packet Loss Degradation Audit',
    categoryId: 'analysis',
    description: 'Diagnoses network transport throughput bottlenecks: TCP congestion window collapse, MTU black holes, and packet loss.',
    tags: ['analysis', 'networking', 'tcp', 'mtu', 'throughput', 'latency'],
    semanticType: 'process_directive',
    sectionName: 'TCP Transport & Network Degradation Protocol',
    ruSectionName: 'Аудит пропускной способности TCP, MTU и потери пакетов',
    instructionsEn: [
      'Calculate Bandwidth-Delay Product (BDP = Bandwidth x RTT) to determine minimum required TCP window buffer size.',
      'Diagnose Path MTU Discovery (PMTUD) black holes caused by intermediate firewalls dropping ICMP "Fragmentation Needed" packets.',
      'Audit TCP retransmission rates: packet loss >1% triggers severe cubic/reno congestion window collapse.',
      'Recommend BBR congestion control algorithm and TCP window scaling flags for high-BDP cross-region pipes.',
    ],
    instructionsRu: [
      'Рассчитайте произведение пропускной способности на задержку (BDP) для настройки буферов окна TCP.',
      'Диагностируйте «черные дыры» MTU при блокировке сетевыми экранами пакетов ICMP «Fragmentation Needed».',
      'Анализируйте долю повторных передач (retransmits): потеря пакетов >1% обрушивает окно перегрузки TCP.',
      'Рекомендуйте алгоритм контроля перегрузки BBR для высокоскоростных межрегиональных каналов связи.',
    ],
  },
  {
    id: 'cache-hit-ratio-eviction-curve-analysis',
    name: 'CacheHitRatioEvictionCurveAnalysisSkill',
    displayName: 'Cache Hit Ratio & Eviction Curve Analysis',
    categoryId: 'analysis',
    description: 'Models cache capacity vs hit ratio curves (LRU/LFU/ARC), identifying working set knee points and optimal TTL horizons.',
    tags: ['analysis', 'caching', 'lru', 'hit-ratio', 'performance'],
    semanticType: 'process_directive',
    sectionName: 'Cache Working Set & Eviction Curve Protocol',
    ruSectionName: 'Анализ кривой попаданий кэша (Hit Ratio) и вытеснения ключей',
    instructionsEn: [
      'Plot cache size against hit ratio percentage to isolate the working set "knee point" of diminishing returns.',
      'Compare eviction algorithm suitability: LRU (recency) vs LFU (frequency) vs Adaptive Replacement Cache (ARC).',
      'Analyze TTL distributions: eliminate premature evictions of hot data caused by under-provisioned memory bounds.',
      'Detect cache churn where high-frequency writes evict stable read-heavy items.',
    ],
    instructionsRu: [
      'Постройте график зависимости процента попаданий (Hit Ratio) от объема памяти кэша для нахождения точки перегиба.',
      'Сравните алгоритмы вытеснения: LRU (свежесть) против LFU (частота) и адаптивного ARC.',
      'Проверьте распределение TTL: исключите преждевременное вытеснение горячих ключей из-за дефицита RAM.',
      'Выявляйте паразитный шум кэша (cache churn), когда частые однократные записи вымывают стабильные данные.',
    ],
  },
  {
    id: 'thread-contention-lock-profiling',
    name: 'ThreadContentionLockProfilingSkill',
    displayName: 'Thread Contention & Lock Profiling Analysis',
    categoryId: 'analysis',
    description: 'Profiles mutex/spinlock wait times, monitor inflation, and CPU core under-utilization caused by coarse-grained synchronized locks.',
    tags: ['analysis', 'thread-contention', 'concurrency', 'multithreading', 'locks'],
    semanticType: 'process_directive',
    sectionName: 'Thread Contention & Lock Profiling Architecture',
    ruSectionName: 'Профилирование конкуренции потоков и блокировок (Lock Contention)',
    instructionsEn: [
      'Measure percentage of thread time spent in BLOCKED or WAITING state versus active RUNNABLE state.',
      'Identify coarse-grained critical sections where multiple threads serialize on a single shared mutex.',
      'Recommend lock-striping, read-write locks (`SharedMutex`), or lock-free atomic primitives (`AtomicLong`, CAS).',
      'Verify that thread pool sizing matches hardware parallelism: CPU-bound (N_threads = N_cores + 1) vs I/O-bound.',
    ],
    instructionsRu: [
      'Измерьте долю времени потоков в состоянии ожидания (BLOCKED / WAITING) по сравнению с активным выполнением (RUNNABLE).',
      'Выявите слишком крупные критические секции, где потоки выстраиваются в очередь на одном мьютексе.',
      'Предложите разделение блокировок (lock striping), чтение-запись (ReadWriteLock) или lock-free атомики (CAS).',
      'Проверьте соответствие пула потоков типу нагрузки: CPU-bound (число ядер + 1) против I/O-bound.',
    ],
  },
  {
    id: 'blast-radius-topological-graph-traversal',
    name: 'BlastRadiusTopologicalGraphTraversalSkill',
    displayName: 'Topological Blast Radius & Failure Propagation Traversal',
    categoryId: 'analysis',
    description: 'Traverses directed service dependency graphs to compute maximum blast radius, downstream cascading risks, and critical failure nodes.',
    tags: ['analysis', 'blast-radius', 'dependency-graph', 'cascading-failure', 'topology'],
    semanticType: 'process_directive',
    sectionName: 'Topological Blast Radius Traversal Protocol',
    ruSectionName: 'Топологический расчет радиуса поражения (Blast Radius Analysis)',
    instructionsEn: [
      'Construct a directed acyclic graph (DAG) of all synchronous RPC, database, and message queue dependencies.',
      'Simulate failure of a single upstream node: traverse the dependency graph to compute all reachable downstream impacted services.',
      'Quantify the Total Blast Radius: number of affected end-user endpoints, degraded SLAs, and transactional revenue at risk.',
      'Locate missing bulkheads, circuit breakers, and fallback caches that fail to arrest propagation.',
    ],
    instructionsRu: [
      'Постройте направленный граф синхронных RPC-вызовов, баз данных и очередей сообщений.',
      'Смоделируйте отказ отдельного узла: обойдите граф зависимостей для выявления всех каскадно затронутых сервисов.',
      'Количественно оцените радиус поражения: число недоступных эндпоинтов, падение SLA и финансовые потери.',
      'Укажите места отсутствия изоляционных переборок (bulkheads) и предохранителей (circuit breakers).',
    ],
  },
  {
    id: 'cognitive-walkthrough-usability-inspection',
    name: 'CognitiveWalkthroughUsabilityInspectionSkill',
    displayName: 'Wharton Cognitive Walkthrough Usability Inspection',
    categoryId: 'analysis',
    description: 'Evaluates task workflows step-by-step through 4 cognitive questions: user intent, action visibility, action association, and feedback.',
    tags: ['analysis', 'cognitive-walkthrough', 'ux', 'usability', 'hci'],
    semanticType: 'process_directive',
    sectionName: 'Cognitive Walkthrough Usability Inspection Protocol',
    ruSectionName: 'Когнитивное пошаговое прохождение сценариев (Cognitive Walkthrough)',
    instructionsEn: [
      'Deconstruct the user journey into discrete mechanical micro-actions required to achieve the goal.',
      'Answer 4 questions for every action: 1) Will the user try to achieve the right effect? 2) Is the action visible? 3) Will the user recognize the action achieves the desired effect? 4) Does the user get clear feedback?',
      'Document every friction point where user mental model diverges from system designer assumptions.',
      'Redesign problematic steps to provide immediate visual signifiers and feedback confirmations.',
    ],
    instructionsRu: [
      'Разложите пользовательский сценарий на последовательность конкретных действий для достижения цели.',
      'Ответьте на 4 вопроса для каждого шага: 1) Понятно ли пользователю, что нужно делать? 2) Виден ли нужный элемент? 3) Свяжет ли он этот элемент со своей целью? 4) Получит ли понятную обратную связь?',
      'Зафиксируйте точки трения, где ментальная модель пользователя расходится с логикой интерфейса.',
      'Скорректируйте интерфейс, добавив явные визуальные подсказки и подтверждения статуса операции.',
    ],
  },
];

// 38 skills for agentic (current 32 -> 70)
const agenticSkills = [
  {
    id: 'multi-agent-blackboard-pattern',
    name: 'MultiAgentBlackboardPatternSkill',
    displayName: 'Multi-Agent Blackboard Shared Memory Pattern',
    categoryId: 'agentic',
    description: 'Coordinates specialized sub-agents via a central shared blackboard workspace with event-driven change notifications.',
    tags: ['agentic', 'blackboard-pattern', 'multi-agent', 'orchestration', 'shared-memory'],
    semanticType: 'structural_directive',
    sectionName: 'Multi-Agent Blackboard Architecture',
    ruSectionName: 'Мультиагентный паттерн общей доски (Blackboard Pattern)',
    instructionsEn: [
      'Establish a centralized, structured Blackboard state repository accessible to all specialized worker agents.',
      'Allow domain-specialist agents (e.g. Coder, Tester, Security Auditor) to inspect current blackboard state and publish incremental solutions.',
      'Implement an arbitrator controller monitoring state changes and dynamically activating the most relevant specialist.',
      'Maintain an immutable append-only event log recording which agent produced each hypothesis or modification.',
    ],
    instructionsRu: [
      'Создайте централизованное структурированное хранилище состояния (доску), доступное специализированным агентам.',
      'Разрешите профильным агентам (программист, тестировщик, аудитор) читать состояние доски и публиковать решения.',
      'Внедрите контроллер-арбитр, анализирующий обновления и активирующий наиболее подходящего агента.',
      'Ведите неизменяемый журнал событий с фиксацией авторства каждой гипотезы или правки.',
    ],
  },
  {
    id: 'self-healing-tool-output-repair',
    name: 'SelfHealingToolOutputRepairSkill',
    displayName: 'Tool Output Schema Validation & Self-Healing Repair',
    categoryId: 'agentic',
    description: 'Validates tool outputs against Zod/JSON schemas; on validation failure, injects targeted diagnostic hints for self-repair.',
    tags: ['agentic', 'self-healing', 'schema-validation', 'tool-use', 'error-recovery'],
    semanticType: 'process_directive',
    sectionName: 'Tool Output Validation & Self-Healing Protocol',
    ruSectionName: 'Валидация вывода инструментов и самовосстановление (Self-Healing)',
    instructionsEn: [
      'Parse and validate raw tool execution responses against strict schema definitions (e.g. Zod or JSON Schema).',
      'When schema validation fails, capture the exact path and error message (e.g. "missing property `status` at root").',
      'Feed the schema error directly back into the agent context with a targeted repair instruction rather than aborting execution.',
      'Limit self-repair retries to a maximum of 3 attempts before escalating to fallback degradation.',
    ],
    instructionsRu: [
      'Валидируйте сырые ответы вызванных инструментов по строгим схемам (Zod или JSON Schema).',
      'При ошибке схемы фиксируйте точный путь и причину (например, «отсутствует обязательное поле status»).',
      'Передавайте текст ошибки обратно в контекст агента с инструкцией исправления формата вместо аварийной остановки.',
      'Ограничивайте число попыток самовосстановления тремя итерациями перед переходом к запасному сценарию.',
    ],
  },
  {
    id: 'dynamic-token-budget-governor',
    name: 'DynamicTokenBudgetGovernorSkill',
    displayName: 'Dynamic Token Budget Governor & Cost Guard',
    categoryId: 'agentic',
    description: 'Tracks accumulated prompt and completion tokens across agent turns, enforcing hard financial limits and context pruning.',
    tags: ['agentic', 'token-budget', 'cost-control', 'finops', 'context-pruning'],
    semanticType: 'guardrail_directive',
    sectionName: 'Dynamic Token Budget & Cost Governor',
    ruSectionName: 'Динамический регулятор токенов и контроль затрат агента',
    instructionsEn: [
      'Maintain running totals of input tokens, output tokens, and calculated dollar expenditure across the complete trajectory.',
      'Enforce soft budget threshold (70%): automatically compress long conversation turns and summarize intermediate tool payloads.',
      'Enforce hard budget threshold (100%): gracefully finalize the current deliverable and return the best partial synthesis without spawning new tool calls.',
    ],
    instructionsRu: [
      'Ведите непрерывный подсчет потраченных токенов на вход и выход с калькуляцией стоимости в реальном времени.',
      'При достижении мягкого лимита (70%): автоматически сжимайте прошлые шаги и суммаризируйте ответы инструментов.',
      'При достижении жесткого лимита (100%): завершайте работу, выдавая наилучший синтез результатов без новых запросов к API.',
    ],
  },
  {
    id: 'human-in-the-loop-diff-approval',
    name: 'HumanInTheLoopDiffApprovalSkill',
    displayName: 'Human-in-the-Loop Explicit Diff Approval Gate',
    categoryId: 'agentic',
    description: 'Halts autonomous agent execution prior to high-stakes destructive mutations, generating a clean unified diff for human confirmation.',
    tags: ['agentic', 'human-in-the-loop', 'approval-gate', 'safety', 'diff'],
    semanticType: 'guardrail_directive',
    sectionName: 'Human-in-the-Loop Diff Approval Gate',
    ruSectionName: 'Шлюз подтверждения человеком с отображением дифа (Human-in-the-Loop)',
    instructionsEn: [
      'Identify critical state mutations: file deletions, database writes, external network calls, or production deployments.',
      'Suspend execution immediately prior to invoking the destructive mutation.',
      'Format a concise unified diff showing exact deletions (-) and additions (+), estimated financial cost, and blast radius.',
      'Resume execution only upon receiving explicit, authenticated human approval.',
    ],
    instructionsRu: [
      'Определяйте критические операции: удаление файлов, запись в прод-БД, внешние платежи или деплой.',
      'Приостанавливайте работу агента непосредственно перед выполнением необратимого действия.',
      'Формируйте наглядный diff с отображением удаляемых (-) и добавляемых (+) строк, стоимости и рисков.',
      'Возобновляйте выполнение только после получения явного подтверждения от авторизованного оператора.',
    ],
  },
  {
    id: 'hierarchical-task-network-htn-planner',
    name: 'HierarchicalTaskNetworkHtnPlannerSkill',
    displayName: 'Hierarchical Task Network (HTN) Recursive Decomposition',
    categoryId: 'agentic',
    description: 'Decomposes compound goals into progressively refined sub-tasks until primitive, tool-executable action nodes are reached.',
    tags: ['agentic', 'htn', 'planning', 'task-decomposition', 'orchestration'],
    semanticType: 'process_directive',
    sectionName: 'HTN Hierarchical Task Decomposition Protocol',
    ruSectionName: 'Иерархическая декомпозиция задач (HTN Planning)',
    instructionsEn: [
      'Represent the overarching objective as a Compound Root Task.',
      'Select applicable decomposition methods based on current world state preconditions to break compound tasks into sub-tasks.',
      'Recurse until every leaf node in the task tree is an executable Primitive Task bound to a specific tool API.',
      'Execute primitive tasks sequentially, updating world state preconditions before triggering subsequent branches.',
    ],
    instructionsRu: [
      'Представьте главную цель как составную задачу верхнего уровня.',
      'Подберите методы декомпозиции с учетом текущих условий среды, разбив задачу на подзадачи.',
      'Повторяйте декомпозицию до тех пор, пока все листовые узлы дерева не станут примитивными действиями инструментов.',
      'Выполняйте примитивные действия, обновляя состояние среды перед переходом к следующим веткам.',
    ],
  },
  {
    id: 'agentic-memory-consolidation-rag',
    name: 'AgenticMemoryConsolidationRagSkill',
    displayName: 'Episodic Memory Consolidation & Semantic Retrieval',
    categoryId: 'agentic',
    description: 'Consolidates short-term session interactions into long-term episodic memories via embeddings and semantic cosine similarity search.',
    tags: ['agentic', 'memory', 'rag', 'embeddings', 'long-term-memory'],
    semanticType: 'process_directive',
    sectionName: 'Episodic Memory Consolidation & RAG Architecture',
    ruSectionName: 'Консолидация эпизодической памяти и семантический поиск (RAG)',
    instructionsEn: [
      'Extract high-signal facts, user preferences, and operational lessons from completed session turns.',
      'Generate vector embeddings for extracted episodic memories and store in a persistent semantic vector store.',
      'Prior to answering novel queries, perform top-k cosine similarity search to retrieve relevant historical lessons.',
      'Inject retrieved episodic context into the agent prompt with relevance confidence scores.',
    ],
    instructionsRu: [
      'Извлекайте ключевые факты, предпочтения пользователя и уроки из завершенных диалоговых сессий.',
      'Генерируйте векторные эмбеддинги для сохраненных воспоминаний и записывайте их в векторную базу.',
      'Перед выполнением нового запроса делайте поиск k ближайших релевантных воспоминаний по косинусному сходству.',
      'Внедряйте извлеченный контекст в системный промпт с указанием степени уверенности.',
    ],
  },
  {
    id: 'idempotent-tool-call-caching',
    name: 'IdempotentToolCallCachingSkill',
    displayName: 'Idempotent Tool Call Caching & Deduplication',
    categoryId: 'agentic',
    description: 'Computes cryptographic hashes of tool names and arguments, serving identical read-only requests from an in-memory cache.',
    tags: ['agentic', 'idempotency', 'caching', 'tool-use', 'performance'],
    semanticType: 'process_directive',
    sectionName: 'Tool Call Deduplication & Idempotency Protocol',
    ruSectionName: 'Идемпотентное кэширование и дедупликация вызовов инструментов',
    instructionsEn: [
      'Compute SHA-256 digest hash of tool name and canonicalized JSON argument payload.',
      'For read-only idempotent tools (e.g. `read_file`, `web_search`), check the session cache prior to executing external network calls.',
      'Return cached result immediately on cache hit, saving token latency and downstream API costs.',
      'Invalidate cached entries whenever a state-mutating tool (e.g. `write_file`, `delete_file`) modifies the underlying entity.',
    ],
    instructionsRu: [
      'Вычисляйте SHA-256 хэш от имени инструмента и нормализованного JSON-пейлоада его аргументов.',
      'Для безопасных read-only инструментов проверяйте кэш перед отправкой повторного сетевого вызова.',
      'Мгновенно возвращайте результат из кэша при совпадении, экономя время и квоты API.',
      'Сбрасывайте кэш, как только мутирующий инструмент (`edit_file`, `create_file`) изменяет состояние системы.',
    ],
  },
  {
    id: 'plan-repair-dynamic-replanning',
    name: 'PlanRepairDynamicReplanningSkill',
    displayName: 'Dynamic Plan Repair & Runtime Replanning',
    categoryId: 'agentic',
    description: 'Monitors execution preconditions; when environment divergence occurs, repairs remaining plan steps without full restart.',
    tags: ['agentic', 'replanning', 'plan-repair', 'adaptability', 'resilience'],
    semanticType: 'process_directive',
    sectionName: 'Runtime Plan Repair & Replanning Protocol',
    ruSectionName: 'Динамическая починка плана и перепланирование на лету',
    instructionsEn: [
      'Verify that expected preconditions hold before dispatching each scheduled plan step.',
      'When an action fails or returns unexpected environmental state, immediately halt the linear plan sequence.',
      'Execute localized plan repair: retain completed valid milestones and rewrite only the broken and subsequent sub-steps.',
      'Verify that the repaired sub-plan still converges on the terminal goal before resuming execution.',
    ],
    instructionsRu: [
      'Проверяйте соблюдение предусловий перед запуском каждого очередного шага плана.',
      'При сбое действия или получении неожиданного состояния среды останавливайте линейное выполнение.',
      'Выполняйте локальный ремонт плана: сохраняйте уже пройденные шаги и переписывайте только сломавшуюся ветку.',
      'Убедитесь, что скорректированный план гарантированно ведет к исходной цели, и продолжайте работу.',
    ],
  },
  {
    id: 'async-parallel-subagent-fanout',
    name: 'AsyncParallelSubagentFanoutSkill',
    displayName: 'Asynchronous Sub-Agent Fan-Out & Map-Reduce Fan-In',
    categoryId: 'agentic',
    description: 'Dispatches multiple parallel sub-agents across decomposed sub-problems and reconciles their outputs via structured map-reduce.',
    tags: ['agentic', 'parallel-agents', 'fan-out', 'fan-in', 'map-reduce'],
    semanticType: 'structural_directive',
    sectionName: 'Sub-Agent Fan-Out & Aggregation Protocol',
    ruSectionName: 'Асинхронный запуск субагентов (Fan-Out) и сборка результатов (Fan-In)',
    instructionsEn: [
      'Identify independent sub-problems that can be solved concurrently without shared state dependencies.',
      'Spawn isolated sub-agent tasks with localized context envelopes and targeted prompt mandates (Fan-Out).',
      'Collect sub-agent results asynchronously using a completion barrier timeout.',
      'Execute a synthesis reducer step (Fan-In) resolving conflicts and integrating outputs into a unified master deliverable.',
    ],
    instructionsRu: [
      'Выделяйте независимые подзадачи, которые могут выполняться параллельно без общих блокировок.',
      'Запускайте изолированных субагентов с компактным контекстом под каждую подзадачу (Fan-Out).',
      'Ожидайте завершения работы всех субагентов с контролем общего тайм-аута.',
      'Выполняйте финальную сборку (Fan-In), устраняя противоречия и формируя целостный итоговый результат.',
    ],
  },
  {
    id: 'supervisor-critic-adversarial-gate',
    name: 'SupervisorCriticAdversarialGateSkill',
    displayName: 'Supervisor-Critic Adversarial Verification Gate',
    categoryId: 'agentic',
    description: 'Employs a dedicated Critic agent that aggressively stress-tests the Worker agent\'s output against security, edge-case, and SLA criteria.',
    tags: ['agentic', 'supervisor-critic', 'adversarial', 'verification', 'quality-gate'],
    semanticType: 'process_directive',
    sectionName: 'Supervisor-Critic Verification Architecture',
    ruSectionName: 'Архитектура «Исполнитель-Критик» (Supervisor-Critic Gate)',
    instructionsEn: [
      'Separate Worker generation from Critic verification into distinct agent roles with independent prompts.',
      'Empower the Critic agent with strict rejection criteria: security vulnerabilities, edge-case negligence, and non-compliance.',
      'Require the Worker agent to address all specific rejection points before deliverable publication.',
      'Limit adversarial critique loops to maximum 2 rounds to prevent endless pedantic debates.',
    ],
    instructionsRu: [
      'Разделяйте генерацию решения и его проверку между двумя разными агентами (Исполнитель и Критик).',
      'Наделяйте Критика правом вето по критериям безопасности, граничных случаев и соответствия ТЗ.',
      'Обязывайте Исполнителя устранить замечания Критика перед финальной публикацией результата.',
      'Ограничивайте цикл критики максимум двумя раундами во избежание бесконечных споров.',
    ],
  },
  {
    id: 'contract-based-pre-post-conditions',
    name: 'ContractBasedPrePostConditionsSkill',
    displayName: 'Design-by-Contract Tool Pre- and Post-Conditions',
    categoryId: 'agentic',
    description: 'Surrounds all agent tool calls with Meyer\'s Design-by-Contract assertions: verified preconditions before call, postconditions after.',
    tags: ['agentic', 'design-by-contract', 'preconditions', 'postconditions', 'formal-methods'],
    semanticType: 'constraints',
    sectionName: 'Design-by-Contract Tool Execution Protocol',
    ruSectionName: 'Контрактное выполнение инструментов (Design-by-Contract)',
    instructionsEn: [
      'Precondition Check: Verify environmental invariants (e.g. file exists, credentials valid) before dispatching the tool call.',
      'Abort immediately if preconditions fail, outputting a clear explanation of the missing prerequisite.',
      'Postcondition Check: Verify that the tool execution achieved its promised state change (e.g. file size > 0, HTTP status 200).',
      'Roll back or report defect if postconditions are violated despite a "success" exit code.',
    ],
    instructionsRu: [
      'Проверка предусловий: Убедитесь в готовности среды (файл существует, права доступа есть) до отправки запроса инструменту.',
      'Немедленно отменяйте вызов при несоблюдении предусловий с фиксацией отсутствующего требования.',
      'Проверка постусловий: Убедитесь, что инструмент реально перевел систему в целевое состояние (файл создан, статус 200).',
      'Инициируйте откат, если инструмент вернул код успеха, но постусловие фактически нарушено.',
    ],
  },
  {
    id: 'openinference-agent-tracing-spans',
    name: 'OpenInferenceAgentTracingSpansSkill',
    displayName: 'OpenInference Agent Telemetry & Span Tracing',
    categoryId: 'agentic',
    description: 'Structures agent workflows into standardized OpenInference spans: Agent, Chain, Tool, and LLM semantic telemetry conventions.',
    tags: ['agentic', 'openinference', 'telemetry', 'tracing', 'observability'],
    semanticType: 'structural_directive',
    sectionName: 'OpenInference Telemetry & Span Architecture',
    ruSectionName: 'Телеметрия агента по стандарту OpenInference (Spans & Traces)',
    instructionsEn: [
      'Emit structured span records adhering to OpenInference semantic conventions: SpanKind (AGENT, CHAIN, TOOL, LLM).',
      'Record input parameters, output payloads, token counts, and latency duration for every nested execution span.',
      'Propagate trace ID and parent span ID across all asynchronous sub-agent invocations.',
      'Record exception event logs with full stack traces whenever an execution span terminates abnormally.',
    ],
    instructionsRu: [
      'Формируйте записи спанов по стандартам OpenInference с указанием типа: AGENT, CHAIN, TOOL, LLM.',
      'Фиксируйте входные данные, результат, расход токенов и задержку для каждого вложенного вызова.',
      'Пробрасывайте сквозной Trace ID и Parent Span ID через все вызовы асинхронных субагентов.',
      'Логируйте события ошибок с полным контекстом при аварийном завершении любого спана.',
    ],
  },
  {
    id: 'goal-drift-semantic-anchor-guard',
    name: 'GoalDriftSemanticAnchorGuardSkill',
    displayName: 'Goal Drift & Semantic Alignment Anchor Guard',
    categoryId: 'agentic',
    description: 'Computes cosine semantic similarity between current execution steps and the initial user goal, aborting if drift exceeds threshold.',
    tags: ['agentic', 'goal-drift', 'alignment', 'guardrails', 'cosine-similarity'],
    semanticType: 'guardrail_directive',
    sectionName: 'Goal Drift Detection & Alignment Anchor Protocol',
    ruSectionName: 'Защита от смещения цели (Goal Drift) и семантический якорь',
    instructionsEn: [
      'Maintain an immutable representation of the primary user goal anchored at the top of working context.',
      'Evaluate current sub-task trajectory every 3 steps: verify that active operations directly contribute to the original mandate.',
      'Detect semantic drift: flag when the agent begins pursuing tangential rabbit holes or solving invented side-problems.',
      'Force an immediate course correction back to the primary objective if semantic alignment drops below 80%.',
    ],
    instructionsRu: [
      'Закрепляйте неизменяемый текст первоначальной цели пользователя в начале рабочего контекста.',
      'Каждые 3 шага сопоставляйте текущие действия с исходной задачей: ведут ли они к прямому результату.',
      'Выявляйте смещение фокуса: пресекайте увлечение агента второстепенными деталями и решением надуманных проблем.',
      'Принудительно возвращайте траекторию к главной цели при падении смысловой связи ниже 80%.',
    ],
  },
  {
    id: 'agentic-loop-stuck-circuit-breaker',
    name: 'AgenticLoopStuckCircuitBreakerSkill',
    displayName: 'Anti-Thrashing Action Loop Circuit Breaker',
    categoryId: 'agentic',
    description: 'Detects repetitive alternating tool sequences (e.g. edit -> test fail -> revert -> test fail) and trips a hard circuit breaker.',
    tags: ['agentic', 'anti-thrashing', 'circuit-breaker', 'loop-breaker', 'stability'],
    semanticType: 'guardrail_directive',
    sectionName: 'Anti-Thrashing Loop Circuit Breaker Protocol',
    ruSectionName: 'Размыкатель зацикливаний и метаний агента (Anti-Thrashing Breaker)',
    instructionsEn: [
      'Maintain a circular rolling window of the last 6 tool invocation signatures.',
      'Detect oscillating thrash cycles: alternating patterns such as Action A -> Action B -> Action A -> Action B.',
      'Trip the circuit breaker immediately upon identifying repetitive cyclical thrashing.',
      'Force a radical heuristic shift: summarize the impasse, formulate an orthogonal strategy, or request human clarification.',
    ],
    instructionsRu: [
      'Ведите скользящее окно последних 6 вызовов инструментов с их аргументами.',
      'Распознавайте осцилляции и метания: повторяющиеся цепочки вида Действие А -> Действие Б -> Действие А -> Действие Б.',
      'Размыкайте цепь (trip circuit) при первом обнаружении устойчивого циклического повторения.',
      'Принудительно меняйте подход: зафиксируйте тупик, выберите принципиально иную стратегию или запросите совет человека.',
    ],
  },
];

console.log('Appending Analysis skills...');
appendSkillsToCategory('analysis', analysisSkills);

console.log('Appending Agentic skills...');
appendSkillsToCategory('agentic', agenticSkills);
