const { appendSkillsToCategory } = require('./appendSkills.cjs');

// 17 more skills for reasoning to reach 70 (currently 53)
const reasoningSkillsPart2 = [
  {
    id: 'pareto-frontier-multi-objective-optimization',
    name: 'ParetoFrontierMultiObjectiveOptimizationSkill',
    displayName: 'Pareto Frontier Multi-Objective Optimization',
    categoryId: 'reasoning',
    description: 'Solves conflicting multi-criteria tradeoffs by plotting non-dominated Pareto frontiers where no metric improves without degrading another.',
    tags: ['reasoning', 'pareto-frontier', 'multi-objective', 'trade-offs', 'optimization'],
    semanticType: 'process_directive',
    sectionName: 'Pareto Frontier Multi-Objective Optimization',
    ruSectionName: 'Оптимизация границы Парето для многокритериальных задач',
    instructionsEn: [
      'Define the conflicting objective functions (e.g. latency vs consistency vs cost) explicitly.',
      'Plot candidate architectures along the multi-dimensional parameter space.',
      'Isolate the non-dominated Pareto frontier: discard all strictly dominated sub-optimal candidates.',
      'Guide stakeholder trade-off choices exclusively among verified points on the Pareto frontier.',
    ],
    instructionsRu: [
      'Явно определите конфликтующие целевые функции (задержка vs согласованность vs бюджет).',
      'Разместите альтернативные архитектурные варианты в многомерном пространстве критериев.',
      'Выделите множество Парето: отсейте все варианты, уступающие другим по всем показателям одновременно.',
      'Предлагайте выбор только между точками истинной границы Парето с понятной ценой каждого компромисса.',
    ],
  },
  {
    id: 'feynman-algorithm-breakdown',
    name: 'FeynmanAlgorithmBreakdownSkill',
    displayName: 'Feynman Problem-Solving Algorithm & Black-Box Dissection',
    categoryId: 'reasoning',
    description: 'Applies Feynman\'s approach: 1) Write down the problem, 2) Think very hard, 3) Write down the solution — grounded in total conceptual clarity.',
    tags: ['reasoning', 'feynman', 'clarity', 'problem-solving', 'first-principles'],
    semanticType: 'process_directive',
    sectionName: 'Feynman Conceptual Dissection Protocol',
    ruSectionName: 'Алгоритм решения задач Фейнмана (предельная ясность сути)',
    instructionsEn: [
      'State the precise problem in simple, jargon-free language that a bright 12-year-old would comprehend.',
      'Decompose the black box into mechanical sub-steps, identifying the exact sub-step where understanding breaks down.',
      'Construct a clean, physical or visual analogy representing the core mechanism without obfuscating mathematics.',
    ],
    instructionsRu: [
      'Сформулируйте суть проблемы простыми словами без академического и корпоративного жаргона.',
      'Декомпозируйте «черный ящик» на шаги, точно локализовав точку, где теряется ясность механизма.',
      'Создайте наглядную механическую или физическую аналогию, объясняющую работу системы без заумных абстракций.',
    ],
  },
  {
    id: 'sorites-paradox-boundary-hardening',
    name: 'SoritesParadoxBoundaryHardeningSkill',
    displayName: 'Sorites Paradox & Vagueness Boundary Hardening',
    categoryId: 'reasoning',
    description: 'Hardens fuzzy, continuous boundaries against Sorites paradoxes (heap of sand dilemma) via discrete mathematical thresholds.',
    tags: ['reasoning', 'sorites-paradox', 'boundaries', 'precision', 'thresholds'],
    semanticType: 'constraints',
    sectionName: 'Sorites Boundary Hardening Protocol',
    ruSectionName: 'Устранение парадокса кучи (Sorites Paradox) и фиксация порогов',
    instructionsEn: [
      'Detect vague continuum terms (e.g. "large payload", "active user", "stale cache") susceptible to boundary drift.',
      'Replace qualitative fuzziness with mathematically hard boundary predicates (e.g. `payload > 10_485_760 bytes`).',
      'Implement hysteresis bands around thresholds to prevent high-frequency state flapping.',
    ],
    instructionsRu: [
      'Выявляйте размытые качественные понятия («большой запрос», «активный юзер», «устаревший кэш»).',
      'Заменяйте нечеткие формулировки строгими числовыми предикатами (например, `payload > 10 МБ`).',
      'Внедряйте зоны гистерезиса вокруг порогов для предотвращения дребезга переключения состояний.',
    ],
  },
  {
    id: 'burden-of-proof-hitchens-razor',
    name: 'BurdenOfProofHitchensRazorSkill',
    displayName: 'Hitchens\'s Razor & Burden of Proof Protocol',
    categoryId: 'reasoning',
    description: 'Enforces: "What can be asserted without evidence can also be dismissed without evidence", placing proof burden on claimant.',
    tags: ['reasoning', 'hitchens-razor', 'burden-of-proof', 'epistemology', 'skepticism'],
    semanticType: 'constraints',
    sectionName: 'Burden of Proof & Hitchens\'s Razor Protocol',
    ruSectionName: 'Бритва Хитченса и распределение бремени доказательства',
    instructionsEn: [
      'Place the burden of proof strictly upon the entity asserting a claim, vulnerability, or feature necessity.',
      'Dismiss speculative claims lacking empirical traces or reproducible test benchmarks without wasting engineering cycles.',
      'Mandate that any security or performance assertion present executable reproduction scripts.',
    ],
    instructionsRu: [
      'Возлагайте бремя доказательства строго на сторону, заявляющую о наличии проблемы, угрозы или необходимости фичи.',
      'Безжалостно отклоняйте голословные гипотезы без воспроизводимых тестов или фактов, экономя время команды.',
      'Требуйте минимальный воспроизводимый скрипт (repro) для любого заявления о баге или деградации скорости.',
    ],
  },
  {
    id: 'hume-guillotine-is-ought-separator',
    name: 'HumeGuillotineIsOughtSeparatorSkill',
    displayName: 'Hume\'s Guillotine (Is-Ought Gap Separation)',
    categoryId: 'reasoning',
    description: 'Strictly separates empirical factual description ("what is") from prescriptive normative policies ("what ought to be").',
    tags: ['reasoning', 'hume-guillotine', 'is-ought', 'ethics', 'policy'],
    semanticType: 'process_directive',
    sectionName: 'Humean Fact/Normative Policy Separation',
    ruSectionName: 'Гильотина Юма: строгое разделение фактов и предписаний',
    instructionsEn: [
      'Strictly decouple factual empirical observations ("CPU is at 95%") from value judgments ("we must scale up").',
      'Explicitly surface the hidden normative business premise connecting observed facts to recommended actions.',
      'Verify that technical recommendations acknowledge underlying organizational value trade-offs.',
    ],
    instructionsRu: [
      'Четко разделяйте констатацию объективных фактов («CPU загружен на 95%») и ценностные предписания («надо масштабировать»).',
      'Вскрывайте скрытые нормативные предпосылки бизнеса, связывающие наблюдение с предлагаемым действием.',
      'Следите, чтобы технические предложения явно учитывали приоритеты и ограничения стоимости компании.',
    ],
  },
  {
    id: 'gricean-maxims-cooperative-principle',
    name: 'GriceanMaximsCooperativePrincipleSkill',
    displayName: 'Gricean Maxims of Conversational Cooperation',
    categoryId: 'reasoning',
    description: 'Governs communication via Paul Grice\'s 4 Maxims: Quantity (informative as required), Quality (truthful), Relation (relevant), Manner (clear).',
    tags: ['reasoning', 'gricean-maxims', 'linguistics', 'cooperation', 'communication'],
    semanticType: 'process_directive',
    sectionName: 'Gricean Conversational Maxims Architecture',
    ruSectionName: 'Максимы Грайса: правила кооперативного общения',
    instructionsEn: [
      'Maxim of Quantity: Provide exactly as much information as required for task execution; neither less nor more.',
      'Maxim of Quality: State only what has empirical backing; never assert falsehoods or unsubstantiated speculation.',
      'Maxim of Relation: Ensure every sentence directly contributes to resolving the active objective.',
      'Maxim of Manner: Avoid obscurity, ambiguity, and wordiness; maintain orderly and concise discourse.',
    ],
    instructionsRu: [
      'Максима количества: Давайте ровно столько информации, сколько нужно для решения задачи; ни больше, ни меньше.',
      'Максима качества: Утверждайте только то, что проверено; исключайте ложные и недоказанные догадки.',
      'Максима релевантности: Каждая мысль должна прямо служить решению поставленной задачи.',
      'Максима манеры: Избегайте двусмысленности, путаницы и многословия; излагайте упорядоченно и ясно.',
    ],
  },
  {
    id: 'moores-paradox-doxastic-coherence',
    name: 'MooresParadoxDoxasticCoherenceSkill',
    displayName: 'Moore\'s Paradox & Doxastic Coherence Guard',
    categoryId: 'reasoning',
    description: 'Eliminates absurd self-contradictory belief states of the form: "It is raining, but I do not believe it is raining".',
    tags: ['reasoning', 'moores-paradox', 'epistemic-logic', 'coherence', 'consistency'],
    semanticType: 'constraints',
    sectionName: 'Doxastic Consistency & Epistemic Coherence',
    ruSectionName: 'Парадокс Мура и проверка доксатической согласованности',
    instructionsEn: [
      'Scan generated outputs for cognitive dissonance where an assertion is made alongside an explicit denial of belief in it.',
      'Align recommendations with stated analytical conclusions: never output a diagnosis followed by an incompatible prescription.',
      'Enforce epistemic harmony across all emitted assertions and system state evaluations.',
    ],
    instructionsRu: [
      'Сканируйте текст на когнитивный диссонанс, когда факт утверждается, но одновременно ставится под сомнение вера в него.',
      'Синхронизируйте рекомендации с диагнозом: недопустимо выдать анализ сбоя и предложить несовместимое с ним лечение.',
      'Обеспечивайте логическую непротиворечивость между выводами и практическими шагами.',
    ],
  },
  {
    id: 'quine-web-of-belief-recalibration',
    name: 'QuineWebOfBeliefRecalibrationSkill',
    displayName: 'Quinean Web of Belief Structural Recalibration',
    categoryId: 'reasoning',
    description: 'Models knowledge as an interconnected web: adjusts peripheral empirical beliefs before disturbing core mathematical/logical axioms.',
    tags: ['reasoning', 'quine', 'web-of-belief', 'epistemology', 'holism'],
    semanticType: 'process_directive',
    sectionName: 'Quinean Web of Belief Adjustment Architecture',
    ruSectionName: 'Паутина убеждений Куайна: иерархическая рекалибровка',
    instructionsEn: [
      'When new recalcitrant evidence contradicts system models, first adjust peripheral observational nodes.',
      'Preserve the core logical and mathematical axioms of the system unless external evidence is overwhelmingly disruptive.',
      'Map the ripple effects across connected beliefs when a major architectural assumption is revised.',
    ],
    instructionsRu: [
      'При появлении противоречащих фактов в первую очередь корректируйте периферийные предположения.',
      'Оберегайте центральные аксиомы системы от хаотичных пересмотров, пока периферийные гипотезы жизнеспособны.',
      'Прослеживайте каскадные изменения в зависимых подсистемах при фундаментальном изменении архитектуры.',
    ],
  },
  {
    id: 'kahneman-system1-vs-system2-auditor',
    name: 'KahnemanSystem1VsSystem2AuditorSkill',
    displayName: 'System 1 Heuristic Override & System 2 Deliberation',
    categoryId: 'reasoning',
    description: 'Identifies impulsive System 1 associative pattern matching and triggers slow, deliberate System 2 logical recalculation.',
    tags: ['reasoning', 'kahneman', 'system1-system2', 'deliberation', 'cognitive-control'],
    semanticType: 'process_directive',
    sectionName: 'System 2 Deliberative Override Architecture',
    ruSectionName: 'Переопределение интуиции Системы 1 анализом Системы 2 (Канеман)',
    instructionsEn: [
      'Detect when an initial intuitive answer is triggered by superficial pattern recognition or lexical similarity.',
      'Engage explicit System 2 deliberation: write down intermediate computational steps, variables, and edge-case exceptions.',
      'Verify calculations step-by-step to prevent seductive intuitive traps (e.g. bat-and-ball problem).',
    ],
    instructionsRu: [
      'Распознавайте моменты, когда ответ формируется поверхностной ассоциативной интуицией (Система 1).',
      'Принудительно включайте медленное аналитическое рассуждение (Система 2) с записью промежуточных вычислений.',
      'Пошагово пересчитывайте результат, нейтрализуя обманчиво очевидные ментальные ловушки.',
    ],
  },
  {
    id: 'trilemma-munchhausen-epistemic-grounding',
    name: 'TrilemmaMunchhausenEpistemicGroundingSkill',
    displayName: 'Münchhausen Trilemma Epistemic Grounding',
    categoryId: 'reasoning',
    description: 'Navigates the foundational justification trilemma: circularity, infinite regress, or dogmatic axiomatic halting.',
    tags: ['reasoning', 'munchhausen-trilemma', 'foundationalism', 'epistemology', 'axioms'],
    semanticType: 'process_directive',
    sectionName: 'Münchhausen Trilemma Foundational Grounding',
    ruSectionName: 'Трилемма Мюнхгаузена: обоснование предельных оснований',
    instructionsEn: [
      'Recognize that every chain of reasons threatens infinite regress, vicious circularity, or arbitrary dogmatism.',
      'Declare explicit axiomatic foundational stopping points (e.g. hardware specs, physics limits, legal compliance).',
      'Clearly justify why the chosen stopping axioms represent pragmatically stable engineering ground.',
    ],
    instructionsRu: [
      'Осознавайте, что любая цепочка обоснований рискует уйти в бесконечный регресс, порочный круг или догматизм.',
      'Явно фиксируйте предельные прагматические аксиомы остановки анализа (спецификации железа, законы физики, нормы закона).',
      'Обосновывайте, почему выбранный фундамент является надежной базой для инженерного компромисса.',
    ],
  },
  {
    id: 'newcomb-paradox-decision-theory',
    name: 'NewcombParadoxDecisionTheorySkill',
    displayName: 'Causal vs Evidential Decision Theory Calibration',
    categoryId: 'reasoning',
    description: 'Distinguishes Causal Decision Theory (actions bring about states) from Evidential Decision Theory (actions provide news of states).',
    tags: ['reasoning', 'newcomb-paradox', 'decision-theory', 'cdt-edt', 'causality'],
    semanticType: 'process_directive',
    sectionName: 'Decision-Theoretic Alignment Architecture',
    ruSectionName: 'Каузальная vs эвиденциальная теория решений (Парадокс Ньюкома)',
    instructionsEn: [
      'Distinguish whether taking an action causally produces an outcome or merely serves as statistical evidence of an underlying state.',
      'Apply Causal Decision Theory (CDT) in engineering environments where physics and causal networks govern outcomes.',
      'Avoid superstitious correlation traps where teams perform rituals that correlate with past success without causal impact.',
    ],
    instructionsRu: [
      'Разграничивайте случаи, когда действие напрямую вызывает результат, и ситуации, где оно лишь коррелирует со скрытым фактором.',
      'Применяйте каузальную теорию решений в инженерных задачах, опираясь на физику и граф зависимостей.',
      'Искореняйте ритуалы «карго-культа», которые коррелировали с успешными релизами, но не имели причинной связи.',
    ],
  },
  {
    id: 'simpson-paradox-stratification-audit',
    name: 'SimpsonParadoxStratificationAuditSkill',
    displayName: 'Simpson\'s Paradox Demographic Stratification',
    categoryId: 'reasoning',
    description: 'Diagnoses Simpson\'s Paradox where a statistical trend present in sub-populations reverses or disappears when aggregated.',
    tags: ['reasoning', 'simpsons-paradox', 'statistics', 'stratification', 'confounding'],
    semanticType: 'process_directive',
    sectionName: 'Simpson\'s Paradox Stratification Protocol',
    ruSectionName: 'Выявление парадокса Симпсона через стратификацию данных',
    instructionsEn: [
      'Never rely exclusively on aggregated macro-metrics that pool disparate cohorts.',
      'Stratify data across confounding background variables (e.g. user tier, geography, hardware generation).',
      'Verify whether the observed causal effect holds consistently within every stratum before declaring global conclusions.',
    ],
    instructionsRu: [
      'Никогда не делайте выводов исключительно по агрегированным средним показателям.',
      'Стратифицируйте выборку по скрытым конфаундерам (тарифный план, география, тип устройства).',
      'Проверяйте, сохраняется ли направление эффекта внутри каждой отдельной подгруппы до подведения итогов.',
    ],
  },
  {
    id: 'berkson-paradox-selection-collider-filter',
    name: 'BerksonParadoxSelectionColliderFilterSkill',
    displayName: 'Berkson\'s Fallacy & Collider Selection Bias',
    categoryId: 'reasoning',
    description: 'Detects artificial negative correlations between independent traits caused by conditioning on a common collider/selection gate.',
    tags: ['reasoning', 'berksons-paradox', 'collider-bias', 'selection-bias', 'causality'],
    semanticType: 'process_directive',
    sectionName: 'Collider Conditioning & Selection Bias Filter',
    ruSectionName: 'Парадокс Берксона и фильтрация смещения отбора (Collider Bias)',
    instructionsEn: [
      'Identify whether the sampled dataset was conditioned on a common effect or selection gate (e.g. only reviewing merged PRs or admitted patients).',
      'Explain how the selection filter creates artificial negative correlations between actually independent variables.',
      'Re-examine the broader unconditioned population to evaluate the true causal relationship.',
    ],
    instructionsRu: [
      'Определяйте, не подверглась ли выборка предварительной фильтрации по общему признаку (только принятые PR или успешные транзакции).',
      'Показывайте, как порог отбора порождает ложную отрицательную корреляцию между независимыми факторами.',
      'Анализируйте исходную генеральную совокупность до фильтрации для поиска истинной причинности.',
    ],
  },
  {
    id: 'lotka-volterra-predator-prey-oscillation',
    name: 'LotkaVolterraPredatorPreyOscillationSkill',
    displayName: 'Predator-Prey Population Dynamics (Lotka-Volterra)',
    categoryId: 'reasoning',
    description: 'Models cyclical oscillations between competing system populations: requests vs workers, spammers vs anti-fraud classifiers.',
    tags: ['reasoning', 'lotka-volterra', 'predator-prey', 'oscillations', 'systems-thinking'],
    semanticType: 'structural_directive',
    sectionName: 'Predator-Prey Systemic Dynamics Protocol',
    ruSectionName: 'Моделирование динамики «хищник-жертва» (Лотка-Вольтерра)',
    instructionsEn: [
      'Model coupled adversarial populations: identify the "prey" (e.g. system throughput, attacker accounts) and "predator" (e.g. security rules, autoscaling workers).',
      'Formulate non-linear phase-plane equations tracking lag times between prey growth and predator response.',
      'Introduce damping mechanisms (e.g. rate limits, exponential backoff) to stabilize violent cyclic oscillation collapses.',
    ],
    instructionsRu: [
      'Моделируйте противоборствующие популяции в системе: нагрузка («жертва») и воркеры («хищник»), спамеры и спам-фильтры.',
      'Оценивайте фазовые запаздывания между всплеском нагрузки и реакцией масштабирования инфраструктуры.',
      'Внедряйте демпфирующие контуры (рейтлимиты, экспоненциальные паузы) для гашения колебательных штормов.',
    ],
  },
  {
    id: 'coase-theorem-transaction-cost-optima',
    name: 'CoaseTheoremTransactionCostOptimaSkill',
    displayName: 'Coase Theorem & Transaction Cost Architecture',
    categoryId: 'reasoning',
    description: 'Determines optimal boundaries between internal monoliths and distributed microservices by quantifying friction and transaction costs.',
    tags: ['reasoning', 'coase-theorem', 'transaction-costs', 'microservices', 'monolith'],
    semanticType: 'process_directive',
    sectionName: 'Coasean Transaction Cost System Boundary Protocol',
    ruSectionName: 'Теорема Коуза: транзакционные издержки и границы систем',
    instructionsEn: [
      'Calculate the total transaction costs of network boundaries: serialization, network latency, distributed tracing, and coordination overhead.',
      'Apply Coase\'s theorem: keep components within a single process/monolith when external interface coordination friction exceeds internal management costs.',
      'Carve out autonomous services only when interface boundaries are clean, stable, and exhibit near-zero coordination tax.',
    ],
    instructionsRu: [
      'Рассчитывайте суммарные транзакционные издержки межсервисных границ: сериализация, задержки сети, распределенные транзакции.',
      'Применяйте теорему Коуза: объединяйте компоненты в монолит, если издержки сетевого взаимодействия превышают выгоды разделения.',
      'Выносите микросервис наружу только при наличии четкого, стабильного API с околонулевыми издержками координации.',
    ],
  },
  {
    id: 'arrow-impossibility-voting-aggregation',
    name: 'ArrowImpossibilityVotingAggregationSkill',
    displayName: 'Arrow\'s Impossibility Consensus Aggregator',
    categoryId: 'reasoning',
    description: 'Navigates Arrow\'s theorem in distributed consensus: proves that no ranked multi-criteria voting system satisfies all democratic criteria.',
    tags: ['reasoning', 'arrows-theorem', 'consensus', 'voting', 'social-choice'],
    semanticType: 'process_directive',
    sectionName: 'Arrow Impossibility Consensus Architecture',
    ruSectionName: 'Теорема невозможности Эрроу и агрегация предпочтений',
    instructionsEn: [
      'Acknowledge that no ranked voting aggregation system can simultaneously satisfy Unrestricted Domain, Pareto Efficiency, Independence of Irrelevant Alternatives, and Non-Dictatorship.',
      'When aggregating stakeholder ratings across 3+ architectural options, explicitly declare which fairness axiom is pragmatically relaxed.',
      'Avoid cyclic preference deadlocks (Condorcet paradox) through cardinal weighted scoring rather than ordinal voting.',
    ],
    instructionsRu: [
      'Учитывайте, что никакая система рангового голосования не может одновременно удовлетворить всем идеальным критериям справедливости.',
      'При выборе из трех и более архитектурных вариантов открыто фиксируйте, каким критерием система осознанно поступается.',
      'Предотвращайте циклические тупики голосования (парадокс Кондорсе), используя взвешенные балльные оценки вместо простого ранжирования.',
    ],
  },
  {
    id: 'condorcet-jury-theorem-ensemble-reliability',
    name: 'CondorcetJuryTheoremEnsembleReliabilitySkill',
    displayName: 'Condorcet Jury Theorem & Majority Ensemble Scaling',
    categoryId: 'reasoning',
    description: 'Proves mathematical conditions where aggregating independent weak classifiers or LLM evaluators approaches 100% precision.',
    tags: ['reasoning', 'condorcet-jury', 'ensembles', 'scaling-laws', 'consensus'],
    semanticType: 'process_directive',
    sectionName: 'Condorcet Ensemble Precision Scaling',
    ruSectionName: 'Теорема Кондорсе о жюри присяжных и ансамблирование',
    instructionsEn: [
      'Verify the fundamental Condorcet precondition: each individual evaluator/classifier must have an independent probability p > 0.5 of being correct.',
      'Ensure genuine structural independence among ensemble evaluators (different models, prompts, or data shards) to prevent correlated failure modes.',
      'Calculate ensemble size N required to achieve target reliability (e.g. 99.99%) under majority voting.',
    ],
    instructionsRu: [
      'Проверяйте базовое условие теоремы Кондорсе: каждый отдельный валидатор обязан быть прав с вероятностью p > 0.5.',
      'Гарантируйте независимость оценщиков (разные архитектуры моделей, разные системные промпты), исключая коррелированные ошибки.',
      'Рассчитывайте минимально необходимый размер ансамбля N для достижения целевого уровня надежности через мажоритарное голосование.',
    ],
  },
];

console.log('Appending remaining Reasoning skills...');
appendSkillsToCategory('reasoning', reasoningSkillsPart2);
