const { appendSkillsToCategory } = require('./appendSkills.cjs');

// 39 skills for core (current 31 -> 70)
const coreSkills = [
  {
    id: 'falsifiability-criterion-enforcer',
    name: 'FalsifiabilityCriterionEnforcerSkill',
    displayName: 'Popperian Falsifiability Criterion',
    categoryId: 'core',
    description: 'Requires all claims, hypotheses, and assertions to declare concrete conditions under which they would be proven false.',
    tags: ['core', 'epistemology', 'falsifiability', 'scientific-method', 'logic'],
    semanticType: 'constraints',
    sectionName: 'Falsifiability & Refutation Protocol',
    ruSectionName: 'Протокол фальсифицируемости по Попперу',
    instructionsEn: [
      'Demand that every substantive factual or causal assertion be accompanied by at least one observable condition that would refute it.',
      'Explicitly reject unfalsifiable tautologies, vague truisms, and self-sealing arguments.',
      'Delineate what empirical data or systemic state would constitute decisive disproof of the proposed thesis.',
    ],
    instructionsRu: [
      'Требуйте, чтобы каждое утверждение о фактах или причинности сопровождалось критерием его опровержения.',
      'Категорически отсекайте тавтологии, размытые общие фразы и нефальсифицируемые формулировки.',
      'Четко формулируйте, какие наблюдаемые данные или сбои станут однозначным опровержением гипотезы.',
    ],
  },
  {
    id: 'pareto-principle-8020-isolation',
    name: 'ParetoPrinciple8020IsolationSkill',
    displayName: 'Pareto Principle (80/20) Root Lever Isolation',
    categoryId: 'core',
    description: 'Identifies the critical 20% of inputs, variables, or bottlenecks generating 80% of systemic outcomes or friction.',
    tags: ['core', 'pareto', 'prioritization', 'efficiency', 'leverage'],
    semanticType: 'process_directive',
    sectionName: 'Pareto 80/20 Leverage Architecture',
    ruSectionName: 'Выделение ключевого рычага по принципу Парето (80/20)',
    instructionsEn: [
      'Rank all variables by impact magnitude and isolate the top quintile (20%) yielding the vast majority of business/technical value.',
      'Deprioritize marginal optimizations that consume excessive engineering or cognitive overhead with sub-5% upside.',
      'Provide an explicit sensitivity table demonstrating outcome elasticity relative to the isolated high-leverage factors.',
    ],
    instructionsRu: [
      'Ранжируйте переменные по силе влияния и выделите верхние 20%, дающие подавляющий результат.',
      'Отсекайте вторичные оптимизации, требующие несоразмерных затрат при потенциале прироста менее 5%.',
      'Формируйте матрицу чувствительности системы к ключевым факторам максимального рычага.',
    ],
  },
  {
    id: 'first-order-vs-second-order-effects',
    name: 'FirstOrderVsSecondOrderEffectsSkill',
    displayName: 'Second-Order & Higher-Order Consequences Mapping',
    categoryId: 'core',
    description: 'Maps second-, third-, and nth-order systemic ramifications, perverse incentives, and unintended ripple effects of any decision.',
    tags: ['core', 'systems-thinking', 'second-order-effects', 'unintended-consequences'],
    semanticType: 'process_directive',
    sectionName: 'Higher-Order Effects & Feedback Loops',
    ruSectionName: 'Картирование последствий второго и высших порядков',
    instructionsEn: [
      'Differentiate between immediate first-order gains and downstream secondary/tertiary systemic distortions.',
      'Map feedback loops: identify whether corrective actions introduce reinforcing cycles, compensatory dampening, or perverse incentives (Cobra effect).',
      'Quantify the temporal delay between initial execution and the manifestation of second-order debt or benefits.',
    ],
    instructionsRu: [
      'Четко разделяйте сиюминутный выигрыш первого порядка и отложенные системные искажения второго и третьего порядков.',
      'Анализируйте петли обратной связи и эффект кобры: не стимулирует ли решение нежелательное поведение участников системы.',
      'Оценивайте временной лаг между внедрением изменения и проявлением побочных эффектов.',
    ],
  },
  {
    id: 'inversion-thinking-jacobi',
    name: 'InversionThinkingJacobiSkill',
    displayName: 'Inversion Principle (Jacobi: "Invert, Always Invert")',
    categoryId: 'core',
    description: 'Solves complex problems by determining how to achieve guaranteed failure and systematically eradicating those failure paths.',
    tags: ['core', 'inversion', 'mental-models', 'risk-eradication', 'problem-solving'],
    semanticType: 'process_directive',
    sectionName: 'Inversion & Failure Eradication Protocol',
    ruSectionName: 'Принцип инверсии мышления (Инвертируй, всегда инвертируй)',
    instructionsEn: [
      'Begin by formulating the exact inverted objective: "How could we reliably guarantee complete, catastrophic project failure?"',
      'Catalog every discrete vulnerability, friction point, and complacency trap identified through this inverted perspective.',
      'Convert each fatal vulnerability into an uncompromising preventive safeguard in the primary execution plan.',
    ],
    instructionsRu: [
      'Сформулируйте инвертированную задачу: «Какими действиями мы гарантированно приведем проект к полному краху?».',
      'Составьте исчерпывающий перечень точек фатального отказа, выявленных этим обратным анализом.',
      'Преобразуйте каждую точку отказа в обязательный защитный барьер основного плана реализации.',
    ],
  },
  {
    id: 'chesterton-fence-precondition-check',
    name: 'ChestertonFencePreconditionCheckSkill',
    displayName: 'Chesterton\'s Fence Precondition Protocol',
    categoryId: 'core',
    description: 'Forbids removing, refactoring, or deprecating any existing rule, code block, or process until the original rationale is fully reconstructed.',
    tags: ['core', 'chesterton-fence', 'refactoring', 'legacy-systems', 'due-diligence'],
    semanticType: 'constraints',
    sectionName: 'Chesterton\'s Fence Historical Rationale Audit',
    ruSectionName: 'Протокол забора Честертона (исторический аудит)',
    instructionsEn: [
      'Prohibit deleting or altering legacy architectures, configurations, or organizational rules without documenting why they were originally created.',
      'Reconstruct the historical context, constraints, and past failures that motivated the current seemingly suboptimal mechanism.',
      'Demonstrate conclusively that the original motivating hazard no longer exists or is superseded by a strictly superior mitigation.',
    ],
    instructionsRu: [
      'Запрещайте удаление или переписывание legacy-кода и правил до тех пор, пока не выяснена истинная причина их появления.',
      'Восстановите исторический контекст, внешние ограничения и инциденты, приведшие к созданию текущей конструкции.',
      'Докажите документально, что первоначальная угроза устранена или надежно нейтрализована новым механизмом.',
    ],
  },
  {
    id: 'steelmanning-strongest-opposing-case',
    name: 'SteelmanningStrongestOpposingCaseSkill',
    displayName: 'Steelmanning Opposing Perspectives',
    categoryId: 'core',
    description: 'Reconstructs rival perspectives in their strongest, most compelling, and charity-calibrated form before offering counter-arguments.',
    tags: ['core', 'steelmanning', 'intellectual-honesty', 'argumentation', 'debate'],
    semanticType: 'process_directive',
    sectionName: 'Steelmanning & Intellectual Charity Architecture',
    ruSectionName: 'Стилменнинг: усиление противоположной позиции',
    instructionsEn: [
      'Articulate the opposing argument so convincingly that its proponents would agree: "Yes, that captures our view better than we did."',
      'Grant all valid empirical points and shared premises before identifying precise divergences in axioms, trade-off values, or data.',
      'Eliminate strawman arguments, rhetorical mockery, and caricatured oversimplifications.',
    ],
    instructionsRu: [
      'Сформулируйте аргументы оппонента в предельно сильной форме, вызывающей согласие авторов позиции.',
      'Признайте справедливые факты и общие предпосылки до перехода к обоснованию расхождений.',
      'Полностью исключите подмену тезиса (strawman), сарказм и примитивизацию конкурирующей точки зрения.',
    ],
  },
  {
    id: 'occams-razor-parsimony-pruning',
    name: 'OccamsRazorParsimonyPruningSkill',
    displayName: 'Occam\'s Razor Parsimonious Pruning',
    categoryId: 'core',
    description: 'Systematically prunes unnecessary entities, auxiliary assumptions, and speculative mechanisms, favoring the simplest sufficient explanation.',
    tags: ['core', 'occams-razor', 'simplicity', 'parsimony', 'epistemology'],
    semanticType: 'constraints',
    sectionName: 'Occam\'s Razor Parsimony Audit',
    ruSectionName: 'Бритва Оккама: сокращение избыточных сущностей',
    instructionsEn: [
      'Strip away redundant intermediate layers, speculative dependencies, and auxiliary assumptions that do not increase predictive accuracy.',
      'Select the simplest architectural or explanatory model that fully accounts for all verified observations.',
      'Demand extraordinary justification before introducing novel abstractions, unproven libraries, or convoluted protocols.',
    ],
    instructionsRu: [
      'Устраняйте лишние промежуточные слои, избыточные допущения и абстракции, не влияющие на результат.',
      'Выбирайте простейшую архитектурную модель из всех, полностью объясняющих факты и требования.',
      'Требуйте веских доказательств перед внедрением новых сущностей, концепций и непроверенных зависимостей.',
    ],
  },
  {
    id: 'hanlon-razor-benevolent-attribution',
    name: 'HanlonRazorBenevolentAttributionSkill',
    displayName: 'Hanlon\'s Razor Attribution Filter',
    categoryId: 'core',
    description: 'Never attributes to malice or conspiracy that which is adequately explained by operational friction, cognitive bias, or misalignment.',
    tags: ['core', 'hanlon-razor', 'root-cause', 'attribution', 'blameless'],
    semanticType: 'behavior_directive',
    sectionName: 'Hanlon\'s Razor Attribution Filter',
    ruSectionName: 'Бритва Хэнлона: фильтр атрибуции сбоев',
    instructionsEn: [
      'Analyze systemic breakdown assuming informational asymmetries, confusing UX, or misaligned incentives rather than bad faith or incompetence.',
      'Examine whether ambiguous requirements or fragmented documentation naturally created the failure pathway.',
      'Focus root-cause remedies on architectural guardrails, clearer contracts, and deterministic constraints rather than punitive admonitions.',
    ],
    instructionsRu: [
      'Анализируйте сбои через призму информационных пробелов, запутанного UX и несогласованных стимулов, а не злого умысла.',
      'Выявляйте, как размытые требования или противоречивые регламенты закономерно привели к ошибке исполнителя.',
      'Направляйте решения на системные ограничения и архитектурные барьеры вместо поиска и наказания виновных.',
    ],
  },
  {
    id: 'circle-of-competence-boundary-lock',
    name: 'CircleOfCompetenceBoundaryLockSkill',
    displayName: 'Circle of Competence Explicit Perimeter',
    categoryId: 'core',
    description: 'Strictly distinguishes areas of proven mastery from adjacent speculative domains, refusing to overconfidently guess beyond boundaries.',
    tags: ['core', 'competence', 'epistemic-humility', 'boundaries', 'expertise'],
    semanticType: 'constraints',
    sectionName: 'Circle of Competence Boundary Enforcement',
    ruSectionName: 'Очерчивание границ круга компетентности',
    instructionsEn: [
      'Explicitly demarcate what is known with high deterministic confidence versus what represents heuristic estimation or speculation.',
      'State "I do not know" or flag high variance when queried on domains outside verified baseline competencies.',
      'Prescribe empirical validation steps and expert consultation pathways rather than hallucinating plausible answers.',
    ],
    instructionsRu: [
      'Четко разделяйте доказанные факты высокой уверенности и предположительные эвристические оценки.',
      'Прямо заявляйте о границах знаний и высокой неопределенности при выходе за пределы подтвержденной базы.',
      'Предлагайте конкретный протокол верификации и привлечения профильных экспертов вместо генерации догадок.',
    ],
  },
  {
    id: 'asymmetric-risk-convexity-maximizer',
    name: 'AsymmetricRiskConvexityMaximizerSkill',
    displayName: 'Convexity & Asymmetric Risk/Reward Positioning',
    categoryId: 'core',
    description: 'Maximizes upside convexity (unbounded gain with bounded loss) while aggressively eliminating fatal ruin exposure (concavity).',
    tags: ['core', 'asymmetry', 'risk-management', 'convexity', 'antifragility'],
    semanticType: 'process_directive',
    sectionName: 'Convex Risk Positioning Architecture',
    ruSectionName: 'Позиционирование с положительной асимметрией (Convexity)',
    instructionsEn: [
      'Structure solutions so downside risk is strictly capped (bounded financial/temporal loss) while potential upside remains open-ended.',
      'Strictly avoid concavity: reject options offering small steady gains that carry hidden tail risks of total ruin or catastrophic outage.',
      'Apply Taleb\'s barbell strategy: combine hyper-conservative core resilience with small exploratory high-convexity experiments.',
    ],
    instructionsRu: [
      'Формируйте решения с жестко ограниченным риском убытков и неограниченным потенциалом выигрыша.',
      'Исключайте вогнутые риски: отвергайте варианты с малой выгодой, несущие скрытую угрозу полного краха системы.',
      'Применяйте стратегию штанги: сверхнадежное консервативное ядро плюс серия дешевых экспериментов с высоким потенциалом.',
    ],
  },
  {
    id: 'opportunity-cost-counterfactual-auditor',
    name: 'OpportunityCostCounterfactualAuditorSkill',
    displayName: 'Opportunity Cost & Counterfactual Capital Allocation',
    categoryId: 'core',
    description: 'Evaluates decisions against the best forgone alternative, quantifying trade-offs in engineering bandwidth, latency, and capital.',
    tags: ['core', 'opportunity-cost', 'counterfactual', 'economics', 'resource-allocation'],
    semanticType: 'process_directive',
    sectionName: 'Opportunity Cost & Counterfactual Evaluation',
    ruSectionName: 'Оценка альтернативных издержек (Opportunity Cost)',
    instructionsEn: [
      'Never evaluate an action in isolation; evaluate it against the single best alternative use of the identical resources.',
      'Quantify what critical projects, features, or architectural debts are delayed by choosing this path.',
      'Calculate the counterfactual baseline: what would naturally happen if zero intervention or code were deployed?',
    ],
    instructionsRu: [
      'Никогда не оценивайте инициативу изолированно: сравнивайте ее с лучшим альтернативным использованием тех же ресурсов.',
      'Количественно фиксируйте, какие задачи и устранение какого техдолга откладываются при выборе этого решения.',
      'Оценивайте контрфактический сценарий: что произойдет естественным образом при полном отсутствии вмешательства.',
    ],
  },
  {
    id: 'skin-in-the-game-incentive-alignment',
    name: 'SkinInTheGameIncentiveAlignmentSkill',
    displayName: 'Skin-in-the-Game & Moral Hazard Elimination',
    categoryId: 'core',
    description: 'Ensures decision-makers bear personal or operational exposure to the consequences of their architectural and strategic choices.',
    tags: ['core', 'skin-in-the-game', 'incentives', 'moral-hazard', 'accountability'],
    semanticType: 'constraints',
    sectionName: 'Skin-in-the-Game & Incentive Integrity',
    ruSectionName: 'Принцип ответственности (Skin in the Game) и исключение moral hazard',
    instructionsEn: [
      'Eliminate moral hazards where architects or planners reap rewards while externalizing operational failures to on-call engineers or users.',
      'Mandate that authors of complex system proposals participate directly in production support, telemetry triage, and incident remediation.',
      'Align organizational incentives so that systemic simplicity and resilience are rewarded more than resume-driven complexity.',
    ],
    instructionsRu: [
      'Устраняйте ситуации moral hazard, когда инициатор получает выгоду, а риски и сбои перекладываются на дежурных инженеров.',
      'Обязывайте авторов сложных архитектурных изменений лично участвовать в поддержке, дежурствах и разборах аварий.',
      'Выстраивайте стимулы так, чтобы надежность и простота поощрялись выше, чем внедрение модных и неоправданно сложных инструментов.',
    ],
  },
  {
    id: 'reversibility-one-way-vs-two-way-doors',
    name: 'ReversibilityOneWayVsTwoWayDoorsSkill',
    displayName: 'Reversibility Architecture (Type 1 vs Type 2 Decisions)',
    categoryId: 'core',
    description: 'Classifies choices into irreversible "one-way doors" requiring deep deliberation vs reversible "two-way doors" demanding rapid execution.',
    tags: ['core', 'reversibility', 'bezos-doors', 'decision-velocity', 'speed'],
    semanticType: 'process_directive',
    sectionName: 'Reversibility & Decision Velocity Matrix',
    ruSectionName: 'Матрица обратимости решений (One-Way vs Two-Way Doors)',
    instructionsEn: [
      'Classify decisions as Type 1 (irreversible, high blast radius) or Type 2 (easily reversible, low blast radius).',
      'Accelerate Type 2 decisions with high velocity, minimal consensus meetings, and automated rollbacks.',
      'Subject Type 1 decisions (database migrations, major protocol changes, public API commitments) to exhaustive multi-party review.',
    ],
    instructionsRu: [
      'Классифицируйте решения: Type 1 (необратимые, высокий радиус поражения) или Type 2 (легко обратимые, безопасные для экспериментов).',
      'Принимайте решения Type 2 на максимальной скорости с минимальными согласованиями и механизмом быстрого отката.',
      'Решения Type 1 (миграция баз данных, изменение публичных API, выбор лицензий) подвергайте глубокому всестороннему аудиту.',
    ],
  },
  {
    id: 'antifragility-stress-gain-architecture',
    name: 'AntifragilityStressGainArchitectureSkill',
    displayName: 'Antifragility (Systemic Gain from Volatility & Stress)',
    categoryId: 'core',
    description: 'Designs systems that actively grow stronger, more resilient, and more optimized when subjected to randomness and volatility.',
    tags: ['core', 'antifragility', 'taleb', 'resilience', 'evolutionary-design'],
    semanticType: 'structural_directive',
    sectionName: 'Antifragile Systemic Architecture',
    ruSectionName: 'Антихрупкость: извлечение выгоды из стресса и сбоев',
    instructionsEn: [
      'Design architectures with distributed modularity so individual component failures strengthen the overarching system via automated self-tuning.',
      'Incorporate controlled stochastic stressors (chaos testing, fuzzing, rate surges) to continuously trigger adaptive hardening.',
      'Avoid over-optimization to a single static operating point; preserve functional redundancy and dynamic reconfiguration capacity.',
    ],
    instructionsRu: [
      'Проектируйте модульную архитектуру, где локальные сбои компонентов приводят к адаптивному самообучению всей системы.',
      'Внедряйте контролируемые стресс-нагрузки (chaos engineering, фаззинг, пиковые всплески) для постоянной закалки сервисов.',
      'Избегайте чрезмерной подгонки под одну статическую точку: сохраняйте функциональный запас и гибкость переконфигурации.',
    ],
  },
  {
    id: 'goodharts-law-metric-corruption-guard',
    name: 'GoodhartsLawMetricCorruptionGuardSkill',
    displayName: 'Goodhart\'s Law & Proxy Metric Gaming Defense',
    categoryId: 'core',
    description: 'Guards against metric corruption ("When a measure becomes a target, it ceases to be a good measure") via paired counter-metrics.',
    tags: ['core', 'goodharts-law', 'metrics', 'gaming-prevention', 'kpi'],
    semanticType: 'guardrail_directive',
    sectionName: 'Goodhart\'s Law & Metric Integrity Protocol',
    ruSectionName: 'Защита от закона Гудхарта: спаренные балансирующие метрики',
    instructionsEn: [
      'Whenever an optimization metric is declared (e.g. speed, ticket throughput, code coverage), identify how it will naturally be gamed.',
      'Pair every primary metric with a counter-balancing quality metric (e.g. throughput paired with defect escape rate, velocity paired with technical debt ratio).',
      'Prohibit single-metric evaluation gates; enforce composite multidimensional health scorecards.',
    ],
    instructionsRu: [
      'При введении любой целевой метрики (скорость, число закрытых тикетов) заранее опишите пути манипуляции ею.',
      'Связывайте каждую количественную метрику с парной качественной (скорость разработки с процентом регрессий, покрытие тестами с надежностью).',
      'Запрещайте принятие решений по единственному показателю; используйте многомерные балансирующие карты здоровья системы.',
    ],
  },
  {
    id: 'diminishing-returns-marginal-cutoff',
    name: 'DiminishingReturnsMarginalCutoffSkill',
    displayName: 'Law of Diminishing Marginal Returns Cutoff',
    categoryId: 'core',
    description: 'Establishes clear mathematical stopping thresholds where incremental effort yields negligible or negative marginal benefit.',
    tags: ['core', 'diminishing-returns', 'stopping-rules', 'efficiency', 'pragmatism'],
    semanticType: 'process_directive',
    sectionName: 'Diminishing Marginal Returns Stopping Boundary',
    ruSectionName: 'Граница убывающей отдачи и правило остановки',
    instructionsEn: [
      'Graph the marginal utility curve of additional iterations, refactorings, or precision expansions.',
      'Establish an explicit stopping condition when marginal cost exceeds marginal gain (e.g. moving from 99.9% to 99.99% reliability for an internal tool).',
      'Declare "good enough for production" criteria that release engineering bandwidth for unaddressed bottlenecks.',
    ],
    instructionsRu: [
      'Оценивайте кривую предельной полезности от дополнительных доработок, микро-оптимизаций и правок.',
      'Вводите жесткое правило остановки, когда затраты на следующий шаг превышают практическую пользу.',
      'Фиксируйте четкие критерии достаточности для релиза, высвобождая ресурсы для решения ключевых нерешенных задач.',
    ],
  },
  {
    id: 'survivorship-bias-complete-corpus-audit',
    name: 'SurvivorshipBiasCompleteCorpusAuditSkill',
    displayName: 'Survivorship Bias Counter-Analysis',
    categoryId: 'core',
    description: 'Audits case studies and best-practice retrospectives by actively unearthing the invisible cemetery of failed and vanished counterparts.',
    tags: ['core', 'survivorship-bias', 'cognitive-biases', 'benchmarking', 'evidence'],
    semanticType: 'process_directive',
    sectionName: 'Survivorship Bias Correction Protocol',
    ruSectionName: 'Аудит систематической ошибки выжившего (Survivorship Bias)',
    instructionsEn: [
      'Do not analyze success stories in isolation; actively investigate failed companies, deprecated frameworks, and abandoned initiatives that used the exact same tactics.',
      'Identify attributes common to both survivors and casualties to eliminate false causal correlations.',
      'Reconstruct the invisible denominator (total initial population) to compute true base-rate success probabilities.',
    ],
    instructionsRu: [
      'Не анализируйте кейсы победителей в отрыве от контекста: исследуйте закрывшиеся проекты, использовавшие те же самые практики.',
      'Выявляйте общие признаки у выживших и погибших систем, исключая ложные причинно-следственные связи.',
      'Восстанавливайте полный объем начальной выборки для расчета реальной базовой вероятности успеха.',
    ],
  },
  {
    id: 'base-rate-neglect-prior-calibration',
    name: 'BaseRateNeglectPriorCalibrationSkill',
    displayName: 'Base Rate Integration & Prior Probability Calibration',
    categoryId: 'core',
    description: 'Anchors risk assessments and projections in empirical historical base rates before evaluating individual case specifics.',
    tags: ['core', 'base-rate', 'bayesian', 'probability', 'calibration'],
    semanticType: 'process_directive',
    sectionName: 'Base Rate & Prior Probability Calibration',
    ruSectionName: 'Учет базовой частоты (Base Rate) и априорная калибровка',
    instructionsEn: [
      'Establish the industry or historical base rate for the class of problem before evaluating unique features of the current project.',
      'Heavily discount optimistic narrative claims that deviate radically from documented reference class outcomes.',
      'Apply formal Bayesian updating: require overwhelming empirical proof before shifting posterior confidence far from base rate reality.',
    ],
    instructionsRu: [
      'Определяйте историческую базовую вероятность для данного класса задач до рассмотрения уникальных деталей проекта.',
      'Критически снижайте оптимистичные прогнозы, кардинально расходящиеся со статистикой эталонного класса (reference class).',
      'Используйте байесовское обновление: требуйте веских доказательств для смещения оценки далеко от объективной базовой частоты.',
    ],
  },
  {
    id: 'parkinsons-law-compression-timeboxing',
    name: 'ParkinsonsLawCompressionTimeboxingSkill',
    displayName: 'Parkinson\'s Law Scope Compression & Aggressive Timeboxing',
    categoryId: 'core',
    description: 'Combats work expansion by enforcing aggressive temporal constraints and strictly timeboxed execution windows.',
    tags: ['core', 'parkinsons-law', 'timeboxing', 'velocity', 'scope-management'],
    semanticType: 'process_directive',
    sectionName: 'Scope Compression & Timeboxing Architecture',
    ruSectionName: 'Закон Паркинсона: агрессивный таймбоксинг и сжатие скоупа',
    instructionsEn: [
      'Compress allotted timeframes by 30-50% to force ruthless prioritization and eliminate non-essential bikeshedding.',
      'Establish hard timeboxes with non-negotiable end times; scope is variable, but delivery deadline is fixed.',
      'Mandate working increment demonstration at each timebox boundary regardless of feature completeness.',
    ],
    instructionsRu: [
      'Сжимайте сроки выполнения на 30–50% для запуска вынужденного отсечения второстепенного и устранения затягивания.',
      'Вводите жесткие таймбоксы: дедлайн неизменен, варьироваться может только объем включаемых опций.',
      'Требуйте демонстрации работающего прототипа по завершении каждого таймбокса вне зависимости от полноты функционала.',
    ],
  },
  {
    id: 'confirmation-bias-falsifying-search',
    name: 'ConfirmationBiasFalsifyingSearchSkill',
    displayName: 'Confirmation Bias Red-Teaming & Disconfirming Search',
    categoryId: 'core',
    description: 'Actively searches for facts, data points, and edge cases that refute preferred beliefs rather than accumulating confirming evidence.',
    tags: ['core', 'confirmation-bias', 'red-teaming', 'disconfirmation', 'objectivity'],
    semanticType: 'process_directive',
    sectionName: 'Active Disconfirming Evidence Search',
    ruSectionName: 'Поиск опровергающих свидетельств (борьба с confirmation bias)',
    instructionsEn: [
      'Formulate explicit search queries specifically engineered to discover counter-arguments, failure reports, and security disclosures.',
      'Log disconfirming data points with equal or greater visibility than confirming evidence in technical trade-off documents.',
      'Assign an active devil\'s advocate role to stress-test the favored proposal before architectural consensus is declared.',
    ],
    instructionsRu: [
      'Формулируйте поисковые запросы, нацеленные на поиск отчетов об авариях, недостатков и уязвимостей выбранного подхода.',
      'Фиксируйте опровергающие факты с тем же приоритетом, что и подтверждающие, в сводных таблицах решений.',
      'Назначайте рецензента с явной ролью поиска слабых мест перед утверждением любого ключевого архитектурного выбора.',
    ],
  },
  {
    id: 'sunk-cost-fallacy-zero-base-reset',
    name: 'SunkCostFallacyZeroBaseResetSkill',
    displayName: 'Sunk Cost Eradication & Zero-Based Evaluation',
    categoryId: 'core',
    description: 'Ignores historical investments, lines of code, and emotional attachment, evaluating ongoing projects strictly from current state forward.',
    tags: ['core', 'sunk-cost', 'zero-based', 'rationality', 'pivot'],
    semanticType: 'process_directive',
    sectionName: 'Zero-Based Decision Reset Protocol',
    ruSectionName: 'Ликвидация ловушки невозвратных затрат (Sunk Cost Fallacy)',
    instructionsEn: [
      'Eradicate past time, money, and emotional capital already spent from all future continuation calculations.',
      'Ask the zero-based question: "If we arrived today with zero prior code and clean cash, would we choose to invest in building this exact roadmap?"',
      'Recommend project termination or pivot without hesitation when future ROI falls below competitive benchmarks.',
    ],
    instructionsRu: [
      'Полностью исключайте прошлые затраты труда, времени и средств из расчетов целесообразности продолжения проекта.',
      'Задавайте вопрос с чистого листа: «Если бы у нас не было этого кода и мы начинали сегодня, стали бы мы инвестировать в эту идею?».',
      'Без колебаний рекомендуйте закрытие проекта или смену курса, если будущая отдача уступает альтернативам.',
    ],
  },
  {
    id: 'anchoring-heuristic-debiasing-protocol',
    name: 'AnchoringHeuristicDebiasingProtocolSkill',
    displayName: 'Anchoring Heuristic Debiasing Protocol',
    categoryId: 'core',
    description: 'Identifies arbitrary initial figures, vendor estimates, or early benchmarks and computes objective ground-up independent valuations.',
    tags: ['core', 'anchoring', 'debiasing', 'estimation', 'negotiation'],
    semanticType: 'process_directive',
    sectionName: 'Anchoring Debiasing & Ground-Up Estimation',
    ruSectionName: 'Дебиасинг эффекта привязки (Anchoring Heuristic)',
    instructionsEn: [
      'Identify initial numbers, estimates, or deadlines proposed early in conversations and isolate their potential biasing distortion.',
      'Derive completely independent bottom-up estimates using first principles, component breakdowns, and empirical benchmarks.',
      'Present estimates as probabilistic ranges with explicit confidence intervals rather than single anchored points.',
    ],
    instructionsRu: [
      'Выявляйте первоначально названные цифры, сроки или оценки бюджета и изолируйте их искажающее влияние.',
      'Рассчитывайте независимую оценку снизу вверх на основе калькуляции трудозатрат, компонентов и рыночных бенчмарков.',
      'Представляйте результаты в виде вероятностного диапазона с указанием доверительного интервала вместо точечной цифры.',
    ],
  },
  {
    id: 'hyperbolic-discounting-long-term-anchor',
    name: 'HyperbolicDiscountingLongTermAnchorSkill',
    displayName: 'Hyperbolic Discounting Correction & Long-Term Anchoring',
    categoryId: 'core',
    description: 'Counteracts human bias toward immediate gratification by systematically protecting high-ROI multi-year strategic architectures.',
    tags: ['core', 'hyperbolic-discounting', 'long-term-strategy', 'technical-debt'],
    semanticType: 'process_directive',
    sectionName: 'Long-Term Value Preservation Protocol',
    ruSectionName: 'Коррекция гиперболического дисконтирования и долгосрочный якорь',
    instructionsEn: [
      'Expose short-term tactical shortcuts that borrow against future engineering velocity and create compounding technical debt.',
      'Quantify the true multi-year cost of ownership of tactical hacks vs clean, extensible foundational architectures.',
      'Establish non-negotiable allocations (e.g. 20% engineering bandwidth) permanently dedicated to platform longevity and tech debt remediation.',
    ],
    instructionsRu: [
      'Вскрывайте сиюминутные костыли, дающие быстрый результат за счет накопления критического технического долга в будущем.',
      'Рассчитывайте реальную многолетнюю стоимость владения временным решением в сравнении с чистой расширяемой архитектурой.',
      'Закрепляйте фиксированную долю ресурсов команды (минимум 20%) на устранение техдолга и поддержание устойчивости платформы.',
    ],
  },
  {
    id: 'availability-heuristic-cross-check',
    name: 'AvailabilityHeuristicCrossCheckSkill',
    displayName: 'Availability Heuristic Empirical Cross-Check',
    categoryId: 'core',
    description: 'Prevents over-indexing on recent memorable outages or vivid edge-cases by demanding rigorous statistical frequency distributions.',
    tags: ['core', 'availability-heuristic', 'incident-management', 'statistics'],
    semanticType: 'process_directive',
    sectionName: 'Empirical Frequency vs Vividness Audit',
    ruSectionName: 'Проверка эвристики доступности по статистическим данным',
    instructionsEn: [
      'Detect when architectural decisions are disproportionately driven by a recent dramatic outage rather than objective probability distributions.',
      'Extract longitudinal frequency logs to verify whether the feared failure mode is genuinely common or an ultra-rare outlier.',
      'Calibrate defensive engineering investments proportionally to calculated Expected Annual Loss (EAL).',
    ],
    instructionsRu: [
      'Отслеживайте ситуации, когда архитектура перегружается защитой от недавнего яркого сбоя вопреки общей статистике.',
      'Поднимайте исторические логи инцидентов для проверки реальной частоты пугающего сценария отказа.',
      'Калибруйте инженерные затраты на защиту пропорционально расчетному математическому ожиданию потерь.',
    ],
  },
  {
    id: 'fundamental-attribution-error-shield',
    name: 'FundamentalAttributionErrorShieldSkill',
    displayName: 'Fundamental Attribution Error Blameless Shield',
    categoryId: 'core',
    description: 'Enforces blameless systemic analysis: treats human error as a symptom of flawed tooling and processes, never as the root cause.',
    tags: ['core', 'blameless', 'fundamental-attribution-error', 'incident-review', 'safety'],
    semanticType: 'behavior_directive',
    sectionName: 'Blameless Systemic Causation Protocol',
    ruSectionName: 'Исключение фундаментальной ошибки атрибуции (Blameless Systems)',
    instructionsEn: [
      'Strictly prohibit concluding an incident review with "human error" or "operator mistake" as the root cause.',
      'Investigate environmental affordances: why did the tooling allow a destructive action without confirmation or guardrail safeguards?',
      'Engineer systemic mechanisms (e.g. read-only production defaults, dual-control approvals) that render human mistakes structurally impossible.',
    ],
    instructionsRu: [
      'Категорически запрещайте завершать разбор инцидента выводом о «человеческом факторе» или ошибке оператора.',
      'Исследуйте окружение: почему интерфейс и CLI позволили совершить разрушительное действие без защиты от ошибки?',
      'Внедряйте системные барьеры (двойное подтверждение, защищенные права, автоматический откат), делающие ошибку невозможной.',
    ],
  },
  {
    id: 'status-quo-bias-disruption-challenge',
    name: 'StatusQuoBiasDisruptionChallengeSkill',
    displayName: 'Status Quo Bias Active Disruption Challenge',
    categoryId: 'core',
    description: 'Constructively challenges legacy defaults and inertia by treating the status quo with the same rigorous skepticism as new proposals.',
    tags: ['core', 'status-quo-bias', 'innovation', 'questioning-defaults', 'architecture'],
    semanticType: 'process_directive',
    sectionName: 'Status Quo Justification & Disruption Protocol',
    ruSectionName: 'Преодоление предвзятости статус-кво (Status Quo Bias)',
    instructionsEn: [
      'Do not give existing processes or architectures automatic benefit of the doubt; subject incumbent designs to active justification hurdles.',
      'Examine what historical assumptions have quietly expired due to advances in cloud infrastructure, compilers, or market dynamics.',
      'Formulate a greenfield challenge: "How would we design this subsystem today if we had zero legacy baggage?"',
    ],
    instructionsRu: [
      'Не давайте существующим процессам автоматического карт-бланша: требуйте регулярного обоснования их эффективности.',
      'Выявляйте устаревшие предпосылки, утратившие силу благодаря развитию инструментов, языков и инфраструктуры.',
      'Формулируйте задачу с чистого листа: «Как бы мы спроектировали эту подсистему сегодня без оглядки на старый стек?».',
    ],
  },
  {
    id: 'dunning-kruger-calibration-gate',
    name: 'DunningKrugerCalibrationGateSkill',
    displayName: 'Dunning-Kruger Competency Calibration Gate',
    categoryId: 'core',
    description: 'Calibrates architectural confidence: flags unearned certainty in novice domains and surfaces nuanced complexity.',
    tags: ['core', 'dunning-kruger', 'calibration', 'nuance', 'depth'],
    semanticType: 'process_directive',
    sectionName: 'Dunning-Kruger Calibration & Nuance Injection',
    ruSectionName: 'Калибровка уверенности по кривой Даннинга-Крюгера',
    instructionsEn: [
      'Detect early signs of overconfidence where simple solutions are proposed for deeply wicked, nuanced distributed problems.',
      'Surface hidden edge cases, failure domains, and historical war stories showing why the problem is harder than it appears.',
      'Encourage calibrated humility: replace sweeping dogmatic declarations with nuanced trade-off matrices.',
    ],
    instructionsRu: [
      'Выявляйте необоснованную сверхуверенность, когда для сложных распределенных систем предлагаются тривиальные рецепты.',
      'Вскрывайте скрытые граничные случаи, отказы сети и исторический опыт, объясняющий реальную глубину проблемы.',
      'Заменяйте категоричный догматизм взвешенными матрицами компромиссов с оценкой рисков.',
    ],
  },
  {
    id: 'framing-effect-reframing-lens',
    name: 'FramingEffectReframingLensSkill',
    displayName: 'Multi-Perspective Cognitive Reframing Lens',
    categoryId: 'core',
    description: 'Exposes how semantic framing distorts perception and analyzes challenges through gain, loss, risk, and operational lenses.',
    tags: ['core', 'framing', 'cognitive-bias', 'perspective', 'communication'],
    semanticType: 'process_directive',
    sectionName: 'Cognitive Reframing & Perspective Flipping',
    ruSectionName: 'Мультиперспективный рефрейминг проблемы',
    instructionsEn: [
      'Identify whether a challenge is currently framed in terms of gains, losses, fears, or technical jargon.',
      'Reframe the identical proposition through 3 alternative lenses: 1) Risk mitigation, 2) Business revenue enablement, 3) Customer friction reduction.',
      'Evaluate whether stakeholder consensus shifts dramatically when the semantic framing is neutralized.',
    ],
    instructionsRu: [
      'Определяйте, в какой модальности подана проблема: через призму потерь, страха рисков или технического жаргона.',
      'Переформулируйте тезис через 3 альтернативные оптики: снижение рисков, рост выручки и устранение барьеров пользователя.',
      'Проверяйте, сохраняется ли привлекательность решения при смене эмоциональной рамки на нейтральные факты.',
    ],
  },
  {
    id: 'survivability-ruin-barrier-enforcer',
    name: 'SurvivabilityRuinBarrierEnforcerSkill',
    displayName: 'Zero-Ruin Probability Operational Barrier',
    categoryId: 'core',
    description: 'Enforces that any strategy or deployment carrying even a non-zero probability of existential ruin is strictly disqualified.',
    tags: ['core', 'ruin-barrier', 'existential-risk', 'safety-first', 'invariants'],
    semanticType: 'constraints',
    sectionName: 'Zero-Ruin Probability Enforcement',
    ruSectionName: 'Абсолютный барьер риска необратимого краха (Ruin Barrier)',
    instructionsEn: [
      'Disqualify any technical or business proposal that carries a non-zero tail risk of total data loss, insolvency, or regulatory shutdown.',
      'Reject expected value calculations when survival is at stake: infinite upside cannot compensate for a 1% chance of terminal ruin.',
      'Mandate fail-safe airgapped backups, isolated quorum gates, and non-negotiable blast radius limiters.',
    ],
    instructionsRu: [
      'Отклоняйте любые решения, несущие даже малую вероятность полной потери данных, банкротства или отзыва лицензии.',
      'Отвергайте расчеты матожидания при угрозе гибели системы: никакой выигрыш не оправдывает риск катастрофы.',
      'Требуйте изолированных резервных копий, строгих кворумов подтверждения и ограничения радиуса поражения сбоя.',
    ],
  },
  {
    id: 'conjunction-fallacy-probability-pruning',
    name: 'ConjunctionFallacyProbabilityPruningSkill',
    displayName: 'Conjunction Fallacy Narrative Pruning',
    categoryId: 'core',
    description: 'Prunes convoluted multi-step narratives that sound intuitively plausible but are mathematically far less probable than simple baselines.',
    tags: ['core', 'conjunction-fallacy', 'probability', 'narrative-trap', 'logic'],
    semanticType: 'process_directive',
    sectionName: 'Conjunction Fallacy Probability Pruning',
    ruSectionName: 'Предотвращение ошибки конъюнкции (эффект Линды)',
    instructionsEn: [
      'Remember that P(A and B) is strictly less than or equal to P(A); eliminate overly detailed speculative failure storylines.',
      'Flag when team members convince themselves of a failure scenario simply because the vivid narrative sounds cinematic.',
      'Ground system models in base probability components rather than interconnected chain stories.',
    ],
    instructionsRu: [
      'Помните, что вероятность пересечения событий P(A и B) всегда меньше вероятности P(A): отсекайте многосоставные фантазии.',
      'Предостерегайте от веры в сценарий только из-за его кинематографичности и подробной сюжетной детализации.',
      'Опирайтесь на математические вероятности независимых компонентов вместо многозвенных гипотетических цепочек.',
    ],
  },
  {
    id: 'survivable-experimentation-sandbox',
    name: 'SurvivableExperimentationSandboxSkill',
    displayName: 'Safe-to-Fail Controlled Experimentation Sandbox',
    categoryId: 'core',
    description: 'Enables rapid innovation by designing experiments whose failure is cheap, local, silent, and educational.',
    tags: ['core', 'safe-to-fail', 'experimentation', 'innovation', 'sandboxing'],
    semanticType: 'process_directive',
    sectionName: 'Safe-to-Fail Experimentation Architecture',
    ruSectionName: 'Архитектура безопасных экспериментов (Safe-to-Fail)',
    instructionsEn: [
      'Ensure every exploratory test has an automated blast radius containment boundary (feature flag, ephemeral environment, canary cohort).',
      'Set clear metrics for experimental falsification: define upfront what performance signals will trigger automatic rollback.',
      'Treat negative experimental findings as high-value knowledge discoveries, conducting rapid blameless retrospectives.',
    ],
    instructionsRu: [
      'Ограничивайте любой эксперимент защитным периметром: фиче-флаги, изолированное окружение, канареечный трафик.',
      'Задавайте четкие критерии автоматического отката эксперимента при ухудшении целевых сигналов здоровья системы.',
      'Воспринимайте отрицательный результат как ценное устранение неопределенности, поощряя быструю фиксацию инсайтов.',
    ],
  },
  {
    id: 'ergodicity-time-vs-ensemble-audit',
    name: 'ErgodicityTimeVsEnsembleAuditSkill',
    displayName: 'Ergodicity Audit (Time-Average vs Ensemble-Average)',
    categoryId: 'core',
    description: 'Distinguishes between ensemble averages across parallel runs and the time-average experience of a single persistent system.',
    tags: ['core', 'ergodicity', 'probability', 'systems-thinking', 'risk'],
    semanticType: 'process_directive',
    sectionName: 'Ergodicity & Time-Average Sustainability',
    ruSectionName: 'Аудит эргодичности: среднее по времени vs среднее по ансамблю',
    instructionsEn: [
      'Distinguish between parallel ensemble averages (1,000 systems running once) and time-series averages (1 system running for 1,000 days).',
      'Eliminate paths where an ensemble statistic looks positive but a single absorbing failure state terminates the persistent entity.',
      'Optimize strictly for long-term survival of the continuous entity over cross-sectional benchmark snapshots.',
    ],
    instructionsRu: [
      'Различайте параллельное среднее по ансамблю (1000 систем по 1 дню) и временной ряд одной непрерывно живущей системы.',
      'Исключайте сценарии, где усредненная статистика привлекательна, но для конкретного инстанса есть риск фатального выбывания.',
      'Оптимизируйте архитектуру на долгосрочное непрерывное выживание конкретной системы во времени.',
    ],
  },
  {
    id: 'cognitive-load-split-attention-guard',
    name: 'CognitiveLoadSplitAttentionGuardSkill',
    displayName: 'Cognitive Load & Split-Attention Elimination',
    categoryId: 'core',
    description: 'Optimizes developer ergonomics and prompt readability by eliminating extraneous cognitive friction and split-attention layouts.',
    tags: ['core', 'cognitive-load', 'dx', 'clarity', 'ergonomics'],
    semanticType: 'structural_directive',
    sectionName: 'Cognitive Load Reduction Architecture',
    ruSectionName: 'Снижение когнитивной нагрузки и устранение split-attention',
    instructionsEn: [
      'Place related technical instructions, constraints, and data formats in close physical and conceptual proximity.',
      'Eliminate extraneous cognitive load: replace confusing abbreviations and fragmented cross-references with self-contained directives.',
      'Structure prompts and code with clear visual hierarchies, intuitive signposts, and progressive disclosure.',
    ],
    instructionsRu: [
      'Размещайте связанные инструкции, требования к типам и форматы вывода в непосредственной логической близости.',
      'Устраняйте посторонний шум: заменяйте неочевидные сокращения и перекрестные отсылки самодостаточными формулировками.',
      'Форматируйте материал с четкой визуальной иерархией, выделяя ключевые мысли и структурируя детали.',
    ],
  },
  {
    id: 'metacognitive-calibration-scoring',
    name: 'MetacognitiveCalibrationScoringSkill',
    displayName: 'Metacognitive Confidence Calibration Scoring',
    categoryId: 'core',
    description: 'Requires the system to append calibrated subjective probability estimates to its assertions and track predictive Brier scores.',
    tags: ['core', 'metacognition', 'confidence-calibration', 'brier-score', 'probabilities'],
    semanticType: 'output_format',
    sectionName: 'Metacognitive Confidence Scoring Specification',
    ruSectionName: 'Метакогнитивная калибровка уверенности (Brier Score)',
    instructionsEn: [
      'Append explicit percentage confidence ratings (e.g. [Confidence: 85%]) to high-impact technical recommendations and estimates.',
      'Ensure confidence calibration: when asserting 80% confidence, the underlying statement should be correct approximately 8 out of 10 times.',
      'Provide clear epistemic justifications explaining what evidence bounds confidence below 100%.',
    ],
    instructionsRu: [
      'Сопровождайте ключевые выводы и рекомендации явными процентами уверенности (например, [Уверенность: 85%]).',
      'Соблюдайте калибровку: высказывания с заявленной уверенностью 80% должны оказываться верными в 8 случаях из 10.',
      'Обосновывайте оценку: приводите аргументы, почему уверенность не является абсолютной (что остается неизвестным).',
    ],
  },
  {
    id: 'triangulation-independent-sources',
    name: 'TriangulationIndependentSourcesSkill',
    displayName: 'Multi-Source Independent Triangulation',
    categoryId: 'core',
    description: 'Requires factual verification through at least three orthogonal, structurally independent evidence streams.',
    tags: ['core', 'triangulation', 'verification', 'epistemology', 'evidence'],
    semanticType: 'process_directive',
    sectionName: 'Orthogonal Evidence Triangulation Protocol',
    ruSectionName: 'Триангуляция данных по независимым источникам',
    instructionsEn: [
      'Never accept a single source as definitive proof; require verification across at least 3 structurally independent data streams.',
      'Verify that cited sources are genuinely orthogonal rather than echo-chamber citations tracing back to a single root press release.',
      'Highlight discrepancies between source methodologies and synthesize a consensus reality bounded by explicit error bars.',
    ],
    instructionsRu: [
      'Никогда не считайте единственный источник доказательством: требуйте подтверждения минимум из трех независимых каналов.',
      'Проверяйте независимость источников: убедитесь, что они не цитируют один и тот же исходный пресс-релиз.',
      'Анализируйте нестыковки в методологиях источников и формируйте взвешенную оценку с указанием погрешности.',
    ],
  },
  {
    id: 'regret-minimization-framework-bezos',
    name: 'RegretMinimizationFrameworkBezosSkill',
    displayName: 'Bezos Regret Minimization Strategic Horizon',
    categoryId: 'core',
    description: 'Projects decision consequences to an 80-year-old perspective to eliminate trivial social friction and pursue foundational missions.',
    tags: ['core', 'regret-minimization', 'strategy', 'vision', 'decision-making'],
    semanticType: 'process_directive',
    sectionName: 'Regret Minimization Horizon Analysis',
    ruSectionName: 'Фреймворк минимизации сожалений (Regret Minimization)',
    instructionsEn: [
      'Frame pivotal strategic dilemmas by projecting forward to the end of career or life: "Will I regret not attempting this bold leap?"',
      'Filter out transient embarrassment, temporary social friction, and short-term quarterly turbulence.',
      'Prioritize decisions that foster long-term mastery, enduring platform ownership, and foundational contributions.',
    ],
    instructionsRu: [
      'Оценивайте ключевые развилки с перспективы долгосрочного горизонта: «Буду ли я сожалеть, что не попробовал сделать этот шаг?».',
      'Отсеивайте сиюминутный страх критики, временный дискомфорт и квартальную турбулентность.',
      'Отдавайте приоритет выборам, ведущим к фундаментальному развитию компетенций и созданию непреходящей ценности.',
    ],
  },
  {
    id: 'subsidiarity-principle-delegation',
    name: 'SubsidiarityPrincipleDelegationSkill',
    displayName: 'Principle of Subsidiarity & Edge Delegation',
    categoryId: 'core',
    description: 'Enforces resolving matters at the lowest, most decentralized competent level, escalating to central authority only when strictly necessary.',
    tags: ['core', 'subsidiarity', 'decentralization', 'autonomy', 'governance'],
    semanticType: 'process_directive',
    sectionName: 'Principle of Subsidiarity & Edge Autonomy',
    ruSectionName: 'Принцип субсидиарности и децентрализованного контроля',
    instructionsEn: [
      'Resolve technical decisions at the localized edge (microservice, pod, individual team) closest to the problem domain.',
      'Require central architectural governance only for cross-cutting protocols, network security boundaries, and shared contract interfaces.',
      'Empower edge components with autonomous failure recovery capabilities rather than routing all triage through centralized orchestrators.',
    ],
    instructionsRu: [
      'Принимайте решения на самом низком и близком к проблеме уровне (микросервис, команда компонента).',
      'Ограничивайте централизованное регулирование только общими протоколами, безопасностью периметра и межсервисными контрактами.',
      'Наделяйте краевые сервисы автономными механизмами самовосстановления без ожидания команд от центрального оркестратора.',
    ],
  },
  {
    id: 'signal-to-noise-maximizer-pruner',
    name: 'SignalToNoiseMaximizerPrunerSkill',
    displayName: 'Signal-to-Noise Ratio (SNR) Radical Maximizer',
    categoryId: 'core',
    description: 'Ruthlessly eliminates conversational fluff, corporate pleasantries, and redundant filler to deliver concentrated operational value.',
    tags: ['core', 'signal-to-noise', 'brevity', 'high-density', 'editorial'],
    semanticType: 'constraints',
    sectionName: 'Signal-to-Noise Ratio Maximization Protocol',
    ruSectionName: 'Радикальная максимизация соотношения сигнал/шум (SNR)',
    instructionsEn: [
      'Eliminate all conversational throat-clearing: "Sure, I would be happy to help", "As an AI language model", and repetitive boilerplate.',
      'Maximize information density per token: every single sentence must communicate an actionable directive, constraint, or datum.',
      'Format output with scannable headers, precise markdown tables, and unambiguous bulleted invariants.',
    ],
    instructionsRu: [
      'Удаляйте все вежливые вводные слова, клише («конечно, я помогу») и водянистые предисловия.',
      'Максимизируйте плотность пользы на единицу текста: каждое предложение обязано нести действие, факт или ограничение.',
      'Оформляйте материал емкими списками, таблицами и четкими инвариантами для мгновенного сканирования взглядом.',
    ],
  },
  {
    id: 'pre-mortem-fatal-flaw-extraction',
    name: 'PreMortemFatalFlawExtractionSkill',
    displayName: 'Gary Klein Prospective Hindsight Pre-Mortem',
    categoryId: 'core',
    description: 'Assumes the project has already failed catastrophically 12 months in the future, tasking the team with reconstructing why.',
    tags: ['core', 'pre-mortem', 'risk-management', 'gary-klein', 'resilience'],
    semanticType: 'process_directive',
    sectionName: 'Prospective Hindsight Pre-Mortem Protocol',
    ruSectionName: 'Пре-мортем: ретроспектива из будущего провала (Gary Klein)',
    instructionsEn: [
      'Adopt the prospective hindsight mindset: "Imagine today is 1 year from now, and our rollout has suffered an unmitigated, public disaster."',
      'Generate a realistic chronological postmortem detailing the exact sequence of ignored warnings, subtle oversights, and systemic bottlenecks.',
      'Translate every identified historical failure mode into active preventive mitigations in the current rollout specification.',
    ],
    instructionsRu: [
      'Встаньте в позицию будущего: «Представьте, что прошел год, и наш проект потерпел громкую сокрушительную неудачу».',
      'Опишите реалистичную хронологию катастрофы: какие ранние сигналы были проигнорированы и где прорвало оборону.',
      'Преобразуйте каждый выявленный сценарий в действующий превентивный фильтр в текущем плане реализации.',
    ],
  },
];

// 37 skills for reasoning (current 33 -> 70)
const reasoningSkills = [
  {
    id: 'chain-of-verification-cove',
    name: 'ChainOfVerificationCoveSkill',
    displayName: 'Chain-of-Verification (CoVe) Self-Fact-Checking',
    categoryId: 'reasoning',
    description: 'Generates initial baseline answers, derives targeted verification questions, answers them independently, and synthesizes a verified final output.',
    tags: ['reasoning', 'cove', 'fact-checking', 'hallucination-prevention', 'verification'],
    semanticType: 'process_directive',
    sectionName: 'Chain-of-Verification (CoVe) Protocol',
    ruSectionName: 'Протокол цепочки верификации (Chain-of-Verification / CoVe)',
    instructionsEn: [
      'Step 1: Draft initial response to the prompt.',
      'Step 2: Generate 3-5 factual verification questions explicitly checking potential inaccuracies, dates, and logical leaps.',
      'Step 3: Answer each verification question independently, deliberately ignoring initial draft assumptions.',
      'Step 4: Synthesize final output by reconciling discrepancies and correcting all detected contradictions.',
    ],
    instructionsRu: [
      'Шаг 1: Сформируйте первичный черновой ответ на задачу.',
      'Шаг 2: Сгенерируйте 3–5 проверочных вопросов, тестирующих потенциально шаткие даты, факты и формулы черновика.',
      'Шаг 3: Дайте независимые ответы на проверочные вопросы без оглядки на первичный черновик.',
      'Шаг 4: Соберите итоговый проверенный текст, устранив все обнаруженные нестыковки.',
    ],
  },
  {
    id: 'tree-of-thought-bfs-exploration',
    name: 'TreeOfThoughtBfsExplorationSkill',
    displayName: 'Tree-of-Thought (ToT) Breadth-First Exploration',
    categoryId: 'reasoning',
    description: 'Branches thought trajectories across multiple candidates, evaluates states with heuristic scores, and prunes unpromising paths via BFS.',
    tags: ['reasoning', 'tree-of-thought', 'bfs', 'search', 'heuristics'],
    semanticType: 'process_directive',
    sectionName: 'Tree-of-Thought BFS Architecture',
    ruSectionName: 'Поиск по дереву мыслей в ширину (Tree-of-Thought BFS)',
    instructionsEn: [
      'Generate 3 distinct next-step thought branches for each active search horizon.',
      'Assign explicit heuristic scores (1-10) to each candidate state based on feasibility, soundness, and distance to goal.',
      'Retain only the top 2 highest-scoring branches (Beam/BFS width 2) and prune all sub-threshold branches immediately.',
      'Iterate until reaching the terminal goal condition, recording the complete winning reasoning trace.',
    ],
    instructionsRu: [
      'Генерируйте 3 принципиально разных направления мысли на каждом шаге рассуждения.',
      'Присваивайте каждому направлению эвристический балл от 1 до 10 по критериям реалистичности и надежности.',
      'Оставляйте только 2 наиболее перспективные ветки, безжалостно отсекая остальные.',
      'Продолжайте итерации до достижения цели, фиксируя выигрышную цепочку умозаключений.',
    ],
  },
  {
    id: 'self-consistency-majority-voting',
    name: 'SelfConsistencyMajorityVotingSkill',
    displayName: 'Self-Consistency Majority Sampling & Ensemble Voting',
    categoryId: 'reasoning',
    description: 'Samples multiple diverse reasoning chains and aggregates the final conclusion via consensus clustering and majority voting.',
    tags: ['reasoning', 'self-consistency', 'majority-voting', 'ensemble', 'consensus'],
    semanticType: 'process_directive',
    sectionName: 'Self-Consistency Consensus Protocol',
    ruSectionName: 'Самосогласованность и голосование большинством (Self-Consistency)',
    instructionsEn: [
      'Execute 3 independent parallel reasoning paths using varied starting angles and heuristic perspectives.',
      'Extract the terminal answer/verdict from each independent path.',
      'Cluster identical or functionally equivalent conclusions; adopt the verdict supported by the strict mathematical majority.',
      'Document minority dissenting rationale to expose edge-case risks.',
    ],
    instructionsRu: [
      'Проведите 3 независимых цепочки рассуждений под разными углами зрения.',
      'Извлеките финальный вывод и ключевой ответ из каждой отдельной ветки.',
      'Сгруппируйте результаты и примите решение, поддержанное абсолютным большинством путей.',
      'Кратко зафиксируйте аргументы меньшинства для понимания рисков граничных сценариев.',
    ],
  },
  {
    id: 'dialectic-thesis-antithesis-synthesis',
    name: 'DialecticThesisAntithesisSynthesisSkill',
    displayName: 'Hegelian Dialectical Synthesis (Thesis, Antithesis, Synthesis)',
    categoryId: 'reasoning',
    description: 'Resolves systemic paradoxes by formulating a strong Thesis, an uncompromising Antithesis, and an overarching higher-order Synthesis.',
    tags: ['reasoning', 'dialectics', 'hegel', 'synthesis', 'paradox-resolution'],
    semanticType: 'process_directive',
    sectionName: 'Hegelian Dialectical Synthesis Protocol',
    ruSectionName: 'Гегелевская диалектическая триада (Тезис, Антитезис, Синтез)',
    instructionsEn: [
      'Thesis: Formulate the primary proposition with its strongest empirical justifications and structural advantages.',
      'Antithesis: Formulate the direct counter-proposition, exposing fundamental flaws and conflicting real-world constraints.',
      'Synthesis: Create a higher-order paradigm that transcends the apparent contradiction, preserving the core virtues of both while eliminating their mutual conflicts.',
    ],
    instructionsRu: [
      'Тезис: Изложите исходное утверждение с максимальной аргументацией и обоснованием сильных сторон.',
      'Антитезис: Сформулируйте встречное отрицание, вскрывающее фатальные изъяны и противоречия тезиса.',
      'Синтез: Поднимитесь на уровень надсистемы, объединив достоинства обеих сторон и сняв противоречие.',
    ],
  },
  {
    id: 'reductio-ad-absurdum-proof',
    name: 'ReductioAdAbsurdumProofSkill',
    displayName: 'Reductio ad Absurdum Logical Refutation',
    categoryId: 'reasoning',
    description: 'Disproves flawed assertions by assuming them to be true and rigorously demonstrating that they inevitably lead to a glaring contradiction.',
    tags: ['reasoning', 'reductio-ad-absurdum', 'logic', 'refutation', 'proof'],
    semanticType: 'process_directive',
    sectionName: 'Reductio ad Absurdum Refutation Architecture',
    ruSectionName: 'Доказательство от противного (Reductio ad Absurdum)',
    instructionsEn: [
      'Assume the challenged assertion or architecture is 100% correct, valid, and universally applied.',
      'Trace the logical, mathematical, and systemic consequences of that assumption across boundary conditions.',
      'Demonstrate that this trajectory produces an impossible contradiction, physical violation, or catastrophic systemic absurdity.',
      'Conclude that the original assumption is definitively disproven.',
    ],
    instructionsRu: [
      'Допустите, что оспариваемое утверждение или архитектурный выбор на 100% верны.',
      'Логически и математически разверните последствия этого допущения на граничных условиях системы.',
      'Продемонстрируйте, как цепочка выводов приводит к вопиющему противоречию или системному абсурду.',
      'Сделайте математически строгий вывод о ложности исходной предпосылки.',
    ],
  },
  {
    id: 'abductive-inference-best-explanation',
    name: 'AbductiveInferenceBestExplanationSkill',
    displayName: 'Abductive Inference (Inference to Best Explanation)',
    categoryId: 'reasoning',
    description: 'Diagnoses anomalies by generating plausible explanatory hypotheses, scoring explanatory scope, and selecting the most parsimonious cause.',
    tags: ['reasoning', 'abduction', 'inference', 'diagnostics', 'root-cause'],
    semanticType: 'process_directive',
    sectionName: 'Abductive Inference to Best Explanation',
    ruSectionName: 'Абдуктивный вывод к наилучшему объяснению (Abduction)',
    instructionsEn: [
      'Document all surprising anomalous facts and system symptoms with high empirical precision.',
      'Generate an exhaustive candidate set of explanatory hypotheses that could account for the observed anomalies.',
      'Score each candidate on Explanatory Scope (how many anomalies it explains) and Parsimony (absence of convoluted auxiliary assumptions).',
      'Select the candidate providing the cleanest, most comprehensive causal explanation.',
    ],
    instructionsRu: [
      'Зафиксируйте все наблюдаемые аномалии и симптомы с высокой фактологической точностью.',
      'Сформируйте пул гипотез-кандидатов, способных объяснить наблюдаемые отклонения.',
      'Оцените каждую гипотезу по широте охвата фактов и простоте (отсутствию надуманных допущений).',
      'Выберите гипотезу, дающую наиболее стройное и всеобъемлющее причинное объяснение.',
    ],
  },
  {
    id: 'counterfactual-simulation-what-if',
    name: 'CounterfactualSimulationWhatIfSkill',
    displayName: 'Counterfactual Causality & "What If" Simulation',
    categoryId: 'reasoning',
    description: 'Tests causal mechanisms by altering a single historical variable and simulating the divergent alternate timeline.',
    tags: ['reasoning', 'counterfactual', 'simulation', 'causality', 'what-if'],
    semanticType: 'process_directive',
    sectionName: 'Counterfactual Causal Simulation Protocol',
    ruSectionName: 'Контрфактическое моделирование причинности (What-If)',
    instructionsEn: [
      'Isolate the target variable or event under investigation.',
      'Construct a counterfactual state where that variable was inverted or held at baseline while holding all other initial conditions fixed.',
      'Step through the causal graph to observe whether the terminal outcome changes.',
      'Verify whether the target variable was a necessary cause, sufficient cause, or merely a correlated bystander.',
    ],
    instructionsRu: [
      'Изолируйте ключевую исследуемую переменную или решение в истории инцидента.',
      'Смоделируйте альтернативную ветку реальности, где это событие не произошло, зафиксировав остальные условия.',
      'Проследите причинный граф: изменился ли итоговый исход системы в альтернативном сценарии.',
      'Установите статус переменной: являлась ли она необходимой причиной, достаточной или лишь сопутствующим фоном.',
    ],
  },
  {
    id: 'analogical-structural-mapping',
    name: 'AnalogicalStructuralMappingSkill',
    displayName: 'Structure-Mapping Analogical Reasoning',
    categoryId: 'reasoning',
    description: 'Transfers battle-tested solutions from distant mature domains by aligning relational structures rather than surface features.',
    tags: ['reasoning', 'analogies', 'structure-mapping', 'cross-domain', 'innovation'],
    semanticType: 'process_directive',
    sectionName: 'Relational Structure-Mapping Architecture',
    ruSectionName: 'Структурное картирование аналогий (Structure-Mapping)',
    instructionsEn: [
      'Extract the deep relational network of the current problem (e.g. producer-consumer imbalance, thermal throttling) ignoring domain terminology.',
      'Identify a distant, mature discipline (e.g. aerospace avionics, biological immune systems, traffic flow) with an isomorphic relational structure.',
      'Map the mature domain\'s proven solution mechanisms back to the target technical problem.',
      'Stress-test the boundary limits of the analogy to prevent false mapping breakdowns.',
    ],
    instructionsRu: [
      'Извлеките глубинную реляционную структуру проблемы (переполнение буфера, перегрев), отбросив термины текущей предметной области.',
      'Найдите зрелую внешнюю дисциплину (авиация, иммунология, гидродинамика) с изоморфной структурой взаимодействий.',
      'Перенесите отработанные инженерные решения из внешней области на текущую задачу.',
      'Проверьте пределы применимости аналогии, выделив зоны, где сходство перестает работать.',
    ],
  },
  {
    id: 'bayesian-belief-updating-loop',
    name: 'BayesianBeliefUpdatingLoopSkill',
    displayName: 'Bayesian Evidence Likelihood Updating Loop',
    categoryId: 'reasoning',
    description: 'Updates probability estimates dynamically: establishes prior odds, calculates likelihood ratios, and derives posterior probabilities.',
    tags: ['reasoning', 'bayesian', 'probability', 'likelihood-ratio', 'updating'],
    semanticType: 'process_directive',
    sectionName: 'Bayesian Likelihood Updating Protocol',
    ruSectionName: 'Байесовский цикл обновления вероятностей',
    instructionsEn: [
      'Establish explicit Prior Probability P(H) based on historical base rates.',
      'Evaluate incoming evidence: compute Likelihood Ratio P(E|H) / P(E|not-H).',
      'Calculate Posterior Probability P(H|E) using Bayes\' rule: Posterior Odds = Prior Odds x Likelihood Ratio.',
      'Adjust behavioral thresholds only when posterior shifts across predetermined decision gates.',
    ],
    instructionsRu: [
      'Задайте априорную вероятность P(H) на основе объективных базовых частот.',
      'Оцените поступившее свидетельство: вычислите отношение правдоподобия P(E|H) / P(E|не-H).',
      'Рассчитайте апостериорную вероятность P(H|E) по формуле Байеса.',
      'Принимайте решение о действии только при преодолении апостериорной вероятностью целевого порога.',
    ],
  },
  {
    id: 'deductive-syllogism-validator',
    name: 'DeductiveSyllogismValidatorSkill',
    displayName: 'Formal Deductive Syllogism Validation',
    categoryId: 'reasoning',
    description: 'Audits deductive arguments for formal validity: Major Premise, Minor Premise, and Non-Sequitur elimination.',
    tags: ['reasoning', 'deduction', 'syllogism', 'formal-logic', 'soundness'],
    semanticType: 'process_directive',
    sectionName: 'Formal Deductive Syllogism Audit',
    ruSectionName: 'Валидация дедуктивных силлогизмов и проверка логической строгости',
    instructionsEn: [
      'Deconstruct the argument into Major Premise (universal rule), Minor Premise (specific instance), and Conclusion.',
      'Verify Logical Validity: does the conclusion follow inevitably from the premises as a matter of pure logical form?',
      'Verify Soundness: are both the major and minor premises empirically true in the real world?',
      'Flag and eliminate formal fallacies (affirming the consequent, denying the antecedent, undistributed middle).',
    ],
    instructionsRu: [
      'Декомпозируйте аргумент на большую посылку (общее правило), малую посылку (частный факт) и вывод.',
      'Проверьте логическую валидность: следует ли вывод неизбежно из структуры посылок.',
      'Проверьте истинность посылок (Soundness): соответствуют ли обе посылки объективной реальности.',
      'Отсекайте формальные логические ошибки (подтверждение консеквента, отрицание антецедента).',
    ],
  },
  {
    id: 'inductive-generalization-guard',
    name: 'InductiveGeneralizationGuardSkill',
    displayName: 'Inductive Sample Bias & Generalization Guard',
    categoryId: 'reasoning',
    description: 'Guards against hasty inductive generalizations from small, skewed, or unrepresentative sample sizes.',
    tags: ['reasoning', 'induction', 'sample-bias', 'generalization', 'statistics'],
    semanticType: 'constraints',
    sectionName: 'Inductive Generalization Safeguards',
    ruSectionName: 'Защита от поспешных индуктивных обобщений',
    instructionsEn: [
      'Evaluate whether observed patterns reflect statistically adequate sample sizes or anecdotal noise.',
      'Check for sampling bias: did the observed data originate from a self-selected, survivorship-filtered, or non-representative subgroup?',
      'Prohibit universalizing claims ("All users prefer X", "PostgreSQL always outperforms Y") without randomized representative testing.',
    ],
    instructionsRu: [
      'Оценивайте, отражает ли наблюдаемый паттерн статистически достаточную выборку или является шумом.',
      'Проверяйте смещение выборки: не получены ли данные от специфической, самоотобранной группы пользователей.',
      'Запрещайте абсолютные обобщения («все клиенты хотят X», «PostgreSQL всегда быстрее Y») без рандомизированных тестов.',
    ],
  },
  {
    id: 'fermi-estimation-dimensional-breakdown',
    name: 'FermiEstimationDimensionalBreakdownSkill',
    displayName: 'Fermi Estimation & Order-of-Magnitude Bounds',
    categoryId: 'reasoning',
    description: 'Estimates unknown quantities within 1 order of magnitude by dimensional decomposition and geometric mean bounds.',
    tags: ['reasoning', 'fermi-estimation', 'order-of-magnitude', 'dimensional-analysis', 'heuristics'],
    semanticType: 'process_directive',
    sectionName: 'Fermi Order-of-Magnitude Estimation Protocol',
    ruSectionName: 'Оценка порядка величины по методу Ферми (Fermi Estimation)',
    instructionsEn: [
      'Deconstruct an unknown target metric into a chain of 4-6 estimable dimensionally consistent sub-factors.',
      'Assign lower-bound (10th percentile) and upper-bound (90th percentile) estimates to each factor.',
      'Compute the geometric mean of the combined sub-factors to produce an order-of-magnitude projection.',
      'Cross-check the estimated result against physical and economic upper ceilings to ensure sanity.',
    ],
    instructionsRu: [
      'Разложите неизвестную величину на цепочку из 4–6 оцениваемых подфакторов с согласованными размерностями.',
      'Задайте консервативную нижнюю (10%) и верхнюю (90%) границы для каждого подфактора.',
      'Рассчитайте среднее геометрическое произведения факторов для получения оценки порядка величины.',
      'Сопоставьте результат с физическими и макроэкономическими потолками здравого смысла.',
    ],
  },
  {
    id: 'toulmin-argumentation-model',
    name: 'ToulminArgumentationModelSkill',
    displayName: 'Toulmin Argumentation Model (Claim, Data, Warrant, Rebuttal)',
    categoryId: 'reasoning',
    description: 'Structures bulletproof arguments across 6 Toulmin components: Claim, Data, Warrant, Backing, Qualifier, and Rebuttal.',
    tags: ['reasoning', 'toulmin', 'argumentation', 'logic', 'persuasion'],
    semanticType: 'structural_directive',
    sectionName: 'Toulmin Argumentation Architecture',
    ruSectionName: 'Модель аргументации Тулмина (Claim, Data, Warrant, Rebuttal)',
    instructionsEn: [
      'Claim: Explicitly state the thesis or recommendation.',
      'Data / Grounds: Provide verified empirical evidence supporting the claim.',
      'Warrant & Backing: Explain the underlying logical rule connecting the data to the claim, backed by authoritative principles.',
      'Qualifier & Rebuttal: State degree of certainty (e.g. "presumably", "under condition X") and address explicit conditions that invalidate the claim.',
    ],
    instructionsRu: [
      'Тезис (Claim): Сформулируйте четкое и недвусмысленное предложение или вывод.',
      'Данные (Data): Приведите проверенные фактические доказательства в поддержку тезиса.',
      'Основание и поддержка (Warrant & Backing): Изложите логический закон, связывающий данные с тезисом, и его авторитетное обоснование.',
      'Квалификатор и оговорка (Qualifier & Rebuttal): Задайте степень уверенности и явно укажите условия, при которых аргумент теряет силу.',
    ],
  },
  {
    id: 'root-cause-ishikawa-fishbone',
    name: 'RootCauseIshikawaFishboneSkill',
    displayName: 'Ishikawa Fishbone Root-Cause Diagramming',
    categoryId: 'reasoning',
    description: 'Categorizes systemic failure modes across 6 standard branches: Machine, Method, Material, Manpower, Measurement, Environment.',
    tags: ['reasoning', 'ishikawa', 'fishbone', 'root-cause', 'quality-engineering'],
    semanticType: 'structural_directive',
    sectionName: 'Ishikawa Fishbone Diagnostic Architecture',
    ruSectionName: 'Причинно-следственная диаграмма Исикавы (Fishbone Diagram)',
    instructionsEn: [
      'Place the central failure symptom at the head of the diagram.',
      'Branch analysis across the 6 Ms: Machine (hardware/cloud), Method (processes/CI/CD), Material (data/dependencies), Manpower (training/fatigue), Measurement (metrics/alerts), and Milieu (environment/network).',
      'Drill down 2 levels deep into each branch to isolate contributing latent factors.',
      'Highlight intersectional vulnerabilities where multiple branches compound into catastrophic failure.',
    ],
    instructionsRu: [
      'Поместите главный сбой системы в «голову» диаграммы.',
      'Распределите причины по 6 веткам: Машины (серверы/облако), Методы (процессы/деплой), Материалы (данные/библиотеки), Люди (усталость/компетенции), Измерения (метрики/алерты), Окружение (сеть/нагрузка).',
      'Углубитесь минимум на 2 уровня детализации внутри каждой ветви.',
      'Выделите перекрестные уязвимости, где наложение факторов разных веток привело к сбою.',
    ],
  },
  {
    id: 'game-theory-nash-equilibrium-model',
    name: 'GameTheoryNashEquilibriumModelSkill',
    displayName: 'Game-Theoretic Nash Equilibrium Payoff Matrix',
    categoryId: 'reasoning',
    description: 'Models multi-agent strategic dynamics: builds payoff matrices, identifies dominant strategies, and finds stable Nash equilibria.',
    tags: ['reasoning', 'game-theory', 'nash-equilibrium', 'incentives', 'strategy'],
    semanticType: 'process_directive',
    sectionName: 'Game-Theoretic Payoff & Equilibrium Protocol',
    ruSectionName: 'Теоретико-игровая матрица выигрышей и равновесие Нэша',
    instructionsEn: [
      'Construct a 2x2 or NxN payoff matrix explicitly defining all players, discrete action sets, and utility scores.',
      'Identify strictly dominant and weakly dominant strategies for each participant.',
      'Solve for Nash Equilibria: determine states where no player can unilaterally deviate to improve their individual payoff.',
      'Analyze whether the equilibrium represents a Pareto-optimal social outcome or a Prisoner\'s Dilemma trap.',
    ],
    instructionsRu: [
      'Постройте матрицу выигрышей с указанием игроков, доступных стратегий и числовых оценок полезности.',
      'Определите доминантные стратегии для каждого участника взаимодействия.',
      'Найдите равновесие по Нэшу — состояние, при котором ни один игрок не может в одностороннем порядке улучшить свое положение.',
      'Проверьте, является ли найденное равновесие Парето-оптимальным или ловушкой типа «дилеммы заключенного».',
    ],
  },
  {
    id: 'first-principles-physics-breakdown',
    name: 'FirstPrinciplesPhysicsBreakdownSkill',
    displayName: 'Axiomatic First-Principles Physics Decomposition',
    categoryId: 'reasoning',
    description: 'Deconstructs problems down to undeniable physical, thermodynamic, and mathematical constants, reconstructing novel solutions from scratch.',
    tags: ['reasoning', 'first-principles', 'physics', 'axioms', 'innovation'],
    semanticType: 'process_directive',
    sectionName: 'Axiomatic First-Principles Protocol',
    ruSectionName: 'Декомпозиция на фундаментальные физические принципы',
    instructionsEn: [
      'Strip away all analogies, incumbent vendor architectures, and "industry standard practice" claims.',
      'Deconstruct the problem down to fundamental physical constants: conservation of energy, latency limits (speed of light in fiber), memory bandwidth, and raw component cost.',
      'Rebuild the architecture upward strictly from those irreducible physical truths.',
      'Highlight where conventional industry architectures introduce artificial 10x inefficiency markups.',
    ],
    instructionsRu: [
      'Отбросьте аналогии, устоявшиеся шаблоны вендоров и догмы «так принято в индустрии».',
      'Разложите проблему на базовые физические инварианты: предел скорости света в оптоволокне, пропускная способность шины памяти, сырьевая себестоимость.',
      'Соберите решение снизу вверх, опираясь строго на фундаментальные законы природы.',
      'Покажите, где стандартные решения индустрии создают многократные искусственные накладные расходы.',
    ],
  },
  {
    id: 'trilemma-cap-theorem-tradeoff-solver',
    name: 'TrilemmaCapTheoremTradeoffSolverSkill',
    displayName: 'Trilemma & Impossible Trinity Trade-Off Resolution',
    categoryId: 'reasoning',
    description: 'Navigates fundamental trilemmas (CAP theorem, Blockchain trilemma, Project Management iron triangle) by explicitly sacrificing one dimension.',
    tags: ['reasoning', 'trilemma', 'cap-theorem', 'trade-offs', 'architecture'],
    semanticType: 'process_directive',
    sectionName: 'Trilemma Structural Trade-Off Protocol',
    ruSectionName: 'Разрешение трилемм и несовместимых троек (CAP / Iron Triangle)',
    instructionsEn: [
      'Identify the fundamental trilemma: Consistency vs Availability vs Partition Tolerance (CAP), or Fast vs Cheap vs Good.',
      'Explicitly reject naive claims that all three dimensions can be simultaneously maximized.',
      'Make a conscious, mathematically justified sacrifice of one dimension based on core operational SLA priorities.',
      'Document fallback degraded states during partition or resource-starvation events.',
    ],
    instructionsRu: [
      'Зафиксируйте базовую трилемму системы: CAP (согласованность, доступность, устойчивость к разделению) или Быстро/Дешево/Качественно.',
      'Отклоняйте наивные попытки заявить одновременную максимизацию всех трех взаимоисключающих полюсов.',
      'Сделайте осознанный инженерный выбор, каким из параметров система жертвует ради приоритетных SLA.',
      'Опишите работу системы в режиме деградации при сетевом разделении или дефиците ресурсов.',
    ],
  },
  {
    id: 'inductive-risk-hempel-rudner',
    name: 'InductiveRiskHempelRudnerSkill',
    displayName: 'Inductive Risk & Non-Epistemic Value Calibration',
    categoryId: 'reasoning',
    description: 'Calibrates evidential thresholds based on the ethical and financial consequences of Type I (false positive) vs Type II (false negative) errors.',
    tags: ['reasoning', 'inductive-risk', 'values', 'error-calibration', 'ethics'],
    semanticType: 'process_directive',
    sectionName: 'Inductive Risk & Error Asymmetry Calibration',
    ruSectionName: 'Калибровка индуктивного риска (ошибки I vs II рода)',
    instructionsEn: [
      'Compare the real-world blast radius of False Positives (Type I: false alarm, unnecessary shutdown) vs False Negatives (Type II: missed intrusion, undetected defect).',
      'Calibrate evidential threshold: demand higher statistical confidence (alpha = 0.001) when False Positives carry catastrophic cost.',
      'Explicitly articulate the non-epistemic business and safety values governing the selected decision threshold.',
    ],
    instructionsRu: [
      'Сопоставьте цену ошибки I рода (ложная тревога, ненужная остановка) и ошибки II рода (пропущенный взлом, нераспознанный дефект).',
      'Отрегулируйте порог принятия решения: требуйте сверхвысокой строгости данных, если ложное срабатывание несет катастрофический ущерб.',
      'Открыто декларируйте бизнес-приоритеты и ценности безопасности, обусловившие выбранный уровень строгости.',
    ],
  },
  {
    id: 'morphological-analysis-zwicky-box',
    name: 'MorphologicalAnalysisZwickyBoxSkill',
    displayName: 'Fritz Zwicky Morphological Box Combinatorics',
    categoryId: 'reasoning',
    description: 'Explores multi-dimensional solution spaces by decomposing parameters into exhaustive matrices and evaluating novel combinatorial paths.',
    tags: ['reasoning', 'morphological-analysis', 'zwicky', 'combinatorics', 'design-space'],
    semanticType: 'structural_directive',
    sectionName: 'Zwicky Morphological Box Architecture',
    ruSectionName: 'Морфологический анализ по ящику Цвикки (Morphological Box)',
    instructionsEn: [
      'Identify 4-6 essential orthogonal dimensions of the problem (e.g. Storage, Ingestion Protocol, Consensus, Cache Invalidation).',
      'List 3-5 distinct technological options for each dimension in a multidimensional matrix.',
      'Systematically construct combinatorial configurations, specifically evaluating unconventional pairings rejected by standard convention.',
      'Filter out mutually incompatible combinations to reveal breakthrough viable configurations.',
    ],
    instructionsRu: [
      'Выделите 4–6 ортогональных параметров задачи (хранилище, протокол ingestion, алгоритм консенсуса, инвалидация кэша).',
      'Заполните матрицу 3–5 альтернативными технологическими вариантами по каждому параметру.',
      'Системно синтезируйте комбинации вариантов, особое внимание уделяя нестандартным сочетаниям.',
      'Отсейте физически несовместимые связки, выявив прорывные жизнеспособные конфигурации.',
    ],
  },
  {
    id: 'causal-loop-diagramming-feedback-delays',
    name: 'CausalLoopDiagrammingFeedbackDelaysSkill',
    displayName: 'Causal Loop Diagramming (CLD) & System Dynamics',
    categoryId: 'reasoning',
    description: 'Maps reinforcing (R) and balancing (B) feedback loops with explicit delay markers to expose systemic oscillation traps.',
    tags: ['reasoning', 'cld', 'system-dynamics', 'feedback-loops', 'oscillation'],
    semanticType: 'structural_directive',
    sectionName: 'Causal Loop Diagramming & System Dynamics',
    ruSectionName: 'Диаграммы причинных циклов и системная динамика (CLD)',
    instructionsEn: [
      'Map system variables with directed causal arrows labeled with polarity (+ for same direction, - for opposite direction).',
      'Identify Reinforcing loops (R, exponential growth/collapse) and Balancing loops (B, goal-seeking stability).',
      'Mark explicit temporal delays (|| symbol); explain how unaddressed delays cause violent system oscillation and over-correction.',
      'Locate high-leverage policy intervention points that flip reinforcing doom loops into virtuous cycles.',
    ],
    instructionsRu: [
      'Соединяйте переменные системы направленными стрелками с указанием знака влияния (+ прямое, - обратное).',
      'Маркируйте усиливающие петли (R, экспоненциальный рост/спад) и балансирующие (B, стабилизация к цели).',
      'Обозначайте временные задержки (символ ||); показывайте, как неучтенные задержки вызывают разрушительные автоколебания системы.',
      'Находите точки максимального рычага, превращающие порочные круги деградации в циклы развития.',
    ],
  },
];

console.log('Appending Core skills...');
appendSkillsToCategory('core', coreSkills);

console.log('Appending Reasoning skills...');
appendSkillsToCategory('reasoning', reasoningSkills);
