const { appendSkillsToCategory } = require('./appendSkills.cjs');

const analysisNew = [
  {
    id: 'cyclomatic-complexity-mccabe-audit',
    name: 'CyclomaticComplexityMccabeAuditSkill',
    displayName: 'McCabe Cyclomatic Complexity Metric Audit',
    categoryId: 'analysis',
    description: 'Calculates McCabe cyclomatic complexity M = E - N + 2P across control-flow graphs, flagging functions with M > 10 for refactoring.',
    tags: ['analysis', 'cyclomatic-complexity', 'mccabe', 'code-metrics', 'refactoring'],
    semanticType: 'process_directive',
    sectionName: 'McCabe Cyclomatic Complexity Audit Protocol',
    ruSectionName: 'Аудит цикломатической сложности Маккейба (M = E - N + 2P)',
    instructionsEn: [
      'Construct control-flow graphs for critical procedures and count decision points (if, while, for, case, catch, &&, ||).',
      'Compute cyclomatic complexity M; enforce hard ceiling of M <= 10 for standard modules and M <= 15 for complex state machines.',
      'Refactor high-complexity functions using extract-method, strategy patterns, or lookup tables.',
      'Require 100% branch test coverage matching the calculated linearly independent path count.',
    ],
    instructionsRu: [
      'Постройте граф потока управления и подсчитайте число точек ветвления (if, while, for, case, catch, &&, ||).',
      'Рассчитайте цикломатическую сложность M; требуйте удержания M <= 10 для стандартных функций.',
      'Декомпозируйте функции с M > 10 через выделение методов, паттерн Strategy или таблицы переходов.',
      'Обеспечьте 100% покрытие тестами всех линейно независимых путей выполнения.',
    ],
  },
  {
    id: 'halstead-software-science-metrics',
    name: 'HalsteadSoftwareScienceMetricsSkill',
    displayName: 'Halstead Complexity & Cognitive Volume Metrics',
    categoryId: 'analysis',
    description: 'Measures distinct operators and operands to calculate Halstead Program Length, Volume, Difficulty, and Estimated Bugs.',
    tags: ['analysis', 'halstead', 'software-metrics', 'cognitive-volume', 'effort'],
    semanticType: 'process_directive',
    sectionName: 'Halstead Software Science Measurement Protocol',
    ruSectionName: 'Метрики программной сложности Холстеда (Halstead Metrics)',
    instructionsEn: [
      'Count distinct operators (n1), distinct operands (n2), total operators (N1), and total operands (N2).',
      'Calculate Program Vocabulary n = n1 + n2, Length N = N1 + N2, and Program Volume V = N * log2(n).',
      'Compute Difficulty D = (n1 / 2) * (N2 / n2) and Effort E = D * V to evaluate maintenance burden.',
      'Estimate latent defect count B = V / 3000 to allocate targeted code-review focus.',
    ],
    instructionsRu: [
      'Подсчитайте число уникальных операторов (n1), операндов (n2) и их суммарные вхождения (N1, N2).',
      'Рассчитайте словарь программы n = n1 + n2, длину N = N1 + N2 и когнитивный объем V = N * log2(n).',
      'Оцените сложность понимания D и трудоемкость поддержки E = D * V.',
      'Рассчитайте ожидаемое число дефектов B = V / 3000 для приоритезации ревью.',
    ],
  },
  {
    id: 'chappatte-defect-latency-window',
    name: 'ChappatteDefectLatencyWindowSkill',
    displayName: 'Defect Latency Window & Escaped Bug Audit',
    categoryId: 'analysis',
    description: 'Tracks time lag between bug introduction and production detection, pinpointing QA and CI feedback loop failures.',
    tags: ['analysis', 'defect-latency', 'qa', 'escaped-defects', 'ci-cd'],
    semanticType: 'process_directive',
    sectionName: 'Defect Latency & Escaped Bug Analysis Protocol',
    ruSectionName: 'Анализ задержки обнаружения дефектов (Defect Latency Window)',
    instructionsEn: [
      'Calculate Defect Latency: timestamp difference between original committing git sha and production bug report.',
      'Categorize escape points: Unit test gap, Integration gap, Staging discrepancy, or Observability blind spot.',
      'Mandate that every escaped bug postmortem produce at least one automated test reproducing the defect in pre-merge CI.',
      'Track trend lines of Mean Time to Detect (MTTD) across engineering squads.',
    ],
    instructionsRu: [
      'Измеряйте задержку обнаружения: разницу во времени между коммитом бага и сообщением об аварии в проде.',
      'Классифицируйте точку пропуска: пробел unit-тестов, интеграционный стык или расхождение сред.',
      'Обязывайте по каждому пропущенному багу добавлять регрессионный тест в pre-merge пайплайн.',
      'Отслеживайте динамику среднего времени обнаружения (MTTD) по подсистемам.',
    ],
  },
  {
    id: 'chaos-mesh-blast-radius-partition',
    name: 'ChaosMeshBlastRadiusPartitionSkill',
    displayName: 'Chaos Mesh Network Partition Failure Matrix',
    categoryId: 'analysis',
    description: 'Simulates Kubernetes pod-to-pod network drops, asymmetric packet delays, and split-brain DNS blackholes.',
    tags: ['analysis', 'chaos-mesh', 'fault-injection', 'network-partition', 'resilience'],
    semanticType: 'process_directive',
    sectionName: 'Chaos Mesh Fault Injection & Partition Matrix',
    ruSectionName: 'Матрица сетевых разделений и сбоев (Chaos Mesh)',
    instructionsEn: [
      'Inject synthetic network partition scenarios: isolate leader nodes from followers in distributed state stores.',
      'Verify that consensus systems (Raft/Paxos) gracefully halt writes rather than accepting split-brain mutations.',
      'Introduce asymmetric latency (e.g. 500ms delay in one direction) to test timeout and circuit breaker coordination.',
      'Confirm automated self-healing and data reconciliation upon partition healing.',
    ],
    instructionsRu: [
      'Имитируйте сетевое разделение (network partition) между лидером и репликами в распределенных базах.',
      'Проверяйте, что система консенсуса останавливает запись при потере кворума, исключая рассинхронизацию (split-brain).',
      'Внедряйте асимметричные задержки трафика (500 мс в одну сторону) для стресс-теста таймаутов.',
      'Контролируйте автоматическое восстановление связности и синхронизацию данных после снятия сбоя.',
    ],
  },
  {
    id: 'flaky-test-quarantine-entropy-audit',
    name: 'FlakyTestQuarantineEntropyAuditSkill',
    displayName: 'Flaky Test Quarantine & Non-Determinism Entropy Audit',
    categoryId: 'analysis',
    description: 'Detects non-deterministic test failures caused by async race conditions, wall-clock coupling, or shared test state.',
    tags: ['analysis', 'flaky-tests', 'ci-cd', 'testing', 'determinism'],
    semanticType: 'process_directive',
    sectionName: 'Flaky Test Quarantine & Root-Cause Protocol',
    ruSectionName: 'Карантин и аудит недетерминированных тестов (Flaky Tests)',
    instructionsEn: [
      'Run suspect test suites 50 times in randomized order to compute empirical failure variance.',
      'Isolate top flakiness triggers: non-mocked `Date.now()`, unawaited asynchronous promises, and shared database state.',
      'Automatically quarantine flaky tests into an isolated non-blocking CI pipeline while alerting owners.',
      'Require deterministic mocking of clocks, virtual timers, and isolated database schemas before de-quarantining.',
    ],
    instructionsRu: [
      'Запускайте подозрительный набор тестов 50 раз со случайным порядком выполнения для выявления нестабильности.',
      'Локализуйте причины: немокированное системное время (`Date.now()`), гонки промисов, общая база данных.',
      'Изолируйте флакающие тесты в отдельный неблокирующий пайплайн с оповещением авторов.',
      'Требуйте использования виртуального времени, явных ожиданий и очистки тестовых баз перед возвратом из карантина.',
    ],
  },
  {
    id: 'strangler-fig-migration-progress-audit',
    name: 'StranglerFigMigrationProgressAuditSkill',
    displayName: 'Strangler Fig Migration & Cutover Progress Audit',
    categoryId: 'analysis',
    description: 'Tracks incremental monolith-to-microservice migration: proxy route cutovers, data sync lag, and legacy surface retirement.',
    tags: ['analysis', 'strangler-fig', 'migration', 'architecture', 'legacy-modernization'],
    semanticType: 'process_directive',
    sectionName: 'Strangler Fig Migration Verification Protocol',
    ruSectionName: 'Аудит миграции методом удушения монолита (Strangler Fig)',
    instructionsEn: [
      'Map monolith endpoints to target modern microservice replacements via an API Gateway / Ingress router.',
      'Track percentage of production traffic shifted: 1% canary -> 10% dark traffic -> 50% dual-run -> 100% cutover.',
      'Execute shadow verification: mirror live requests to both legacy and new services, comparing responses for diff discrepancies.',
      'Formally deprecate and physically delete retired monolith code paths to prevent ghost maintenance overhead.',
    ],
    instructionsRu: [
      'Свяжите эндпоинты монолита с новыми микросервисами через проксирующий шлюз (API Gateway).',
      'Отслеживайте прогресс переключения трафика: 1% канарейка -> 10% теневой трафик -> 50% дублирующий прогон -> 100% релиз.',
      'Проводите теневую сверку (shadow traffic): дублируйте боевые запросы в обе системы и сравнивайте ответы.',
      'Физически удаляйте старый код монолита после переключения трафика, исключая фантомный техдолг.',
    ],
  },
  {
    id: 'cache-stampede-probabilistic-xfetch-audit',
    name: 'CacheStampedeProbabilisticXfetchAuditSkill',
    displayName: 'Cache Stampede XFetch Probabilistic Early Refresh',
    categoryId: 'analysis',
    description: 'Audits hot key caching under high concurrent read loads, applying the XFetch algorithm to eliminate thundering herd stampedes.',
    tags: ['analysis', 'cache-stampede', 'xfetch', 'redis', 'concurrency'],
    semanticType: 'process_directive',
    sectionName: 'Cache Stampede & XFetch Probabilistic Audit',
    ruSectionName: 'Защита от лавины кэша (Cache Stampede / XFetch Algorithm)',
    instructionsEn: [
      'Identify critical cache keys experiencing read concurrency >1,000 QPS with computation duration >100ms.',
      'Implement the probabilistic XFetch algorithm: refresh cache asynchronously before hard expiry when `delta * beta * log(random()) > (expiry - now)`.',
      'Complement with distributed mutex locking on cache misses ensuring only a single worker recomputes backend data.',
      'Verify that database read spikes during key expiry remain strictly zero.',
    ],
    instructionsRu: [
      'Выявляйте горячие ключи кэша с нагрузкой >1000 RPS и длительностью генерации ответа >100 мс.',
      'Внедряйте алгоритм вероятностного обновления XFetch для асинхронного фонового пересчета до наступления TTL.',
      'Дополняйте распределенной мьютекс-блокировкой на случай холодного старта, допуская к БД ровно один поток.',
      'Контролируйте отсутствие всплесков нагрузки на базу данных в моменты планового сброса кэша.',
    ],
  },
  {
    id: 'db-connection-pool-sizing-amdahls-law',
    name: 'DbConnectionPoolSizingAmdahlsLawSkill',
    displayName: 'HikariCP Database Connection Pool Sizing & Wait Ratio',
    categoryId: 'analysis',
    description: 'Calculates optimal DB pool sizing using `connections = (cores * 2) + disk_spindle_count` to eliminate queue saturation.',
    tags: ['analysis', 'connection-pool', 'hikaricp', 'database', 'performance'],
    semanticType: 'process_directive',
    sectionName: 'Database Connection Pool Optimization Protocol',
    ruSectionName: 'Расчет пула соединений БД (HikariCP / Amdahl\'s Law)',
    instructionsEn: [
      'Eliminate oversized pools: prove why 1,000 connections cause CPU thrashing and context-switch degradation on a 16-core database.',
      'Apply standard hardware sizing formula: `connections = (cpu_cores * 2) + effective_spindle_count`.',
      'Monitor pool acquisition latency metrics: alert when pool wait time exceeds 10ms.',
      'Configure aggressive leak detection thresholds and connection timeout limits.',
    ],
    instructionsRu: [
      'Устраняйте завышенные размеры пулов: покажите, почему 1000 коннектов убивают 16-ядерную БД переключением контекстов.',
      'Применяйте стандартную формулу калибровки: `число_коннектов = (ядра_CPU * 2) + дисковые_шпиндели`.',
      'Мониторьте задержку захвата коннекта из пула: поднимайте алерт при ожидании более 10 мс.',
      'Настраивайте детекцию утечек коннектов (leak detection) и жесткий таймаут ожидания соединения.',
    ],
  },
  {
    id: 'api-rate-limit-token-bucket-capacity',
    name: 'ApiRateLimitTokenBucketCapacitySkill',
    displayName: 'Token Bucket & Leaky Bucket API Rate Limit Calibration',
    categoryId: 'analysis',
    description: 'Calculates token refill rates, burst capacity buffers, and sliding window counters to protect backend APIs from overload.',
    tags: ['analysis', 'rate-limiting', 'token-bucket', 'api-gateway', 'dos-protection'],
    semanticType: 'process_directive',
    sectionName: 'API Rate Limiting & Token Bucket Calibration',
    ruSectionName: 'Калибровка лимитов запросов API (Token Bucket / Sliding Window)',
    instructionsEn: [
      'Select rate limiting algorithm: Token Bucket (supports bursts), Leaky Bucket (smooth pacing), or Sliding Window Counter.',
      'Define burst capacity and continuous refill rate per tenant tier (free vs enterprise).',
      'Emit standard HTTP headers on every response: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and `Retry-After`.',
      'Verify graceful HTTP 429 response handling without backend connection exhaustion.',
    ],
    instructionsRu: [
      'Подбирайте алгоритм ограничения: Token Bucket (допускает пиковые всплески), Leaky Bucket (сглаживание) или Sliding Window.',
      'Задавайте емкость ведра и скорость пополнения токенов по тарифным планам (бесплатный vs Enterprise).',
      'Возвращайте стандартные заголовки: `X-RateLimit-Limit`, `X-RateLimit-Remaining` и `Retry-After` при превышении.',
      'Контролируйте выдачу статуса 429 Too Many Requests без расходования ресурсов внутренних сервисов.',
    ],
  },
  {
    id: 'sla-sli-slo-error-budget-burn-rate',
    name: 'SlaSliSloErrorBudgetBurnRateSkill',
    displayName: 'Multi-Window Multi-Burn-Rate SLO Alerting',
    categoryId: 'analysis',
    description: 'Implements Google SRE multi-window burn rate alerts (14.4x for 1h, 6x for 6h) to eliminate alert fatigue while catching outages.',
    tags: ['analysis', 'sre', 'slo', 'sli', 'error-budget', 'burn-rate'],
    semanticType: 'process_directive',
    sectionName: 'Error Budget Multi-Burn-Rate Alerting Architecture',
    ruSectionName: 'Алертинг по скорости расхода бюджета ошибок (Error Budget Burn Rate)',
    instructionsEn: [
      'Define quantitative SLI: ratio of successful fast requests to total valid requests over a rolling 30-day window.',
      'Set target SLO (e.g. 99.9%) and determine Error Budget (0.1% = 43 minutes of total downtime per month).',
      'Implement multi-window alerts: Page on-call only when 1-hour burn rate > 14.4x (2% budget consumed in 1 hour).',
      'Create ticket alerts for slow 3-day burn rates (>1x) without paging engineers at night.',
    ],
    instructionsRu: [
      'Определите SLI: долю быстрых успешных запросов к общему числу за 30-дневное скользящее окно.',
      'Задайте целевой SLO (99.9%) и рассчитайте бюджет ошибок (0.1% = 43 минуты простоя в месяц).',
      'Настройте пейджерный алерт только при скорости сгорания бюджета > 14.4x за 1 час (тратится 2% бюджета за час).',
      'Медленные утечки бюджета (1x за 3 дня) направляйте в тикеты в рабочее время без ночных звонков.',
    ],
  },
  {
    id: 'canary-statistical-mann-whitney-u-test',
    name: 'CanaryStatisticalMannWhitneyUTestSkill',
    displayName: 'Canary Analysis via Mann-Whitney U-Test',
    categoryId: 'analysis',
    description: 'Applies non-parametric statistical Mann-Whitney U testing to compare canary vs baseline latency and error distributions.',
    tags: ['analysis', 'canary', 'mann-whitney', 'ab-testing', 'statistics'],
    semanticType: 'process_directive',
    sectionName: 'Canary Non-Parametric Hypothesis Testing Protocol',
    ruSectionName: 'Статистический анализ канареечного релиза (Критерий Манна-Уитни)',
    instructionsEn: [
      'Collect raw latency and error distributions from twin baseline and canary deployment cohorts.',
      'Reject naive mean comparison: apply non-parametric Mann-Whitney U-test to handle skewed, multi-modal latency curves.',
      'Compute p-value against null hypothesis that canary performance is identical to baseline; set alpha = 0.01.',
      'Trigger automatic canary rollback if p-value demonstrates statistically significant performance regression.',
    ],
    instructionsRu: [
      'Соберите замеры задержки и ошибок с контрольной (baseline) и канареечной (canary) групп подов.',
      'Откажитесь от сравнения средних: примените непараметрический U-критерий Манна-Уитни для мультимодальных распределений.',
      'Рассчитайте p-значение против нулевой гипотезы об идентичности выборок с порогом альфа = 0.01.',
      'Запускайте автоматический откат релиза при обнаружении статистически значимой деградации метрик.',
    ],
  },
  {
    id: 'circuit-breaker-hysteresis-state-machine',
    name: 'CircuitBreakerHysteresisStateMachineSkill',
    displayName: 'Circuit Breaker State Machine & Exponential Recovery',
    categoryId: 'analysis',
    description: 'Designs Closed, Open, and Half-Open circuit breaker state machines with failure rate thresholds and gradual traffic probing.',
    tags: ['analysis', 'circuit-breaker', 'resilience', 'state-machine', 'distributed-systems'],
    semanticType: 'structural_directive',
    sectionName: 'Circuit Breaker Hysteresis State Machine Protocol',
    ruSectionName: 'Конечный автомат предохранителя с гистерезисом (Circuit Breaker)',
    instructionsEn: [
      'Model the 3 canonical states: Closed (normal traffic), Open (fast-fail without calling downstream), and Half-Open (trial probing).',
      'Trip from Closed to Open when error rate exceeds threshold (e.g. >50% failures over 10-second rolling window).',
      'Transition to Half-Open after sleep window (e.g. 30 seconds), permitting exactly 5% trial requests.',
      'Return to Closed if all trial requests succeed; reset sleep window with exponential backoff if any trial request fails.',
    ],
    instructionsRu: [
      'Моделируйте 3 состояния: Closed (норма), Open (мгновенный сброс без вызова), Half-Open (пробный зонд).',
      'Переходите в Open при превышении порога ошибок (более 50% сбоев за 10-секундное окно).',
      'Переходите в Half-Open по истечении тайм-аута (30 сек), допуская ровно 5% пробных запросов.',
      'Возвращайтесь в Closed при успехе всех пробных запросов; удваивайте паузу при повторном сбое.',
    ],
  },
  {
    id: 'distributed-tracing-critical-path-analysis',
    name: 'DistributedTracingCriticalPathAnalysisSkill',
    displayName: 'Distributed Trace Critical Path & Longest Sub-Span Analysis',
    categoryId: 'analysis',
    description: 'Extracts the true critical latency path across asynchronous microservice trace trees, identifying serial blocker spans.',
    tags: ['analysis', 'distributed-tracing', 'critical-path', 'opentelemetry', 'latency'],
    semanticType: 'process_directive',
    sectionName: 'Distributed Trace Critical Path Extraction Protocol',
    ruSectionName: 'Анализ критического пути в распределенном трейсинге (Critical Path)',
    instructionsEn: [
      'Ingest complete trace span DAGs representing a single end-to-end user transaction.',
      'Differentiate concurrent asynchronous branches from serial blocking dependencies.',
      'Compute the mathematical Critical Path: the contiguous sequence of dependent spans that dictates total duration.',
      'Focus optimization exclusively on spans lying on the critical path; ignore non-critical parallel spans.',
    ],
    instructionsRu: [
      'Загрузите полный граф спанов трейса пользовательской транзакции из OpenTelemetry/Jaeger.',
      'Разделите параллельные асинхронные вызовы и блокирующие синхронные зависимости.',
      'Вычислите критический путь: непрерывную цепочку зависимых спанов, определяющую итоговое время ответа.',
      'Фокусируйте оптимизацию строго на спанах критического пути, игнорируя фоновые параллельные ветки.',
    ],
  },
  {
    id: 'dns-propagation-ttl-resolution-audit',
    name: 'DnsPropagationTtlResolutionAuditSkill',
    displayName: 'DNS Propagation, Resolver Caching & Negative TTL Audit',
    categoryId: 'analysis',
    description: 'Diagnoses domain migration and failover failures caused by lingering recursive DNS resolver caches and negative SOA TTLs.',
    tags: ['analysis', 'dns', 'ttl', 'networking', 'failover'],
    semanticType: 'process_directive',
    sectionName: 'DNS Resolution & Propagation Verification Protocol',
    ruSectionName: 'Аудит DNS-резолвинга, TTL и кэширования отрицательных ответов',
    instructionsEn: [
      'Pre-migration planning: lower DNS Record TTL to 60 seconds at least 48 hours prior to planned IP cutover.',
      'Audit SOA negative caching TTL: verify that failed NXDOMAIN queries do not get cached for hours across global ISPs.',
      'Detect internal application JVM DNS caching defaults (`networkaddress.cache.ttl = -1` forever) and override to 30 seconds.',
      'Verify dual-stack IPv4 (A) and IPv6 (AAAA) record alignment across all authoritative nameservers.',
    ],
    instructionsRu: [
      'Планирование миграции: снижайте TTL DNS-записей до 60 секунд минимум за 48 часов до переключения IP.',
      'Проверяйте параметр отрицательного кэширования SOA: исключите кэширование ошибок NXDOMAIN на часы у провайдеров.',
      'Устраняйте вечный кэш DNS в JVM (`networkaddress.cache.ttl = -1`), выставляя принудительный таймаут 30 секунд.',
      'Контролируйте синхронность записей IPv4 (A) и IPv6 (AAAA) на всех авторитетных DNS-серверах.',
    ],
  },
  {
    id: 'log-entropy-anomaly-detection',
    name: 'LogEntropyAnomalyDetectionSkill',
    displayName: 'Log Information Entropy & Shannon Anomaly Detection',
    categoryId: 'analysis',
    description: 'Computes Shannon information entropy over log streams to detect silent zero-day failures and novel unclassified error spikes.',
    tags: ['analysis', 'log-entropy', 'shannon-entropy', 'anomaly-detection', 'observability'],
    semanticType: 'process_directive',
    sectionName: 'Log Shannon Entropy Anomaly Detection Protocol',
    ruSectionName: 'Детекция аномалий по информационной энтропии логов (Шеннон)',
    instructionsEn: [
      'Tokenize incoming structured log messages into template clusters, stripping dynamic IDs and timestamps.',
      'Compute Shannon Entropy H(X) = -sum(p(x) * log2(p(x))) across log template frequency distributions in 5-minute windows.',
      'Trigger security and operational anomaly alerts on sudden entropy drops (repetitive failure storms) or entropy surges (chaotic crashes).',
      'Isolate the specific new log templates driving the divergence from baseline entropy.',
    ],
    instructionsRu: [
      'Токенизируйте структурированные логи на шаблоны, отделяя переменные ID и таймстемпы.',
      'Рассчитывайте энтропию Шеннона по распределению частот шаблонов за 5-минутные окна.',
      'Поднимайте алерты при резком падении энтропии (шторм однотипных ошибок) или ее всплеске (хаотичный сбой).',
      'Выделяйте новые шаблоны сообщений, вызвавшие отклонение от эталонного профиля энтропии.',
    ],
  },
  {
    id: 'container-cgroup-cpu-throttling-audit',
    name: 'ContainerCgroupCpuThrottlingAuditSkill',
    displayName: 'Kubernetes CFS CPU Throttling & Quota Audit',
    categoryId: 'analysis',
    description: 'Diagnoses microservice tail latency spikes caused by Linux Completely Fair Scheduler (CFS) container CPU quota throttling.',
    tags: ['analysis', 'kubernetes', 'cfs-throttling', 'cgroups', 'performance'],
    semanticType: 'process_directive',
    sectionName: 'CFS CPU Quota Throttling Diagnostic Protocol',
    ruSectionName: 'Диагностика троттлинга CPU в контейнерах Kubernetes (CFS Quota)',
    instructionsEn: [
      'Monitor container metric `container_cpu_cfs_throttled_periods_total` against `container_cpu_cfs_periods_total`.',
      'Alert when throttling ratio exceeds 5% even if overall Pod CPU utilization appears low (e.g. 30%).',
      'Explain multi-threaded burst dynamics: how 8 threads simultaneously bursting exhaust a 100ms CFS quota in 12ms.',
      'Recommend removing hard CPU limits while keeping CPU requests, or tuning CFS quota period to 20ms.',
    ],
    instructionsRu: [
      'Отслеживайте метрику троттлинга `container_cpu_cfs_throttled_periods_total` относительно общего числа периодов.',
      'Поднимайте тревогу, если доля троттлинга >5%, даже при низкой средней утилизации CPU (например, 30%).',
      'Объясните эффект залповой нагрузки: 8 потоков исчерпывают 100-мс квоту CFS за 12 мс, вызывая простой в 88 мс.',
      'Рекомендуйте снятие жестких CPU limits при сохранении CPU requests или уменьшение периода квоты до 20 мс.',
    ],
  },
  {
    id: 'oauth2-jwt-token-lifecycle-audit',
    name: 'Oauth2JwtTokenLifecycleAuditSkill',
    displayName: 'OAuth 2.0 & JWT Token Lifecycle Security Audit',
    categoryId: 'analysis',
    description: 'Audits JWT issuance, signature verification (RS256 vs HS256 algorithm confusion), clock skew, and JWKS key rotation.',
    tags: ['analysis', 'oauth2', 'jwt', 'security', 'auth', 'jwks'],
    semanticType: 'constraints',
    sectionName: 'OAuth 2.0 & JWT Security Audit Protocol',
    ruSectionName: 'Аудит безопасности жизненного цикла токенов OAuth 2.0 и JWT',
    instructionsEn: [
      'Verify strict algorithm enforcement: reject `alg: none` and prevent asymmetric/symmetric confusion attacks.',
      'Validate standard claims: `exp` (expiration), `nbf` (not before), `iss` (issuer whitelist), and `aud` (audience verification).',
      'Calibrate allowed clock skew tolerance to maximum 60 seconds.',
      'Audit JWKS endpoint caching: ensure public keys are cached with TTL while handling key rotation gracefully.',
    ],
    instructionsRu: [
      'Проверяйте явную фиксацию алгоритма подписи: блокируйте `alg: none` и путаницу между RSA и HMAC.',
      'Валидируйте стандартные клеймы: срок жизни `exp`, период `nbf`, белый список издателей `iss` и аудиторию `aud`.',
      'Ограничивайте допустимый дрейф системных часов (clock skew) не более чем 60 секундами.',
      'Контролируйте кэширование эндпоинта JWKS: публичные ключи должны кэшироваться с понятным TTL при плановой ротации.',
    ],
  },
  {
    id: 'web-vitals-inp-lcp-cls-performance',
    name: 'WebVitalsInpLcpClsPerformanceSkill',
    displayName: 'Core Web Vitals (LCP, INP, CLS) Frontend Diagnostics',
    categoryId: 'analysis',
    description: 'Diagnoses frontend bottlenecks: Largest Contentful Paint (LCP < 2.5s), Interaction to Next Paint (INP < 200ms), Cumulative Layout Shift (CLS < 0.1).',
    tags: ['analysis', 'web-vitals', 'performance', 'frontend', 'inp', 'lcp'],
    semanticType: 'process_directive',
    sectionName: 'Core Web Vitals Diagnostic Protocol',
    ruSectionName: 'Диагностика Core Web Vitals (LCP, INP, CLS)',
    instructionsEn: [
      'LCP (< 2.5s): Prioritize hero image preload, eliminate render-blocking CSS/fonts, and configure CDN edge caching.',
      'INP (< 200ms): Break long JavaScript tasks (>50ms) using `scheduler.yield()` or Web Workers to ensure rapid main-thread response.',
      'CLS (< 0.1): Mandate explicit `width` and `height` aspect-ratio dimensions on all images, video embeds, and dynamic ads.',
      'Track 75th percentile (p75) field data from Chrome User Experience Report (CrUX) rather than synthetic lab scores.',
    ],
    instructionsRu: [
      'LCP (< 2.5с): Предзагружайте главное изображение первого экрана, устраняйте блокирующий CSS и шрифты, настраивайте CDN.',
      'INP (< 200мс): Дробите тяжелые JavaScript-задачи (>50мс) с помощью `scheduler.yield()` для мгновенного отклика интерфейса.',
      'CLS (< 0.1): Обязательно задавайте размеры `width` и `height` для картинок, видео и баннеров, исключая сдвиг макета.',
      'Ориентируйтесь на 75-й перцентиль (p75) реальных пользователей (RUM / CrUX), а не на синтетические замеры в лаборатории.',
    ],
  },
  {
    id: 'rest-vs-graphql-payload-overfetching-audit',
    name: 'RestVsGraphqlPayloadOverfetchingAuditSkill',
    displayName: 'API Payload Over-Fetching & Under-Fetching Audit',
    categoryId: 'analysis',
    description: 'Quantifies mobile network payload waste caused by REST over-fetching and audits GraphQL nested N+1 request waterfalls.',
    tags: ['analysis', 'api', 'graphql', 'rest', 'payload-optimization'],
    semanticType: 'process_directive',
    sectionName: 'API Payload Efficiency & Over-Fetching Protocol',
    ruSectionName: 'Аудит избыточной выборки данных API (Over-Fetching & Under-Fetching)',
    instructionsEn: [
      'Measure Payload Efficiency Ratio: percentage of bytes transmitted in response that are actually rendered by client UI.',
      'Detect REST Over-Fetching where multi-megabyte JSON arrays are sent to display 3 table columns; implement sparse fieldsets.',
      'Detect GraphQL Under-Fetching and N+1 resolver waterfalls: mandate DataLoader batching for nested relationship fields.',
      'Benchmark JSON gzip/brotli transfer sizes against binary Protocol Buffer representations.',
    ],
    instructionsRu: [
      'Измеряйте коэффициент полезности пейлоада: процент переданных байт, реально отображаемых в интерфейсе клиента.',
      'Выявляйте избыточную выборку (Over-Fetching) в REST, когда клиенту отдаются гигабайты ненужных полей вместо выборки колонок.',
      'Пресекайте проблему N+1 в GraphQL: обязывайте применять DataLoader для пакетного объединения запросов к БД.',
      'Сравнивайте вес сжатого JSON (brotli) с бинарными Protocol Buffers на мобильных сетях с высокой задержкой.',
    ],
  },
  {
    id: 'git-merge-conflict-ast-semantic-diff',
    name: 'GitMergeConflictAstSemanticDiffSkill',
    displayName: 'Semantic AST-Based Merge Conflict Resolution',
    categoryId: 'analysis',
    description: 'Resolves git merge conflicts at the Abstract Syntax Tree (AST) level, eliminating false line-based text collisions.',
    tags: ['analysis', 'git', 'merge-conflicts', 'ast', 'version-control'],
    semanticType: 'process_directive',
    sectionName: 'AST Semantic Merge Conflict Resolution Protocol',
    ruSectionName: 'Семантическое разрешение конфликтов слияния Git (AST Diff)',
    instructionsEn: [
      'Parse conflicting file versions into Abstract Syntax Trees (base, ours, theirs).',
      'Distinguish trivial non-interfering AST transformations (e.g. independent imports, reordered independent functions) from semantic logic clashes.',
      'Automatically resolve structural non-conflicts that appear as textual line collisions in standard three-way diffs.',
      'Flag true semantic conflicts (conflicting mutations of identical state or function signatures) for human developer review.',
    ],
    instructionsRu: [
      'Парсите конфликтующие версии файлов в абстрактные синтаксические деревья (Base, Ours, Theirs).',
      'Отличайте неконфликтующие изменения на уровне AST (добавление независимых импортов) от реальных логических коллизий.',
      'Автоматически разрешайте ложные конфликты, возникающие из-за совпадения соседних строк в текстовом diff.',
      'Выделяйте истинные семантические противоречия (изменение сигнатуры одной функции обеими ветками) для ревью программистом.',
    ],
  },
];

console.log('Appending remaining Analysis skills...');
appendSkillsToCategory('analysis', analysisNew);
