const { appendSkillsToCategory } = require('./appendSkills.cjs');

const agenticNew = [
  {
    id: 'agentic-state-snapshot-replay-debugger',
    name: 'AgenticStateSnapshotReplayDebuggerSkill',
    displayName: 'Time-Travel State Snapshot & Replay Debugger',
    categoryId: 'agentic',
    description: 'Captures deterministic state snapshots after every agent tool step, enabling time-travel debugging and branching reruns.',
    tags: ['agentic', 'time-travel', 'debugging', 'snapshots', 'determinism'],
    semanticType: 'process_directive',
    sectionName: 'Agentic State Snapshot & Replay Protocol',
    ruSectionName: 'Снапшоты состояния и time-travel отладка агента',
    instructionsEn: [
      'Serialize working context, memory state, and tool outputs into an immutable snapshot at each discrete execution step.',
      'Allow developers to roll back agent execution to snapshot step N and re-run with an alternate system prompt or tool result.',
      'Record environmental non-deterministic variables (timestamps, random seeds) to guarantee 100% reproducible execution replays.',
    ],
    instructionsRu: [
      'Сериализуйте рабочий контекст, память и вывод инструментов в неизменяемый снимок на каждом шаге агента.',
      'Обеспечьте возможность отката агента к любому прошлому снапшоту N для ветвления с альтернативным промптом.',
      'Фиксируйте генераторы случайных чисел и системное время для гарантии 100% воспроизводимости прогона.',
    ],
  },
  {
    id: 'dynamic-tool-discovery-registry',
    name: 'DynamicToolDiscoveryRegistrySkill',
    displayName: 'Dynamic Semantic Tool Discovery & JIT Loading',
    categoryId: 'agentic',
    description: 'Replaces massive upfront tool definitions by dynamically searching and injecting tool schemas just-in-time via vector similarity.',
    tags: ['agentic', 'tool-discovery', 'jit-loading', 'token-optimization', 'registry'],
    semanticType: 'process_directive',
    sectionName: 'Dynamic Tool Discovery & Schema Injection Protocol',
    ruSectionName: 'Динамический поиск и JIT-подгрузка схем инструментов',
    instructionsEn: [
      'Maintain an index of hundreds of available enterprise tools in a semantic vector registry.',
      'Do not inject all tool schemas into the initial prompt; evaluate the active user sub-task and retrieve top-5 most relevant tools.',
      'Dynamically inject retrieved JSON schemas into the model context only when required by the execution trajectory.',
      'Unload unused tool schemas to preserve precious context window space and reduce model confusion.',
    ],
    instructionsRu: [
      'Ведите семантический индекс сотен доступных инструментов в векторном реестре.',
      'Не загружайте все инструменты разом: извлекайте только топ-5 релевантных под текущую подзадачу.',
      'Динамически внедряйте JSON-схемы инструментов в контекст модели по требованию (Just-in-Time).',
      'Выгружайте неиспользуемые схемы для экономии контекстного окна и исключения путаницы модели.',
    ],
  },
  {
    id: 'multi-agent-negotiation-contract-protocol',
    name: 'MultiAgentNegotiationContractProtocolSkill',
    displayName: 'Multi-Agent Bilateral Contract Negotiation',
    categoryId: 'agentic',
    description: 'Enables autonomous sub-agents to negotiate service-level agreements, output data formats, and latency contracts before execution.',
    tags: ['agentic', 'negotiation', 'multi-agent', 'contract-negotiation', 'sla'],
    semanticType: 'process_directive',
    sectionName: 'Bilateral Agent Contract Negotiation Protocol',
    ruSectionName: 'Протокол двусторонних контрактов между агентами',
    instructionsEn: [
      'Initiating agent transmits a structured Request for Proposal (RFP) specifying required schema, latency limit, and confidence threshold.',
      'Fulfilling agent evaluates internal capacity and responds with a formal counter-offer or binding commitment contract.',
      'Establish cryptographic handshake signatures verifying agreed expectations before payload processing begins.',
      'Execute automated arbitration penalty protocols if either agent breaches contract SLA parameters.',
    ],
    instructionsRu: [
      'Агент-заказчик отправляет запрос (RFP) со спецификацией структуры данных, лимита задержки и требуемой точности.',
      'Агент-исполнитель оценивает свои ресурсы и возвращает встречное предложение или контракт обязательств.',
      'Фиксируйте согласованные условия цифровой подписью перед началом выполнения задачи.',
      'Применяйте штрафные санкции и арбитраж при нарушении агентом параметров заключенного SLA.',
    ],
  },
  {
    id: 'environment-grounding-visual-confirmation',
    name: 'EnvironmentGroundingVisualConfirmationSkill',
    displayName: 'Multimodal Visual DOM & Screen Grounding',
    categoryId: 'agentic',
    description: 'Grounds web/desktop automation actions using visual screenshots, bounding-box coordinate detection, and DOM tree cross-checking.',
    tags: ['agentic', 'visual-grounding', 'multimodal', 'gui-agent', 'bounding-box'],
    semanticType: 'process_directive',
    sectionName: 'Visual Screen Grounding & Coordinate Verification',
    ruSectionName: 'Визуальное заземление интерфейса (GUI Grounding & Coordinates)',
    instructionsEn: [
      'Capture viewport screenshot and assign numbered bounding boxes to interactive UI elements (Set-of-Mark prompting).',
      'Cross-reference visual element coordinates with underlying accessibility DOM tree nodes.',
      'Execute click and input actions using precise center-point (x, y) normalized coordinates.',
      'Take post-action screenshot to visually confirm expected DOM state transition (e.g. modal opened, button state changed).',
    ],
    instructionsRu: [
      'Делайте скриншот экрана с разметкой интерактивных элементов маркированными рамками (Set-of-Mark).',
      'Сопоставляйте визуальные координаты элементов с деревом доступности (Accessibility Tree) DOM.',
      'Выполняйте клики и ввод строго по нормализованным координатам центра элемента (x, y).',
      'Делайте контрольный скриншот после действия для визуального подтверждения перехода интерфейса в новое состояние.',
    ],
  },
  {
    id: 'agentic-sandboxed-repl-evaluator',
    name: 'AgenticSandboxedReplEvaluatorSkill',
    displayName: 'Sandboxed Python/Node.js REPL Code Execution Gate',
    categoryId: 'agentic',
    description: 'Empowers agents to solve mathematical, statistical, and data-manipulation queries by generating and running isolated code snippets.',
    tags: ['agentic', 'code-execution', 'repl', 'sandbox', 'python'],
    semanticType: 'process_directive',
    sectionName: 'Sandboxed REPL Code Execution Protocol',
    ruSectionName: 'Выполнение кода в изолированном REPL для точных вычислений',
    instructionsEn: [
      'Prohibit mental arithmetic or complex string processing: mandate writing executable Python/JavaScript code snippets.',
      'Execute code inside an airgapped, resource-capped container sandbox with execution timeout <= 5 seconds.',
      'Capture stdout/stderr streams and feed results directly back into the agent reasoning context.',
      'Interpret script runtime exceptions and iteratively self-correct code syntax.',
    ],
    instructionsRu: [
      'Запрещайте устные вычисления сложных формул: требуйте генерации исполняемого кода на Python или JS.',
      'Запускайте скрипт в изолированной песочнице с лимитом по памяти и таймаутом выполнения не более 5 секунд.',
      'Передавайте потоки вывода (stdout/stderr) обратно в контекст рассуждений агента.',
      'Анализируйте системные ошибки выполнения и итеративно исправляйте код до получения корректного ответа.',
    ],
  },
  {
    id: 'plan-progress-monolithic-summarizer',
    name: 'PlanProgressMonolithicSummarizerSkill',
    displayName: 'Structured Plan Progress Monolithic Checkpoint',
    categoryId: 'agentic',
    description: 'Maintains an explicit markdown checklist of plan progress, updating completed milestones and active blockers on every turn.',
    tags: ['agentic', 'progress-tracking', 'checklist', 'milestones', 'transparency'],
    semanticType: 'structural_directive',
    sectionName: 'Plan Progress Checkpoint Protocol',
    ruSectionName: 'Чекпоинт прогресса выполнения плана (Markdown Checklist)',
    instructionsEn: [
      'Prefix every agent action turn with an updated structural markdown checklist: [x] completed, [>] in-progress, [ ] pending.',
      'State immediate next sub-goal clearly before issuing subsequent tool invocations.',
      'Log unexpected blockers encountered during the step and document dynamic plan adjustments.',
    ],
    instructionsRu: [
      'Предваряйте каждый шаг агента обновленным чек-листом плана: [x] завершено, [>] выполняется, [ ] предстоит.',
      'Четко формулируйте атомарную подцель текущего действия перед вызовом очередного инструмента.',
      'Фиксируйте возникшие препятствия и внесенные изменения в оставшиеся шаги плана.',
    ],
  },
  {
    id: 'graceful-degradation-fallback-cascade',
    name: 'GracefulDegradationFallbackCascadeSkill',
    displayName: 'Multi-Tier Graceful Degradation Fallback Cascade',
    categoryId: 'agentic',
    description: 'Implements a 3-tier fallback ladder when primary APIs or tools fail: Tier 1 full tool -> Tier 2 local heuristic -> Tier 3 safe approximation.',
    tags: ['agentic', 'graceful-degradation', 'fallback', 'resilience', 'availability'],
    semanticType: 'process_directive',
    sectionName: 'Graceful Degradation Fallback Cascade Protocol',
    ruSectionName: 'Каскад плавного снижения функциональности (Graceful Degradation)',
    instructionsEn: [
      'Tier 1 (Optimal): Query authoritative primary API with full real-time parameters.',
      'Tier 2 (Fallback): On persistent Tier 1 failure/timeout, query cached stale replica or local heuristic model.',
      'Tier 3 (Safe Approximation): On Tier 2 failure, synthesize conservative rule-based estimate accompanied by explicit degradation disclaimer.',
      'Never emit unhandled fatal error screens when a safe degraded approximation is viable.',
    ],
    instructionsRu: [
      'Уровень 1 (Оптимум): Запрос к основному боевому API с полным набором параметров в реальном времени.',
      'Уровень 2 (Резерв): При таймауте Уровня 1 — обращение к кэшированной реплике или локальной эвристике.',
      'Уровень 3 (Аппроксимация): При отказе Уровня 2 — консервативная оценка с обязательным уведомлением о деградации.',
      'Никогда не выдавайте фатальную ошибку, если задачу можно закрыть безопасным приближенным расчетом.',
    ],
  },
  {
    id: 'agentic-intent-disambiguation-clarifier',
    name: 'AgenticIntentDisambiguationClarifierSkill',
    displayName: 'Ambiguous Intent Proactive Disambiguation',
    categoryId: 'agentic',
    description: 'Detects underspecified user prompts with multiple divergent interpretations, pausing to ask 1-3 targeted multiple-choice questions.',
    tags: ['agentic', 'disambiguation', 'clarification', 'ux', 'intent-recognition'],
    semanticType: 'process_directive',
    sectionName: 'Intent Disambiguation & Clarification Protocol',
    ruSectionName: 'Проактивное устранение двусмысленности намерений (Disambiguation)',
    instructionsEn: [
      'Evaluate incoming user requests for underspecified parameters or branching intent ambiguities.',
      'Do not guess blindly when a wrong assumption incurs massive compute or rework costs.',
      'Formulate 2-3 structured clarification options with explicit trade-offs and recommended default choice.',
      'Resume full autonomous execution immediately upon user selection.',
    ],
    instructionsRu: [
      'Анализируйте входящий запрос на предмет скрытой неоднозначности и неполноты требований.',
      'Не делайте рискованных догадок, если ошибочное направление приведет к перерасходу ресурсов.',
      'Сформулируйте 2–3 конкретных варианта с описанием компромиссов и рекомендуемым выбором по умолчанию.',
      'Мгновенно возобновляйте автономную работу после получения уточнения от пользователя.',
    ],
  },
  {
    id: 'tool-parameter-fuzzing-preflight',
    name: 'ToolParameterFuzzingPreflightSkill',
    displayName: 'Tool Argument Defensive Preflight Sanitization',
    categoryId: 'agentic',
    description: 'Sanitizes and boundary-checks tool arguments before emission: validates types, trims whitespace, and prevents command injection payloads.',
    tags: ['agentic', 'preflight', 'sanitization', 'tool-arguments', 'security'],
    semanticType: 'guardrail_directive',
    sectionName: 'Tool Argument Preflight Sanitization Protocol',
    ruSectionName: 'Предварительная санитизация аргументов инструментов (Preflight Check)',
    instructionsEn: [
      'Validate that all tool argument values match expected schema datatypes (e.g. integer vs string).',
      'Strip leading/trailing whitespace, null bytes, and accidental unescaped newline characters.',
      'Inspect file paths: verify path remains strictly confined within permitted workspace boundaries (prevent path traversal `../`).',
      'Block shell metacharacters (`;`, `|`, `&&`, `` ` ``) in commands unless specifically mandated.',
    ],
    instructionsRu: [
      'Проверяйте соответствие типов аргументов схеме вызова (число, строка, массив).',
      'Очищайте строки от случайных пробелов по краям, нулевых байтов и неэкранированных переносов строк.',
      'Проверяйте файловые пути: исключайте атаки выхода из каталога (path traversal `../`).',
      'Блокируйте инъекции спецсимволов командной строки (`;`, `|`, `&&`) перед передачей в CLI.',
    ],
  },
  {
    id: 'confidence-gated-tool-dispatch',
    name: 'ConfidenceGatedToolDispatchSkill',
    displayName: 'Subjective Confidence Gated Tool Dispatch',
    categoryId: 'agentic',
    description: 'Requires the agent to evaluate subjective confidence before invoking expensive tools, choosing cheaper exploratory options if confidence < 70%.',
    tags: ['agentic', 'confidence-gate', 'cost-optimization', 'heuristics', 'decision-making'],
    semanticType: 'process_directive',
    sectionName: 'Confidence-Gated Tool Dispatch Architecture',
    ruSectionName: 'Гейтирование вызовов инструментов по уровню уверенности',
    instructionsEn: [
      'Assign an internal subjective confidence rating (0-100%) to the proposed action trajectory.',
      'If confidence >= 80%: Dispatch standard high-power execution tools.',
      'If confidence is between 50-79%: Dispatch low-cost diagnostic probes (e.g. read schema, search index) to reduce variance first.',
      'If confidence < 50%: Request human steerage or execute safe baseline search.',
    ],
    instructionsRu: [
      'Оценивайте уровень субъективной уверенности в успехе действия (от 0 до 100%).',
      'При уверенности >= 80%: запускайте стандартные мощные инструменты исполнения.',
      'При уверенности 50–79%: запускайте дешевые диагностические зонды (чтение схемы, поиск), чтобы сначала снизить неопределенность.',
      'При уверенности < 50%: запрашивайте подтверждение оператора или используйте базовый поиск.',
    ],
  },
  {
    id: 'agentic-self-critique-reflection-turn',
    name: 'AgenticSelfCritiqueReflectionTurnSkill',
    displayName: 'Intra-Trajectory Reflexion & Self-Critique Turn',
    categoryId: 'agentic',
    description: 'Executes a dedicated internal self-critique turn after complex tool outputs, validating correctness before synthesizing responses.',
    tags: ['agentic', 'reflexion', 'self-critique', 'reasoning', 'quality'],
    semanticType: 'process_directive',
    sectionName: 'Intra-Trajectory Reflexion Architecture',
    ruSectionName: 'Внутренняя рефлексия и самокритика агента (Reflexion)',
    instructionsEn: [
      'After receiving complex tool output, pause before emitting user-facing conclusions.',
      'Execute an explicit `<reflection>` mental turn: 1) Did the tool execute as expected? 2) Does the data satisfy user requirements? 3) What subtle inconsistencies remain?',
      'If reflection exposes defects, immediately issue corrective tool action.',
      'Synthesize final output only after reflection confirms 100% satisfactory state.',
    ],
    instructionsRu: [
      'После получения сложного ответа от инструмента возьмите внутреннюю паузу перед ответом пользователю.',
      'Выполните рефлексивный анализ: 1) Сработало ли действие как ожидалось? 2) Закрывают ли данные задачу? 3) Какие нестыковки остались?',
      'Если найдены изъяны — немедленно запустите корректирующий вызов инструмента.',
      'Формируйте итоговый ответ только после успешного прохождения внутреннего аудита.',
    ],
  },
  {
    id: 'state-machine-action-lock-guard',
    name: 'StateMachineActionLockGuardSkill',
    displayName: 'Finite State Machine Transition Lock Guard',
    categoryId: 'agentic',
    description: 'Enforces that agent actions transition strictly through legal states in a predefined Finite State Machine (FSM).',
    tags: ['agentic', 'state-machine', 'fsm', 'guardrails', 'workflow'],
    semanticType: 'constraints',
    sectionName: 'FSM Action Transition Lock Protocol',
    ruSectionName: 'Защита переходов по конечному автомату (FSM Action Lock)',
    instructionsEn: [
      'Define valid workflow states: e.g. PLANNING -> GATHERING -> CODING -> TESTING -> DEPLOYING.',
      'Prohibit illegal state transitions (e.g. attempting DEPLOYING directly from PLANNING without verified TESTING).',
      'Validate that current action corresponds strictly to permitted actions within the active state.',
      'Advance to next state only upon satisfying verified transition assertions.',
    ],
    instructionsRu: [
      'Задайте строгие фазы рабочего процесса: ПЛАНИРОВАНИЕ -> СБОР ДАННЫХ -> КОД -> ТЕСТЫ -> ДЕПЛОЙ.',
      'Блокируйте недопустимые скачки (например, попытку ДЕПЛОЯ сразу после ПЛАНИРОВАНИЯ в обход ТЕСТОВ).',
      'Проверяйте, что выбранный инструмент разрешен для использования в текущей активной фазе.',
      'Переходите в следующую фазу только после выполнения обязательных условий выхода из текущей.',
    ],
  },
  {
    id: 'declarative-goal-tree-verifier',
    name: 'DeclarativeGoalTreeVerifierSkill',
    displayName: 'Declarative Goal Tree & Sub-Goal Invariant Verifier',
    categoryId: 'agentic',
    description: 'Tracks hierarchical goals with declarative invariant checks, marking sub-goals complete only when automated verification passes.',
    tags: ['agentic', 'goal-tree', 'verification', 'invariants', 'planning'],
    semanticType: 'process_directive',
    sectionName: 'Declarative Goal Tree Verification Protocol',
    ruSectionName: 'Декларативное дерево целей с проверкой инвариантов',
    instructionsEn: [
      'Represent compound missions as a tree of sub-goals, each with an automated invariant test.',
      'Never mark a sub-goal complete based on assumption: run the explicit invariant check.',
      'If invariant check fails, keep sub-goal status open and formulate targeted remedial actions.',
      'Declare overall mission completion only when all leaf invariant checks evaluate to true.',
    ],
    instructionsRu: [
      'Представляйте составные задачи в виде дерева подцелей, снабженных автоматическими тестами инвариантов.',
      'Никогда не отмечайте подцель закрытой на основе догадки: запускайте явную проверку.',
      'При провале теста оставляйте подцель открытой и формируйте точечные действия по исправлению.',
      'Объявляйте миссию завершенной только тогда, когда все проверки листовых целей вернули true.',
    ],
  },
  {
    id: 'conversational-context-compactor-lru',
    name: 'ConversationalContextCompactorLruSkill',
    displayName: 'Context Window Compactor & LRU Pruning',
    categoryId: 'agentic',
    description: 'Compacts multi-turn history when approaching context limits, preserving initial goals, recent turns, and key tool artifacts.',
    tags: ['agentic', 'context-compaction', 'lru', 'token-management', 'context-window'],
    semanticType: 'process_directive',
    sectionName: 'Context Compaction & LRU Pruning Protocol',
    ruSectionName: 'Компактификация контекстного окна и LRU-вытеснение',
    instructionsEn: [
      'Monitor total tokens across conversation history relative to model context limit.',
      'When context utilization exceeds 75%, trigger automated compaction.',
      'Preserve: 1) System prompt and root user mandate, 2) The 3 most recent turns, 3) Key tool artifacts.',
      'Summarize intermediate verbose tool outputs into dense 2-line factual statements.',
    ],
    instructionsRu: [
      'Контролируйте общий объем токенов в истории диалога относительно лимита контекстного окна.',
      'При заполнении контекста более чем на 75% инициируйте процедуру компактификации.',
      'Сохраняйте в неизменном виде: 1) Системный промпт и исходную цель, 2) Последние 3 хода, 3) Ключевые артефакты.',
      'Многословные промежуточные ответы инструментов сжимайте в плотные двухстрочные фактологические резюме.',
    ],
  },
  {
    id: 'sandbox-filesystem-jail-enforcer',
    name: 'SandboxFilesystemJailEnforcerSkill',
    displayName: 'Filesystem Chroot Jail & Path Confinement',
    categoryId: 'agentic',
    description: 'Confines all agent file operations to an isolated working directory, blocking symlink escapes, relative `..` traversal, and root writes.',
    tags: ['agentic', 'filesystem-jail', 'chroot', 'security', 'isolation'],
    semanticType: 'guardrail_directive',
    sectionName: 'Filesystem Confinement & Jail Enforcement Protocol',
    ruSectionName: 'Ограничение файловой системы агента (Chroot Jail & Path Confinement)',
    instructionsEn: [
      'Resolve all incoming file paths to canonical absolute paths before issuing filesystem calls.',
      'Verify that resolved absolute path starts with permitted workspace root directory (`path.resolve(target).startsWith(workspaceRoot)`).',
      'Reject any path containing `..`, resolving through symlinks outside root, or accessing sensitive OS files (`/etc/passwd`, `~/.ssh`).',
      'Enforce read-only locks on configuration and project manifest files.',
    ],
    instructionsRu: [
      'Резолвите любые файловые пути в абсолютные канонические пути перед обращением к диску.',
      'Проверяйте, что путь строго начинается с префикса разрешенной рабочей папки.',
      'Блокируйте пути с `..`, симлинки на внешние директории и доступ к системным файлам (`/etc`, `~/.ssh`).',
      'Устанавливайте флаг «только для чтения» на системные конфигурационные манифесты проекта.',
    ],
  },
  {
    id: 'agentic-heartbeat-liveness-probe',
    name: 'AgenticHeartbeatLivenessProbeSkill',
    displayName: 'Asynchronous Heartbeat & Liveness Probe Watchdog',
    categoryId: 'agentic',
    description: 'Emits periodic liveness heartbeats during long-running background tasks, aborting and alerting if task becomes unresponsive.',
    tags: ['agentic', 'heartbeat', 'liveness-probe', 'watchdog', 'background-tasks'],
    semanticType: 'process_directive',
    sectionName: 'Agent Heartbeat & Watchdog Protocol',
    ruSectionName: 'Сторожевой таймер и проверка жизнеспособности (Liveness Probe)',
    instructionsEn: [
      'Emit a structured heartbeat telemetry ping every 10 seconds during long execution sequences.',
      'Include current progress percentage, active step name, and memory utilization in the heartbeat payload.',
      'Configure external watchdog timer: trigger timeout alert if 3 consecutive heartbeats are missed (30s silence).',
      'Gracefully terminate frozen background sub-tasks and initiate recovery orchestration.',
    ],
    instructionsRu: [
      'Отправляйте телеметрический сигнал жизнедеятельности (heartbeat) каждые 10 секунд при длительных операциях.',
      'Включайте в heartbeat процент выполнения, имя текущего шага и потребление памяти.',
      'Настройте внешний сторожевой таймер (watchdog): бейте тревогу при пропуске 3 сигналов подряд (30 сек тишины).',
      'Корректно завершайте зависшие фоновые процессы и запускайте процедуру восстановления.',
    ],
  },
  {
    id: 'agentic-tool-concurrency-limiter',
    name: 'AgenticToolConcurrencyLimiterSkill',
    displayName: 'Tool Call Concurrency & Semaphore Throttling',
    categoryId: 'agentic',
    description: 'Throttles parallel tool execution using semaphore tokens (e.g. max 4 concurrent network requests) to prevent rate limits.',
    tags: ['agentic', 'concurrency', 'semaphore', 'rate-limiting', 'throttling'],
    semanticType: 'process_directive',
    sectionName: 'Tool Concurrency Semaphore Architecture',
    ruSectionName: 'Семафор ограничения параллельных вызовов инструментов',
    instructionsEn: [
      'Enforce an asynchronous semaphore boundary around external tool invocations.',
      'Limit concurrent in-flight requests to maximum 4 parallel tasks to prevent socket exhaustion and downstream API 429 errors.',
      'Queue excess tool requests in a FIFO backlog with queue timeout bounds.',
      'Dynamically reduce concurrency window upon detecting latency degradation or upstream rate limiting.',
    ],
    instructionsRu: [
      'Внедрите асинхронный семафор вокруг вызовов внешних инструментов и API.',
      'Ограничьте число одновременных запросов (не более 4 параллельно) для предотвращения ошибок 429 Too Many Requests.',
      'Выстраивайте избыточные запросы в очередь FIFO с ограничением времени ожидания.',
      'Динамически сужайте окно параллелизма при росте задержек или предупреждениях о лимитах.',
    ],
  },
  {
    id: 'agentic-output-idempotency-key',
    name: 'AgenticOutputIdempotencyKeySkill',
    displayName: 'Transactional Idempotency Key Injection',
    categoryId: 'agentic',
    description: 'Generates and propagates unique UUID v4 idempotency keys for all state-mutating tool invocations to prevent duplicate actions.',
    tags: ['agentic', 'idempotency-key', 'transactions', 'deduplication', 'safety'],
    semanticType: 'process_directive',
    sectionName: 'Transactional Idempotency Key Injection Protocol',
    ruSectionName: 'Генерация ключей идемпотентности для мутирующих операций',
    instructionsEn: [
      'Generate a unique cryptographic UUID v4 Idempotency-Key for every mutating action (payment, message send, database write).',
      'Pass the key in headers or payload parameters to downstream services.',
      'On network failure or timeout, safely retry with identical Idempotency-Key: downstream service recognizes retry and returns cached result.',
      'Guarantee zero duplicate side effects across all transient network reconnection cycles.',
    ],
    instructionsRu: [
      'Генерируйте уникальный ключ идемпотентности (UUID v4) для каждого мутирующего действия (платеж, отправка письма, запись).',
      'Передавайте ключ в заголовке `Idempotency-Key` или теле запроса к сервису.',
      'При обрыве связи безопасно повторяйте вызов с тем же ключом: сервис вернет результат без дублирования операции.',
      'Гарантируйте полное отсутствие повторных списаний и дублей записей при сбоях сети.',
    ],
  },
  {
    id: 'agentic-telemetry-cost-attribution',
    name: 'AgenticTelemetryCostAttributionSkill',
    displayName: 'Per-Task Token & Dollar Cost Attribution Tagging',
    categoryId: 'agentic',
    description: 'Tags every sub-task with explicit token expenditure and dollar cost attribution, generating an itemized billing receipt.',
    tags: ['agentic', 'cost-attribution', 'finops', 'billing', 'telemetry'],
    semanticType: 'structural_directive',
    sectionName: 'Per-Task Cost Attribution Architecture',
    ruSectionName: 'Пошаговый учет стоимости токенов и расходов агента (FinOps)',
    instructionsEn: [
      'Record input tokens, output tokens, and reasoning tokens for every individual LLM and tool invocation.',
      'Calculate financial cost based on exact model pricing tiers (input $/1M, output $/1M).',
      'Attribute costs hierarchically to parent task ID, sub-goal, and end-user tenant ID.',
      'Output a final itemized execution receipt detailing runtime duration, token volumes, and total cost in USD.',
    ],
    instructionsRu: [
      'Фиксируйте входящие, исходящие и reasoning токены для каждого вызова модели и инструмента.',
      'Рассчитывайте финансовую стоимость по официальным тарифам провайдера за 1 млн токенов.',
      'Атрибутируйте расходы по иерархии: ID задачи, подцель и клиентский аккаунт.',
      'Формируйте итоговый структурированный чек с детализацией времени, объема токенов и стоимости в USD.',
    ],
  },
  {
    id: 'agentic-domain-ontology-grounding',
    name: 'AgenticDomainOntologyGroundingSkill',
    displayName: 'Formal Domain Ontology Alignment & Entity Grounding',
    categoryId: 'agentic',
    description: 'Maps conversational user terminology to formal domain ontologies, preventing misunderstandings of industry-standard entities.',
    tags: ['agentic', 'ontology', 'entity-grounding', 'knowledge-graph', 'domain-modeling'],
    semanticType: 'process_directive',
    sectionName: 'Domain Ontology Entity Grounding Protocol',
    ruSectionName: 'Заземление сущностей по доменной онтологии (Ontology Grounding)',
    instructionsEn: [
      'Load the authoritative domain ontology or entity glossary before processing domain queries.',
      'Map colloquial user terms to standardized ontological entities (e.g. map "user checkout" to `OrderPlacementEvent`).',
      'Enforce entity relationship constraints: verify that referenced attributes belong to the bound entity type in the ontology schema.',
      'Flag ontological contradictions early before dispatching downstream database queries.',
    ],
    instructionsRu: [
      'Загружайте канонический глоссарий и онтологию предметной области перед выполнением задачи.',
      'Сопоставляйте разговорные термины пользователя со стандартизированными сущностями онтологии.',
      'Контролируйте связи сущностей: проверяйте, что запрашиваемые атрибуты действительно принадлежат данному объекту.',
      'Выявляйте терминологические противоречия до формирования и отправки запросов в базу данных.',
    ],
  },
  {
    id: 'agentic-recursive-backtracking-solver',
    name: 'AgenticRecursiveBacktrackingSolverSkill',
    displayName: 'Recursive Backtracking Search with Pruning',
    categoryId: 'agentic',
    description: 'Explores combinatorial configuration spaces via recursive depth-first backtracking, undoing failed trial assignments.',
    tags: ['agentic', 'backtracking', 'search', 'constraint-satisfaction', 'recursion'],
    semanticType: 'process_directive',
    sectionName: 'Recursive Backtracking Search Protocol',
    ruSectionName: 'Рекурсивный поиск с возвратом и отсечением (Backtracking)',
    instructionsEn: [
      'Formulate combinatorial dilemmas as Constraint Satisfaction Problems (variables, domains, constraints).',
      'Assign values recursively; check constraints after each assignment.',
      'On constraint violation, immediately backtrack: undo the assignment and try the next domain candidate.',
      'Apply forward checking and arc consistency to prune unpromising branches before descent.',
    ],
    instructionsRu: [
      'Формулируйте сложные задачи комбинаторного выбора как задачи удовлетворения ограничений (CSP).',
      'Присваивайте значения переменным рекурсивно, проверяя соблюдение правил на каждом шаге.',
      'При нарушении ограничений немедленно делайте откат (backtrack): отменяйте шаг и пробуйте следующий вариант.',
      'Применяйте упреждающую проверку (forward checking) для раннего отсечения заведомо тупиковых ветвей.',
    ],
  },
  {
    id: 'agentic-peer-consensus-round-robin',
    name: 'AgenticPeerConsensusRoundRobinSkill',
    displayName: 'Peer Agent Round-Robin Deliberation & Voting',
    categoryId: 'agentic',
    description: 'Executes structured multi-turn round-robin debate among equal peer agents, culminating in Borda count preference aggregation.',
    tags: ['agentic', 'peer-consensus', 'round-robin', 'deliberation', 'borda-count'],
    semanticType: 'process_directive',
    sectionName: 'Round-Robin Peer Consensus Protocol',
    ruSectionName: 'Круговая дискуссия агентов и консенсус (Round-Robin Consensus)',
    instructionsEn: [
      'Assemble 3 diverse peer agents with orthogonal domain viewpoints.',
      'Execute round-robin deliberation: each agent reviews peer outputs and publishes constructive critiques and counter-arguments.',
      'Limit deliberation to exactly 2 rounds to maintain crisp momentum.',
      'Aggregate preferences using the Borda Count voting method to select the consensus deliverable.',
    ],
    instructionsRu: [
      'Сформируйте группу из 3 независимых агентов с разными профессиональными взглядами.',
      'Проведите круговую дискуссию: каждый агент изучает предложения коллег и вносит конструктивные замечания.',
      'Ограничивайте обсуждение строго двумя раундами для сохранения динамики работы.',
      'Агрегируйте выбор методом подсчета Борда для определения наиболее сбалансированного решения.',
    ],
  },
  {
    id: 'agentic-interruptible-task-suspension',
    name: 'AgenticInterruptibleTaskSuspensionSkill',
    displayName: 'Cooperative Task Preemption & Resumable Suspension',
    categoryId: 'agentic',
    description: 'Enables cooperative suspension of running agent tasks upon user interruption, saving execution checkpoints for later resumption.',
    tags: ['agentic', 'interruption', 'preemption', 'checkpointing', 'suspension'],
    semanticType: 'process_directive',
    sectionName: 'Cooperative Task Preemption Protocol',
    ruSectionName: 'Кооперативная приостановка и возобновление задач (Task Preemption)',
    instructionsEn: [
      'Check for user interrupt signals at every tool execution boundary.',
      'Upon receiving an interrupt, pause execution gracefully without corrupting intermediate state.',
      'Serialize active working memory, pending plan steps, and task parameters into a persistent Resumable Checkpoint.',
      'Handle urgent user query, then offer 1-click option to resume paused background mission from exact checkpoint.',
    ],
    instructionsRu: [
      'Проверяйте наличие сигнала прерывания от пользователя на границах между вызовами инструментов.',
      'При поступлении сигнала плавно приостанавливайте работу, не повреждая промежуточные данные.',
      'Сохраняйте состояние памяти, оставшиеся шаги плана и параметры в контрольную точку возобновления.',
      'Ответьте на срочный вопрос пользователя и предложите продолжить прерванную задачу с сохраненного места.',
    ],
  },
  {
    id: 'agentic-provenance-data-lineage-tracker',
    name: 'AgenticProvenanceDataLineageTrackerSkill',
    displayName: 'W3C PROV Agent Data Lineage & Provenance Tracker',
    categoryId: 'agentic',
    description: 'Tracks full W3C PROV data provenance: records which agent generated which artifact, using what sources, at what timestamp.',
    tags: ['agentic', 'provenance', 'data-lineage', 'w3c-prov', 'auditability'],
    semanticType: 'structural_directive',
    sectionName: 'W3C PROV Data Lineage Architecture',
    ruSectionName: 'Отслеживание происхождения данных по стандарту W3C PROV',
    instructionsEn: [
      'Generate W3C PROV records: map Entities (data artifacts), Activities (tool runs), and Agents (sub-agents).',
      'Record explicit `wasDerivedFrom`, `wasGeneratedBy`, and `wasAttributedTo` relational links.',
      'Attach cryptographic hashes of source documents to prove exact data provenance.',
      'Export verifiable audit graphs alongside final deliverables for compliance verification.',
    ],
    instructionsRu: [
      'Формируйте записи по модели W3C PROV: Сущности (артефакты), Активности (вызовы утилит), Агенты.',
      'Фиксируйте связи происхождения: `wasDerivedFrom` (из чего получено), `wasGeneratedBy` (кем сгенерировано).',
      'Прикрепляйте контрольные хэши исходных документов для доказательства подлинности источников.',
      'Экспортируйте наглядный граф происхождения данных вместе с итоговым результатом для аудита.',
    ],
  },
];

console.log('Appending remaining Agentic skills...');
appendSkillsToCategory('agentic', agenticNew);
